### ISSUE TITLE
Option to hide the icon from Dock

### ISSUE THREAD

**Issue by sundarv85** [pqrs-org/Karabiner-Elements#1497]
It would be great to have an option to hide the icon from Dock, while just having it in the menu bar(which is already available by default). Already an issue #1210 was raised

**Comment by roryokane** [comment]
Isn’t this already possible? I’m using Karabiner Elements 12.10 on macOS 10.13.6. I always see Karabiner’s square icon in the menu bar. I only see the <q><kbd>KEY</kbd></q> icon in the Dock after choosing “Preferences…” from that menu. After quitting that app that opens, the Dock icon is gone and Karabiner is still running in the background, and still displaying the menu item.

**Comment by zandwacht** [comment]
I'm pretty sure this is not fixed in 2023: app is visible in dock and task switcher, there is no option in setting to hide it (only menu)

**Comment by Aary-Thatte** [comment]
same here
