### ISSUE TITLE
Karabiner not working at all in Mojave

### ISSUE THREAD

**Issue by quinnalexander** [pqrs-org/Karabiner-Elements#1581]
Seriously. No effect whatsoever. Quit working upon updating to Mojave two days ago. None of my simple mods are working even. Restart didn't fix it. Anyone else having this issue?

**Comment by TheOddCoder** [comment]
I do have it sometimes. It really depends :( sometimes it works and sometimes it doesnt and presses every key twice :(

**Comment by msaffitz** [comment]
Reinstalling Karabiner fixed the issue for me on Mojave.  The underlying issue appeared to be:

```
[grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
```

And the kext not being active / installed on my system.

**Comment by TheOddCoder** [comment]
> Reinstalling Karabiner fixed the issue for me on Mojave. The underlying issue appeared to be:
> 
> ```
> [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
> ```
> And the kext not being active / installed on my system.

Yep this actually worked I'm surprized.

**Comment by detailyang** [comment]
fixed by upgrade to beta version

**Comment by silentred** [comment]
I upgraded macos from high sierra, then 3 karabiner daemons (karabiner-console and 2 others) killed my keyboard. I had to restart to safe mode to delete Karabiner under /Library/Application Support/org... by hand.

**Comment by Glurz** [comment]
Parts of karabiner elements seem to work under Mojave, but I'm unable to get mac hot keys working (fn + function keys) with my WASD keyboard.

**Comment by alvaro1728** [comment]
Just confirmed that reinstalling fixes the problem.  Thanks @msaffitz!

**Comment by HBinswanger** [comment]
With Mojave, is there any way to import the key mappings I used with Yosemite? I couldn't do that with High Sierra.

**Comment by shinjisr** [comment]
> Reinstalling Karabiner fixed the issue for me on Mojave. The underlying issue appeared to be:
> 
> ```
> [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
> ```
> And the kext not being active / installed on my system.

It worked for me too, thank you!

**Comment by HBinswanger** [comment]
Can somebody tell me how to at least have shifted states be hotkeys? E.g. to have ctrl-h send Home? The old Karabiner could be programmed. The new one shows no way of doing that. 

   -- HB

**Comment by bwanaaa** [comment]
* OS X version:  Mojave (10.14)
* Karabiner version:  12.10.0
  (You can confirm the version in "Misc & Uninstall" tab in Karabiner Preferences.)
* Your Mac hardware: MacBook Pro (Retina, 15-inch, Late 2013)
* Your keyboard hardware: integrated keyboard

I have assigned the shift-ctrl-option-command combo with the left bracket to resize a window to the left half of the screen using slate. This works properly.

 I have assigned caps_lock to hyper(shift-ctrl-option-command combo) in karabiner elements in the complex actions. 

Holding keycap and pressing left bracket does nothing. here is the event viewer log
eventType:key_down        code:0x6e       name:f19             misc:
eventType:key_down        code:0x2f       name:open_bracket    misc:
eventType:key_up          code:0x2f       name:open_bracket    misc:
eventType:key_up          code:0x6e       name:f19             misc:

but holding the hift-ctrl-option-command combo and open bracket properly resizes the finder window to the left half of the screen. 
eventType:key_down        code:0xe1       name:left_shift      misc:
eventType:key_down        code:0xe0       name:left_control    misc:
eventType:key_down        code:0xe2       name:left_alt        misc:
eventType:key_down        code:0xe3       name:left_gui        misc:
eventType:key_down        code:0x2f       name:open_bracket    misc:
eventType:key_up          code:0x2f       name:open_bracket    misc:
eventType:key_up          code:0xe0       name:left_control    misc:
eventType:key_up          code:0xe2       name:left_alt        misc:
eventType:key_up          code:0xe1       name:left_shift      misc:
eventType:key_up          code:0xe3       name:left_gui        misc:


This system was updated to mojave from el capitan. In el capitan (10.11.15 i think) I was using seil and karabiner  and these worked fine. Of course  they do not work in mojave so i uninstalled them both and installed karabiner elements. my login items (under users and groups in sys prefs) includes karabiner elements.

Whether I have assigned caps lock to no action in the keyboard prefs makes no difference. For both the apple internal keyboard and the virtual hid karabiner keyboard.

How can i troubleshoot this further? I really like using slate and the hyper key is invaluable.

Another thing I miss was the ability to type an open parenthesis by holding the left shift key but cannot do this either.

**Comment by petrr** [comment]
I made clean install on Mojave cannot run the app at all it keeps crashing

**Comment by dpo** [comment]
No go for me either. I'm on Mojave and I'm trying to remap Caps-Lock to Ctrl-b to use as Tmux prefix. I downloaded the modification `Tmux Prefix (rev 3)` and enabled `Tmux Prefix Mode [caps_lock as trigger key] (rev 2)` and `Tmux Prefix Mode [ ctrl+B as prefix ]`.

The Karabiner EventViewer always shows "key_down caps_lock" and "key_up caps_lock" when I press Caps-Lock. However, all it does it what Caps Lock usually does; it does not send Ctrl-b to Tmux (which is indeed my prefix).

I restarted the Mac half a dozen times, uninstalled/reinstalled, upgraded to the beta release, but still no go. For what it's worth, my config is here: https://gist.github.com/dpo/fdfd81f88d178f80ef34ab6d574fbe97.

Thanks.

**Comment by HBinswanger** [comment]
Why did they take a great, easy to use program and make it require the
incredible baroque, fussy complexity of a JSON file?!

I consider it unusable.

**Comment by rweng** [comment]
Hmm, so I've also had this problem on Mojave with

    [2019-02-28 10:55:04.103] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.

Reinstalling helped, but now I've just restarted and the problem occurs again... I'll try reinstalling again, but maybe it's some OS X Security Problem?

**Comment by arooni** [comment]
I stumbled on this page via google; and can confirm that @rweng's solution worked great!  Added karabiner-elements manually to accessibility settings, then restarted, and now everything works great!  Thanks for saving me time.

running 10.14.4

**Comment by dpo** [comment]
How does one add Karabiner-Elements to the accessibility settings?

**Comment by legel** [comment]
Thanks to all for this. I still faced issues (in my case, to disabling a stuck key), but managed to solve the problem. I've documented my approach here: https://github.com/tekezo/Karabiner-Elements/issues/1863#issuecomment-500126291

**Comment by cube7707** [comment]
I had the same issue but it was resolved by making a new json file inside of the ~/.config folder since it didn't exist. To make a new json file you just create a new file with text edit and replace .txt with .json

**Comment by brandon-arnold** [comment]
rweng said: 
> I did try to add Karabiner-Elements to `System Preferences -> Security -> Accessibility` first and restarted. This seemed to do the trick.

This also did it for me, after Karbiner-Elements quit working after a recent system update. Same error in my console. Suggest a PR for Karbiner-Elements to check regularly for its privileges and prompt the user to add itself to Accessibility if not.

**Comment by matt-mcgee-roostify** [comment]
Same issue here. I resolved it following suggestions from @legel and @cube7707. There was a symlink to the .json file in .config, but it didn't seem to be working correctly (i.e. edits were not showing up in the .json). I made a new karabiner directory and placed the .json inside following @cube7707 suggestion, copying over the .json file from the symlink and it worked.

**Comment by lwouis** [comment]
Karabiner stopped working after an OS update (to 10.14.6 (18G95)). Fixed the issue by updating Karabiner to beta version.

**Comment by n8gray** [comment]
Similar issue. Updated OS to 10.14.6 and Karabiner stopped working.  Added Karabiner Elements to `System Preferences/Security & Privacy/Accessibility` and rebooted.  Problem solved!

**Comment by badalsaibo** [comment]
I remember the old version working completely fine with Mojave, so I recently downloaded Karabiner version 11.6.0 and surprisingly it works fine all the time.

I needed to allow this app from the Security and Privacy menu in settings for the first time and that's it. No more issue after waking from sleep too!

https://karabiner-elements.pqrs.org/docs/releasenotes/#karabiner-elements-1160
