### ISSUE TITLE
Feature request: Implement simplified multitouch extension

### ISSUE THREAD

**Issue by johngb** [pqrs-org/Karabiner-Elements#1794]
The older Karabiner (not elements) had the multitouch extension, which quite frankly was amazing.  It was the reason that I stayed on a lower OS for so long, but alas I now have to upgrade to Mojave.

Thinking about the complexity of implementing the multitouch extension, I realised that there are (in my mind at least), two separate problems:

 1) Constraining the touch area of the trackpad.  I expect that this would be a bigger challenge as it would entail intercepting and blocking certain hardware signals.
 2) Picking up how many fingers are touching the touchpad, and using that as a modifier with the keyboard.

Both of these are useful, but even just the second one would be immensely useful.  From a technical point of view is there any major obstacle to any or both of these?  If so, would someone more familiar with it mind explaining what the problem is.  I realise that development time is always in short supply, but in this case I'm really looking to find out whether this could happen (or is likely to happen) in the future, or is just something I should get over.

**Comment by johngb** [comment]
@tekezo Would you be able to share your insight into what the primary barrier to the multitouch extension is at the moment?  I can understand if it hasn't been implemented due to time and resources, but I'm trying to understand whether there is a deeper issue at stake that is insurmountable with the newer versions of Mac OS.

**Comment by vjuge** [comment]
is there another app which provide this feature, since it seems karabiner won't continue to support it ?

**Comment by johngb** [comment]
@vjuge I haven't come across one, but if you happen to find one, please let me know.

What isn't clear to me yet, is _why_ Karabiner Elements doesn't support this.  Is it an OS API issue, which isn't solvable, or something that just requires work to implement.

**Comment by tekezo** [comment]
MultitouchExtension is back at v12.6.9.
You can confirm it with the latest beta version.

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

Usage of MultitouchExtension:
https://pqrs.org/osx/karabiner/document.html#multitouch-extension

**Comment by johngb** [comment]
@tekezo Fantastic, thanks.  After a day of fighting with my computer, this really has made my day.  Even after months without all my customised thumbsense settings, I still reflexively try to use them every day.

I've installed the beta, and it's working well.  I just have to move over my custom settings from the old private.xml file to the json settings.  On that note, are there any limitations with the new thumbsense which the previous one didn't have?  For example, I can only find thumbsense settings for when one or more fingers are touching the touchpad, but with the old thumbsense I had different key bindings depending on how many fingers were touching the touchpad.  Is that still possible?  If so, could you point me to any example setting with 2, 3, or 4 finger activation?

To clarify, I see that the following `conditions` are set for thumbsense bindings:

``` json
"conditions": [
  {
     "name": "multitouch_extension_finger_count_total",
     "type": "variable_unless",
     "value": 0
   }
 ],
```

Is the "name" a reserved name specific for thumbsense?  What does "value" represent?  I apologise for all the questions, but I'm just excited to get my mac back to where it used to be.

In case it's not clear.  Thanks a million.  I really am grateful for all the effort that you've put into this.

**Comment by tekezo** [comment]
> are there any limitations with the new thumbsense which the previous one didn't have?

There is a limitation (which is not MultitouchExtension limitation, but Karabiner-Elements one).
Karabiner-Elements cannot change the trackpad and magic mouse events.
Thus, Wheel feature (S,L key) is not provided.

> I had different key bindings depending on how many fingers were touching the touchpad. Is that still possible?

Yes.
For example, Multitouch Vi Mode provides such feature.
https://pqrs.org/osx/karabiner/complex_modifications/#multitouch_vi_mode

Please define rules for each fingers as follows.

```json
// One finger
"conditions": [
  {
    "type": "variable_if",
    "name": "multitouch_extension_finger_count_total",
    "value": 1
   }
]

...

// Two fingers
"conditions": [
  {
    "type": "variable_if",
    "name": "multitouch_extension_finger_count_total",
    "value": 2
   }
]

...

// Other count of fingers (3,4,5,...)
"conditions": [
  {
     "type": "variable_unless",
     "name": "multitouch_extension_finger_count_total",
     "value": 0
   }
 ]
```

The `multitouch_extension_finger_count_total` variable is not thumbsense specific.
The variables are described in json reference manual.
https://pqrs.org/osx/karabiner/json.html#multitouch-extension

**Comment by johngb** [comment]
@tekezo Thanks for the information.

I'm working on moving my old settings, and I realised that it would be quite useful to be able to have comments.  I know that some JSON libraries allow commenting, but it's not clear to me if any of them are used here.  Is there any way to comment in the karabiner.json file?

**Comment by tekezo** [comment]
@johngb 
Karabiner-Elements does not support json comment.
If you want to use comments (you are making very complex rules), I recommend you to use some json generator.

For example, the distributed json file are commonly generated by ruby script.
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/multitouch_vi_mode.json.rb

And there are some nifty generator such as Goku.
https://github.com/yqrashawn/GokuRakuJoudo

**Comment by johngb** [comment]
@tekezo Thanks for the clarification.  I think I'll probably use a generator, thanks.
