### ISSUE TITLE
Emulating dual-function keys as in ErgoDox.

### ISSUE THREAD

**Issue by dragonsmith** [pqrs-org/Karabiner-Elements#1861]
Hey!
Thanks a lot for an amazing tool!

I'm trying to configure dual-function keys the way they are implemented in ErgoDox. E.g.: Z being pressed gives Z, Z being held down gives Ctrl.

If I understand the documentation correctly the right way to do that is like that:

```json
{
    "manipulators": [
        {
            "description": "Dual key: Z/Left Ctrl",
            "from": {
                "key_code": "z"
            },
            "to": [
                {
                    "key_code": "left_control"
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "z"
                }
            ],
            "type": "basic"
        }
    ]
}
```

And it basically works, but turns out if I type relatively fast(not even lightning fast) I get a lot of misfires with `Ctrl+smthng` combinations being triggered instead of just letter Z.

I've checked 4 timing values which are described in the doc - they seem to be irrelevant in my case.

Is it possible to tune some other timings somehow or use different approach to achieve the same result and fix the misfiring problem?

Thank you!

**Comment by fdr** [comment]
I am also having problems getting the heuristics on Karabiner to be as good as Ergodox's. My intention is to use d/f and j/k as alt/ctrl ctrl/alt for heavy use of emacs key bindings. I think(?) the difference is that Ergodox has a setting (by default) that both keys must be tapped for a certain amount of time:

"Ignore mod tap
default ON
Similar to Permissive Hold, this alters how the firmware processes input for fast typist. If you press a dual-function modifier key (such as "Ctrl when held, Z when tapped"), press another key (such as "X"), release the modifier key, and then release the normal key, it would normally output the modded key ("Ctrl+X" in this case), which may not be desirable. This makes sure that both keys are sent (eg "zx") unless both keys are held for the Tapping Term. If "Permissive Hold" and "Ignore Mod Tap" are both enabled, this changes how both work. In this case, the regular key has the modifier added if the first key is released first *or* if both keys are held longer than the "Tapping Term"."

Or perhaps it is, and I just haven't figured out how to jiggle the several timeouts to make things work smoothly.

**Comment by Madd0g** [comment]
I created a [similar issue](https://github.com/tekezo/Karabiner-Elements/issues/1667) because I had a problem with holding vs. tapping a key, I never really found a solution and only use rare edge keys for holding (z, slash, brackets, period, comma).

In my setup, I'm using z as a modifier, but a new modifier, it's accomplished with a variable - holding z sets a variable and then other keys get remapped only if the variable is set. Unfortunately, that's also a bit spotty for me, typing fast also causes issues, I really wish holding was as solid as it was in the old Karabiner.

**Comment by dragon788** [comment]
I would suggest taking a look at the complex_modifications file after importing the Caps_lock to Ctrl and Esc modifier rules. I use this one and it behaves very much like what you are saying, if I tap Caps it presses Esc, if I hold it down it becomes Ctrl so I can easily switch modes in Vim and also perform shortcuts in Chrome/Vim/Terminal/etc.
