### ISSUE TITLE
Why not support importing my own json rules? 

### ISSUE THREAD

**Issue by huzhiyun** [pqrs-org/Karabiner-Elements#1965]
And still another problem:
Why do you not support importing rule json file directly on the GUI？ If I wrote a rule file myself, I still have to copy the file to ~/.config/karabiner/assets/complex_modifications , it is really not convenient.

**Comment by tekezo** [comment]
I recommend you to use an external tool.
For example, https://github.com/yqrashawn/GokuRakuJoudo

**Comment by dragon788** [comment]
Nothing is stopping you from importing your own rules. As a matter of fact Karabiner-Elements fully supports passing in your ruleset from a URL (and likely a local file as well), you just need to use its' "AppUrl" `karabiner://`.

See this awesome repo for an example, https://github.com/rux616/karabiner-windows-mode#installation

You can also store your rules in a GitHub Gist and use the raw URL to the file to import them and easily share them across multiple computers or with other folks who use a similar workflow.
