### ISSUE TITLE
Keyboard backlight sometimes does not turn on after sleep

### ISSUE THREAD

**Issue by bengrosser** [pqrs-org/Karabiner-Elements#1968]
I am creating this new issue to revive an old issue (#[1676](https://github.com/tekezo/Karabiner-Elements/issues/1676)) that was prematurely closed. From that issue's text:

> Sometimes after sleep the keyboard backlight does not turn on. I can't say exactly from which version this started to happen, but it's pretty recent.

I can personally confirm that downgrading to 12.1.0 fixes the problem.

**Comment by mcmillion** [comment]
What's the purpose of marking this stale and closing it? It's still definitely an issue. Reproduceable with 12.7.0 on macOS 10.15.1
