### ISSUE TITLE
I want to switch screens with the Logitech mouse side button.

### ISSUE THREAD

**Issue by goodGid** [pqrs-org/Karabiner-Elements#1969]
I am using an iMac.
I want to switch screens with the Logitech mouse side button.
Is there a way?

**Comment by dragon788** [comment]
Try opening the Karabiner-EventViewer. If the keypress events don't show up there, try using the Logitech Options software (their configuration tool) to set the button you want to use to something like F20 and then make a rule for Karabiner-Elements to respond to F20 and perform the switch. Apple uses up to F15, so you can safely use any of F16-F20 for this purpose.

https://gist.github.com/Zenexer/c5243c4216f1f8cd2251

**Comment by dollar2048** [comment]
How you select F20 in "Logitech Options"? How is it possible to "trigger" F20?
