### ISSUE TITLE
Mandatory modifier remains in TO event

### ISSUE THREAD

**Issue by jackromano** [pqrs-org/Karabiner-Elements#1971]
I am using a PC keyboard (Corsair K65) on my MacBook Pro (15-inch, 2018), macOS 10.14.5. I am attempting to make `Ctrl+Left` key work as `Option+Left` would on the mac keyboard. However, the following configuration does not work. In Event Viewer I see that pressing `Ctrl+Left` on the Corsair results in:

```
name: left_arrow
misc: flags left_alt,left_gui
```

and behaves as if I had pressed `Command+Option+Left` on the Macbook. I would expect that because the `left_gui` is mandatory, it would be omitted from the TO event. Any ideas?

simple:
```
"simple_modifications": [
    {
        "from": {
            "key_code": "left_control"
        },
        "to": {
            "key_code": "left_command"
        }
    },
    {
        "from": {
            "key_code": "left_gui"
        },
        "to": {
            "key_code": "left_control"
        }
    }
]
```

complex:
```
...
{
    "conditions": [],
    "from": {
        "key_code": "left_arrow",
        "modifiers": {
            "mandatory": [
                "left_gui"
            ]
        }
    },
    "to": [
        {
            "key_code": "left_arrow",
            "modifiers": [
                "left_alt"
            ]
        }
    ],
    "type": "basic"
},
...
```

**Comment by regalstreak** [comment]
Have the same issue
