### ISSUE TITLE
§ to escape on macbook pro not working after update

### ISSUE THREAD

**Issue by otisoke** [pqrs-org/Karabiner-Elements#1976]
Hello,

I have a macbook pro with touch bar. I changed my § key to function as the escape button some time ago. Unfortunately it stopped working after apple updated my system last night. I can't seem to make it work again and have no experience with coding/scripting. Does someone know the solution for my problem?

Thanks in advance.

**Comment by mmzyk** [comment]
@otisoke Try updating to the latest beta version of Karabiner. I had a similar issue where it stopped working after the latest Mojave supplemental update but using the Karabiner in app updated (under the Misc tab) and having it update to the latest beta version (12.6.6 for me) fixed a similar issue I had.

**Comment by otisoke** [comment]
@mmzyk Thanks a lot, this worked for me!
