### ISSUE TITLE
How to disable Function Key modifications? Removing from karabiner.json only works temporarily.

### ISSUE THREAD

**Issue by christianmagill** [pqrs-org/Karabiner-Elements#1986]
I don't want Karabiner Elements to change any of my Function key mappings. It causes issues with my Craft Keyboard when it does.

I've found that I can set "fn_function_keys" to an empty array in karabiner.json, and it resolves the issue, but after a few days the problem shows back up, and the full array is back in my karabiner.json file.

Thanks

**Comment by kulas115** [comment]
Same here. I would like to still use my media keys (Logitech MX Keys) while benefiting from swapping cmd/option/ctrl and so on. So far I was not able to find an option to disable any modification to function keys at all. Is this a bug or a feature?

**Comment by asgmeonerandom** [comment]
I tried to remove F11, F12 from json then close th app and reopen but it doesn't affect.

**Comment by paztis** [comment]
still problematic for me...

**Comment by janklimo** [comment]
Logitech Ergo K860, same issue.

**Comment by MuhammedZakir** [comment]
Is the option `Use F1, F2, F3, etc. keys as normal function keys`[1] not working for you?

[1] I can't remember exact wording. It's probably slightly different.

**Comment by paztis** [comment]
On my side I've a conflit between my mbp touchbar and the external keyboard.

To display the fn keys I press the fn button. I don't have this button on
my external keyboard (fn keys directly accessible).

With karabiner, if I press f5 on the internal keyboard and it refresh my
browser, on my external keyboard it changes brightness, and vice versa

Le sam. 16 janv. 2021 à 15:00, Muhammed Zakir <notifications@github.com> a
écrit :

**Comment by jrhorn424** [comment]
I'd like the default setting for "All Devices" to be pass-through. If you choose "Apple Keyboard", you can select the option to use the default behavior. Can we get that for "All Devices"?

**Comment by zvuc** [comment]
This is still an issue for me. It would be nice if there was an option to completely bypass Karabiner's Function key modifying part and only leave the simple/complex modifications active.

**Comment by mickimnet** [comment]
I'm currently in the process of figuring out how to get a _QMK_ (specific: _Keychron Q3_) keyboard to **completely** work with _Karabiner-Elements_, and what I can tell you from my first findings:

A setting to disable the handling of the _Function Keys_ altogether would help get the full functionality of all keyboards to work.

---

My _Q3_ has 2 layers--one with the standard _macOS_ media controls on the function keys, and on the second layer are the key codes for `F1 to F12`.

Without _Karabiner-Elements_ (to be precise: no _Keychron Q3_ device enabled):
1. pressing the physical _F1_ key ⇒ `display_brightness_decrement` (seen in _Karabiner-EventViewer_)
2. pressing the layer switch key (`MO(1)`) and _F1_ ⇒ `F1` (seen in _Karabiner-EventViewer_)

With _Karabiner-Elements_, and the default settings for _"For all devices"_:
1. pressing the physical _F1_ key ⇒ `display_brightness_decrement`
2. pressing the layer switch key (`MO(1)`) and _F1_ ⇒ `display_brightness_decrement`

With _Karabiner-Elements_, the _Function Keys_ for the keyboard are set to `vk_none`:
1. pressing the physical _F1_ key ⇒ `display_brightness_decrement`
2. pressing the layer switch key (`MO(1)`) and _F1_ ⇒ _nothing_

With _Karabiner-Elements_, the _Function Keys_ for the keyboard are set to the respective `F1 to F12` key codes:
1. pressing the physical _F1_ key ⇒ `display_brightness_decrement`
2. pressing the layer switch key (`MO(1)`) and _F1_ ⇒ `F1`

**Comment by lornally** [comment]
> I don't want Karabiner Elements to change any of my Function key mappings. It causes issues with my Craft Keyboard when it does.
> 
> I've found that I can set "fn_function_keys" to an empty array in karabiner.json, and it resolves the issue, but after a few days the problem shows back up, and the full array is back in my karabiner.json file.
> 
> Thanks

now, when i change the config, it is refresh to back quickly
