### ISSUE TITLE
Caps Lock LED functionality still not working correkctly

### ISSUE THREAD

**Issue by kochsebastian** [pqrs-org/Karabiner-Elements#1990]
With the newest Karabiner elements software and the newest macOS version the Caps Lock LED override functionality still won't work.
What I want:
Remap the Caps Lock function to double shift (works)
Caps Lock LED is still paired to the Caps Lock Key nor the state of Caps Lock (doesn't work)

**Comment by bcassid** [comment]
Running 12.7.0 in Mohave 10.14.6 on a Mac Pro (Late 2013) with an Apple USB Keyboard with Numeric Keypad and when enable the Change caps_lock to command+control+option+shift complex modification, the caps lock LED does not work and neither does caps lock work for capitalization.
