### ISSUE TITLE
Right click turns on/off caps lock led randomly

### ISSUE THREAD

**Issue by curvedb** [pqrs-org/Karabiner-Elements#1991]
Using version 12.7.0 on Mac OS 10.14.6 with Cooler Master Master Keys Lite keyboard. The problem is mouse right click turns on/off randomly when Caps lock is turned. Anyone having the same problem?

**Comment by braham-snyder** [comment]
possibly related: https://github.com/tekezo/Karabiner-Elements/issues/1859

just quitting Karabiner and restarting it might fix it
