### ISSUE TITLE
"Use all F1, F2, etc. keys as standard function keys" isn't saved to ~/.config/karabiner.json

### ISSUE THREAD

**Issue by Nowaker** [pqrs-org/Karabiner-Elements#1992]
I have my Karabiner config in a [git repo](https://gitlab.com/Nowaker/dotfiles-karabiner). Today I realized "Use all F1, F2, etc. keys as standard function keys" is not present in `karabiner.json` config file. Please make this setting part of the config file.

**Comment by Nowaker** [comment]
:(

**Comment by Nowaker** [comment]
😠

**Comment by maxmarcon** [comment]
Yes, and they are not saved in the profiles either (don't know if it's the same as the karabiner.json file), so that one can't switch between profiles and have the "Use F1, F2.. as standard function keys" automatically set as expected. It should be part of the profile IMHO.

**Comment by jamesstidard** [comment]
This caught me out today as well. I sync my `karabiner.json` between machines and the rest of my keybindings assume that option is checked. I feel I was kind of lucky to stumble on this being the difference between the machines that was causing the issue, I could have easily have not seen it.

Would be nice to have it in the `karabiner.json` for completeness and more consistent replication of shortcuts between machines.

Love the project, thanks for the work.

**Comment by Nowaker** [comment]
no

**Comment by jamesstidard** [comment]
@Nowaker you might consider writing a fresh bot to help in your fight against the stale bot :)

**Comment by Nowaker** [comment]
@jamesstidard Ha, ha, that's a great idea!

**Comment by Nowaker** [comment]
No

**Comment by Nowaker** [comment]
No

**Comment by Nowaker** [comment]
Stupid stałe bot. I guess everything in this repo gets closed after months or years of "inactivity".

**Comment by tekezo** [comment]
The setting is a part of macOS configuration, not a Karabiner-Elements setting.
Thus, not included in karabiner.json.

**Comment by Nowaker** [comment]
If you can set it through Karabiner, it's a Karabiner setting to me.
