### ISSUE TITLE
Logitech k780 Fn keys

### ISSUE THREAD

**Issue by tr3buchet** [pqrs-org/Karabiner-Elements#1993]
The logitech k780 function keys continue to operate as random controls that do miscellaneous things. For example, when I press what should be the F12 key, I get a volume increase pop up on the screen. I tried remapping all 3 of the volume increment options to F12, but it doesn't matter. The F12 key, whatever it is, never even makes it to the event viewer. I have attempted to enable treating Fn keys as F keys in the karabiner settings and osx's settings. Neither seems to have any effect. 

Is this keyboard just terrible or what's the deal, cause otherwise it's fantastic, but no F keys is a deal breaker. Not working with karabiner is also a deal breaker!

**Comment by blueacker** [comment]
I have the same problem while my keyboard is Filco (Majestouch-Bluetooth).
It has two Fn key just besides space button, so I want to change Fn to Cmd but they appear as Option key.
