### ISSUE TITLE
Karabiner not respecting current layout

### ISSUE THREAD

**Issue by jacobisaliveandwell** [pqrs-org/Karabiner-Elements#1996]
When using a different "Input Source" (through System Preferences -> Keyboard -> Input Sources), some testing, confirmed by the event viewer, shows Karabiner registering the QWERTY keys.

Note: Using the karabiner complex modification for Dvorak/Colemak/etc is not a preferred solution. I regularly switch back to QWERTY.

Duplicate of #221

**Comment by jacobisaliveandwell** [comment]
lame

**Comment by s-gbz** [comment]
Any news?

**Comment by jacobeatsspam** [comment]
None, and I gave up on MacOS. It's a pile of :hankey:
