### ISSUE TITLE
Settings Do Not Save, Nor Take Effect

### ISSUE THREAD

**Issue by vexir** [pqrs-org/Karabiner-Elements#1999]
Version: 12.7.0
MacOS: 10.14.6

Karabiner-Elements doesn't save any modifications I make anywhere in the preferences window after closing the preferences window. The application doesn't have to be exited to make this bug appear. It's 100% reproducible on my machine. I've tried creating simple modifications and new profiles, and both completely disappear after I reopen the preferences window.

Also, when I make those simple modifications (e.g. swapping left option and left command), they just don't work. Perhaps that's a symptom of the modifications not saving, but I couldn't say.

How can I help diagnose?

**Comment by yangjob** [comment]
I got this too! Since I update to macOS Catalina (10.15), it doesn't work anymore!

**Comment by NasSilverBullet** [comment]
Me too!
I confirmed that Karabiner-Elements does not reflect the settings even though karabiner.json has been modified by Karabiner-Elements.

MacOS: 10.14.6
Karabiner-Elements: 12.7.0

**Comment by jpcampos** [comment]
I can confirm the same, on MacOS Catalina 10.15
Karabiner-Elements:12.7.0

**Comment by thsu3131** [comment]
Me too!

MacOS: Catalina 10.15.1
Karabiner-Elements: 12.7.0

**Comment by vexir** [comment]
Hi, this still happens. I tried a total removal and reinstall of Karabiner.

**Comment by fandy** [comment]
Can confirm it still happens. Works on one keyboard but not the other.

**Comment by wjustice** [comment]
Definitely still happens.

**Comment by AdikolEV** [comment]
Karabiner-Elements doesn't save any setup I make for example new profile or simple modification, after reopening the preferences window is empty. I even reinstall Catalina and Karabiner still don't work, I think config file or something like that is missing. Please help

**Comment by vexir** [comment]
For everyone who is experiencing this issue and is frustrated by a lack of fix from Karabiner, BetterTouchTool can do all the keyboard replacement and swapping you likely need. And their support is responsive.

**Comment by danielo515** [comment]
I'm on the same situation. Is there any workaround? Karabiner is not saving my preferences, nor correctly handling imports

**Comment by shirdekel** [comment]
Having the same issue on my iMac (21.5-inch, 2017), but not on my MacBook Pro (Retina, 13-inch, Late 2013). Both are on Mojave 10.14.6 (18G103) and Karabiner version 12.10.0.

**Comment by underyx** [comment]
After a year of use this suddenly started happening on macOS 11.2.3, karabiner-elements 13.3.0

**Comment by underyx** [comment]
Figured it out! I ran this in the terminal:

```bash
$ file ~/.config/karabiner
/Users/underyx/.config/karabiner: broken symbolic link to /Users/underyx/Google Drive/Mackup/.config/karabiner
```

Turns out Mackup (a backup tool) had changed my karabiner config to point to Google Drive. I changed which account I use for Google Drive syncing and that caused the profile directory to break. I moved the Mackup directory from my old Drive to the new one to fix this.

**Comment by hyojun91** [comment]
(Karabiner-Elements version: 14.4.0 / Mac: As of today, the latest version)

I also occured this kind of problem today. 
Karabiner doesn't save any modifications.
If I just reopened Karabiner-elements, all modifications gone... 😅

The problem is that karabiner can't save modifications.
When  I checked the location of config file, the folder didn't exist. (~/.config/karabiner)
so i just made folder that name is 'karabiner'. 
after making folder, the program works well.

Check 'Misc' -> 'Open config folder' tap works well.
In my case, it didn't work.
After making directory, Karabiner made files(karabiner.json, etc.) by itself and program worked well.

Thanks.

**Comment by tobyclh** [comment]
Just to follow up on @AidenK805 comment, 
You will need to 
```
sudo mkdir ~/.config/karabiner
sudo chown USERNAME ~/.config/karabiner
```
then restart karabiner (or just reboot)

**Comment by Kisokumar** [comment]
You have to enable 'modify events' under the bluetooth keyboard you are trying to modify.

Devices -> *Your keyboard* -> Modify events

**Comment by sniffercraft34** [comment]
It doesn't work for me either. I have a Seenda keyboard.

**Comment by ArsenicBismuth** [comment]
Wow, out of all the automated notification, the dozens of popups to hand-hold the user on the security settings, they managed to mess this up? Is there something that caused whatever `mkdir` call they used internally to fail?

Kinda unexpected, but this is precisely my issue. None of my settings work. And the only hint I have is that none of my settings are preserved on close. Thankfully this issue shows up rather early in my search and fixed everything.

Amazing program tho.

**Comment by tadexmm** [comment]
Hi, everyone.

In my case, Karabiner's config folder did not exist in my Home/.config. What worked for me was granting myself Read & Write permissions to the my ~/.config folder, then  making myself the owner of the ~/.config folder and applying the new permissions to enclosed items.

Steps:

1. Open Finder and press Command + Shift + H to go to your Home folder,
2. Press Command + Shift + . to show hidden items
3. Right click the .config folder and click Get Info
4. If needed, click on the lock in the lower right corner of the Info window that just popped up to allow changes
5. Play around with the settings under 'Sharing & Permissions' (very bottom) to make yourself the owner of the folder and enclosed items

On restarting Karabiner it managed to create the ~/.config/karabiner folder and everything started working.

Hoping this helps someone.
