### ISSUE TITLE
Fn key can't map into Cmd because there are 2 Fn key

### ISSUE THREAD

**Issue by blueacker** [pqrs-org/Karabiner-Elements#2002]
My keyboard is **Filco (Majestouch-Bluetooth)**.
It has two Fn key just besides space button (see attached image), so I want to change `Fn` to `Cmd` and I only could map `Fn` to either `right-command` or `left-command`, and then the two Fn keys appear as option or other key but not command key. 
I think it's maybe because the **two `Fn`** have conflict when I set `Fn` to either `Left Cmd` or  `Right Cmd`.
![WechatIMG620](https://user-images.githubusercontent.com/3889028/65386839-fbadea80-dd72-11e9-9259-f8132187db28.jpeg)

**Comment by quocnguyen** [comment]
i had the same issue and would love to had a fix for this case as well

**Comment by blueacker** [comment]
what？

**Comment by Leezj9671** [comment]
That's really a problem until now...

**Comment by babygau** [comment]
imo u cant expect karabiner to work with all types of keyboard layouts/brands
