### ISSUE TITLE
Profiles specific to device serial_number or instance

### ISSUE THREAD

**Issue by adamczyk777** [pqrs-org/Karabiner-Elements#2007]
Hey folks!

I wanted to get out a very specific feature from karabiner elements. Let me first explain the situation.

I use two Apple Magic keyboards, one of them is a European Polish type of keyboard, the other one is the ANSI US keyboard. The thing that I interchange in these keyboards is grave_accent_tilde, and non_us_backslash. And I wanted to have a way of differentiating between these two keyboards, but as far as I see I can only differentiate by vendor model, so they both are interpreted as the same keyboard.

The question is if there is a way to differentiate them somehow. I've seen they have different serial number, maybe I can add one if and one field in structure to get that functionality, but maybe it is already there.

Is there a way to add serial_number to complex manipulations? I think I added a few lines to `device.hpp` to make it work but the build is failing miserably and I am no way C++/ObjC hero to make sense of these traces.
Maybe this idea is garbage because comparing these values will be too costly or too time-consuming, cause int and bool comparisons are performed right off the but whereas string might not be that fast.

I know how annoying are questions in the issue, but I thought my question is very specific, and if I find a solution I will try to post a PR :)

Have a good day!

**Comment by wmertens** [comment]
I requested tying a profile to a BT id, that would solve this, right? #2022

**Comment by adamczyk777** [comment]
I guess yes, I didn't dive too deep into implementation details so You may have a point here 😄
