### ISSUE TITLE
Multitouch Extension does not seem to have any effect

### ISSUE THREAD

**Issue by mbert** [pqrs-org/Karabiner-Elements#2009]
Maybe I do not understand something properly. I expect areas on my touchpad to be completely ignored after having set ignored areas in Karabiner-Multitouch Extension. This is not the case here. The extension's GUI shows that I am moving the mouse cursor within the ignored area, but the cursor behaves totally normally, and I can also tap (which is what I really want to prevent because I often get cursor jumps when typing). 

Any idea what the problem is? Or am I expecting something that the software is actually not expected to do? 

I am using a MBP with Mojave.

**Comment by longbill** [comment]
+1

**Comment by daylight54** [comment]
+1

**Comment by mbert** [comment]
The problem has not been solved. I would rather not want to see the issue closed as "stale".

**Comment by longbill** [comment]
The problem has not been solved. I would rather not want to see the issue closed as "stale".

**Comment by radartomx** [comment]
+1

**Comment by ToastedIceCream** [comment]
The problem has not been solved. I would rather not want to see the issue closed as "stale".

Karabiner-Elements version: 12.9.3
macOS Catalina:  version: 10.15.4 (19E287)

**Comment by pushpendre** [comment]
The problem has not been solved. I would rather not want to see the issue closed as "stale".

**Comment by DanielAsher** [comment]
Multitouch Vi Mode (rev 2) not working on:
```
System Version:	macOS 10.15.3 (19D76)
Kernel Version:	Darwin 19.3.0
```

**Comment by tahamr83** [comment]
Still not solved

**Comment by ryanoboril** [comment]
Not solved on macOS Catalina 10.15.7

Is this project still being maintained?

**Comment by tahamr83** [comment]
I think so. The commits history shows _some_ activity.

**Comment by jeremylukebennett** [comment]
Same issue on my end, too. 
MacBook Pro (2019)
macOS 11.6.5

**Comment by jbyler** [comment]
For people commenting on this ticket: this Multitouch Extension works fine for me. Do you have any Complex Modifications in your config that use it? For example, are you using the [Multitouch Vi Mode (rev 2)](https://ke-complex-modifications.pqrs.org/#multitouch_vi_mode)? There is documentation for how to use the extension in the docs at [MultitouchExtension integration](https://karabiner-elements.pqrs.org/docs/json/extra/multitouch-extension/). It won't have any effect unless you have some config that uses it.
