### ISSUE TITLE
 Karabiner-Elements  stop sworking after sleep on macOS Mojave. 

### ISSUE THREAD

**Issue by STEVEK750** [pqrs-org/Karabiner-Elements#2010]
Karabiner-Elements 12.7.0   macOS 10.14.6 MacBookAir 2018 internal keyboard
 Disable Left_Shift key works with freshly loaded Karabiner, but fails after sleep.

**Comment by quanganhdo** [comment]
I see this on Catalina beta as well.

**Comment by rahulbir** [comment]
+1 looks like Karabiner-Elements cant recognize my keyboard device after my machine has gone to sleep.

**Comment by sskylar** [comment]
+1

**Comment by quanganhdo** [comment]
For now my workaround is to run `sudo killall karabiner_grabber` to restart the app each time it stops working.

**Comment by badalsaibo** [comment]
I remember the old version working completely fine with Mojave, so I recently downloaded Karabiner version 11.6.0 and surprisingly it works fine all the time.

I needed to allow this app from the Security and Privacy menu in settings for the first time and that's it. No more issue after waking from sleep too!

https://karabiner-elements.pqrs.org/docs/releasenotes/#karabiner-elements-1160
