### ISSUE TITLE
The combination of "CMD+F1" in built-in keyboard doesn't work after karabiner was installed.

### ISSUE THREAD

**Issue by elsdy** [pqrs-org/Karabiner-Elements#2011]
I installed karabiner for using real-force keyboard. 

and I got an error with that
: The combination of "CMD+F1" in built-in keyboard doesn't work after karabiner was installed.

But the combination of "CMD+F1" is working on the real-force keyboard. 

I uninstall karabiner then the "CMD+F1" on built-in keyboard is working... 

I am sure that installing karabiner affect that. :) 

What I want is that
1. installing karabiner for using Real-force keyboard
2. "CMD+F1" combination is working on built-in keyboard

How am I supposed to do?

**Comment by sgronblo** [comment]
I am also experiencing problems with the combination of cmd + function keys with the most recent version of karabiner elements (12.7.0). I think this was working until recently.

I can see it when setting attempting to set up cmd+f8 as a keyboard shortcut in VSCode. While holding cmd the shortcut creation dialog shows "cmd" then when I press f8, the "cmd" disappears and I am left with only "f8".
