### ISSUE TITLE
Unexpected mouse buttons behaviour

### ISSUE THREAD

**Issue by blaszczakphoto** [pqrs-org/Karabiner-Elements#2013]
## General description of the problem
Running karabiner-elements makes my mouse to behave weird. Sometimes when I select test, with left mouse button, it does button_up unexpectedly, so the selection fails.

Sometimes it button_up and button_down again, so my text become mess.

Sometimes the single mouse click become double click, so for example when I archive one email with single left button click, it archives 2 emails. It is very annoying. 

## Workaround
Restarting Karabiner-Elements helps for a short period of time, but after a while the mouse starts the behave weird again.

## Other information:
MacBook Pro (Retina, 13-inch, Early 2015)
MacOs Mojave 10.14.5
Karabiner-Elements 12.7.0

## Devices
The same things happen with different mouses.\

## Log from EventViewer while dragging
```
type:button_down     code:0          name:button1         misc:{x:1779,y:106} click_count:1
type:mouse_dragged   code:0          name:button1         misc:{x:1783,y:103} click_count:1
type:mouse_dragged   code:0          name:button1         misc:{x:1787,y:100} click_count:1
type:mouse_dragged   code:0          name:button1         misc:{x:1792,y:97} click_count:1
type:button_up       code:0          name:button1         misc:{x:1792,y:97} click_count:0
type:button_down     code:0          name:button1         misc:{x:1800,y:93} click_count:1
type:mouse_dragged   code:0          name:button1         misc:{x:1803,y:91} click_count:1
type:mouse_dragged   code:0          name:button1         misc:{x:1805,y:90} click_count:1
type:mouse_dragged   code:0          name:button1         misc:{x:1806,y:89} click_count:1
```

### Log when single click is like double click
```
type:button_down     code:0          name:button1         misc:{x:751,y:88} click_count:1 
type:button_up       code:0          name:button1         misc:{x:751,y:88} click_count:1 
type:button_down     code:0          name:button1         misc:{x:751,y:88} click_count:2 
type:button_up       code:0          name:button1         misc:{x:751,y:88} click_count:2 
```

Anyone can help with this?

**Comment by bennals** [comment]
I've just experienced this same issue with a single click being interpretted as a double click.  Restarting Karabiner also fixes the problem temporarily.
