### ISSUE TITLE
macOS Catalina and AWS WorkSpace double keys

### ISSUE THREAD

**Issue by predmijat** [pqrs-org/Karabiner-Elements#2019]
Hey,

After upgrading to macOS Catalina (10.15), there's an issue with AWS WorkSpace: sometimes (not always), it would start registering each key press twice.

I have to quit Karabiner-Elements, start it again, and then it's fine. Until it breaks again (not sure what's the reason).

Karabiner-Elements version: latest (12.7.0)

**Comment by gschoonheim** [comment]
Indeed, on Catalina AWS WorkSpace is registered in Security & Privacy > Input Monitoring just like Karabiner. 

If I have Karabiner grabber / observer enabled in the Security & Privacy > Input Monitoring together with AWS WorkSpace then things go wrong. Result is that most keypresses are double and that I have to disable Karabiner. 

If I remove AWS WorkSpace from Input Monitoring then I don't get any keypresses / keyboard doesn't work there.

Hope this helps in tracking down the bug.

**Comment by thaddeusa** [comment]
I'm having the same issue. If I quit karabiner and restart it, it works fine but only until I switch apps to anything other than Workspaces. As soon as I return to Workspaces, I get duplicate characters again. Very frustrating. I appreciate any assistance and please let me know if there's any additional information I can provide.
