### ISSUE TITLE
Complex modifications problems on Catalina

### ISSUE THREAD

**Issue by mn3k** [pqrs-org/Karabiner-Elements#2020]
Stop working "Complex modifications" after change user with Fast User Switching.
It works again by re-login.

OS: macOS Catalina 10.15
Karabiner: 12.7.0
Keyboard: PFU HHK Professional 2

**Comment by optimus1509** [comment]
I am facing this issue too. Any fix?

**Comment by mn3k** [comment]
This issue seems fixed in version 12.8.0. Thank you!
