### ISSUE TITLE
Karabiner Stopped working after updating to Catalina (virtual_hid_device_client not connected yet)

### ISSUE THREAD

**Issue by hongjun0107** [pqrs-org/Karabiner-Elements#2021]
Hi, I have just updated to Catalina recently and Karabiner stopped working.

I have tried restarting the Mac, tried re-installing Karabiner-Elements and also tried updating Karabiner to beta version 12.7.2 but still does not work.

Version: 12.7.0 (and 12.7.2) (Both does not work)
OS 10.15

This is the message that i keep seeing. 
Error: virtual_hid_device_client is not connected yet. Please wait for a while.
[info] [kextd] KextManagerLoadKextWithURL: kOSKextReturnAuthentication

Could anyone please help? or is anyone facing a similar issue?

Thank you!

**Comment by tekezo** [comment]
It might be caused by corrupted system cache of macOS.

Try to restart your Mac in safe mode in order to refresh macOS system caches.
Then, I believe you can see the button after restart in normal mode.
(Press and hold the Shift key at boot)
https://support.apple.com/en-us/HT201262

If not, please reinstall Karabiner-Elements after restart in normal mode.

Note:
Safe mode boot takes a long time (~ 10 min) if you enabled Time Machine because safe mode checks all Time Machine snapshots.
Please do it with time to spare.

**Comment by hongjun0107** [comment]
@tekezo Hey tekezo, Thanks for the prompt and detailed reply. 

By the way, what do you mean by "the button" in your 3rd line? Which button are you referring to?

Okay, so I have tried restarting my mac into the safe mode, and then restarted into normal mode.
But I still faced the same issue with the same error message that states:

[2019-10-11 23:32:58.786] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
[2019-10-11 23:32:59.675] [info] [kextd] KextManagerLoadKextWithURL: kOSKextReturnAuthentication

and i keep seeing: 
[2019-10-11 23:37:02.957] [info] [kextd] KextManagerLoadKextWithURL: kOSKextReturnAuthentication
[2019-10-11 23:37:06.159] [info] [kextd] KextManagerLoadKextWithURL: kOSKextReturnAuthentication

So I have also tried re-installing Karabiner-elements after restarting, and also tried the beta version but both does not work with the same error. 

Is there any other possibility? I have attached some snapshot for reference.
<img width="744" alt="Screenshot 2019-10-11 at 11 39 53 PM" src="https://user-images.githubusercontent.com/44223800/66665153-8b62fc80-ec80-11e9-9822-6a9799f7789e.png">
<img width="985" alt="Screenshot 2019-10-11 at 11 40 09 PM" src="https://user-images.githubusercontent.com/44223800/66665154-8b62fc80-ec80-11e9-84b2-99b1b169785f.png">

**Comment by tekezo** [comment]
It seems there is some error around loading kext.
Could you execute the following command in Terminal app?
(The root password will be required in order to run kextutil command.)

```shell
sudo kextutil -t '/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext'
```

**Comment by hongjun0107** [comment]
Hi, thanks for getting back to me.

I could not execute the command as I have this message (as pasted below).
Would there be a way to resolve this? Thanks so much for your patience.

Kext rejected due to insecure location: <OSKext 0x7fc186c67430 [0x7fff94087d10]> { URL = "file:///Library/StagedExtensions/Library/Application%20Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext/", ID = "org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000" }
Kext rejected due to insecure location: <OSKext 0x7fc186c67430 [0x7fff94087d10]> { URL = "file:///Library/StagedExtensions/Library/Application%20Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext/", ID = "org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000" }
Diagnostics for /Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext:


![Screenshot 2019-11-25 at 4 50 57 PM](https://user-images.githubusercontent.com/44223800/69525774-c9538000-0fa3-11ea-8b92-95aa7e772cd6.png)

**Comment by amit-handda** [comment]
I am facing similar issue
:(
