### ISSUE TITLE
Process still running after quit - Edit Cannot perform a clean uninstallation

### ISSUE THREAD

**Issue by zrfrank** [pqrs-org/Karabiner-Elements#2024]
After quit the Karabiner app, i.e. by right click and select quit.
The background process are still running. And they cannot be quit, and cannot be force quit.

 karabiner_session_monitor
 karabiner_observer
 karabiner_grabber
 karabiner_kextd
 karabiner_observer
 karabiner_grabber

Proposal: All processes should be able to be terminated once the app is quit, at least there should be a CLI to quit them entirely.

---edit---
OS: Catalina

**Comment by tekezo** [comment]
Please quit from menu bar or Misc tab in Preferences.
https://pqrs.org/osx/karabiner/document.html#quit

**Comment by zrfrank** [comment]
I tried both methods. But those process are still running and cannot be force quit even.

**Comment by zrfrank** [comment]
In addition, https://pqrs.org/osx/karabiner/help.html#installed-files
said installed files are
```
/Library/Application Support/org.pqrs/Karabiner-Elements
/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice
/Library/Application Support/org.pqrs/config
/Library/Application Support/org.pqrs/tmp
/Library/LaunchDaemons/org.pqrs.karabiner.karabiner_grabber.plist
/Library/LaunchAgents/org.pqrs.karabiner.karabiner_console_user_server.plist
/var/log/karabiner
```

However, In my `/Library/LaunchDaemons/`, I have

```
org.pqrs.karabiner.karabiner_observer.plist
org.pqrs.karabiner.karabiner_kextd.plist
org.pqrs.karabiner.karabiner_grabber.plist
```

In `/Library/LaunchAgents/`

```
org.pqrs.karabiner.karabiner_session_monitor.plist
org.pqrs.karabiner.karabiner_console_user_server.plist
org.pqrs.karabiner.agent.karabiner_observer.plist
org.pqrs.karabiner.agent.karabiner_grabber.plist
```

**Comment by zrfrank** [comment]
After uninstall, using the app's uninstall button. And performing an restart, there is no karabiner background process running.
Although, the following folder/files still remaining:

In folder, `/Library/Application Support/org.pqrs/tmp` 
```
karabiner_observer_state.json
karabiner_kextd_state.json
karabiner_grabber_state.json
karabiner_grabber_manipulator_environment.json
karabiner_grabber_devices.json
karabiner_grabber_device_details.json
karabiner_grabber_alerts.json
rootonly
pid
karabiner_console_user_server
```

In /Library/LaunchDaemons/,
```
org.pqrs.karabiner.agent.karabiner_observer.plist
org.pqrs.karabiner.agent.karabiner_grabber.plist
```

And `/var/log/karabiner`

Also there is a folder not stated by the documentation that's still remaining,

```
/Library/StagedExtensions/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice
```
And this folder cannot be deleted using normal procedure without sudo permission.


Please investigate this issue.

Many thanks,
