### ISSUE TITLE
Is there a key listener with Karabiner ?

### ISSUE THREAD

**Issue by Aarbel** [pqrs-org/Karabiner-Elements#2028]
# Is there a key listener with Karabiner ?

Key mapping is much simpler than knozing the exact ids / modifiers to change them.
For example VsCode key mapper is really great for that.

I want to map `alt + 3` to the special character `é`, it seems a mess to achieve that with karabiner without entering advanced config and documentation reading.

Am i missing a part of the features ?

**Comment by haakonstorm** [comment]
I'm rather a karabiner rookie myself, but try ``goku``. Install with:
`brew install yqrashawn/goku/goku`

**Comment by pukoh** [comment]
Yes! This is what the program is missing. I bluetooth keypad that has esc/tab/=/clear above the number pad that I want to remap to the fn keys. I don't know what those keys are in the drop down list.

**Comment by haakonstorm** [comment]
You guys tried `Karabiner-Eventviewer` that came bundled with `Karabiner-Elements`, right? 

<img width="883" alt="Screenshot of Karabiner-EventViewer (19-10-2019, 17-50-59)" src="https://user-images.githubusercontent.com/193781/67147858-194e7100-f299-11e9-9149-ae88efdfe890.png">
