### ISSUE TITLE
ctrl + any_key not working

### ISSUE THREAD

**Issue by faflo** [pqrs-org/Karabiner-Elements#2031]
I have used karabiner elements for years, but recently (not sure when it started), (left) ctrl on my macbook pro does not modify the key that is pressed with it anymore. 

*Although* Karabiner Eventviewer clearly recognizes it as "left_control" and the modified key plus "flags:left_control", respectively. 

But if I go into e.g. Terminal and want to do ctrl + r for reverse search or ctrl + c for interrupting a running process, it just gives me "r" or "c". Only when turning off Karabiner Elements does it work again, so it is clearly an issue with Karabiner. 

Edit: 
System: MacOS Sierra 10.12.6, Late 2013 Macbook Pro
Karabiner Elements version: 12.7.0
Only Key I have modified so far is right_alt, but the issue persists even if I remove all modifiers

**Comment by pukoh** [comment]
I have this issue too. no modifier keys (cmd ctrl opt) work with a remapped key.

**Comment by moebiusc** [comment]
I think I have a similar issue.
I am trying to remap my end key to ctrl + right arrow to switch desktops.
```json
{"description": "End to right Desktop",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "end",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_control",
                                        "modifiers": [
                                            "right_arrow"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
```

Or is my rule just wrong?

Mac OS Mojave 1.14.6,  Early 2015 MacBook Pro
Karabiner Elements 12.7.0

**Comment by faflo** [comment]
I solved my problem by going back to an earlier version of my system and resetting all keyboard related settings, then reinstalling karabiner. No idea what it was, though.

**Comment by jeannen** [comment]
Experiencing this issue now, is there a fix?
