### ISSUE TITLE
I am admittedly stupid but how do profiles work?

### ISSUE THREAD

**Issue by hawkiboy** [pqrs-org/Karabiner-Elements#2039]
The interface has changed over the years and I find I am wasting a lot of time trying to figure out where things have gone to....

Why is it that when you create or select a profile, that profile is not visible anywhere when you are trying to set modifiers. Instead I am presented only with keyboards that are detected being attached to my computer and not the profiles. Possibly this is just an odd decision from a UI Design perspective, but I am wondering if I am missing something...

**Comment by hazz1925** [comment]
Profiles is used to save keyboard configurations for different people. You can quickly change your profile from the bar besides your wifi icon at the top to quickly change your keyboard configs.
