### ISSUE TITLE
How to Change F3 from Mission Control to Notification Center

### ISSUE THREAD

**Issue by ChaunceyDong** [pqrs-org/Karabiner-Elements#2044]
Mac OS 10.15 & Karabiner-Elements 12.7.0
Hey! I just want to ask how to change F3 to open Notification Central. 
Thanks!!

**Comment by iZero7** [comment]
+1
maybe a workaround for now can be using macos internal functionality of keyboard shortcuts

**Comment by covertoperator** [comment]
<img width="780" alt="Screen Shot 2019-11-14 at 1 01 54 PM" src="https://user-images.githubusercontent.com/21234182/68895810-f15afd80-06de-11ea-8c9c-6aac725c6edf.png">
