### ISSUE TITLE
Caps lock misbehave in Catalina

### ISSUE THREAD

**Issue by Hologos** [pqrs-org/Karabiner-Elements#2046]
Hi,

I am experiencing problems with Caps lock on Catalina on both my hackintoshes. Once I press Caps lock, it works as expected but the LED stays on forever. If I restart the Karabiner Element, I get `Keyboard is ignored temporarily until {"key_code": "caps_lock"} is pressed again` message and Caps lock doesn't work.

Has anyone else experiencing the same issue?

My hackintoshes are HP Elitebook 840 g3 and HP Probook 650 g1 (both on Catalina now).

**Comment by kinoute** [comment]
I have the same problem/message on my hackintosh running 10.14.6 after updating from Karabiner Elements 12.3.0 to 12.7.0. I rollbacked to 12.3.0 because i couldn't stand the notification window showing every time I use the caps lock key.

**Comment by Hologos** [comment]
I noticed that the problem disappeared. I don't know which kext update fixed that, I'll try to find out on the other laptop.
