### ISSUE TITLE
Additional media keys support

### ISSUE THREAD

**Issue by 0x15e** [pqrs-org/Karabiner-Elements#2052]
There are a few media keys on my PC keyboard that I'd like to remap but I don't think they're currently detected / supported by Karabiner-Elements. The one I specifically want is calculator (HID scan code 0xfb according to [this gist](https://gist.github.com/MightyPork/6da26e382a7ad91b5496ee55fdc73db2#file-usb_hid_keys-h-L285)) but I think there are a few others as well.

Is it possible to support the rest of those values? I know at least some of them are coming through because the volume and play / pause keys are working but I haven't been able to get "calculator" to do anything.

**Comment by bland328** [comment]
Just in case @0x15e or anyone else is helped by this, I've also been working on remapping my PC keyboard media keys, and have had _some_ success.

I eventually noticed that under the Devices tab of Karabiner-Elements Preferences, my keyboard _(an iKBC CD108)_ is seen as both a keyboard _and_ a mouse...

<img width="888" alt="Screenshot.png" src="https://user-images.githubusercontent.com/8441277/70836845-30a46900-1dc7-11ea-837c-946c124e7cdb.png">

...but the mouse functionality checkbox is off by default.

Once it was turned on, I was able to use Karabiner to remap `mute` _(consumer key code `0xE2`)_, `volume_decrement` _(consumer key code `0xEA`)_ and `volume_increment` _(consumer key code `0xE9`)_.

However, Karabiner still doesn't see keypresses from my Calculator key, which, according to [some Darwin source](https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-421.6/IOHIDFamily/IOHIDUsageTables.h.auto.html) is apparently consumer key code `0x192`:

`kHIDUsage_Csmr_Mute    = 0xE2,    /* On/Off Control */`
`...`
`kHIDUsage_Csmr_VolumeIncrement    = 0xE9,    /* Re-Trigger Control */`
`kHIDUsage_Csmr_VolumeDecrement    = 0xEA,    /* Re-Trigger Control */`
`...`
**`kHIDUsage_Csmr_ALCalculator    = 0x192,    /* Selector */`**

@tekezo, is there any chance of adding support for `kHIDUsage_Csmr_ALCalculator` _(consumer key code `0x192`)_? Or is it consumed before it can get to Karabiner?

**Comment by tekezo** [comment]
These keys are dropped by macOS kernel as far as my investigation, unfortunately.

If macOS became to pass through these keys, Karabiner-Elements can handle them.
(Karabiner-Elements does not drop them.)

**Comment by 0x15e** [comment]
@tekezo well that's unfortunate. Thank you very much for looking into it though!
