### ISSUE TITLE
Karabiner would be much way more popular, agile and modifiable if you do 2 things:

### ISSUE THREAD

**Issue by bondvt04** [pqrs-org/Karabiner-Elements#2053]
1. Please add possibility to add rules for particular apps. I trying to add WASD layout to my Warhammer 40000 video game and its pain.
2. Please add possibility to add your rules not only from here: https://pqrs.org/osx/karabiner/complex_modifications/
I don't want to do PRs and WAIT until approvement and before I can actually check it. It would be nice to have ability to just update your JSON and add it.

Seriously, this 2 things is a big obstacles to use this app. Do this and many of ppl will use it. Agility.

**Comment by meixuesong** [comment]
For the second thing, I did the following and it works:

1. import a rule from the https://pqrs.org/osx/karabiner/complex_modifications/

**Comment by bondvt04** [comment]
Thank you, @meixuesong ! Nice tip.

**Comment by babygau** [comment]
@bondvt04 spend time on its documentation, you definitely could do it with a few lines of code, there are already rules for you to do so.
