### ISSUE TITLE
FingerStatusManager.m: MultitouchExtension Ignored area detection is inconsistent

### ISSUE THREAD

**Issue by aerobounce** [pqrs-org/Karabiner-Elements#2054]
# Env

- macOS 10.15.1 (19B88)
- MacBook Pro (15-inch, 2016)
- Karabiner 12.7.0

# Steps to reproduce

1. Set whatever number to Ignored areas in `Karabiner-MultitouchExtension`
2. Touch ignored area repeatedly and you will find at some point, touch condition indicates that it is **not ignored** (Red coloured).

### Points

- Seemingly, amount of ignored area of each side is not the key. Whatever it is, it works inconsistently.
- Ignore detection sometime works, sometimes not. Inconsistent.
- Not certain, but if touched point is at the edge of rect, more likely it will fail to ignore touch even the touched location is in ignored area. 

# Supposedly responsible file / method

https://github.com/pqrs-org/Karabiner-Elements/blob/b174d1e4274f9271a5b24fde1cf640305b12144a/src/apps/MultitouchExtension/src/FingerStatusManager.m#L35-L40

# Problem

Karabiner organically blocks original key press event if the app has rules that utilizes multitouch-count. So when _touch-detection_ is not what a user is intended, that is quite annoying.

# In my case

I use MacBook Pro the one with large trackpad.  
When I'm typing, usually part of my palm is touching trackpad.  

I have set `T` + `1 touch` == `CMD + T`.  
You know what will happen.  
A new tab is opened when I type `T` when I'm not intended so. :(

**Comment by aerobounce** [comment]
And If I remember correctly, KeyRemap4MacBook and old Karabiner had the same bug.

**Comment by tekezo** [comment]
I confirmed this issue.
I'll investigate the detail of cause. Please wait for a while.

**Comment by tekezo** [comment]
I fixed this issue at the latest beta version (v12.7.4).
Please confirm it.

How to upgrade Karabiner-Elements to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by aerobounce** [comment]
I appreciate your work @tekezo. 👍🏻

I've installed v12.7.4 and so far, at least the bug is no more reproducible in Karabiner-MultitouchExtension app.
Let give me sometime to confirm that it is also okay in practice use / everyday use. I use multitouch rules intensively so it suppose won't take much time.

**Comment by aerobounce** [comment]
So it's been 2 or 3 days since I've installed v12.7.4 which includes fix for this issue.
In a word, **ROBUST** 💪🏻.
I've had no mis-detection! **NOT EVEN ONCE**. 👍🏻

I'm sure this issue is fixed now. Thanks again, @tekezo !
I'm closing this issue now.

**Comment by tekezo** [comment]
Thank you for confirmation!
