### ISSUE TITLE
Switching two keys is not working anymore

### ISSUE THREAD

**Issue by coletz** [pqrs-org/Karabiner-Elements#2056]
Hi, I am using karabiner to switch non_us_backtick and grave_accent_and_tilde because they are inverted on my keyboard. So I have 2 entries on karabiner (simple modification tab), one *from key* non_us_backtick *to key* grave_accent_and_tilde and one *from key* grave_accent_and_tilde *to key* non_us_backtick. If I use only one of these two mod it is working, if I use both together they are not working. Same setup was working fine about 2 weeks ago. Any idea on what could cause the issue? Or there's a different setting for switching keys? Thanks

**Comment by soulomoon** [comment]
same here simple change pageup to volumn up is not working anymore, it happend in my mbp after the recent update to 10.15.1 (19B88)
