### ISSUE TITLE
Avoid JSON strict check?

### ISSUE THREAD

**Issue by patrickwelker** [pqrs-org/Karabiner-Elements#2057]
Is there a way to prevent or toggle off the strict check introduced in Karabiner-Elements 12.3.0?

I use an additional `_comment` key in my JSON file to have a more descriptive, easily foldable and manageable complex modifications file: 

![](https://f.v1.n0.cdn.getcloudapp.com/items/3x303K0V2C1w2L163r0n/karabiner-elements--strict-check--comments.png)

Otherwise my file gets parsed without errors, but I can't upgrade because of "Unknown key" and "Invalid type" errors…

```
[2019-11-11 10:09:10.926] [error] [grabber] complex_modifications json error: Unknown key: _comment in {"_comment":"Show Menubar in Context Menu"}
[2019-11-11 10:09:10.926] [error] [grabber] complex_modifications json error: Invalid type in to_event_definition: {"_comment":"Show Menubar in Context Menu"}

```

**Comment by tekezo** [comment]
There is not a plan, unfortunately.

I recommend using json generator if you write much rules which need comments.
Example: https://github.com/yqrashawn/GokuRakuJoudo

**Comment by schmidhauser** [comment]
Why not substitute `_comment` by `description`?

**Comment by patrickwelker** [comment]
> Why not substitute `_comment` by `description`?

Thanks to @schmidhauser I upgraded from Karabiner-Elements 12.2.0. to the latest version.

I haven't thought of this. Sometimes the answer is right in front of one.
