### ISSUE TITLE
don't support macro keys in Razer gaming keyboard

### ISSUE THREAD

**Issue by aszx0413** [pqrs-org/Karabiner-Elements#2058]
First of all, thanks for this great software. 
Can this support macro keys in Razer gaming keyboard?
I have a Razer BalckWidow, And I want to control M1 to M5 as a macro function. Like Razer Synapse did.
![image](https://user-images.githubusercontent.com/2009321/68641833-10268c00-0547-11ea-8125-124d7cf117f7.png)

**Comment by covertoperator** [comment]
If nothing shows up when you press the key in Karabiner-EventViewer, then it cannot. (unless you do a set up with Razer's software, then.. maybe)
