### ISSUE TITLE
Delay after alone press of caps lock

### ISSUE THREAD

**Issue by pricheal** [pqrs-org/Karabiner-Elements#2059]
I am using the complex modification rule that changes caps lock to be control if pressed with other keys and escape when pressed alone. It is working correctly, but there seems to be a slight delay when I hit caps lock alone (as escape) between the time I actually hit the key and when the escape event happens. I have played with the parameters and nothing seems to change this.

My desired behavior is really any alone up and down of the caps lock key under 1 second should instantly fire the escape, and after the 1 second it turns into a ctrl key hold. If the caps lock is held with another key within that 1 second it should be a ctrl. Is there a way to do this so I don't have any delay when I hit escape by itself?

**Comment by henrikskog** [comment]
@pricheal  Did you ever find a solution to this?
