### ISSUE TITLE
How to map key_code to consumer_key+key_code+modifier?

### ISSUE THREAD

**Issue by demharusnam** [pqrs-org/Karabiner-Elements#2061]
I am trying to map the page_up button to shift+control+eject for my macbook (shift+control+eject puts my mac to sleep). Here is the complex modification code I have:

`"complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": [
                    {
                        "manipulators": [
                            {
                                "description": "Change page_up to shift+control+eject",
                                "from": {
                                    "key_code": "page_up",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "consumer_key_code": "eject",
                                        "key_code": "shift",
                                        "modifiers": [
                                            "left_control"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            }`

And the error I get from the event viewer is: 

> [2019-11-13 15:09:43.997] [error] [grabber] karabiner.json error: `to` entry error: multiple types are specified: `{"consumer_key_code":"eject","key_code":"shift","modifiers":["left_control"]}`

Thank you for your help!

**Comment by covertoperator** [comment]
is the 'power' option in simple modifications, not good enough? It puts your mac to sleep if tapped and powers off if held down for 6 seconds.

**Comment by demharusnam** [comment]
Thank you!! Changing shift to a modifier fixed!
