### ISSUE TITLE
tilde forcefully remapped to paragraph §

### ISSUE THREAD

**Issue by eba-ts** [pqrs-org/Karabiner-Elements#2071]
This is somewhat similar to https://github.com/pqrs-org/Karabiner-Elements/issues/1753 but is not solved with reboot

I've been using Karabiner-Elements on macos to swap fn and control. It was being super positive experience since yesterday. 

Yesterday I connected an external USB keyboard with has some Danish keys next to enter, as well as added Danish as input source. Now I have an issue, even after I both disconnected the keyboard and removed the input source. 

**Issue:** when I press tilda key, trying to get _grave accent_ character (reversed '), I get §
Pressing shift+tilda gives ± 
Both are exactly the characters engraved on danish built-in keyboards for mac pro's (my colleagues have some). 

Issues disappears if I "Quit Karabiner-Elements" and returns when I start it. 

Reboots, kill -9, updating to the 12.8, removing _~/.config/karabiner/karabiner.json_ did not help. 

The only guess about 'leftovers' I have - I see a device in Karabiner, which _might_ be the keyboard in question (or any other keyboard - while the danish one was probably the only one I attached in 10month I have laptop)

![image](https://user-images.githubusercontent.com/14124598/69059688-4caa2a00-0a16-11ea-97e6-cc5a747ebf95.png)

**Below are technical details**
version 12.8.0
macOS Mojave 10.14.6 (18G103) 
MacBook Pro (15-inch, 2017) regular US keyboard 
hardware keyboard - don't have any anymore (detached)

![image](https://user-images.githubusercontent.com/14124598/69059675-4156fe80-0a16-11ea-859b-39208ccf59bc.png)

![image](https://user-images.githubusercontent.com/14124598/69059710-5b90dc80-0a16-11ea-95ac-6cdf3fc418d8.png)

**Comment by eba-ts** [comment]
Weird staff I don't understand. I noticed § on the screenshot with Input sources above
Quite Karabiner-Elements, added US input source one, started KE issue persisted
removed US input source
The issue still there, but the picture shows proper character

![image](https://user-images.githubusercontent.com/14124598/69060112-1b7e2980-0a17-11ea-945f-7c10046a9ef5.png)

**Comment by eba-ts** [comment]
Some of you might have noticed § on the screenshot above, showing Input elements

It shows there when I press Shift as part of Cmd+Shift+4 and  esc key removes it back
This happens with KE running, if I quit KE it does not behave like that.

Below is the shot taken with Screenshot app, not using any hotkeys
<img width="1008" alt="Screen Shot 2019-11-18 at 15 26 36" src="https://user-images.githubusercontent.com/14124598/69060594-e6260b80-0a17-11ea-88cb-dc3994ebf88f.png">

**Comment by eba-ts** [comment]
Found this thread https://groups.google.com/forum/#!topic/osx-karabiner/5QeXanhNxj4
Tried, did not work
![image](https://user-images.githubusercontent.com/14124598/69074221-3d83a600-0a2f-11ea-9c63-e253e49c3961.png)

**Comment by eba-ts** [comment]
Found this https://github.com/pqrs-org/Karabiner-Elements/issues/450

Applied the fix and it helped 
![image](https://user-images.githubusercontent.com/14124598/69585483-20774600-0fe0-11ea-95f8-1c9de0f9984f.png)

**Comment by thatRobR** [comment]
I honestly feel like this issue should be re-opened, I just had the same problem using a Mac with US keyboard and DK and US English layouts enabled.

I've tried the above mentioned attempts at solving it and only the last most solution helped me.

The issue only just surfaced for me after using Karabiner for a long while, yet I haven't changed anything about my setup other than an update to macOS.

**Comment by yspreen** [comment]
I second this. I recently updated my macOS and my karabiner so it's hard which of those two caused the issue.

But hitting **`** resulted in **§** getting pressed. Swapping non_us_backslash and grave_tilde solved the issue.

**Comment by ezekini** [comment]
I have a US keyboard (switching between US and Spanish in Mac OS) and the problem persists with either language.

**Comment by SamuelPinho** [comment]
I faced the same issue today and it was because my country settings were wrong for some reason
<img width="641" alt="image" src="https://github.com/user-attachments/assets/43ed5b77-b0c4-4554-bbfd-27642a080499">

**Comment by zyriab** [comment]
I had the same issue and solution as @SamuelPinho 
If you want to change your keyboard type, you can find the option in "Virtual Keyboard" in the menu on the left.
![image](https://github.com/user-attachments/assets/56dd5e60-02a7-42ae-8039-07a87f173fbe)

**Comment by mridulks** [comment]
I faced this issue just few days ago after updating KE. Just now solved this by changing the keyboard type to ANSI. Thanks to @SamuelPinho.

**Comment by itsdaiego** [comment]
+1 to @SamuelPinho  solution, thank you :) took me a while to figure this out!

**Comment by JesalR** [comment]
Also have this issue. Have an ISO keyboard but have to set it to ANSI to get the tilde in the correct position. This seems like a bug

**Comment by andru** [comment]
I've been using Karibener for years and today, without any changes to my config, this bug just popped up. I have a UK Macbook, with the backtick/tilde key next to left shift.

Today it started outputting § instead.

In settings, my keyboard is set as as ISO as it always has been.

Setting it to ANSI appears to fix the issue, though I think the UK Macbook keyboard is closer to ISO than it is ANSI.

**Comment by TxHawks** [comment]
Having the same issue as @andru, but with a proper ISO keyboard, so changing to ANSI isn't a solution for me

**Comment by chrisstuartparry** [comment]
Yep, same here - ISO UK MacBook Pro built-in keyboard basically swaps ` and § keys when Karabiner-Elements is running. I have Karabiner-Elements' virtual keyboard set to the "ISO" setting, and this issue is fixed when changing it to "ANSI", but this is opposite to what should be the case.

**Comment by norrila** [comment]
Same here with ISO swedish Macbook pro. I just updated Karabiner and it reset my keyboard settings in Karabiner to ISO and it messed up my <> key with tilde key. Google led me here and thankfully a solution. Setting to ANSI fixed the problem.

**Comment by enizvk** [comment]
Same here. US keyboard, mac book pro and Logitech Mx Keys.
Changing to ASCII helped but creates other issue for me as I am more ISO Europe.

**Comment by solemgar** [comment]
This helped, thanks a lot!

**Comment by solemgar** [comment]
> Same here. US keyboard, mac book pro and Logitech Mx Keys. Changing to ASCII helped but creates other issue for me as I am more ISO Europe.

which issues , just curious :)

**Comment by elizabethpretzel** [comment]
M1 Macbook Air, British keyboard, same issue. I only have one modification in Karabiner (fn + f1/f2 control keyboard backlight).

I kept my virtual keyboard setting to ISO as I didn't want to cause any more issues, but the following works for now. As others have said, Karabiner viewer showed the keystrokes as "correct" but the output was mixed up. Viewer shows them as wrong now, but they work fine. 

<img width="1092" alt="Image" src="https://github.com/user-attachments/assets/ef570bba-755d-4882-afff-7017127dada2" />

**Comment by joshwcomeau** [comment]
M4 Macbook Pro Max, same issue. The issue persisted even after uninstalling Karabiner, which is concerning 😬

Info:
- Karabiner-Elements 15.4.0
- macOS Sequoia 15.4.1
- Keyboard is a NuPhy Halo 75, though the issue occurs on the built-in keyboard as well as another external keyboard so I don't think it's keyboard-specific

**Comment by AnubisGreat** [comment]
My God, thank you. I have (magic keyboard) again tilde! Changed to ANSI!

**Comment by StErMi** [comment]
Hi, I have an Italian macbook pro M3 and this issue just popped up this morning. I don't know how to fix it and it's driving me crazy because having the tilde is a core part of my daily work. 

Do you know how to fix it?
