### ISSUE TITLE
Karabiner stopped working

### ISSUE THREAD

**Issue by popo63301** [pqrs-org/Karabiner-Elements#2072]
Hello,

I have a splitted keyboard and I use Karabiners to control the combinations of "cmd" key from the left/right and keys from the other keyboard part. It was working wonderfully until MacOS Vista ... oups... Catalina. 

So basically, when I log in the keyboard is working correctly until a certain moment, the keyboard stops working. Then, I have to unplug it and replug it, changing the current window and typing  random text to assure myself its working. Usually, the keyboard is working but the Karabiners configuration stops working (the mapping of CMD keys) and only my external splitted keyboard work but not my native Macbook Pro keyboard... 

How can I solve my issue?

**Comment by juanfernandoe** [comment]
The same here but with the internal keyboard, I always have to restart my computer.

**Comment by popo63301** [comment]
Yes, me too. I always to restart to make things work again. This is unbearable...

**Comment by c3s4** [comment]
Hi, the same happens to me.
After a while I figured out that this happens after hitting _Caps Lock_ key.

**Comment by juanfernandoe** [comment]
Hi, I confirm it's when Caps Lock key is hit.

**Comment by popo63301** [comment]
Can you share your complex modification so that I can download it from here: https://pqrs.org/osx/karabiner/complex_modifications/ , please ? :)

**Comment by juanfernandoe** [comment]
I'm using one called  Change caps_lock key (rev 4) specifically shift + caps_lock.

**Comment by brunoedig** [comment]
> Hi, the same happens to me.
> After a while I figured out that this happens after hitting _Caps Lock_ key.

Yep, same here. It's VERY annoying as I have to reset the whole thing every time it happens.

**Comment by tekezo** [comment]
macOS has an issue that a process will stuck when manipulating caps lock LED for some device. (eg., external keyboard which does not have caps lock LED.)

Please confirm your configuration about "Manipulate LED" on Devices tab, and then turn off the checkboxes.
https://pqrs.org/osx/karabiner/document.html#configuration-devices

**Comment by popo63301** [comment]
Actually, it is turned off already

**Comment by popo63301** [comment]
Still bugging ...

**Comment by popo63301** [comment]
@juanfernandoe  Your modification is "Change caps_lock key to command+control+option+shift. (Use shift+caps_lock as caps_lock)", right? I enabled it but it's not working, should I restart the computer to make it work?
