### ISSUE TITLE
Simply want to disable Apple Internal Keyboard

### ISSUE THREAD

**Issue by myst729** [pqrs-org/Karabiner-Elements#2073]
![image](https://user-images.githubusercontent.com/519733/69235743-14008100-0bcd-11ea-9278-c950156a5cf8.png)
This is typically how I work on my laptop. The 2017 MBP internal keyboard sucks, some keys are dead already. Apps like KeyboardCleanTool disable BOTH internal and external keyboards. What I'm looking for is a tool that ONLY disables the internal keyboard, and leaves the trackpad enabled.

Karabiner Elements does the job right now. Just wondering is there such an app that's more light-weighted with zero configuration. Say, Karabiner Lite, or a shell script. Is this achievable?

**Comment by covertoperator** [comment]
There is only one Karabiner. If you don't want it, there might be other apps that do the job.

Maybe you can create a layout, using Ukulele, that maps every key to nothing. This will not affect modifier keys and probably won't affect the space bar, but you won't need an extra program taking up your precious CPU clocks.

Karabiner has the additional benefit that it can also disable the built in trackpad.

**Comment by nidlol** [comment]
the maker of BetterTouchTool also wrote an app called [KeyboardCleaningTool](https://folivora.ai/keyboardcleantool) and should be exactly what you want.

**Comment by myst729** [comment]
> the maker of BetterTouchTool also wrote an app called [KeyboardCleanTool](https://folivora.ai/keyboardcleantool) and should be exactly what you want.

![image](https://user-images.githubusercontent.com/519733/69235743-14008100-0bcd-11ea-9278-c950156a5cf8.png)
This is typically how I work on my laptop. The 2017 MBP internal keyboard sucks, some keys are dead already. So what I'm looking for is a tool that ONLY disables the internal keyboard. KeyboardCleanTool disables both internal and external keyboards.

Karabiner does the job right now. Just wondering is there something more light-weighted with zero configuration.

**Comment by myst729** [comment]
> the maker of BetterTouchTool also wrote an app called [KeyboardCleanTool](https://folivora.ai/keyboardcleantool) and should be exactly what you want.

![image](https://user-images.githubusercontent.com/519733/69235743-14008100-0bcd-11ea-9278-c950156a5cf8.png)
This is typically how I work on my laptop. The 2017 MBP internal keyboard sucks, some keys are dead already. So what I'm looking for is a tool that ONLY disables the internal keyboard. KeyboardCleanTool disables BOTH internal and external keyboards.

Karabiner does the job right now. Just wondering is there some app that is more light-weighted with zero configuration. Or a shell script.

**Comment by n3h3m** [comment]
This item can be closed, It's already possible with the latest Karabiner Elements. 

<img width="919" alt="Screenshot 2019-12-04 16 40 30" src="https://user-images.githubusercontent.com/1170505/70115753-cd268700-16b4-11ea-83f3-30a987031aea.png">
