### ISSUE TITLE
Karabiner not working in catalina 10.15.1

### ISSUE THREAD

**Issue by asaadmahmood** [pqrs-org/Karabiner-Elements#2075]
Tried suggestions here:
https://github.com/pqrs-org/Karabiner-Elements/issues/1932

![Screenshot 2019-11-20 at 7 42 18 PM](https://user-images.githubusercontent.com/11034289/69248381-05669980-0bce-11ea-9bd3-0268483ecd96.png)

![Screenshot 2019-11-20 at 7 42 32 PM](https://user-images.githubusercontent.com/11034289/69248435-1ca58700-0bce-11ea-968d-3a4c54cf8b46.png)

**Comment by zhaotonggit** [comment]
I have the same issue. Please fix this soon.

**Comment by nroose** [comment]
When I updated karabiner, I had this issue. I thought perhaps I should kill background Karabiner processes. I was unable to. I ended up restarting and Karabiner started working again.

**Comment by rackstar** [comment]
same here. exact the same issue with Catalina 10.15.1 as @asaadmahmood

Karabiner-Elements is an essential part of my everyday workflow. Would greatly appreciate if we can get it working with Catalina.

Thanks!

**Comment by ironicsquiddesign** [comment]
I'm having the same problem. I have the latest best version. sudo killall doesn't help. The only thing I can do is restart my computer and I CAN'T do that every single time KE plays the 'no buffer space game.' Please help.

**Comment by lavandongen** [comment]
I am running into the same issue here too https://github.com/pqrs-org/Karabiner-Elements/issues/2087

**Comment by fkupper** [comment]
Same happening here.

**Comment by lavandongen** [comment]
I had Karabiner fail on me again just now. My keys locked up, then after connecting and reconnecting my ` key kept being pressed and my keybindings did not work anymore.

**Comment by lavandongen** [comment]
Well, it is still happening. I Just had Karabiner fail on me again forcing me to restart my pc in the middle of the work I was doing. Not even being able to save because my computer kept pressing the key I had binded.

**Comment by ironicsquiddesign** [comment]
It's still happening to me too. Every day Karabiner will stop working - hitting my function keys gets me the thump sound and in the Karabiner log it's "no buffer space available". I NEED the function keys to work so I can switch between programs, I need to use several programs at a time to complete project. Not to mention I can't skip/play/pause music when Karabiner stops working.

I can't just up and restart my computer every time this happens.

**Comment by j-f1** [comment]
Same here
