### ISSUE TITLE
12.8 totally disables caps lock LED

### ISSUE THREAD

**Issue by peterpqa** [pqrs-org/Karabiner-Elements#2076]
Karabiner-Elements 12.8 totally disabled my caps-lock LED. I reverted to 12.7, which USUALLY lets the caps-lock LED work (sometimes I have to toggle it).

MacBook Pro Retina 15" mid-2015, 2.2 GHz QC IC i7, 16 GB memory, macOS Catalina 10.15.1

**Comment by tekezo** [comment]
If you are using external keyboard and fails to control external keyboard LED,
please turn on "Manipulate LED" checkbox for your device.
https://pqrs.org/osx/karabiner/document.html#configuration-devices

**Comment by peterpqa** [comment]
I'm not using an external keyboard, just the MacBook Pro's built-in keyboard. 12.7 is working fine.
