### ISSUE TITLE
mouse_motion_to_scroll don't work for Kensington Expert Wireless Trackball

### ISSUE THREAD

**Issue by yqrashawn** [pqrs-org/Karabiner-Elements#2077]
It works fine on a logitech mouse. But won't work on the trackball mouse.
![image](https://user-images.githubusercontent.com/15090582/69325757-a06e7a80-0c85-11ea-8a07-6685382b37bd.png)

```json
 {
        "device_id": 4295019916,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": false,
        "is_pointing_device": true,
        "location_id": 336789504,
        "manufacturer": "Kensington",
        "product": "Expert Wireless TB",
        "product_id": 32792,
        "transport": "USB",
        "vendor_id": 1149
 }
```

**Comment by yqrashawn** [comment]
up

**Comment by tekezo** [comment]
Karabiner-Elements might not work with third vendor driver.
Are you using Kensington driver?

**Comment by yqrashawn** [comment]
Yes. I'm using the KensingtonWorks download from [here](https://www.kensington.com/software/kensingtonworks/)

**Comment by tekezo** [comment]
Thank you for confirmation.
I guess you have to choose either KensingtonWorks or Karabiner-Elements for your Trackball.

**Comment by yqrashawn** [comment]
The driver I used before is `TrackballWorks` [here](https://www.kensington.com/en-gb/software/trackballworks-customization-software2/).

I just tried KensingtonWorks [here](https://www.kensington.com/software/kensingtonworks/).

`mouse_motion_to_scroll` works now!

The behavior now is:
- KensingtonWorks only controls the pointer speed and acceleration, slow pointer and single-axis movement are broken
- Karabiner controls the rest

![image](https://user-images.githubusercontent.com/15090582/72773525-5c2a3700-3c42-11ea-8f33-0c429699338e.png)

I'm totally fine with it. Thanks.
