### ISSUE TITLE
Remapping æ stopped working in Catalina

### ISSUE THREAD

**Issue by aslakrin** [pqrs-org/Karabiner-Elements#2078]
I had a rule that used to work, to get æ on AltGr+e. Now the rule seems to do nothing, until i change æ to one of the more boring a-z letters.

What has changed?

```
                             {
                                 "type": "basic",
                                 "from": {
                                     "key_code": "e",
                                     "modifiers": {
                                         "mandatory": [
                                             "right_option"
                                         ],
                                         "optional": [
                                             "shift"
                                         ]
                                     }
                                 },
                                 "to": [
                                     {
                                         "key_code": "æ",
                                         "modifiers": [
                                             "right_option"
                                         ]
                                     }
                                 ]
                             }
```

**Comment by zamkevich** [comment]
@aslakrin  try the last beta 

![image](https://user-images.githubusercontent.com/13717428/71062505-64f89a80-21b6-11ea-8add-c60928f164de.png)

**Comment by aslakrin** [comment]
I now get an entry in the log about it not working at least. Should I be doing something else?

```2019-12-31 10:54:36.042] [info] [grabber] core_configuration is updated.
[2019-12-31 10:54:36.042] [info] [grabber] virtual_hid_device_client is opened.

[2019-12-31 10:54:36.042] [error] [grabber] karabiner.json error: `to` entry error: `key_code` error: unknown key_code: `"æ"`

[2019-12-31 10:54:36.042] [info] [grabber] virtual_hid_device_client_ is connected
[2019-12-31 10:54:36.043] [info] [grabber] initialize_virtual_hid_keyboard
[2019-12-31 10:54:36.043] [info] [grabber]   country_code:0
```

**Comment by schmidhauser** [comment]
As the error log says, the character ‘æ’ is not a keycode. If you activate the ABC – Extended keyboard, you should be able to use the following:

```
{
	"type": "basic",
	"from": {
		"key_code": "e",
		"modifiers": {
			"mandatory": [
				"option"
			],
			"optional": [
				"shift"
			]
		}
	},
	"to": [
		{
			"key_code": "quote",
			"modifiers": "option"
		}
	]
}
```

**Comment by aslakrin** [comment]
Hi,

It's not that I can't read, but æ used to be a keycode, or at least it used to work, which is what confused me and caused this issue.

On the other hand I had no idea that the same letter was hiding behind option+quote. Thanks! :D

On the third hand I resolved my use-case meanwhile by using Ukulele and making a custom keyboard layout that matches what I want.

Feel free to close this if you think the breaking change (as I would categorize it) isn't a bug or is sufficiently resolved.

**Comment by schmidhauser** [comment]
Glad you’ve got it worked out. I too have my own handcrafted keyboard layout plus a `karabiner.json`. Incidentally, the Keyboard Viewer is often very helpful in such cases – if you cannot see a character with your respective layout, then you generally won’t be able to use Karabiner to assign a shortcut to it.
