### ISSUE TITLE
Karabiner stopped working in Catalina with `virtual_hid_device_client is not connected yet` error.

### ISSUE THREAD

**Issue by raryo** [pqrs-org/Karabiner-Elements#2079]
Hi, karabiner-element stopped working after updating to Catalina.

![kara](https://user-images.githubusercontent.com/29229535/69473864-b8b4d580-0dfc-11ea-91a8-b3792e31a7d1.png)

I have already tried the following solutions as mentioned in  #2021 :
- Reinstalling karabiner-element
- Restarting in safe-mode to refresh system caches.

macOS version: macOS 10.15.1
Karabiner version: 12.8.0
MacBook Pro

Is anyone facing a similar issue?

Thank you.

**Comment by tekezo** [comment]
It seems there is some error around loading kext.
Could you execute the following command in Terminal app?
(The root password will be required in order to run kextutil command.)

```shell
sudo kextutil -t '/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext'
```

**Comment by raryo** [comment]
Thank you for replay. 
I tried `kextutil`  command, get  `Kext rejected due to insecure location`.

So, I tried SIP disable, successfully work karabiner-element .

**Comment by raryo** [comment]
However, when SIP was enabled again, karabiner-element stopped working . Is there any way to deal with this? (I'm sorry if this error outside the scope of this project.)

**Comment by tekezo** [comment]
Did you install SOPHOS software?
This discussion seems similar to your situation.
https://discussions.apple.com/thread/250038463

**Comment by raryo** [comment]
I didn't install SOPHOS. I read the discussion, and the status of `/Library/Application Support/org.pqrs` is `norestricted`. 
Is it correct ?
<img width="876" alt="スクリーンショット 2019-11-25 20 38 24" src="https://user-images.githubusercontent.com/29229535/69537468-886b6380-0fc3-11ea-92ed-5a9da8a88e52.png">

**Comment by DKroot** [comment]
I had the same issue on High Sierra. No SOPHOS, but I was able to fix this by following the recipe from https://discussions.apple.com/thread/250038463:

# (Recovery) $ csrutil disable
# (Normal boot) $ sudo chflags -R restricted /Library/StagedExtensions 
# (Recovery) $ csrutil enable

None of the other solutions (e.g. from https://github.com/pqrs-org/Karabiner-Elements/issues/1508) worked.
