### ISSUE TITLE
Can't detect Fn + Left/Right arrow nor Fn + Home/End

### ISSUE THREAD

**Issue by WalterGR** [pqrs-org/Karabiner-Elements#2080]
I'm trying to map the Fn + Left/Right arrow keys (those are the names of the keys on the physical keyboard) to anything that will mimic PC Home/End.

After about 4 hours, I'm still failing to accomplish this on 

* macOS Mojave
* early 2015 Macbook Pro
* using the internal keyboard
* both Karabiner 12.7.0 and 12.8.0.

In my karabiner.json I've tried every combination of Fn required / Fn optional / left_arrow / right_arrow / home / end and nothing works.  (Those are the internal names.)

I haven't been able to find a minimal test case to demonstrate these, because during experimenting with this, it seems like things that used to work no longer work, and things that work in some apps don't work in others (even when not using conditions.)

Three questions:

* Does Karabiner provide any logs about it matching rules or not matching rules?  It seems like a black box, and 4 hours is a long time.  :)
* Do I potentially need to delete any saved state that exists outside karabiner.json when changing karabiner.json? 
* How can I accomplish the mapping I've described?

**Comment by bvankuik** [comment]
Just a question; you are aware that macOS has a default key combo for home/end? Cmd-Up is Home, Cmd-Down is End.

**Comment by WalterGR** [comment]
Yep.  But Mac home/end is different than PC home/end.  I'm trying to accomplish the latter.

**Comment by etauker** [comment]
Anyone have any update on this? 
I am trying to achieve the same with no success.

**Comment by janiosarmento** [comment]
I'm facing the very same issue on 13.1.0.

There is no way that I can map Fn+Left/Right Arrow to Home/End.

**Comment by SaadBazaz** [comment]
Having this same problem.

```
            "simple_modifications": [
                {
                    "from": {
                        "key_code": "f3"
                    },
                    "to": {
                        "key_code": "right_arrow",
                        "modifiers": [
                            "fn"
                        ]
                    }
                }
]
```

This doesn't work...

**Comment by MuhammedZakir** [comment]
Most keyboards handle `fn` key internally and for these keyboards, Karabiner (or any other apps/tools) won't be able to detect `fn` key. You can check if it can be detected using on-screen keyboard.

**Comment by SaadBazaz** [comment]
Yes! That seems like the issue. Thank you for the explanation, I've ditched the idea for now... 😅
