### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by st74burner** [pqrs-org/Karabiner-Elements#2082]
I suspect Karabiner is causing problems with my MBP's keyboard on wake.  Attempted to uninstall.  It's impossible.  Clicking "Uninstall" under Misc in the program itself does nothing whatsoever.  And you've set the permissions so everything is essentially undeletable by brute force.  Really a catastrophic mess.

macOS version: 10.15.1 (Catalina)
Karabiner version: 12.7.0
Your Mac hardware: 16-inch MBP (late 2019)
Your keyboard hardware: internal keyboard

**Comment by tekezo** [comment]
I'm sorry for your trouble.
Could you boot Safe Mode and try the uninstaller?

Safe Mode: https://support.apple.com/en-us/HT201262
