### ISSUE TITLE
[[Bug]] Swapping Left_Command and Left_Option Seems to Cause Control-Option-B to Not Get Recognized

### ISSUE THREAD

**Issue by WammKD** [pqrs-org/Karabiner-Elements#2086]
I can't be certain that this is the only cause, given that I've adjusted quite a few things, but I lose the ability for Control-Option-B key chord to be recognized when I swap Left_Command and Left-Option with Karabiner Elements.

Ever with all other custom settings enabled, the key chord doesn't break down until I swap the keys.

The key chord doesn't seem recognized, at all (e.g. trying to set the chord for a command for Mission Control doesn't even put the keys with those keys not working; instead, it remains waiting for keyboard input to assign a key chord to the command).

The settings I have can be seen here: 
<img width="1000" alt="Screen Shot 2019-12-03 at 10 51 38 AM" src="https://user-images.githubusercontent.com/10533934/70071930-acc6d180-15bb-11ea-8958-d8af1546732a.png">

**Comment by WammKD** [comment]
And, since removing and readding the above settings, now the key chord Shift-Option-. (aka Option->) isn't recognized anymore, either.

**Comment by tekezo** [comment]
It's a hardware limitation, 2-key rollover.
https://en.wikipedia.org/wiki/Rollover_(key)#Keyboard_usage

Use N-key rollover keyboard or another key combination (e.g. control + right option + b).

**Comment by WammKD** [comment]
Sorry about taking so long to respond; thanks a ton for clarifying and helping me understand. Obviously, nothing else you can do here so I'll close this ticket.
