### ISSUE TITLE
Feature request: Automatic profile switching 

### ISSUE THREAD

**Issue by taylorthurlow** [pqrs-org/Karabiner-Elements#2091]
Just a short feature request here, it would be really nice to be able to switch to/from a profile when a particular device is plugged into the computer.

**Comment by dhopfm** [comment]
I'll second that: with my use case it would be great if profiles could be tied to the selected keyboard layout (which can be different per application). I'm using the US layout for everything coding and the [Neo2 layout](https://en.wikipedia.org/wiki/Neo_(keyboard_layout)) for (German) natural language writing with applications such as e-mail clients.

Neo2 remaps a lot of modifier keys so using its Karabiner profile in conjunction with the US layout isn't an option. On the other hand, having to constantly switch profiles is quite tedious as well so it would be great if it could be automated.
