### ISSUE TITLE
Export profile to import on fresh install?

### ISSUE THREAD

**Issue by cyberfunk** [pqrs-org/Karabiner-Elements#2103]
Hello and thanks for this excellent app. How do I export a profile to import on a fresh install or another computer? Or do I simply backup/restore the preferences plist once I have everything configured to taste?

**Comment by tekezo** [comment]
You can export/import by copying ~/.config/karabiner/karabiner.json file.

You can do it via GUI at the latest beta version as follows:
https://pqrs.org/osx/karabiner/document.html#export

Upgrade to the latest beta version, then follow above instruction.
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>
