### ISSUE TITLE
Karabiner duplicates characters & any keystrokes when typing "fast" with Catalina

### ISSUE THREAD

**Issue by hello-rsbr** [pqrs-org/Karabiner-Elements#2105]
Hello!
I recently installed macOS Catalina (Version 10.15.2) on a MacBook Pro (Retina, Mid 2014), running Karabiner Elements 12.8.3 with an [AmazonBasics Wired Keyboard](https://www.amazon.com/gp/product/B005EOWBHC/). The setup has worked wonderfully for almost two years now (thank you, Karabiner!) until I installed Catalina.

Now, when I type even moderately "fast," any keystrokes become duplicated (any letter in the alphabet, backspace, enter, etc.). When I poke the keys in one at a time, the problem doesn't occur, as if slowing down allows the keystroke to be processed.

To demonstrate, please view the following sentences I typed in succession:

The quick **he quick** brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The **quhe** quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The **quickhe quic** brown fox jumps over the lazy dog.
The **quhe** quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The **he** quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.

Please help? Thank you!!

P.S. The reason I use Karabiner is that some water I idiotically spilled on my internal keyboard caused some keys to malfunction (right Shift, right option, right fn). (Again, thank you, Karabiner!) When I turn off Karabiner and use my internal keyboard with its malfunctions and all, I don't have a problem with duplicated keystrokes.

P.P.S. Also just tested this with another wired keyboard, and the duplications still happen.
P.P.P.S. This entry is largely free of spelling errors because I painstakingly corrected all the duplicates for legibility.

**Comment by drye** [comment]
I'm experiencing the same thing. I think this might be a widespread Catalina bug related to input monitoring. When I google for repeating characters problem, the remedy that seems to always help is to disable input monitoring for everything. This effectively disables Karabiner, so that's not much of a remedy anyway.

Some links: 
* https://discussions.apple.com/thread/250733138?answerId=251805879022#251805879022
* https://github.com/pqrs-org/Karabiner-Elements/issues/2019

**Comment by selkovjr** [comment]
It has only gotten worse with time. After the first Cattalina install, it only happened somettimes. Now I have to o fix every other word annd llogging in after a shutdown is next to impoossible. It's a handicap race.

All I neeed is the right Ctrl key.
