### ISSUE TITLE
Can't input tilde anymore

### ISSUE THREAD

**Issue by SamZhangQingChuan** [pqrs-org/Karabiner-Elements#2107]
Hi there. I cannot input tilde by pressing the key above tab anymore regardless of using the built-in keyboard or an external one. The event-viewer shows that the key I press is indeed 'grave_accent_and_tilde'.

<img width="332" alt="Screen Shot 2020-01-01 at 21 40 37" src="https://user-images.githubusercontent.com/8025859/71639663-7033e600-2cdf-11ea-8b48-434ba00d059f.png">

I get § instead now and ` if I quit karabiner.

**Comment by rzuritamilla** [comment]
I have a similar issue. I am running KE 12.9.0 in my MBP (16" with Catalina 10.15.2).
I am using the keyboard of the MBP and noticed that the keys ~` and ±§ have been swapped. Any solution? Thanks!

**Comment by MTCoster** [comment]
This looks like the same problem as #2027

**Comment by rzuritamilla** [comment]
Thanks!! The proposed [quick fix]( https://github.com/pqrs-org/Karabiner-Elements/issues/2027#issuecomment-550211764 ) works well. I hope that this issue can be addressed soon.
