### ISSUE TITLE
Remap ⌘+Tab to ⌘+Tab w/ delayed modifier ⌥

### ISSUE THREAD

**Issue by jakecast** [pqrs-org/Karabiner-Elements#2113]
I'm looking to remap the task switch in macOS (⌘+Tab) to the task switcher with the option key held down (⌘+⌥+Tab) to un-minimize windows of the selected application.
However, I need the option key to be added after ⌘+Tab is invoked otherwise the task switcher is not invoked. I also need the option key to remain key_down while command is key_down.

I experimented with using `to_delayed_action` and setting a conditional var, but couldn't quite get it to work.. 
Does anyone know how to accomplish this?

**Comment by RyoIkarashi** [comment]
I'm also looking for the exact same key remapping.
Any snippet to get this work?
