### ISSUE TITLE
pqrs.org seems to be down

### ISSUE THREAD

**Issue by wissem** [pqrs-org/Karabiner-Elements#2116]
I can't download the package since your website is down.
Also while trying to build the package locally it doesn't work and I get this error:
<details>
<summary>Error</summary>
<p>

> 
> 2020-01-13 17:28:30.196 ibtoold[1741:26131227] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error getting value for parameter key 'class' of extension 'Xcode.InterfaceBuilderKit.PepperIntegration.ConfigurationList' in plug-in 'com.apple.dt.IDE.IDEInterfaceBuilderWatchKitIntegration''
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff38938cfd __exceptionPreprocess + 256
> 	1   libobjc.A.dylib                     0x00007fff62fdea17 objc_exception_throw + 48
> 	2   DVTFoundation                       0x00000001065cf4e4 -[DVTExtensionParameter valueForKey:error:] + 0
> 	3   Foundation                          0x00007fff3ab271b7 -[NSArray(NSKeyValueCoding) valueForKey:] + 432
> 	4   Foundation                          0x00007fff3ab703be -[NSArray(NSKeyValueCoding) valueForKeyPath:] + 436
> 	5   Foundation                          0x00007fff3aaee1ec -[NSObject(NSKeyValueCoding) valueForKeyPath:] + 260
> 	6   IDEInterfaceBuilderKit              0x0000000105850a61 -[IBPlatform matchesExtension:] + 47
> 	7   IDEInterfaceBuilderKit              0x0000000105850bf2 __42-[IBPlatform extensionsForExtensionPoint:]_block_invoke + 24
> 	8   IBFoundation                        0x0000000106bc777a -[NSSet(IBSetAdditions) ib_setByFilteringUsingBlock:] + 258
> 	9   IDEInterfaceBuilderKit              0x0000000105850bb3 -[IBPlatform extensionsForExtensionPoint:] + 201
> 	10  IDEInterfaceBuilderKit              0x000000010584fca2 -[IBPlatform registerMemberConfigurationVariables] + 171
> 	11  IDEInterfaceBuilderKit              0x00000001059917d0 -[IBScopedSingletonRegistry init] + 1339
> 	12  IDEInterfaceBuilderKit              0x0000000105991280 __43+[IBScopedSingletonRegistry sharedInstance]_block_invoke + 32
> 	13  libdispatch.dylib                   0x00007fff6475f63d _dispatch_client_callout + 8
> 	14  libdispatch.dylib                   0x00007fff64760d4c _dispatch_once_callout + 20
> 	15  IDEInterfaceBuilderKit              0x000000010599125d +[IBScopedSingletonRegistry sharedInstance] + 45
> 	16  IDEInterfaceBuilderKit              0x00000001057a12b7 -[IBInterfaceBuilderPlugin init] + 149
> 	17  IDEInterfaceBuilderKit              0x00000001057a1208 +[IBInterfaceBuilderPlugin ide_initializeWithOptions:error:] + 34
> 	18  IDEFoundation                       0x0000000106ee94c6 _IDEInitializeOnePlugInAndPrerequisites + 2290
> 	19  IDEFoundation                       0x0000000106ee8df2 _IDEInitializeOnePlugInAndPrerequisites + 542
> 	20  IDEFoundation                       0x0000000106ee8df2 _IDEInitializeOnePlugInAndPrerequisites + 542
> 	21  IDEFoundation                       0x0000000106ee7d10 _IDEInitializePlugIns + 1410
> 	22  IDEFoundation                       0x0000000106ee6ddc IDEInitialize + 7572
> 	23  ibtoold                             0x0000000105487d27 IBIDEInitialize + 52
> 	24  ibtoold                             0x0000000105486b73 main + 744
> 	25  libdyld.dylib                       0x00007fff647ac3d5 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> Command /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool failed with exit code 6. The tool may have crashed. Please file a bug report at https://feedbackassistant.apple.com with the above output and attach any crash logs for ibtool, ibtoold, Xcode, and IBAgent created around the time of this failure. These logs can be found in ~/Library/Logs/DiagnosticReports or /Library/Logs/DiagnosticReports.
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileXIB Resources/MainMenu.xib
> (1 failure)
> make[4]: *** [build_xcode] Error 65
> make[3]: *** [all] Error 2
> make[2]: *** [all] Error 2
> make[1]: *** [build] Error 2
> 

</details>

Any other way to download the package? Thanks.

**Comment by tobiasboyd** [comment]
I'm seeing errors from the Check for Update in the app too; seems like it might be more reliable to host the binaries for releases on GH?

**Comment by CanRau** [comment]
Down for me as well

**Comment by PWKad** [comment]
Seems to be fixed now for me!

**Comment by tekezo** [comment]
Sorry for inconvenience.
pqrs.org is back just now.


For future reference:
github files are available for downloading Karabiner-Elements.
https://github.com/tekezo/pqrs.org/tree/master/webroot/osx/karabiner/files
