### ISSUE TITLE
Capslock remap not working on Logitech MX Keys

### ISSUE THREAD

**Issue by sdaitzman** [pqrs-org/Karabiner-Elements#2118]
macOS 10.15.2 // Karabiner-Elements 12.8.0

Capslock remap to "CMD + Space" is working on my internal keyboard on my 16" MacBook Pro but does not work on my external Logitech MX Keys keyboard.

**Comment by sdaitzman** [comment]
﻿
![screenshot](https://user-images.githubusercontent.com/1499476/72468647-a1b2b400-37ab-11ea-8d1c-681b4561811a.png)

Interestingly, the key events *do* appear in Karabiner-EventViewer

**Comment by kule** [comment]
@sdaitzman I have a similar issue, did you figure this out?

**Comment by sarfata** [comment]
@sdaitzman / @kule same here.

**Comment by sarfata** [comment]
For anyone else finding this thread: I went in Karabiner Preferences -> Devices and checked the MX Keys and now it works.

**Comment by sdaitzman** [comment]
@kule there were a few system configuration errors between Karabiner and another kernel extension, but to make things simple: check if you have any less stable keyboard modifiers installed and make sure your Karabiner install has the keyboard actually enabled 😄
