### ISSUE TITLE
Mouse and Trackpad Separation

### ISSUE THREAD

**Issue by auspoke** [pqrs-org/Karabiner-Elements#2120]
I've recently gotten a Mac and have been trying to use Karabiner to change the mouse scroll settings while leaving the trackpad settings, but I can't find the scroll direction options in the key settings for my mouse. No options are appearing under mouse keys.

**Comment by lavandongen** [comment]
I believe Karabiner only works for keyboard shortcuts and the like. I have been using [scrollreverser](https://pilotmoon.com/scrollreverser/) for this exact use case, successfully, for a number of years now. Works perfectly alongside Karabiner :)
