### ISSUE TITLE
Karabiner Elements crashes Macbook after X minutes [Critical]

### ISSUE THREAD

**Issue by gotwig** [pqrs-org/Karabiner-Elements#2122]
I am here to report about my long and hard journey to find out that Karabiner Elements caused my Macbook 2013 to crash after a random set of minutes.

One month ago I started using Karabiner Elements, everything seemed to work fine, but after some time my macbook was just randomly shutting down. I had no clue its Karabiner, so eventualy at some point after I did X things in trying to fix it (it wasnt happening in safe mode) I was reinstalling my mac system, and after I installed Karabiner Elements the error started again so I removed it and since then no more shutting down.

The shutdown happened as follows:
The screen just went black, the keyboard was still light up, after some time everything was shutdown.

My setting in karabiner elements was setup as follows:
FN -> Left Shift Key

The shutting down occured after I left for example a heavy game or sometimes just randomly after 1 hour or 2. But when I restarted sometimes it just happened instant again, and again and again.

Then I tried to rescue some data onto an external NTFS harddrive, but the shutdown happened again.. and eventualy corrupted my whole NTFS partition of 300gb... it realy pissed me off and I couldnt even repair it. It showed up as "allocated data" or something, it was just marked black and not mountable or fixable, not even anymore by windows.

Of course I was super frustrated by this.

I hope you find this useful...

**Comment by gotwig** [comment]
i found it had to do with another issue: https://www.reddit.com/r/MacOSBeta/comments/c6f6e7/catalina_random_shutdown_applethunderboltnhikext/

sry guys

**Comment by azumbrunnen** [comment]
It does not. I experiences the exact same issue in Big Sur. It honestly got to the point where I felt my iMac pro is getting broken.

This behavior is pretty unacceptable and I have seen various complaints like this.

Whoever reads this: stay away from this software. Once you install it, it becomes a pain to even remove it. Unacceptable.
