### ISSUE TITLE
Help with Complex Modifications

### ISSUE THREAD

**Issue by ksmyth08** [pqrs-org/Karabiner-Elements#2129]
Hi,

I just downloaded Karabiner and was hoping for some help with complex modifications.
I’m using an apple wired keyboard with numeric keypad attached to a 2014 15” MacBook Pro.
I'm a heavy excel user that switched back to a Mac and am running 2016 Microsoft office for Mac- there’s a couple differences that make it a pain to use so I was hoping to make some shortcuts.
Here is a quick list of what I want to do (followed with expanded explanations):

1. Create a Fn Lock (by pressing Fn + esc) for mac internal keyboard
2. Right Command Key → Control+Shift+V in Microsoft Office, Command+Shift+V in all other apps
3. Right Option Key → Alt+Shift+F10 in Excel, Shift+F10 all other apps
4. Right Control Key → Shift+Command+T
5. F1 → Control+Shift+Z in excel (or all apps)
6. F19 → Control+Shift+A in excel (or all apps)

- 

1.  I used Karabiner to move my music keys to F13-F18 on my external keyboard so I can leave my F1-F12 keys function as F1,F2,etc. and don’t need to switch back and forth, but when I take my computer on the go I would like to have the option to switch back and forth. So I really just need to be able to switch the internal keyboard back and forth, but I think with both an apple internal and external keyboard they have to be the same.       Another option would be to only make F keys function as F1,F2,etc. only in excel for both keyboards (not sure what is easier to do)

2. I made a macro in excel/word/powerpoint to paste values using the shortcut _Control_+Shift+V.  I would like to be able to press the Right COMMAND Key to execute this action.  And then for other apps, the default shortcut on the mac to paste without formatting is _Command_+Shift+V.  I copy and paste in google sheets pretty frequently so it would be nice to have the right command key paste values in excel, but paste unformatted text in other apps.  If it isn’t possible to have both options (microsoft office and other apps) then I would prefer the Control+Shift+V to be assigned to the right command key.

3. Alt+Shift+F10 brings up the paste menu in excel, but I’d like to be able to do this by pressing the Right OPTION Key.  Excel is the only app I need this in, but that shortcut has no effect in other apps so it can be programmed to work in just excel or all apps.  If it’s possible to make the right option key be Shift+F10 in powerpoint and word that would be great too (or all other apps besides excel if that is easier.  Shift+F10 without the alt is the right click menu in microsoft office, but not as useful as paste menu in excel). 

4. Shift+Command+T is the shortcut for autosum in excel.  Instead of hitting 3 keys, I’d rather make it the Right CONTROL Key.  This can be excel specific or all apps, I don't use the right control key.

5. I use my F1, F2, etc. keys as standard function keys and F1 in excel pulls up the help menu which I never use.  I made a macro that resets zoom to 100% (Control+Shift+Z), so when I press F1 I would like that action to happen.  I don’t use the F1 key in any other apps so this can be for all apps.  Not sure if Fn-F1 will still lower brightness or not after making this change, but it is okay if it doesn’t.

6. Same as number 5-  I don’t have anything assigned to F19 so it can be excel app specific or for all apps
 
Last, I have a Logitech mouse and haven’t downloaded Logitech options, but I was wondering if I can download and use it while Karabiner is running. If that’s not possible let me know if there is some type of workaround.
 
Thank you so much!

**Comment by ronniejob** [comment]
I am looking for the shift-f10 functionality and would support anyone who would help develop that. OMG it would save me a lot of time to get that context-menu working in Office for Mac. I am new to Github, but love the idea. I am willing to pay for any help with this, but not sure how this really works?

**Comment by ksmyth08** [comment]
Same!   Btw Ronnie are you using office for mac or just using mac keyboard with excel for windows?  I originally thought I would want the context menu (shift+F10) as my shortcut until I realized none of the paste options show up when you right click in the mac version so the right click is kind of useless.  I actually think the paste menu shortcut is quicker (alt+shift+f10) if you copy, paste normal, and then pick out your paste option.  Otherwise with the right click you need to open the paste special which is a separate menu and ends up being more keystrokes to do.

**Comment by ronniejob** [comment]
I am using it on Mac. And I really, really miss the context menu from my Windows days...Haha!

**Comment by ronniejob** [comment]
I am not using Excel much so I am not the efficient-guy there... you seem to have much need to make things work in an optimal manner there....
