### ISSUE TITLE
Add not listed key

### ISSUE THREAD

**Issue by samuelbarata** [pqrs-org/Karabiner-Elements#2136]
Hi, is there a way do add keys that are not “listed” there?
Like those keyboards that have calculator/email/browser buttons
Can those be changed?

**Comment by samuelbarata** [comment]
Activity 🙄

**Comment by marlonrichert** [comment]
To find out if Karabiner-Elements supports a particular key, you can try to see if it shows up in its EventViewer when you press that key. See https://github.com/pqrs-org/Karabiner-Elements/issues/2228#issuecomment-615119061 for more info.
