### ISSUE TITLE
Retaining the correct keyboard in the 'disable the built-in' feature

### ISSUE THREAD

**Issue by philipt18** [pqrs-org/Karabiner-Elements#2139]
I'm trying to use the 'Disable the built-in keyboard while one of the following selected devices is connected' feature to disable the built-in keyboard when using a specific Bluetooth keyboard. The feature works, but after I disconnect it forget the specific keyboard, and even disables the built-in keyboard even if I plug in a different external USB keyboard. I don't know if this is a bug or I'm not doing something right. How do I get it to remember my keyboard, and to disable the built-in keyboard only when it is connected, and to re-enable the built-in whenever it is disconnected?

I'm running Karabiner-Elements 12.9.0 on a MBP running macOS 10.14.6. The BT keyboard I'm using is the NuType F1 (https://nuphy.com/). In the window it is listed as: NUTYPE F1 (Unknown) [1452,591].

**Comment by jordan-chan** [comment]
Hi, 

I'm wondering the same!  I can enable the feature, although it doesn't seem to work, then it disables itself once I close the app.
