### ISSUE TITLE
Translate left_gui to Meta key (linux KDE)

### ISSUE THREAD

**Issue by frenchie1980** [pqrs-org/Karabiner-Elements#2141]
Hi,

I use karabiner to modify the keyboard mapping when using a pcoip host to VNC into a remote Linux machine (from my mac). I have an external standard (non apple) keyboard with regular windows key, and Alt. I mainly use it to override the Alt behaviour to act as regular Alt instead of the Apple command key for tab switching.

What I really want to be able to do is map the Windows key (left_gui in karabiner) to what the Linux box calls the Meta key, so that I can use it for window moving, resizing. The KDE window prefs only allow me to use Meta or Alt for this and I need Alt for other things.

<img width="566" alt="Screenshot 2020-01-31 at 11 17 04" src="https://user-images.githubusercontent.com/20396241/73535734-30663880-441c-11ea-93d8-2bf607ef3cdc.png">

**Comment by frenchie1980** [comment]
Anyone know if this is possible?

**Comment by marlonrichert** [comment]
Isn't Linux's Meta key already the same as Apple's Command key and Microsoft's Windows key? Have you tried if it works out of the box, without needing Karabiner-Elements?
