### ISSUE TITLE
Complex modifications not work anymore (Catalina 10.15.3)

### ISSUE THREAD

**Issue by kevinding0218** [pqrs-org/Karabiner-Elements#2145]
Seems like all the complex modification rules are not working after updating to Catalina 10.15.3

**Comment by AlexPattison** [comment]
I'm also seeing this behavior. Really disappointed in myself for updating without reading what a travesty Catalina has been. This isn't the only thing the update broke for me.

**Comment by wmertens** [comment]
This is a duplicate of at least #1867 and #1895
