### ISSUE TITLE
Impact of macOS 10.15.4 kext deprecation

### ISSUE THREAD

**Issue by RickCogley** [pqrs-org/Karabiner-Elements#2149]
Hi - apparently Apple will deprecate kext in the next macOS, 10.15.4. Does this have an impact on Karabiner-Elements / should we avoid upgrading?

**Comment by saagarjha** [comment]
Karabiner Elements works correctly with SIP disabled on the beta, FWIW.

**Comment by luckman212** [comment]
Ugh. We read you loud and clear Apple. Throw away those silly "computers" and replace with iPads. iPads can do everything a computer can, right? The commercial says so? 😞

**Comment by cristianl** [comment]
There's a WWDC session for the new system extension architecture (https://developer.apple.com/videos/play/wwdc2019/702/) and some documentation for HIDDriverKit (https://developer.apple.com/documentation/hiddriverkit?language=objc) but I couldn't find usage in the wild.

Maybe someone more knowledgeable (i.e. not me) could do some header spelunking: https://github.com/phracker/MacOSX-SDKs/tree/ef9fe35d5691b6dd383c8c46d867a499817a01b6/MacOSX10.15.sdk/System/Library/Frameworks/HIDDriverKit.framework/

**Comment by blacs30** [comment]
> works correctly with SIP disabled on the beta

that's not an option though for many people. I don't even have the possibility to install kext on my business Mac Book. I look forward to a version that does not depend on kexts.

**Comment by zecanard** [comment]
For what it’s worth, Karabiner is still working just like before on 10.15.4 public release. However, there’s no telling what 10.16 will do to kernel extensions.

**Comment by RickCogley** [comment]
Thanks for the heads-up Phong Le. I was waiting to install the combo, to 
see what would happen. Looks like there are plenty of little oddities 
though.
Also like Claas said, I for one don’t want to disable SIP, since there 
are benefits to having it enabled.

**Comment by zecanard** [comment]
@RickCogley Sure, and in case I wasn’t clear, I have not disabled SIP. I didn’t use the beta however, so I can’t speak to those errors people encountered.

**Comment by saagarjha** [comment]
As per [Apple's documentation](https://developer.apple.com/support/kernel-extensions/), the kext should still work even if SIP is enabled, but it should show a warning.

**Comment by RickCogley** [comment]
Ok, I got this when I upgraded to 10.15.4 yesterday: 

<img width="496" alt="JRC Screenshot 2020-03-26 at 15 51 35" src="https://user-images.githubusercontent.com/512328/77702790-a17d3300-6ffc-11ea-9cf1-ecb39270de68.png">

**Comment by gibfahn** [comment]
Got the same, the "Learn More" button in the above image points to https://support.apple.com/en-us/HT210999 .

**Comment by gibfahn** [comment]
Please reopen, still relevant.

**Comment by comex** [comment]
Still relevant.

**Comment by gibfahn** [comment]
I guess this should be closed as a dup of https://github.com/pqrs-org/Karabiner-Elements/issues/2331

**Comment by tekezo** [comment]
Next Karabiner-Elements replaced the legacy system extension with DriverKit.
https://karabiner-elements.pqrs.org/docs/macos-big-sur/
