### ISSUE TITLE
change spanish iso keyboard to latin-american layout (like in old Karabiner)

### ISSUE THREAD

**Issue by lucmart120** [pqrs-org/Karabiner-Elements#2152]
Hi! Sorry to bother you. 

Karabiner (10.22) had the option: 

(For Spanish) "Correct Microsoft Ergonomic Keyboard 4000 Spanish configuration in 'Spanish - ISO' input source." 

that was perfect, but I was unable to find something similar in Karabiner Elements 
(I had to upgrade my old macOS and I'm missing the old Karabiner setup)

Is there a simple way to make that change?
Thank you so much and sorry for asking!

PS: This is the latin-american spanish layout: https://es.wikipedia.org/wiki/Archivo:KB_Latin_American.svg)

**Comment by saratscheff** [comment]
+1
