### ISSUE TITLE
Issues with Logitech Craft keyboard

### ISSUE THREAD

**Issue by sourcesoft** [pqrs-org/Karabiner-Elements#2154]
I've been using Karabiner for almost 4 years. I just got a new Logitech Craft keyboard. Although all the keymappings still work great, but the input dial on the top-left corner no longer functions which is the main feature of this keyboard.
![image](https://user-images.githubusercontent.com/608906/74565220-c337c480-4f3e-11ea-90ce-cf74d2973171.png)

Input dial starts working again as soon as I disable Karabiner or uncheck the device from `Devices` tab.

I love this software and really can't live without it. I use it to map right command key to escape for VIM and left capslock as an extra control, they are still working with the new Logitech Craft keyboard but the dial input basically does nothing now.

Thank you for the help and the awesome app.

Almost related issue https://github.com/pqrs-org/Karabiner-Elements/issues/1450

**Comment by sourcesoft** [comment]
Same happens with f1-f12 or function keys.
The functions keys are only accessible when I actually hold the fn key. It doesn't matter if I enable/disable `Function Keys` in karabiner settings. `Logitech Options` app also have some mappings support and I've tried every scenario in both Karabiner and Logitech Options but F1-F12 do nothing (not even the default old behavior) unless I hold fn key.

**Comment by forivall** [comment]
This also happens with my logitech g710+ (which is an older device, but it still works great), with the "G" keys that are along the left hand side. They don't appear in the event viewer, and as long as I have karabiner-elements intercepting the events, they don't do anything.

In my case, a g710+ linux driver exists and as I've done some low level hid work before, i can grab some raw event info via wireshard. @sourcesoft wireshark might be an option for you as well.

**Comment by christianmagill** [comment]
I was able to get mine working by completely removing the fkeys section from the config file. I'm still on 12.8.0 though.

**Comment by fttx** [comment]
did some manage to make the dial work while karabiner is active?

**Comment by grzegorzkiselev** [comment]
Described my solution here
https://github.com/pqrs-org/Karabiner-Elements/issues/1450#issuecomment-1405613904
