### ISSUE TITLE
Ducky One2 TKL (Calculator)

### ISSUE THREAD

**Issue by jflattery** [pqrs-org/Karabiner-Elements#2155]
Karabiner-Elements sees my keyboard as two "USB-HID" Keyboard's. One as a keyboard, and another as a keyboard and pointing device(mouse). I am trying and failing to get K-E to modify the "Cal" button. Strangely Karabiner-EventViewer is unable to see the keypress actions of "Cal" button, however, [ControllerMate](https://www.orderedbytes.com/controllermate/)(v4.11.1) is able to see the key and refers to it as "AL Calculator." Not only is ControllerMate able to see the key it is able to change the binding.

-------
## More Info
macOS Version: 10.14.6 (18G2022)
Karabiner-Elements: 12.9.0

Keyboard: [Ducky One 2 White LED TKL (DKON1808S)](https://www.duckychannel.com.tw/en/Ducky-One2-White-LED-TKL)
Keyboard Firmware: [1.01.01](https://www.duckychannel.com.tw/en/Support/Detail/22)

Related: #1766

**Comment by jflattery** [comment]
There is comment on [StackExchange](https://apple.stackexchange.com/a/363709) that suggests [USB Overdrive](https://www.usboverdrive.com) is able to see and bind the key as well. The post goes on to state "_It also explains why the other keyboard mappers don’t get the keypress - USB Overdrive registers it as a mouse click event, but apparently whatever mouse click number that is, it’s common enough that the app already knew it was named 'calculator'_."

**Comment by jflattery** [comment]
My apologies if I am being obtuse, but how is ControllerMate able to accomplish this while Karabiner is unable?

**Comment by SiGmAX666** [comment]
This should definitely not be closed, its a real issue. I've seen it discussed in many places. Disappointing as I really like Karabiner but it doesn't work so well with this keyboard.
