### ISSUE TITLE
Uninstalling leaves behind files unable to be removed

### ISSUE THREAD

**Issue by fafuhrmeister** [pqrs-org/Karabiner-Elements#2158]
Running the uninstall either through the app or terminal leaves behind 18 files. 16 of them can be deleted once they're tracked down, but a folder with other files and a kext file are locked and unable to be removed because of permissions issues. I'm left wondering how many other files are hidden in the depths of the OS now and feeling incredibly uncomfortable with the current situation.

How do we remove these files? Why is the software developed in such a way to prevent easy removal? Can we change this? I feel like it would alleviate lots of headache and build some confidence with the app.

**Comment by fafuhrmeister** [comment]
The folder with the kext file is located here:
`/Library/StagedExtensions/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext`

**Comment by tekezo** [comment]
Thank you for pointing out!
It will be removed by running the following command on terminal.
I'll fix the uninstaller to execute the command after files are removed.

```shell
sudo kextcache --prune-staging
```

**Comment by fafuhrmeister** [comment]
Thanks so much! This seems to have worked. Looking forward to the next build that purges any trace of the app.

**Comment by zecanard** [comment]
Stale bot is a forum troll.

**Comment by voodoomailman** [comment]
Hello, that command for the kext file helped me too, thank you! I'm having the same problem though with two files showing up in my Applications folder: 'Karabiner-Elements' and 'Karabiner-EventViewer'. I've gone through uninstalling everything else, nothing shows up in Activity Monitor, these are the last two files (and both are zero bytes, have the 'do not enter' symbol on them and are greyed out). Could you please give me a command to bypass the permissions issue with these as well? Thanks so much!

**Comment by voodoomailman** [comment]
Can anyone please help here?

**Comment by fafuhrmeister** [comment]
Hey voodoomailman,

Your best bet is to perform a clean install of macOS. It's not ideal, but this software was written in a way that makes it nearly impossible to completely remove (and I used to do this for a living at ). It feels really shady that the author has not recompiled the software to fix the permission issues and not leave behind any files after running the uninstaller. Sorry you had to encounter this too. I wish they'd fix this or that I could warn people about it before they installed this.

**Comment by voodoomailman** [comment]
Thank you very much for the advice
