### ISSUE TITLE
karabiner keeps loosing settings after a few hours

### ISSUE THREAD

**Issue by noxxx-13** [pqrs-org/Karabiner-Elements#2162]
Hello,
I am running a Macbook Pro 2012 with OS 10.11.6.  I am using Karabiner 11.6 as I believe it is the last version that runs on El Capitan. I have disabled my left shift key with Karabiner as the key is constantly engaged. It works fine for a while, but after a few hours it stops working. In the Karabiner setings it still says that the left shift key is disabled, however the key is then engaged again. This also happens after I close the lid and open it again. The only remedy is to reboot the computer, it will then remember the settings again. I would be happy with any ideas on how to solve this issue.
Thanks

**Comment by txchen** [comment]
Seems I am having the same issue. After a while, especially after sleep or closing lip, karabiner element stopped working, and reboot can fix the problem.

**Comment by o1dnik** [comment]
@noxxx-13 , @txchen so at any time time you can just restart the OS and everything comes back to as expected? Did you try to restart the karabiner_observer ? Check out here the [code](https://github.com/pqrs-org/Karabiner-Elements/blob/master/src/scripts/uninstall_core.sh#L19) snippet.

**Comment by txchen** [comment]
@o1dnik I tried kill / restart all karabiner processes and it was not helpful. I have to restart the OS to make it work again.
