### ISSUE TITLE
The keyboard layout of the on-screen keyboard is incorrect

### ISSUE THREAD

**Issue by Kerndog73** [pqrs-org/Karabiner-Elements#2167]
The layout of the on-screen keyboard gets extra keys when Karabiner-Elements is running. When the on-screen keyboard is first opened, it appears to work but the layout changes when a key is pressed.

This is the expected layout:

![Screen Shot 2020-02-26 at 13 53 35](https://user-images.githubusercontent.com/10371177/75308955-9caf4d00-589f-11ea-910b-6278b1ae6180.png)

This is the actual layout:

![Screen Shot 2020-02-26 at 13 53 49](https://user-images.githubusercontent.com/10371177/75308988-b05ab380-589f-11ea-8847-06953ead18f2.png)

I'm using Mojave 10.14.6 but this is not a problem on Catalina 10.15.3. To show the on-screen keyboard, open `System Preferences > Keyboard > Keyboard` and enable `Show keyboard and emoji viewers in menu bar`.

**Comment by tiktuk** [comment]
Same here, mine gets changed from ISO to ANSI.
