### ISSUE TITLE
Allow comments in karabiner.json ?

### ISSUE THREAD

**Issue by luckman212** [pqrs-org/Karabiner-Elements#2169]
I know the JSON standard [doesn't officially support it](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json) but some parsers allow C-style comments like
```
{
  "foo": "bar",
  // baz accepts a boolean
  "baz": false
}
```
For now I resorted to this ugly hack:
```
{
--> "documentation_url": "https://pqrs.org/osx/karabiner/json.html",
    "global": {
        "check_for_updates_on_startup": true ...
```
Any chance this could be allowed? It helps me jog my memory when editing this file.

**Comment by marlonrichert** [comment]
If you're going to write modifications that are complex enough that they need comments, then you're probably better off writing them in Ruby instead. For more info, see https://github.com/pqrs-org/KE-complex_modifications#readme
