### ISSUE TITLE
Mousebutton + cursor move scroll stopped working

### ISSUE THREAD

**Issue by StudioMollan** [pqrs-org/Karabiner-Elements#2175]
Hi, 
I've been using Karabiner for years and years and now when updating LCC (Logitech Control Center) to 3.9.11 it stopped working. Ive tried to uninstall both LCC and Karabiner, Reinstalling, rebooting, everything but it will not start working again. 
In EventvViewer i see all commands working  when pressing keys and moving cursor in the "Mouse Area" bu i get no reflection f that to the OS. 
I use the Logitech Trackman Marble, trackball and have really grown a customer to be able to scroll with the trackball while holding button 4, (programmed to small left button)

I'm still on Karabiner 10.22.0 nut it has worked fine up until now. I have tried to ue the latest version of Karabiner Elements today but i could not get it to work there either. 

MAC OS High Sierra 10.13.6
Macpro 5,1 12x3,46GHz 24G Ram
Mac wired keyboard

**Comment by StudioMollan** [comment]
Might be something weird with how Mac OS sees the trackball. 
I have an apple keyboard, a logitech trackman marble (trackball), and an Apple Magic Trackpad connected. The logitech trackball appears as two devises. USB trackball (Apple) and Usb Trackball (logitech). That can't be right? 
Remapping keys on the keyboard works fine but can't remap anything on the mouse. 
![Skärmklipp 2020-03-02 01 52 18](https://user-images.githubusercontent.com/61665234/75637761-9a931880-5c28-11ea-8b32-24b0de4ff3b0.png)

**Comment by StudioMollan** [comment]
This is REALY annoying as its the only way for me to get any scrolling with the trackball. 
I'm sure something is wrong with either the mouse itself or my system after upgrading the LLC app, Karabiner has worked 100% in the past and its not until now that its not working I've found how seriously INVALUABLE the feature is. Would be SOOO happy if anyone could point me in the right direction. 
/
Emil

**Comment by omniraptorr** [comment]
I have this same issue! would like any tips on troubleshooting it
