### ISSUE TITLE
How to hidden the icon from the menu bar?

### ISSUE THREAD

**Issue by xueyuanl** [pqrs-org/Karabiner-Elements#2177]
I know this may be not a good feature, but it really useful to me. So can anyone tell me what exactly to change to achive this ? I could probably compile it myself. Thanks!

**Comment by j-rieck** [comment]
Karabiner-Elements.app > Misc > Show icon in menu bar (Default: on)

Uncheck. Should immediately disappear.

**Comment by xueyuanl** [comment]
> Karabiner-Elements.app > Misc > Show icon in menu bar (Default: on)
> 
> Uncheck. Should immediately disappear.

Thank you so much, I didn't find it, such an idiot...
