### ISSUE TITLE
caps lock issues. CapsLock is always PRESSED

### ISSUE THREAD

**Issue by 4volodin** [pqrs-org/Karabiner-Elements#2183]
I am using hackintosh on high sierra, catalina and I have everywhere issues with capsLock.

when I press capsLock first time after boot,after sleep- in EventViewer I see key_down

and then if I press CapsLock I see key_up and key_down, i.e CapsLock is always pressed and if I assign hyper key for capslock then I have some issues

**Comment by 4volodin** [comment]
the same issue here "When I press caps lock it will show key up and key down the same time. #1874 "

**Comment by believerd** [comment]
It seems like some kind of "hackintosh" issue, I don't know exactly how the hackintosh works, maybe certain driver about keyboard causes this, hope this can help.

**Comment by 4volodin** [comment]
> It seems like some kind of "hackintosh" issue, I don't know exactly how the hackintosh works, maybe certain driver about keyboard causes this, hope this can help.

Have you solved the problem?

**Comment by 4volodin** [comment]
> It seems like some kind of "hackintosh" issue, I don't know exactly how the hackintosh works, maybe certain driver about keyboard causes this, hope this can help.

do you have the same issue also on hackintosh?

**Comment by believerd** [comment]
> > It seems like some kind of "hackintosh" issue, I don't know exactly how the hackintosh works, maybe certain driver about keyboard causes this, hope this can help.
> 
> do you have the same issue also on hackintosh?

Yes, I used to have the same issue on my hackintosh, then I realized it wasn't a problem of this software, because you will get the same result through keyboard setting in system preference. Just modify your "Caps Lock" to any other key in system setting, then you will see it.

**Comment by 4volodin** [comment]
oh, it's so sadly....((( 
Did you send a message  for RehabMan about the problem with driver?

**Comment by believerd** [comment]
No, but I found a similar here. Maybe you can open a new issue.
https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/103
