### ISSUE TITLE
CMD Tab eventually stops working and clicks interpreted as if modifiers were pressed

### ISSUE THREAD

**Issue by danfooo** [pqrs-org/Karabiner-Elements#2184]
I'd just like to leave the feedback that after running Karabiner-Elements for a while (a couple of days), I start to see issues where CMD Tab stops working (task switcher not coming up). In another case it seemed like all my clicks where interpreted as if CMD was held (Apps shown in finder when I click them in the dock, rather than the app launching).

Restarting the machine seems to temporarily fix it, but over all it's not worth it for me as I was only using it to make Caps Lock useful.

**Comment by cipri-tom** [comment]
In my case, the system was acting as if Shift key was always pressed: CMD tab was going backwards, letters were in CAPS, click was as if Shift + Click. The problem went away after I quit and re-started Karabiner. Although I initially went the full reboot route too.

So try just restarting Karabiner next time.

**Comment by martimarkov** [comment]
I have the same issue. Restarting Karabiner is not helping and this keeps happening. I've disabled Caps Lock manipulation, for now, to see if that fixes it.

**Comment by vesper8** [comment]
I have the same problem.. karabiner is causing all kinds of conflicts, my cmd-tab stops working and my dock is acting super weird and needs to be reset constantly.
