### ISSUE TITLE
ignored area doesn't work

### ISSUE THREAD

**Issue by 4volodin** [pqrs-org/Karabiner-Elements#2185]
I use Catalina
ignored area doesn't work

**Comment by ToastedIceCream** [comment]
I am experiencing the same problem as well and I couldn't find any reference online regarding this.
My environment
* macOS Catalina 10.15.4 (19E266)
* Karabiner-Elements version: 12.9.3
* Hardware:
  # 2018 MackBookPro 13"
   # Magic Trackpad 2

Observation: I can see the "Ignored area" showing red/blue dots in the `Karabiner-MultitouchExtension` preference dialogue. But it has no effect in the system. I can still scroll, click in the marked "Ignored area"

**Comment by ryanoboril** [comment]
I have the same issue on macOS Catalina 10.15.7

**Comment by sohge** [comment]
I have the same issue on macOS Monteray
