### ISSUE TITLE
Feature request: Enable/Disable switch in Karabiner Elements' complex modifications

### ISSUE THREAD

**Issue by prasskaly** [pqrs-org/Karabiner-Elements#2187]
Hi,
Is there a way or a method to disable a selected complex modification from the karabiner app ? 
I have many custom written complex modification rules which I want to selectively turn ON and OFF based on my work. 
I understand this is due to JSON which requires the whole file to be all data and no section comment, but, can this be built into the app to have a scratch pad JSON file and an actual JSON file ? Based on the user's selection, the actual JSON file can be generated from the scratch JSON file. This would allow us to selectively load complex modifications without having to kill the app or miss the custom code if some misbehavior is found.

**Comment by marlonrichert** [comment]
You can store your complex modifications in separate files in `~/.config/karabiner/assets/complex_modifications`. Anything you have in there will show up in the _Complex modifications > Add rule_ drawer. This way, you can easily add back rules you've deleted whenever you need them:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/644725/79553789-b69e2c80-80a5-11ea-992a-94ce4f017ffd.png">
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/644725/79553879-dfbebd00-80a5-11ea-9f5c-c95598fd1bec.png">
<img width="1112" alt="Screen Shot 2020-04-17 at 12 18 32" src="https://user-images.githubusercontent.com/644725/79553754-a6864d00-80a5-11ea-84b8-d8aac3dd6daf.png">

**Comment by drageelr** [comment]
Hello,
Is there any update regarding this feature?
