### ISSUE TITLE
Adjusting screen brightness when in target display mode.

### ISSUE THREAD

**Issue by rrlorentzen** [pqrs-org/Karabiner-Elements#2189]
When I have Karabiner Elements running on an iMac (High Sierra) and put it into target display mode the screen brightness controls do not work (f1 and f2). I can exit target display mode, kill Karabiner Elements, enter target display mode, and then adjust brightness on the iMac using f1 and f2. I have tried a number of combinations in the 'Function keys' settings but I can't get it to work without exiting Karabiner Elements on the iMac.

**Comment by jasperslot** [comment]
I have exact the same issue. It drove me nuts to discover it just won't work :( I would love to see a fix :)
