### ISSUE TITLE
alt + arrow key for jumping between words not working anymore

### ISSUE THREAD

**Issue by amadeusp** [pqrs-org/Karabiner-Elements#2192]
With Karabiner-Elements installed on my 10.15.3 (19D76) 2019 Mac Pro, I can't jump between words with alt + arrow keys anymore. Once uninstalled and rebooted, everything works again.
I was using Karabiner-Elements for many months now and never had such issues.

I did install a new USB hub (ICY BOX IB-AC6113) and since then Karabiner-Elements sees all my devices twice, but not macOS itself (when going to System Profiler > USB every device is only listed once).

![20200321-devices](https://user-images.githubusercontent.com/2808562/77223415-8e7de500-6b5c-11ea-80d5-af73b4de20dd.png)

![20200321-system-profiler](https://user-images.githubusercontent.com/2808562/77223409-79a15180-6b5c-11ea-94c1-7d0ddc16d9fb.png)

I tried to completely delete every single Karabiner-Elements related file from my system and installed everything from scratch (remapped my keys etc.). But Karabiner-Elements still sees all the devices twice. Maybe this has something to do with the issue.

The EventViewer is looking good. All the keys are recognised correctly.

Any idea what could cause this?

Thanks in advance!

Best

**Comment by edytk** [comment]
i have same issue here.
uninstall karabiner-elements, everything work again.

looking for answer here.

**Comment by amadeusp** [comment]
It seems like for me this is only happening consistently as long as nativefier apps (self made Electron apps) are running. As long as these nativefier apps are not running, I don't have any issues.
