### ISSUE TITLE
fn key of Happy Hacking Keyboard not observed

### ISSUE THREAD

**Issue by Zeta611** [pqrs-org/Karabiner-Elements#2194]
Karabiner EventViewer does not observe 'fn' key of my Happy Hacking Professional 2.

**Comment by mcdado** [comment]
Do you refer to this? https://github.com/pqrs-org/Karabiner-Elements/issues/2199

**Comment by Zeta611** [comment]
@mcdado I have those unchecked.

**Comment by ssh352** [comment]
same issue on Realforce R2
