### ISSUE TITLE
Combo doesnt not work

### ISSUE THREAD

**Issue by shawnwang0018** [pqrs-org/Karabiner-Elements#2200]
When I use the Command  + Shift + Fn + F12 on IntelliJ Idea , this is not work. I user the lasted Mac Book pro has the Touch Bar.

**Comment by dmotylev** [comment]
_IntelliJ Goland_  receives `Fn + Command + F3` as `F3` when _Karabiner_ modify events on the keyboard.
I also have Mac Book Pro with Touch Bar
