### ISSUE TITLE
Feature request: Auto detect device and switch between profiles

### ISSUE THREAD

**Issue by AAverin** [pqrs-org/Karabiner-Elements#2202]
Basically same as in #1608
It would be lovely to have some kind of UI present to configure which profile should work with which hardware.
I have now 2 different external keyboard profiles and 1 for buildit keyboard when there are no external devices connected. It's very cumbersome to switch them manually every time.

**Comment by marlonrichert** [comment]
At least for Simple Modifications, you can easily specify which device(s) they should apply to: https://github.com/pqrs-org/Karabiner-Elements/issues/2230#issuecomment-615122005

**Comment by AAverin** [comment]
The issue is still not resolved. Simple Modifictions are not enough.
The idea is that to have Profile switch automatically depending on which device is currently connected (or not connected).
Eg, when there is no device connected I want Profile A, when my Dygma Raize is connected - Profile B, when Logictech is connected - Profile C
