### ISSUE TITLE
feature suggestion: provide guidance on mapping pc keyboard "application" to right side command

### ISSUE THREAD

**Issue by myusrn** [pqrs-org/Karabiner-Elements#2203]
When i'm using windows i always use sharpkeys to remap the context menu key, located on right side of pc keyboards between alt and ctrl, to the windows[/command] key since i want ability to access that windows key using right hand as well as left.

Mac keyboards understand this given they have a command[/windows] key present on both right and left side of keyboard along with option/alt and control keys. 

I installed Karabiner-Elements and thankfully found that your pc keyboard keys section had an "application" key that represents what i've always called the context menu key.  I was able to easily use ke to remap that key to the right side command key.  

My feature suggestion is that somewhere in your docs, or in a first run getting started wizard, you call out this example as it may be very common for someone who does this remapping in windows or a long time apple keyboard using having to use a pc keyboard wanting to do this.

**Comment by dann1** [comment]
@myusrn Application mapping did nothing for me, I just remapped right option to right click mouse.
