### ISSUE TITLE
DELETE Karabiner-Elements and Karainer-EventViewer

### ISSUE THREAD

**Issue by jhewell56** [pqrs-org/Karabiner-Elements#2204]
How do I delete these locked applications?

**Comment by tekezo** [comment]
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

**Comment by jhewell56** [comment]
Sorry, but some elements still remain. I deleted all but one, which is locked:
org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext  within the Library...Staged Extensions...Karabiner-VirtualHIDevice folder.  Also, two elements still exist in my Input Monitoring preferences under Accessibility.  How do get rid of these remnants?

**Comment by charliesday** [comment]
I have tried this but I get "Operation not permitted"

**Comment by bryanyork** [comment]
Make sure you've stopped the software, uninstalled, and then run the kextunload command first.
