### ISSUE TITLE
it still happens: karabiner unusable on macOS 10.15.4. "No buffer space available".

### ISSUE THREAD

**Issue by caecebo** [pqrs-org/Karabiner-Elements#2208]
![Captura de Pantalla 2020-03-30 a la(s) 5 09 58 p  m](https://user-images.githubusercontent.com/62819080/77966762-4ae85100-72a9-11ea-9e8d-56a63d4a823c.png)
Lastest beta version 12.9.2.

**Comment by Keepo12** [comment]
Same errors, macOS version 10.15.3, 12.9.0 Karabiner.

**Comment by shijij** [comment]
Same here.
The bug is triggered after sleep.
And can be fixed on restart. until next sleep..

**Comment by iandol** [comment]
Also seeing this, with none of my complex modifications working any more.

**Comment by iandol** [comment]
Update: fully uninstalling, reinstalling and rebuilding my karabiner.json from scratch fixed this for me.

**Comment by mikhailtugushev** [comment]
> Update: fully uninstalling, reinstalling and rebuilding my karabiner.json from scratch fixed this for me.

Thank you! It works for me :))

**Comment by jgsastre** [comment]
That doesn't work for me
