### ISSUE TITLE
PreferencesWindow-->MainMenu.xib false alarm!

### ISSUE THREAD

**Issue by btwise** [pqrs-org/Karabiner-Elements#2215]
use XCODE 11.3.1 ,in PreferencesWindow-->MainMenu.xib there is misplaced "views" false alarm, and unable to modify the MainMenu. The xib content, can lead to constraint element failure!please fix it!

**Comment by btwise** [comment]
![image](https://user-images.githubusercontent.com/38809560/78336444-f18e6380-75c1-11ea-9821-7df3061eb6f9.png)

**Comment by tekezo** [comment]
This issue annoys me, too.

I think it's an issue of Xcode and I don't succeed to find a workaround.
(I modify constraints without preview, and confirm it by run.)

**Comment by btwise** [comment]
It is a bad idea to directly modify the code of xib, why your previous xib file did not have this problem, hope you can fix it!
