### ISSUE TITLE
SpaceFN: Unwanted triggering at beginning of word.

### ISSUE THREAD

**Issue by kgrossjo** [pqrs-org/Karabiner-Elements#2216]
My configuration is derived from SpaceFN, and I'm struggling with unwanted triggering.  I type normal text, and it seems that I type the combination `<space> <letter>` with overlap sometimes, so that the corresponding SpaceFN binding triggers.

I thought about it and I think it would help if there was a timeout of some sort.  Consider these sequences of events:

* space down; letter down; letter up; space up
* space down; letter down; space up; letter up

I've two ideas for timeouts that might help.  One would be to require a minimum number of milliseonds between space down and letter down -- if the time is shorter, then SpaceFN should not trigger.  The other idea might be to require a minimum number of milliseconds between space down and space up.

I see that Karabiner has a number of parameters with such timeouts, but none seems to fit the bill.  I have already decreased `basic.to_if_alone_milliseconds` to 100 (from 1000), but since the problem happens when I type fast, space is not held down for a long time.

Any ideas?  Maybe there is another parameter that is applicable, I just don't know.

**Comment by marlonrichert** [comment]
I faced the same problem when implementing my complex modification "Ergoemacs mode", but I managed to solve it. Have a look at my code to see how: https://ke-complex-modifications.pqrs.org/?q=ergoemacs#ergoemacs_mode

**Comment by marlonrichert** [comment]
BTW, I think actually found an easier way to fix it, but I still have to test it. I will update the "Ergoemacs mode" complex modification when I'm done.

**Comment by marlonrichert** [comment]
Nope, I tried it, but it doesn't work. The only way to make it work reliably is the way I've done it with my [Ergoemacs mode](https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/ergoemacs_mode.json.rb) mod.

**Comment by kgrossjo** [comment]
Thank you very much, @marlonrichert, for investigating.  I took a peek at your code, and I'm still on the fence whether I should take Ergoemacs and adjust the keybindings, or polish my own.

**Comment by marlonrichert** [comment]
I've tested my Ergoemacs mod extensively and it never triggers accidentally, even when typing very fast. Just give it a go and then you can fine-tune it to your own wishes. 🙂 If you do, please consider contributing your changes as updates to the original SpaceFN mod, so other users can benefit from it, too: https://github.com/pqrs-org/KE-complex_modifications

**Comment by marlonrichert** [comment]
Also, my Ergoemacs mod contains a bunch of DEBUG variables, so you can inspect exactly what is happening in KE internally through its EventViewer:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/644725/79982660-5812ed00-84af-11ea-853e-9a7f0f42947b.png">

The documentation can tell you only so much. I wouldn't have been able to fine-tune my mod without this. 🙂

**Comment by tshu-w** [comment]
For those who are bothered by SpaceFN triggering during fast typing, you can refer to my setting to cancel SpaceFN short time after the last typing https://gist.github.com/tshu-w/82af1843798edaab9062e44cb261d25a#file-spacefn-json-L779

**Comment by BryanSchuetz** [comment]
> For those who are bothered by SpaceFN triggering during fast typing, you can refer to my setting to cancel SpaceFN short time after the last typing https://gist.github.com/tshu-w/82af1843798edaab9062e44cb261d25a#file-spacefn-json-L779

so, basically you're just setting the delayed_aciton_delay to 200 milliseconds for everything?

**Comment by tshu-w** [comment]
Not really. I forbid 200ms SpaceFN after pressing any other key press, and the global `delayed_action_delay` is not changed.

**Comment by luutuankiet** [comment]
> For those who are bothered by SpaceFN triggering during fast typing, you can refer to my setting to cancel SpaceFN short time after the last typing https://gist.github.com/tshu-w/82af1843798edaab9062e44cb261d25a#file-spacefn-json-L779

@tshu-w  thank you so much, after some time looking around other alternatives I think this is the way. Hard work but does what is intended.

**Comment by kvenn** [comment]
Hi @tshu-w, thank you for posting your solution! It's by far the least error prone.

I'm still having some issues when I'm typing particularly fast and it will sometimes skip thespace (<-) key. What would be your recommendation if I'm running into this? I've tried updating all delay variables and that hasn't seemed to work.
(I tried `"basic.to_delayed_action_delay_milliseconds": 200` in the disable, and `"basic.to_if_held_down_threshold_milliseconds": 150` in the enable.)

**Comment by tshu-w** [comment]
Hi @kvenn, I didn't quite notice these problems, maybe because I don't type fast enough ;)

My suggestion is to increase the value of `"basic.to_if_held_down_threshold_milliseconds": 150` to `300`ms to see if the problem is alleviated.

**Comment by kvenn** [comment]
@tshu-w - Thank you for your reply! I don't think I'm crazy fast... I'm around 150WPM. 300ms unfortunately didn't improve the issue. Any chance you have any other suggestions I could try? 

Thanks again

**Comment by tshu-w** [comment]
Hi @kvenn 
There are two reasons why spaces might be ignored:

1. Holding the space bar alone for more than `to_if_alone_timeout_milliseconds` (300ms), the `to_if_alone` is canceled.
2. Pressing the space bar and another key within `to_if_held_down_threshold_milliseconds` (150ms) (space_down, other_key_down, space_up, other_key_up), see discussions at https://github.com/pqrs-org/Karabiner-Elements/issues/3538 and https://github.com/pqrs-org/Karabiner-Elements/issues/1667

For the first scenario, you can resolve it by increasing `to_if_alone_timeout_milliseconds` (like the default 1000ms).
For the second scenario (_which I think you are encountering_), ideally, you could try increasing all `to_delayed_action_delay_milliseconds` values in the configuration file.

You can try the [modified configuration](https://gist.github.com/tshu-w/82af1843798edaab9062e44cb261d25a) I provided.

If that still does not work, then you may need to use `to_if_canceled` as discussed in the issues, but this requires refactoring the configuration from setting the `spacefn_mode` variable to using modifier keys, as `spacefn_mode` cannot be canceled by `to_after_key_up` after adding “halt”.

**Comment by tshu-w** [comment]
Or try these rules:
```json
    ...
    {
      "description": "SpaceFN: Space enables SpaceFN mode (see: https://geekhack.org/index.php?topic=51069.0 & https://spacelauncherapp.com)",
      "manipulators": [
        {
          "conditions": [
            {
              "name": "_spacefn_mode",
              "type": "variable_if",
              "value": 0
            }
          ],
          "from": {
            "key_code": "spacebar"
          },
          "parameters": {
            "basic.to_if_alone_timeout_milliseconds": 500,
            "basic.to_if_held_down_threshold_milliseconds": 200,
            "basic.to_delayed_action_delay_milliseconds": 200
          },
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "spacefn_mode",
                "value": 0
              }
            }
          ],
          "to_delayed_action": {
            "to_if_canceled": [
              {
                "key_code": "spacebar"
              },
              {
                "set_variable": {
                  "name": "spacefn_mode",
                  "value": 0
                }
              }
            ]
          },
          "to_if_alone": [
            {
              "key_code": "spacebar",
              "halt": true
            }
          ],
          "to_if_held_down": [
            {
              "set_variable": {
                "name": "spacefn_mode",
                "value": 1
              }
            }
          ],
          "type": "basic"
        }
      ]
    },
    ...
```
