### ISSUE TITLE
double tap / double press key to run a shell command

### ISSUE THREAD

**Issue by ipatch** [pqrs-org/Karabiner-Elements#2219]
I'd like to be able to _double tap_ a single key, ie. the <kbd>right ⌘</kbd> within ~ 1000 milliseconds and have it fire off a shell command doesn't matter what the shell open does at the moment, but eventually I'd the _double tap_ to launch a _spoon_ installed via Hammerspoon.

I have the below JSON, that I've worked out the syntax errors, thanks to karabiner for hot reloading its configuration files when changes are saved, however haven't figure out how to troubleshoot the logic errors in the JSON snippet 🤷‍♂️

Is there a proper way to troubleshoot logic errors with karabiner elements? I've been using karabiner mostly with installed modifiers from the website, so have little experience writing my own custom modifiers.

```json
{
  "conditions": [
    {
      "name": "right_command pressed",
      "type": "variable_if",
      "value": 1
    }
  ],
  "description": "Right command double click part 1",
  "from": {
    "key_code": "right_command",
    "modifiers": {
      "optional": [
        "any"
      ]
    }
  },
  "to": [
    {
      "shell_command": "open -g '/Applications/Sarfari.app'"
    }
  ],
  "type": "basic"
},
{
  "description": "Right command double click part 2",
  "from": {
    "key_code": "right_command",
    "modifiers": {
      "optional": [
        "any"
      ]
    }
  },
  "to": [
    {
      "set_variable": {
        "name": "right_command pressed",
        "value": 1
      }
    },
    {
      "key_code": "right_command"
    }
  ],
  "to_delayed_action": {
    "to_if_canceled": [
      {
        "set_variable": {
          "name": "right_command pressed",
          "value": 0
        }
      }
    ],
    "to_if_invoked": [
      {
        "set_variable": {
          "name": "right_command pressed",
          "value": 0
        }
      }
    ]
  },
  "type": "basic"
}
```

**Comment by ipatch** [comment]
ended up figuring this one out.

**Comment by josephlim75** [comment]
Hey ipatch,

Do you mind sharing your script to enable double press key to execute shell command ?  I'm trying to perform the same

**Comment by ipatch** [comment]
this is what i ended up rolling with. so far so good.

https://github.com/ipatch/dotfiles/blob/6e2c3a754e7211f4fa83e460e7770c7e47fafaa3/config/karabiner/assets/complex_modifications/change_shift_key_rev2.json

**Comment by MuhammedZakir** [comment]
> this is what i ended up rolling with. so far so good.
> 
> https://github.com/ipatch/dotfiles/blob/6e2c3a754e7211f4fa83e460e7770c7e47fafaa3/config/karabiner/assets/complex_modifications/change_shift_key_rev2.json

I think you meant this -- https://github.com/ipatch/dotfiles/blob/6e2c3a754e7211f4fa83e460e7770c7e47fafaa3/config/karabiner/assets/complex_modifications/ipatch_double_tap_key.json?

@ipatch: For your "Super CAPS with shift keys" modification (the one you linked), `from.simultaneous`[1] is better.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/simultaneous/

**Comment by ipatch** [comment]
@MuhammedZakir thank you, must've copiedpasta'd the file link 🤦‍♀️

https://github.com/ipatch/dotfiles/blob/6e2c3a754e7211f4fa83e460e7770c7e47fafaa3/config/karabiner/assets/complex_modifications/ipatch_double_tap_key.json
