### ISSUE TITLE
Media and Function keys are not generating events for Karabiner on an MS Natural Ergonomic 4000 keyboard

### ISSUE THREAD

**Issue by offbyone** [pqrs-org/Karabiner-Elements#2220]
I'm having the same issue as #586, on much newer versions of the software in question:

* Microsoft Natural Ergonomic 4000 Keyboard
* 15" MBP, 2018 vintage
* macOS Mojave 10.14.6
* Karabiner Elements 12.9.0

The media bar keys do not register in Karabiner Event viewer, even when they work; the play/pause button for example, *does* what it's supposed to but doesn't generate an event in the event viewer.

_Originally posted by @offbyone in https://github.com/pqrs-org/Karabiner-Elements/issues/586#issuecomment-611767115_

**Comment by dioxide** [comment]
+1 for the MS Natural 4000.

**Comment by danvk** [comment]
I'm running into the same issue with the Microsoft Natural 4000, macOS 13.2.1 and Karabiner-Elements version 14.11.0. Some of the keys on the keys on the top row (silver) do work, e.g. the "search" button opens spotlight. But the media keys don't work, and none of them produce any events in the Karabiner event viewer.

**Comment by TrentSlaton** [comment]
Same issue for me. Haven't found a fix yet.
