### ISSUE TITLE
anyone noticed less responsive behaviour?

### ISSUE THREAD

**Issue by pierredelun3** [pqrs-org/Karabiner-Elements#2221]
Since one week I notice a less reliable response of karabiner-elements.
95% of my modifications are simultaneous key presses. Until recently
all combinations worked flawlessly, total reliability.
Since one week, simultaneous key presses are not recognized about 1/3
of the times. What is more puzzling, some of them seem to work
more reliably than others; maybe the reason is that the different position of 
fingers on the keyboard produces different timings for the key presses.

What might be the reason? I did not change anything in my settings, 
my system is Mojave 10.4.16 since several months, no install of new
shady software, no other signs of bad behaviour in my computer.
The number of complex modifications is large (240) but not
overwhelming of K-E I guess.

If I change the simultaneous threshold to a larger value (700) things
seem to improve, but still many failures. I am not 100% sure this improvement
is real or just wishful thinking.

Has this occurred to anyone here? what should I look for?

Thx for suggestions

**Comment by yoavfrancis** [comment]
Same here.

**Comment by justin-levine** [comment]
I was just about to report this.
The thing that's particularly weird about it is it either:
1. Works as before
2. I hit my simultaneous shortcut, a few seconds pass, and then it works
3. I hit my simultaneous shortcut, it doesn't work, but if I press any key, the previously pressed shortcut pops up.

**Comment by justin-levine** [comment]
I am still experiencing this and it's quite a hassle. I now have a habit of pressing my shortcuts many times to get it to work.
