### ISSUE TITLE
The app always shows the main window on startup

### ISSUE THREAD

**Issue by manoelcampos** [pqrs-org/Karabiner-Elements#2222]
Since the app is used almost all the time just running in background, showing the main window on startup is a little bit annoying. Even if I set it to hide at "Login Items" in "System Preferences", that doesn't work.

<img width="444" alt="login-items" src="https://user-images.githubusercontent.com/261605/79027656-77328600-7b63-11ea-92b0-a0bb6e4666ab.png">

**Comment by zecanard** [comment]
Duplicate of #1068.

**Comment by manoelcampos** [comment]
Sorry. I searched just open issues. I've just tried as in #1068 and it works perfectly.

**Comment by zearp** [comment]
Ran into the same issue I think. But there was no Karabiner-elements entry in the Login Items section after installing 9.2.0.

There is no window showing but there's still focus stealing and movement in the Dock when starting up. Is there a way to completely hide this?

I checked the LaunchDeamons and Agents and there's some stuff there, but I don't know which one can be removed without breaking the functionality, if any.

Thank you!

```
LaunchAgents % ls | grep pqrs    
org.pqrs.karabiner.agent.karabiner_grabber.plist
org.pqrs.karabiner.agent.karabiner_observer.plist
org.pqrs.karabiner.karabiner_console_user_server.plist
org.pqrs.karabiner.karabiner_session_monitor.plist
```

```
LaunchDaemons % ls | grep pqrs
org.pqrs.karabiner.karabiner_grabber.plist
org.pqrs.karabiner.karabiner_kextd.plist
org.pqrs.karabiner.karabiner_observer.plist
```
