### ISSUE TITLE
Karabiner will be imcompatible warning

### ISSUE THREAD

**Issue by mesqueeb** [pqrs-org/Karabiner-Elements#2223]
I just updated macOS to 10.15.4 today and got this warning:
> Existing software on your system loaded a system extension signed by “Fumihiko Takayama”, which will be incompatible with a future version of macOS. Contact the developer for support.

Any plans to continue supporting Karabiner?

**Comment by zecanard** [comment]
Duplicate of #2196 and #2149.
See https://github.com/pqrs-org/Karabiner-Elements/issues/2196#issuecomment-604419446.

**Comment by mesqueeb** [comment]
Thanks!
