### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by cppguru** [pqrs-org/Karabiner-Elements#2226]
Hi guys, I am getting kernel panics for days now and it looks like Karabiner is in the stack.  It seems to be some lock-up issue on a late 2013 Mac Pro.  I also had a memory module die on me so I am not 100% sure this is actually Karabiner, but I wonder if anyone uses it on 12 core Mac Pro 6,1?  Anyone has seen kernel panics with Karamiber in the stack?  These are way too frequent.  (In the meantime I stopped all Karabiner related things - I think - to see if it keeps happening.  I am on 12.9.0, essentially clean install because I had no time to learn anything yet.

**Comment by luckman212** [comment]
Some discussion in https://github.com/pqrs-org/Karabiner-Elements/issues/2151

**Comment by cppguru** [comment]
Yeah.  found it later.  As you can see posted there several times.  I had to conclude that this project is abandoned.  The developer has not reacted to anything for a very long time.  Including that kernel panic.  Which I would consider a very serious issue.

I'd love to look into it, but it would take me probably months of learning as all I know about Darwin is its name. :)

**Comment by luckman212** [comment]
No, the project is not abandoned. Just 5 days ago in fact, @tekezo posted [this note](https://github.com/pqrs-org/Karabiner-Elements/issues/2196#issuecomment-604419446):

> I'm working to migration from the old kext

So, we just need to wait...

**Comment by cppguru** [comment]
Weird. I got notifications of all other updates to these 2 issues but not that update. I’m cursed it seems to always make a fool of myself.

**Comment by NSExceptional** [comment]
Anyone know where the kext is? I uninstalled Karabiner but somehow the kext is still on my machine and causing panics.

**Comment by carlbennettnz** [comment]
@NSExceptional For me it was

```
/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/
```

If you open System Report → Extensions and find Karabiner in the list, it should show the kext location in the info pane.

**Comment by NSExceptional** [comment]
Thanks!

**Comment by flybayer** [comment]
stale bot this isn't stale - still a big problem :)

**Comment by carlbennettnz** [comment]
macOS 10.15.5 fixed it for me

**Comment by flybayer** [comment]
I'm still getting kernel panic on 10.15.5

**Comment by tekezo** [comment]
Next Karabiner-Elements replaced the legacy system extension with DriverKit.
It solves any issues around kext.
https://karabiner-elements.pqrs.org/docs/macos-big-sur/

https://github.com/pqrs-org/Karabiner-Elements/issues/2331
