### ISSUE TITLE
Does Karabiner support complex modifications with title name?

### ISSUE THREAD

**Issue by shuxiao9058** [pqrs-org/Karabiner-Elements#2227]
such as in iterm, with emacs "C-SPC" works as "C-\\"

**Comment by marlonrichert** [comment]
I don't understand what you mean. Can you try to explain it a bit more?

**Comment by zecanard** [comment]
There’s a description field already being used by all complex modifications. Is that not what you want?

**Comment by shuxiao9058** [comment]
What I mean in terminal, some key binds can work different when different program running in  current terminal.

**Comment by marlonrichert** [comment]
That's already possible. See, for example, the complex modifications for terminal apps: https://ke-complex-modifications.pqrs.org/?q=terminal

**Comment by shuxiao9058** [comment]
> That's already possible. See, for example, the complex modifications for terminal apps: https://ke-complex-modifications.pqrs.org/?q=terminal

this is not what i want.

**Comment by marlonrichert** [comment]
> What I mean in terminal, some key binds can work different when different program running in current terminal.

I don't think KE supports that, but you might be able to configure it in the programs you run in your terminal.
