### ISSUE TITLE
Menu key cannot be remapped

### ISSUE THREAD

**Issue by mtlberri** [pqrs-org/Karabiner-Elements#2228]
Hi,

I have a MacBook pro and a GK61 keyboard.

I have managed to remap successfully all the keys I wanted, except for the 'Menu' key of that keyboard.
I want to remap it to down arrow but that does not work.

Can you help me with that?
Thanks a lot

OS 10.15.3 (19D76)
MacBook Pro (Retina, 13-inch, Mid 2014)
Keyboard GK61 Mechanical Gaming Keyboard - 61 Keys Multi Color RGB Illuminated LED Backlit

**Comment by marlonrichert** [comment]
From the Karabiner-Elements icon in the menu bar, open the EventViewer:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/644725/79549030-09281a80-809f-11ea-8f00-c5529c070d76.png">
With the EventViewer open, press your Menu key. What "Name" does it show? That's the one you need to remap. For the Menu key, it usually is "application".

**Comment by mtlberri** [comment]
Thank you it helped me a lot and it works now. It was indeed the application key.
Thanks a lot, all good for me.
