### ISSUE TITLE
Karabiner_observer running in background when Karabiner program is closed

### ISSUE THREAD

**Issue by AdamBD** [pqrs-org/Karabiner-Elements#2229]
Can someone explain to me why the observer runs when the main program is not running.

Also how can I disable this behavior, it consumes CPU beginning on startup of my mac even when I dont turn this program on.

**Comment by tekezo** [comment]
Please quit Karabiner-Elements.
https://karabiner-elements.pqrs.org/docs/manual/operation/quit/

**Comment by carlosflorencio** [comment]
Hi,

`karabiner_observer` process keeps running even after manually quitting from the Karabiner Elements UI.

Is this a new behavior?

Apple M1 Pro, 12.4

**Comment by ghembo** [comment]
Same behavior here, Apple M1 Pro, 13.4

**Comment by pecataToshev** [comment]
Why is this clossed? Is it somehow resolved because I face the same isuue?
