### ISSUE TITLE
Simultaneous languages auto layout switch on internal keyboard and external keyboard

### ISSUE THREAD

**Issue by spallas** [pqrs-org/Karabiner-Elements#2230]
I would like to obtain the following experience:
- If I type on the internal keyboard of the macbook I want to type in the language of the keyboard (let's say German, Spanish or Italian)
- I have a second keyboard (wired or on bluetooth) with the US layout, and when I start typing with this keyboard the layout automatically switches to the US layout, then when I start typing back on the internal keyboard the layout switches automatically to the other language layout.

I was thinking about making Karabiner use the US layout only on the external keyboards, while not  making any change to the internal one. Still I don't know if this is possible and how to do it.

I tried autokbisw but without success for now, but I would like to avoid that  #(659). Thank you!

**Comment by marlonrichert** [comment]
Click on the Karabiner-Elements icon in the menu bar and choose Preferences:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/644725/79549482-b4d16a80-809f-11ea-8668-87dc36caec05.png">

In Preferences, click the "Target device" dropdown:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/644725/79549556-cdda1b80-809f-11ea-9d06-133c304772df.png">

Select the device to which you want your modifications to apply:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/644725/79549618-e77b6300-809f-11ea-992d-f7fb5877927e.png">

Modifications you create for a specific device will not apply to other devices. Only those modifications you create under "For all devices" will apply to all devices.

 Alternatively, if there are devices that you never want to modify, you can go to the "Devices" tab in KE preferences and deselect the device that you do not want to modify:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/644725/79549852-332e0c80-80a0-11ea-8caf-dab7f8076afe.png">

**Comment by akbreg** [comment]
Hi! 

I believe I have followed MuhammedZakir's explanation, but only seem to have been able to create a way of toggling between British and Norwegian keyboard using shift+f3. 

I was hoping to create a way of automatically selecting British input source by activating (pressing any key) on my external wireless magic keyboard, and automatically selecting Norwegian input source by activating my MacBookss internal keyboard, and so forth. But so far I don't seem to have been able to create this behavior.

Are there any further steps i need to do in Karabiner, than importing and enabling the modified JSON, to beable to create automatic switching?

**Comment by ManeLippert** [comment]
**Hello All**,

after investigating the documentation I came up with the following complex modification to "automate the language switching. It changes to the desired keyboard layout if you press any key on the external keyboard and switch back to the internal keyboard preset layout. You could also change the identifier (e.g. ```vendor id``` or ```product id```)  for the device, if you want to change a specific external keyboard. 

The only drawback with this method is that you have to press a key on the keyboard and then the language switches. You can not just write immediately in the other language. If someone knows how I could switch the language and write simultaneously, please write!

### Sources
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/select-input-source/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/select-input-source/)
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/)
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/any/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/any/)
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/input-source/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/input-source/)

```json
{
    "title": "Dynamic Keyboard Layout",
    "rules": [
        {
            "description": "Change keyboard layout on external keyboard to, e.g. English US, after pressing any button and back to, e.g. German DE, after pressing any button on the built-in keyboard.",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "any": "key_code"
                    },
                    "to": [
                        {
                            "select_input_source": {
                                "input_source_id": "com.apple.keylayout.US",
                                "language": "en"
                            }
                        }
                    ],
                    "conditions": [
                        {
                            "type": "input_source_if",
                            "input_sources": [
                                {
                                    "language": "de"
                                }
                            ]
                        },
                        {
                            "type": "device_if",
                            "identifiers": [
                                {
                                    "is_built_in_keyboard": false
                                }
                            ]
                        }
                    ]
                },
                {
                    "type": "basic",
                    "from": {
                        "any": "key_code"
                    },
                    "to": [
                        {
                            "select_input_source": {
                                "input_source_id": "com.apple.keylayout.German",
                                "language": "de"
                            }
                        }
                    ],
                    "conditions": [
                        {
                            "type": "input_source_if",
                            "input_sources": [
                                {
                                    "language": "en"
                                }
                            ]
                        },
                        {
                            "type": "device_if",
                            "identifiers": [
                                {
                                    "is_built_in_keyboard": true
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by noahtallen** [comment]
Here is another example of a complex modification. I use an ErgoDox, which has a built-in Colemak profile. (E.g. the computer can just remain on the normal QWERTY layout, and the layout is built into the keyboard.) When I use the laptop by itself, I switch the layout from US to Colemak, so that the MacBook keyboard works as expected.

Some extra info as I was exploring how to do this based on @ManeLippert's snippet:

- You _must_ set the `input_source_if` or `input_source_unless` conditions. Otherwise, it will set the input source on every keystroke, which basically prevents the keyboard from typing anything. (Like @ManeLippert pointed out, the "select input source" action doesn't also write the normal key value.)
- You can use the `input_source_unless` to help it switch in more situations. In this situation, it will switch to US _unless_ it's already in US. (And to Colemak _unless_ it's already in Colemak.
- You can use "Launch event viewer" from the Karabiner menu item, and then checkout "devices" and "variables" to get metadata like the `product_id` to identify the specific keyboard.

So this setup will switch to US when not in US and I begin typing on my ErgoDox. Otherwise, it will switch back to Colemak!

```json
{
  "description": "Change keyboard layout to Colemak based on external keyboard.",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "any": "key_code"
      },
      "to": [
        {
          "select_input_source": {
            "input_source_id": "com.apple.keylayout.US",
            "language": "en"
          }
        }
      ],
      "conditions": [
        {
          "type": "input_source_unless",
          "input_sources": [
            {
              "input_source_id": "com.apple.keylayout.US"
            }
          ]
        },
        {
          "type": "device_if",
          "identifiers": [
            {
              "product_id": 18806
            }
          ]
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "any": "key_code"
      },
      "to": [
        {
          "select_input_source": {
            "input_source_id": "com.apple.keylayout.Colemak",
            "language": "en"
          }
        }
      ],
      "conditions": [
        {
          "type": "input_source_unless",
          "input_sources": [
            {
              "input_source_id": "com.apple.keylayout.Colemak"
            }
          ]
        },
        {
          "type": "device_unless",
          "identifiers": [
            {
              "product_id": 18806
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by nickdring** [comment]
> **Hello All**,
> 
> after investigating the documentation I came up with the following complex modification to "automate the language switching. It changes to the desired keyboard layout if you press any key on the external keyboard and switch back to the internal keyboard preset layout. You could also change the identifier (e.g. `vendor id` or `product id`) for the device, if you want to change a specific external keyboard.
> 
> The only drawback with this method is that you have to press a key on the keyboard and then the language switches. You can not just write immediately in the other language. If someone knows how I could switch the language and write simultaneously, please write!
> 
> ### Sources
> * https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/select-input-source/
> * https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/
> * https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/any/
> * https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/input-source/
> 
> ```json
> {
>     "title": "Dynamic Keyboard Layout",
>     "rules": [
>         {
>             "description": "Change keyboard layout on external keyboard to, e.g. English US, after pressing any button and back to, e.g. German DE, after pressing any button on the built-in keyboard.",
>             "manipulators": [
>                 {
>                     "type": "basic",
>                     "from": {
>                         "any": "key_code"
>                     },
>                     "to": [
>                         {
>                             "select_input_source": {
>                                 "input_source_id": "com.apple.keylayout.US",
>                                 "language": "en"
>                             }
>                         }
>                     ],
>                     "conditions": [
>                         {
>                             "type": "input_source_if",
>                             "input_sources": [
>                                 {
>                                     "language": "de"
>                                 }
>                             ]
>                         },
>                         {
>                             "type": "device_if",
>                             "identifiers": [
>                                 {
>                                     "is_built_in_keyboard": false
>                                 }
>                             ]
>                         }
>                     ]
>                 },
>                 {
>                     "type": "basic",
>                     "from": {
>                         "any": "key_code"
>                     },
>                     "to": [
>                         {
>                             "select_input_source": {
>                                 "input_source_id": "com.apple.keylayout.German",
>                                 "language": "de"
>                             }
>                         }
>                     ],
>                     "conditions": [
>                         {
>                             "type": "input_source_if",
>                             "input_sources": [
>                                 {
>                                     "language": "en"
>                                 }
>                             ]
>                         },
>                         {
>                             "type": "device_if",
>                             "identifiers": [
>                                 {
>                                     "is_built_in_keyboard": true
>                                 }
>                             ]
>                         }
>                     ]
>                 }
>             ]
>         }
>     ]
> }
> ```

Hi, this worked for me, but I had to delete the first two lines with the title and rules because I got an error when I tried to save it. I now have automatic switching between my external US keyboard and my Macbook italian keyboard.

**Comment by rudironsoni** [comment]
I made a complex modification that changes both my input language and my karabiner profile to match the input language:


```json
{
    "description": "Globe (fn) toggles between Spanish (es_ES) and US Intl PC (en_US)",
    "manipulators": [
        {
            "conditions": [
                {
                    "input_sources": [{ "language": "^es$" }],
                    "type": "input_source_if"
                }
            ],
            "from": { "key_code": "fn" },
            "to_if_alone": [
                {
                    "select_input_source": {
                        "input_source_id": "com.apple.keylayout.USInternational-PC",
                        "language": "en"
                    }
                },
                { "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'en_US'" }
            ],
            "type": "basic"
        },
        {
            "conditions": [
                {
                    "input_sources": [{ "language": "^en$" }],
                    "type": "input_source_if"
                }
            ],
            "from": { "key_code": "fn" },
            "to_if_alone": [
                {
                    "select_input_source": {
                        "input_source_id": "com.apple.keylayout.Spanish",
                        "language": "es"
                    }
                },
                { "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'es_ES'" }
            ],
            "type": "basic"
        }
    ]
}
```
