### ISSUE TITLE
Release notes in Software Update contain dead link to release history

### ISSUE THREAD

**Issue by hcaw** [pqrs-org/Karabiner-Elements#2232]
Environment:

- MacOS v10.15.4
- Karabiner-Elements v12.9.0 (installed via brew casks)

Steps to reproduce:

- Navigate to Karabiner-Elements->Preferences->Misc
- Click "Check for beta updates" button
  - Software Update dialog opens, prompting an update to v12.9.3
- In the Release Notes text box, click the "More" hyperlink located at the bottom
  - Browser navigates to a webpage detailing the release history

Issue details:

- The URL linked by the “More” text is `https://pqrs.org/osx/karabiner/history.html`, which returns a 301 redirect to `https://karabiner-elements.pqrs.org/history.html`, which then returns a 404.

**Comment by esusatyo** [comment]
@hcaw Is this supposed to go to https://karabiner-elements.pqrs.org/docs/releasenotes/?

**Comment by hcaw** [comment]
Yes I believe so

**Comment by tekezo** [comment]
Thank you for feedback!
I fixed this issue.

**Comment by hcaw** [comment]
You're welcome, thanks for fixing!
