### ISSUE TITLE
Function keys do not work on Touch Bar if the application uses function keys by default

### ISSUE THREAD

**Issue by Jendker** [pqrs-org/Karabiner-Elements#2233]
I was struggling with the problem that the modifier keys were not used together with function keys (like Shift+F6), but the solution to it is here: https://github.com/pqrs-org/Karabiner-Elements/issues/2201#issuecomment-610990146 https://github.com/pqrs-org/Karabiner-Elements/issues/1972

The problem is that if I use the solution and activate "No product name" as on the image here:

<img width="1112" alt="Bildschirmfoto 2020-04-18 um 15 35 10" src="https://user-images.githubusercontent.com/14967831/79639183-5d5bf900-818a-11ea-9c47-98001f21f1d3.png">

then if I have an application, which uses function keys by default as configured here (sorry for foreign language):
<img width="874" alt="Bildschirmfoto 2020-04-18 um 15 37 22" src="https://user-images.githubusercontent.com/14967831/79639197-8086a880-818a-11ea-888d-e17b2dbb6a5c.png">
then after pressing the function key on touch bar the media control key are triggered instead of wanted function keys.

If I disable "No product name" modification in Karabiner tool then applications configured to show function keys by default will work correctly with function keys, but I run again into the first issue: cannot use modifier key for function keys like Shift+F6.

**Comment by Jendker** [comment]
It is still valid.

**Comment by kota65535** [comment]
@Jendker 
Got the same problem too, but I found the solution.
Have you tried this option?

![image](https://user-images.githubusercontent.com/10975834/85118098-cc250380-b25a-11ea-994d-41836d789173.png)

**Comment by Jendker** [comment]
That's a combination, which I haven't tried yet, thank you :) That fixed it!
