### ISSUE TITLE
Shift + command doesn't work when holding control or option

### ISSUE THREAD

**Issue by thoelze1** [pqrs-org/Karabiner-Elements#2234]
Any combination of remapped modifiers containing control or option can be used with at most one of shift or command.

I am remapping the following keys:

- j to right_shift when held
- k to right_control when held
- l to right_option when held
- semicolon to right_command when held

Here is an excerpt of my modification file (the rules for k, l and semicolon are omitted because they are almost identical to the rule for j):

```
{
    "title": "Home row to modifiers",
    "rules": [
        {
            "description": "Change j to shift if pressed with other keys",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "j",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_shift"
                        }
                    ],
                    "to_if_alone": [
                        {
                            "key_code": "j"
                        }
                    ]
                }
            ]
        }
    ]
}
```

The following modifier combinations don't work:

- control + shift + command (k + j + semicolon)
- option + shift + command (l + j + semicolon)
- control + option + shift + command (k + l + j + semicolon)

However, these combinations don't work only when all keys pressed are the remapped keys (j,k,l, and semicolon). When I use one of the physical modifier keys on my keyboard, the above combinations work. For example, the combination control + shift + command works when the physical keys pressed are k + j + right_command.

**Comment by marlonrichert** [comment]
You're doing it wrong. 🙂 Please see my [Dual keys](https://ke-complex-modifications.pqrs.org/?q=dual#dual_keys) modification for an example on how to do it right.

**Comment by thoelze1** [comment]
That modification does the inverse of mine.
You're remapping existing modifier keys to non-modifier keys when pressed instead of held (e.g. left command posts enter when pressed). I'm remapping non-modifiers to modifiers when held instead of pressed (e.g. j to right shift when held).

**Comment by marlonrichert** [comment]
The same principle applies. It doesn't matter what the input key is.

**Comment by thoelze1** [comment]
You're right, but I'm saying that there's a bug

**Comment by marlonrichert** [comment]
I think that's subjective. You want JKL to work as modifier keys _when held down_. Ergo, you should use `to_if_held_down` for that. And if you want that to trigger immediately, then set the `basic.to_if_held_down_threshold_milliseconds` parameter to zero. That's what I did and it works perfectly.

**Comment by thoelze1** [comment]
If it "works perfectly" then are you able to send, say, shift + command + control + t? My modification is working except for the fact that it cannot send shift + command + meta or shift + command + control.

I tried what you're describing, but keypresses with shift + command + control and shift + command + meta still don't work:
```
{
    "title": "Home row to modifiers",
    "rules": [
        {
            "description": "Change j to shift if pressed with other keys",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "j",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to_if_held_down": [
                        {
                            "key_code": "right_shift"
                        }
                    ],
                    "to_if_alone": [
                        {
                            "key_code": "j"
                        }
                    ]
                }
            ]
        },
        ...
    ]
}
```
(I also changed the to_if_held_down_threshold_milliseconds to zero)

Also, when you do it this way, pressing j alone always sends a ghost right_shift keypress as shown in the events viewer:

| Event type        | Code           | Name  | Misc |
| ------------- |-------------| -----|-----|
| key_downcode      | 229 | right_shift | flags: right_shift |
| key_up      | 229 | right_shift | |
| key_down      | 13 | j | |
| key_up      | 13 | j | |

So I prefer my way (where there is no right-shift event until after to_if_alone_timeout_milliseconds)

**Comment by marlonrichert** [comment]
> If it "works perfectly" then are you able to send, say, shift + command + control + t?

Yes —but I am able to produce that also using your method. 🤔

Perhaps the problem is in your keyboard? Have you tried using the same mod with a different keyboard? It could be that your keyboard simply doesn't support sending that many non-modifier keys at the same time.

**Comment by thoelze1** [comment]
I think you're right, it seems like a hardware problem.

To sum up, I currently have:

- a/s/d/f bound to left_command/left_option/left_control/left_shift
- j/k/l/; bound to right_shift/right_control/right_option/right_command
- spacebar bound to fn

I am able to use a/s/d/f/spacebar in all combinations as expected. As I've said, I am not able to use j/k/l/;/spacebar in all combinations. However, when I bind h to right_command, I can use h/j/k/l in all combinations but not h + j + k + l + spacebar; when I bind p to right_command, I can use j/k/l/p/spacebar in all combinations.

Given that these other combinations work (a/s/d/f/spacebar and j/k/l/p/spacebar) I think that j/k/l/; not working together has to do with the hardware of my keyboard and not karabiner-elements.

Thanks for the help @marlonrichert. Closing this issue now.
