### ISSUE TITLE
XDG compliance does not work

### ISSUE THREAD

**Issue by dlejay** [pqrs-org/Karabiner-Elements#2235]
Using Karabiner-Elements 12.9.0

Despite having set ``XDG_CONFIG_HOME`` and ``XDG_DATA_HOME`` in my ``zshenv``, Karabiner-Elements still creates ``.config`` and ``.local/share`` in my ``$HOME`` directory (and I can't configure anything if I install Karabiner-Elements on a read-only ``$HOME``).

**Comment by tekezo** [comment]
Thank you for feedback.

I guess we have to set the environment variable by a way influencing to a process (`karabiner_console_user_server`) which is run  by launchd.

I don't test it, but there is a documentation for setting system wide environment variables.
https://apple.stackexchange.com/questions/289060/setting-variables-in-environment-plist

**Comment by dlejay** [comment]
Thanks, I understand why it could not work now! I'll try declaring the variables with a plist.

I have found this other post about setting environment variables on macOS (for reference):
[https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x](https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x)

Also, I believe XDG directories are not mentioned in the documentation at [The location of the configuration file](https://karabiner-elements.pqrs.org/docs/manual/misc/configuration-file-path/). I think it's great that Karabiner-Elements supports it and it should be added to the doc :-)

**Comment by dlejay** [comment]
The following method is confirmed working on macOS Catalina.

Create the file ``~/Library/LaunchAgents/environment.plist`` containing
```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">
<dict>
 <key>Label</key>
 <string>setenv.XDG</string>
 <key>Program</key>
 <string>/bin/zsh</string>
 <key>ProgramArguments</key>
 <array>
 <string>/bin/zsh</string>
 <string>-c</string>
 <string>launchctl setenv XDG_CONFIG_HOME "$HOME/Library/Preferences";
 launchctl setenv XDG_DATA_HOME "$HOME/Library/Application Support";
 launchctl setenv XDG_CACHE_HOME "$HOME/Library/Caches";</string>
 </array>
 <key>RunAtLoad</key>
 <true/>
</dict>
</plist>
```
For immediate action, type ``launchctl load environment.plist`` and restart your Terminal/App.

Note: sadly, ``launchctl setenv`` is depreciated by Apple (see ``man launchctl``). So this solution might not last.

One tiny thing not working. In Karabiner-Elements, section ``Misc``, the button reads
``open config folder (~/.config/karabiner)`` even when it will open ``$XDG_CONFIG_HOME/karabiner``.

By curiosity, if Karabiner-Elements is a macOS exclusive app, why does it default to ``.config`` and ``.local/share`` and not macOS specific folders in ``~/Library``?
I would also be happy to see the folder be spelled ``Karabiner`` with a capital ``K`` :-)

**Comment by yochem** [comment]
I tried the solution given by @dlejay, but this does not work after rebooting. When starting, Karabiner can't find the `~/.config/karabiner` path, so the folder is created with the default files and my remaps do not work. When I open the karabiner app and click on `Misc > open config folder (~/.config/karabiner)` though, it opens the right folder (my XDG specified folder). After restarting karabiner, it loads my config and works perfect.

**Comment by slve** [comment]
In order to make @dlejay's solution work even after rebooting you can add in 
```
launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server
```
at the end of the script block in the plist.

**Comment by dlejay** [comment]
It seems the new option to write to the “system default configuration” solves the problem reliably.
<img width="1212" height="844" alt="Image" src="https://github.com/user-attachments/assets/f199abe9-08c7-4042-b8f4-1f3fcc6fbe9b" />
