### ISSUE TITLE
How can I change with only one keyboard layout?

### ISSUE THREAD

**Issue by sajt** [pqrs-org/Karabiner-Elements#2239]
Hello,

I have 2 keyboard layout one for programming (British -PC), and one for one for other (Hungarian) my problem is the first one is QWERTZ and the second is QWERY. I like if only the British-PC change the Y to Z. Is that possible?

**Comment by marlonrichert** [comment]
Not with KE, but you can use [Ukelele](https://software.sil.org/ukelele/) to create a modified version of the British keyboard layout.
