### ISSUE TITLE
[Question] How to catch/map trackpad corner clicks

### ISSUE THREAD

**Issue by cotfas** [pqrs-org/Karabiner-Elements#2241]
How I can catch the trackpad corner clicks/ or force clicks and to execute a shell script?

Already tried with but it does not work:

`{
  "from": {
    "pointing_button": "button1"
  },
  "to": [
    {
      "shell_command": "exec script"
    }
  ],
  "type": "basic"
}`

On the devices tab I can not tick the apple internal mouse:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/3340367/80001232-cfa04680-84c6-11ea-81b3-a988a1370271.png">

Also tried with magic mouse v2 but still no luck.

Karabiner 12.9.0
Catalina 10.15.4

**Comment by marlonrichert** [comment]
If you cannot select them there, then you cannot manipulate them with KE.

**Comment by cotfas** [comment]
And how I can make it selectable?

**Comment by marlonrichert** [comment]
You could try [BetterTouchTool](https://folivora.ai) or [USB Overdrive](https://www.usboverdrive.com).
