### ISSUE TITLE
Cannot remap volume keys on Ducky Shine 7

### ISSUE THREAD

**Issue by rob49ers** [pqrs-org/Karabiner-Elements#2242]
I just purchased a Ducky Shine 7 keyboard. Remapped the F10 (mute), F11 (volume_decrement), F12 (volume_increment) to match Mac layout. The Ducky keys in the F17 (mute), F18 (volume_decrement), F19 (volume_increment) positions cannot remap. Any help would be appreciated.

**Comment by marlonrichert** [comment]
You can use the EventViewer to check what key code they produce: https://github.com/pqrs-org/Karabiner-Elements/issues/2228#issuecomment-615119061

If you cannot see them in the EventViewer, then unfortunately you cannot remap them.

**Comment by rob49ers** [comment]
I appreciate the response.  Yes, I had done that previously.  They do map to "mute", "volume_decrement" and "volume_increment".  However, when I reassign them they do not change their behavior.  

Key code produced:
<img width="874" alt="screenshot_679" src="https://user-images.githubusercontent.com/64179126/80120190-7f18ff80-853f-11ea-811d-204f41636c00.png">

Re-map to F17, F18, F19:
<img width="996" alt="screenshot_681" src="https://user-images.githubusercontent.com/64179126/80120614-2007ba80-8540-11ea-855d-4b8a28f42bb4.png">

Keycodes produced after re-mapping are the same:
<img width="842" alt="screenshot_682" src="https://user-images.githubusercontent.com/64179126/80120573-0f574480-8540-11ea-91ac-8ca8a8d9c065.png">

What could be the issue?

Thanks again!
