### ISSUE TITLE
Window key to left_control

### ISSUE THREAD

**Issue by erica9310** [pqrs-org/Karabiner-Elements#2243]
I have set the window keyboard on Karabiner as below:
from left_control(ctrl key on window keyboard) to left_command

Now I have two command keys (1: ctrl, 2: window key), I hope to set window key to work as 'left_control'. Can you please provide me the guide on how to make the setting on Karabiner?

Thank you.

**Comment by marlonrichert** [comment]
The Windows key is normally the same as the Command key. You can use the EventViewer to verify this: https://github.com/pqrs-org/Karabiner-Elements/issues/2228#issuecomment-615119061

**Comment by zecanard** [comment]
You should be able to remap left_command to left_control.

But if you’re just trying to swap the ⌘Cmd and ⌃Ctrl keys, you don’t need Karabiner at all. You can just go into System Preferences… → Keyboard → Modifier Keys… and swap them there.

**Comment by erica9310** [comment]
@zecanard Thank you! That was very helpful.
In addition, do you know how to set capslock on window keyboard to work as a capslock ? Since I use mackbook in different language, my default setting on capslock work as language input change.

**Comment by zecanard** [comment]
Can’t you just undo that modification? I use a Windows keyboard with multiple languages and my Caps Lock key natively works as a Caps Lock key; I didn’t have to change anything.
