### ISSUE TITLE
Karabiner often suddenly refuse to work, especially after external keyboard reconnection

### ISSUE THREAD

**Issue by windless0530** [pqrs-org/Karabiner-Elements#2244]
MacBook Pro 2018
macOS Catalina 10.15.4
Keyboard - Leopold FC 660M (I don't think this issue has anything to do with specific keyboard type cause it has occurred on multiple external keyboards)

Often after external keyboard disconnect and reconnect, the key remapping refused to work any more. And there is no way to recover except for rebooting my computer.

Re-edit my json configuration file and save does not help.

Here is my configuration.

`{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": [
                    {
                        "description": "A Grave Escape",
                        "manipulators": [
                            {
                                "conditions": [
                                    {
                                        "identifiers": [
                                            {
                                                "product_id": 636,
                                                "vendor_id": 1452
                                            }
                                        ],
                                        "type": "device_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "grave_accent_and_tilde"
                                },
                                "to": [
                                    {
                                        "key_code": "escape"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
                    {
                        "description": "A Grave Escape",
                        "manipulators": [
                            {
                                "conditions": [
                                    {
                                        "identifiers": [
                                            {
                                                "product_id": 521,
                                                "vendor_id": 1241
                                            }
                                        ],
                                        "type": "device_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "escape",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_gui"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "grave_accent_and_tilde",
                                        "modifiers": [
                                            "left_gui"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "conditions": [
                                    {
                                        "identifiers": [
                                            {
                                                "product_id": 521,
                                                "vendor_id": 1241
                                            }
                                        ],
                                        "type": "device_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "escape",
                                    "modifiers": {
                                        "mandatory": [
                                            "option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "grave_accent_and_tilde"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },
            "devices": [
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 636,
                        "vendor_id": 1452
                    },
                    "ignore": false,
                    "manipulate_caps_lock_led": true,
                    "simple_modifications": []
                },
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 34304,
                        "vendor_id": 1452
                    },
                    "ignore": false,
                    "manipulate_caps_lock_led": true,
                    "simple_modifications": [
                        {
                            "from": {
                                "key_code": "escape"
                            },
                            "to": {
                                "key_code": "vk_none"
                            }
                        }
                    ]
                }
            ],
            "fn_function_keys": [
                {
                    "from": {
                        "key_code": "f1"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f2"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f3"
                    },
                    "to": {
                        "key_code": "mission_control"
                    }
                },
                {
                    "from": {
                        "key_code": "f4"
                    },
                    "to": {
                        "key_code": "launchpad"
                    }
                },
                {
                    "from": {
                        "key_code": "f5"
                    },
                    "to": {
                        "key_code": "illumination_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f6"
                    },
                    "to": {
                        "key_code": "illumination_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f7"
                    },
                    "to": {
                        "consumer_key_code": "rewind"
                    }
                },
                {
                    "from": {
                        "key_code": "f8"
                    },
                    "to": {
                        "consumer_key_code": "play_or_pause"
                    }
                },
                {
                    "from": {
                        "key_code": "f9"
                    },
                    "to": {
                        "consumer_key_code": "fastforward"
                    }
                },
                {
                    "from": {
                        "key_code": "f10"
                    },
                    "to": {
                        "consumer_key_code": "mute"
                    }
                },
                {
                    "from": {
                        "key_code": "f11"
                    },
                    "to": {
                        "consumer_key_code": "volume_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f12"
                    },
                    "to": {
                        "consumer_key_code": "volume_increment"
                    }
                }
            ],
            "name": "Default profile",
            "parameters": {
                "delay_milliseconds_before_open_device": 1000
            },
            "selected": true,
            "simple_modifications": [],
            "virtual_hid_keyboard": {
                "country_code": 0,
                "mouse_key_xy_scale": 100
            }
        }
    ]
}
`

**Comment by o1dnik** [comment]
Hey, @windless0530 , did you resolve your issue? I also have macOS and a mechanical keyboard (though another one, Havit HV-KB390L ) ans sometimes the F1..12 reassignments stop working, but just only some of them. Weirdly enough F1-F2 as brightness control works fine, but the following "mission control" and for example volume controls on F11-12 are sometimes lost. Any ideas how would you debug this? I can help maybe.

**Comment by o1dnik** [comment]
And BTW did you try Ukelele ?

**Comment by windless0530** [comment]
> Hey, @windless0530 , did you resolve your issue? I also have macOS and a mechanical keyboard (though another one, Havit HV-KB390L ) ans sometimes the F1..12 reassignments stop working, but just only some of them. Weirdly enough F1-F2 as brightness control works fine, but the following "mission control" and for example volume controls on F11-12 are sometimes lost. Any ideas how would you debug this? I can help maybe.

I am sorry to say, not yet. I am still waiting for official reply ...

**Comment by windless0530** [comment]
> And BTW did you try Ukelele ? I'm not saying it's better or worse - it's solving another task in general, But I'm just curious about experience.

Thanks a lot for your suggestion! I will try it and see if it could meet my need without such weird problems.

**Comment by lixw1021** [comment]
I have the same issue and it was so frustrating, any answer so far?
