### ISSUE TITLE
[Question] Is it possible to disable complex rule on some combination?

### ISSUE THREAD

**Issue by glemmatim** [pqrs-org/Karabiner-Elements#2246]
I would like to enable the following rule which sets the spacebar to left shift when pressed together with another key. The problem is that this disables spotlight search (which uses CMD+spacebar).

Is there a way to disable the spacebar rule when pressed with the command key? An alternative way would be to set the cmd + spacebar to spotlight in Karabiner itself. Is that a possibility (I could find it anywhere the documentation)`

`                  {
                    "description": "Change spacebar to left_shift. (Post spacebar if pressed alone)",
                    "manipulators": [
                        {
                            "from": {
                                "key_code": "spacebar",
                                "modifiers": {
                                    "optional": [
                                        "any"
                                    ]
                                }
                            },
                            "to": [
                                {
                                    "key_code": "left_shift"
                                }
                            ],
                            "to_if_alone": [
                                {
                                    "key_code": "spacebar"
                                }
                            ],
                            "type": "basic"
                        }
                    ]
                }`

**Comment by torarnv** [comment]
This is still an issue. Enter for Cmd+O in Finder results in Spotlight not being able to confirm the choice with Enter if Finder is/was the frontmost app.

**Comment by maliayas** [comment]
See a workaround: https://github.com/pqrs-org/Karabiner-Elements/issues/1982#issuecomment-2395705893
