### ISSUE TITLE
"menu" key on Microsoft keyboard can't be changed to "left_option"

### ISSUE THREAD

**Issue by squintgit** [pqrs-org/Karabiner-Elements#2251]
It doesn't appear the menu key can be changed to left_option on the Microsoft Ergonomic keyboard using Karabiner Elements.

After setting it up as per below, the key behaves the same way it did before installing Karabiner Elements.

<img width="1112" alt="Screen Shot 2020-04-29 at 11 31 27 AM" src="https://user-images.githubusercontent.com/11663794/80622040-d91d3780-8a0d-11ea-936b-5d642a51ab87.png">

**Comment by zecanard** [comment]
It’s the “application” key, if that’s the key you’re referring to.

**Comment by squintgit** [comment]
> It’s the “application” key, if that’s the key you’re referring to.

Thank you, that worked!
