### ISSUE TITLE
Question : Keystroke to a specific application ?

### ISSUE THREAD

**Issue by Badsheep** [pqrs-org/Karabiner-Elements#2258]
Hello,

My question is in the title : is it possible to create a "filter" so that a keystroke would be sent to ONE specific application only ? Using the complex rules for example ?

Thanks !

**Comment by sdondley** [comment]
I haven't tried this myself. I was wondering the same, thing, though. See https://numericjungle.github.io/2018/06/20/mackeymapping.html

**Comment by Badsheep** [comment]
Hello sdondley,

Thank you for your answer !

And would it be possible of that application is not at front and minimized ?

**Comment by sdondley** [comment]
I think what you'd have to do is something like this. It's a little tricky, but can be done, I believe.

Step 1: Issue the keystroke with karabiner

Step 2: have the keystroke trigger a script that gets the contents from the `/Library/Application Support/org.pqrs/tmp/karabiner_grabber_manipulator_environment.json` file and examines it for the `file_path` to determine the name of the current application. Save this name in a variable so you restore your application later.

Step 3: Activate the app
open -a 'AppName'

Step 4: Do the keystroke you want to issue for the app automatically. You may need to do this as part of an Applescript.

Step 5: Activate the app you had opened when you issued the command:
open -a 'OrigApp'

**Comment by Badsheep** [comment]
Hello !

Thanks for your help !
Sounds a bit complicated...

I’ll try if I have the time but I’m thinking of another configuration.

Thank you very much anyway !
