### ISSUE TITLE
Logitech K860 remapping

### ISSUE THREAD

**Issue by hedin-hiervard** [pqrs-org/Karabiner-Elements#2259]
Recently got a new Logitech K860 keyboard. I'm historically using Karabiner for my Mac because all keyboards are German and I need to swap ``` and `§` for my convenience.

So far, I was able to map everything I need, but I'm having trouble with the F4 button. It has two modes: a normal mode, which sends F4, and 'fn' mode, which is supposed to show app windows (or do something else if I rebind it). Unfortunately in this mode, according to events, it just sends `Cmd + Tab` to switch apps and it's no different `Cmd + Tab` than a usual one. So I'm not able to reassign it with Karabiner! 

I tried installing Logitech original software to see if I can remap buttons, but it doesn't work on Catalina. Anyway, I like Karabiner more. 

Is there is a way to somehow remap they key on a deeper level? 

Here is what happens when I press it:
```
type:key_down        code:227        name:left_command    misc:flags: left_command 
type:key_down        code:43         name:tab             misc:flags: left_command 
type:key_up          code:43         name:tab             misc:flags: left_command 
```

**Comment by basnijholt** [comment]
I am having the exact same issue. @hedin-hiervard did you ever manage to solve this?
