### ISSUE TITLE
Using arrows as "modifier keys"

### ISSUE THREAD

**Issue by AndreaCallia** [pqrs-org/Karabiner-Elements#2260]
Hi all and thank you so much for this great tool...

is it possible to use arrows as modifier keys, in either simple or complex modifications?

In order to be able to move diagonally in some old DOS games, I would like to achieve something like this:

Rule 1: from ("up" + "left_arrow") to ("home")
Rule 2: from ("up" + "right_arrow") to ("page_up")
Rule 3: from ("down" + "left_arrow") to ("end")
Rule 4: from ("down" + "right_arrow") to ("page_down")

**Comment by AndreaCallia** [comment]
Made a first attempt, it seems I managed to implement rule 1, by writing the following code.

    {
      "title": "Diagonals",
      "rules": [
        {
          "description": "Diagonals",
          "manipulators": [
            {
                "from": {
                    "key_code": "up_arrow"
                },
                "to": [
                    {
                        "set_variable": {
                            "name": "up_modifier",
                            "value": 1
                        }
                    },
                    {
                      "key_code": "up_arrow"
                    }
                ],
                "to_after_key_up": [
                    {
                        "set_variable": {
                            "name": "up_modifier",
                            "value": 0
                        }
                    }
                ],
                "to_if_alone": [
                  {
                    "key_code": "up_arrow"
                  }
                ],
                "type": "basic"
            },
            {
                "conditions": [
                    {
                        "type": "variable_if",
                        "name": "up_modifier",
                        "value": 1
                    }
                ],
                "from": {
                    "key_code": "left_arrow"
                },
                "to": [
                    {
                        "key_code": "home"
                    }
                ],
                "type": "basic"
            }
          ]
        }
      ]
    }

**Comment by AndreaCallia** [comment]
... but strangely enough, if in the above rule I replace `left_arrow` with `right_arrow` and `home` with `page_up`, I cannot implement Rule 2. How is this possible? This modified rule has the same identical structure as the successful implementation of Rule 1, why would this not work?

**Comment by thoelze1** [comment]
Maybe [simultaneous](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/simultaneous/) can help you?

This works for me, though the "simultaneous" effect may not be what you want:

```
        {
            "description": "Arrow stuff",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "simultaneous": [
                            {
                                "key_code": "up_arrow"
                            },
                            {
                                "key_code": "left_arrow"
                            }
                        ],
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "home"
                        }
                    ]
                }
            ]
        }
```

Also, note that the default [shortcuts on Mac](https://support.apple.com/en-us/HT201236) translate:

- fn+left to home
- fn+right to end
- fn+up to page up
- fn+down to page down

In case that can be helpful

**Comment by AndreaCallia** [comment]
Many thanks @thoelze1 , I tried your attempt and it may work much better than mine (in mine rule number 4 does not work, perhaps because of some bug, in yours even rule number 4 works!)

But there is an issue, sometimes I may want to press, for example the up arrow _while_ I was already pressing the left arrow (or viceversa)... in this case, it seems that the `simultaneous` rule is not triggered, what do you think?

**Comment by AndreaCallia** [comment]
I am realizing that perhaps the `event_changed_if` may halp to solve the issue above, but I have only seen a single sentence about its meaning in the documentation and no examples online or anywhere on internet, and I am not managing to understand how to use it...

**Comment by thoelze1** [comment]
I tried your code, and it worked for me. Specifically, when I held `left_arrow`, then `up_arrow` became `home` and `down_arrow` became `end`; when I held `right_arrow`, then `up_arrow` became `page_up` and `down_arrow` became `page_down`.

However, if I held `up_arrow`, then `left_arrow` still acted as `left_arrow` (instead of `home`, which it sounds like you want it to). So I added rules that make `up_arrow` and `down_arrow` set variables `up_modifier` and `down_modifier`, and I added rules so that when each arrow is pressed, it checks if another arrow is currently being held down, and then remaps according to the 4 rules you originally posted in this issue. Here's the code:

```
{
  "title": "Diagonals",
  "rules": [
    {
      "description": "Diagonals",
      "manipulators": [
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "up_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "left_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "left_modifier",
                "value": 1
              }
            },
            {
              "key_code": "home"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "left_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "down_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "left_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "left_modifier",
                "value": 1
              }
            },
            {
              "key_code": "end"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "left_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "left_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "left_modifier",
                "value": 1
              }
            },
            {
              "key_code": "left_arrow"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "left_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "up_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "right_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "right_modifier",
                "value": 1
              }
            },
            {
              "key_code": "page_up"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "right_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "down_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "right_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "right_modifier",
                "value": 1
              }
            },
            {
              "key_code": "page_down"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "right_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "right_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "right_modifier",
                "value": 1
              }
            },
            {
              "key_code": "right_arrow"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "right_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "left_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "up_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "up_modifier",
                "value": 1
              }
            },
            {
              "key_code": "home"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "up_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "left_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "down_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "down_modifier",
                "value": 1
              }
            },
            {
              "key_code": "end"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "down_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "up_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "up_modifier",
                "value": 1
              }
            },
            {
              "key_code": "page_up"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "up_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_modifier",
              "value": 1
            }
          ],
          "from": {
            "key_code": "down_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "down_modifier",
                "value": 1
              }
            },
            {
              "key_code": "page_down"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "down_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "up_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "up_modifier",
                "value": 1
              }
            },
            {
              "key_code": "up_arrow"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "up_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "down_arrow"
          },
          "to": [
            {
              "set_variable": {
                "name": "down_modifier",
                "value": 1
              }
            },
            {
              "key_code": "down_arrow"
            }
          ],
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "down_modifier",
                "value": 0
              }
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
```

Hope this helps!

**Comment by AndreaCallia** [comment]
Hi @thoelze1 and thank you so much for this... it seems it works much better, but there is still a problem... if, for example, I press the left arrow, and afterwards at some point I also press the up arrow, then it correctly goes diagonally, because the left arrow acted as a sort of "modifier" as expected... and if, after that, I release the up arrow, then it goes left again, as expected...

But, if instead of releasing the up arrow, I release the left arrow instead, I would expect it to go up, since only the up arrow is being held down... but instead it keeps going diagonally...

I am starting to think that the software does not support yet this kind of modification, what do you think? It is a pity, because many games already have this feature natively, and being able to do this via karabiner would make us capable of doing this with all games, not only the ones which have this feature natively...

**Comment by thoelze1** [comment]
I hope that karabiner supports this somehow, because I have been trying to get similar behavior for a modification of my own. Perhaps if we could figure out what `event_changed_if` does, it could be of some help; however, I opened up an issue asking about `event_changed_if` and I spent a while experimenting but I haven't been able to figure it out.

**Comment by AndreaCallia** [comment]
Thank you so much for this @thoelze1 , I have found the issue and I will follow it, let's hope we will manage to make this work :)
