### ISSUE TITLE
Function keys on Razer Blade Stealth 2019 ignore fn key

### ISSUE THREAD

**Issue by reven** [pqrs-org/Karabiner-Elements#2265]
I'm 99% sure this is something specific to my hardware, but wanted to check just in case.

I have a Razer Blade Stealth 2019; the keyboard Vendor ID is 0x1532 and the Product ID is 0x0239. I can set "Use F1, etc as standard function keys" and that works great; when I press the fn key I get the special functions that are predefined by my keyboard (different than MacOS defaults). When I try to swap the behavior and have them as special keys and require fn for function keys, I get the special function no matter what when fn is pressed, even if I define assignments in Karabiner.

So I'm guessing my laptop's firmware circumvents the OS asignments. Or maybe Karabiner is failing to detect those keys properly?

Thanks.

**Comment by Darkade** [comment]
I have this same issue. I'd like to be able to use the razer `fn+...` combinations, but EventViewer is not even registering that I'm pressing the `fn` key in my Razer Huntsman
