### ISSUE TITLE
webpage broken

### ISSUE THREAD

**Issue by clarkewd** [pqrs-org/Karabiner-Elements#2267]
When trying to add complex modifications this page opens:

https://ke-complex-modifications.pqrs.org/example.html

I get an error:

    Index.vue:291 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at Index.vue:291

<img width="743" alt="Screen Region 2020-05-07 at 13 52 42" src="https://user-images.githubusercontent.com/156377/81327954-161aa700-906a-11ea-82e5-6aecc0e6af50.png">

**Comment by satubus** [comment]
same here
