### ISSUE TITLE
How to get the alt gr button?

### ISSUE THREAD

**Issue by dyarfaradj** [pqrs-org/Karabiner-Elements#2268]
On windows keyboard layout the right alt is "Alt Graph" which is used to type these []{}.. 
How can I make the right CMD mapped to Alt Gr, can't find how to do combined keys or find the alt gr on the Karabiner-Elements app

**Comment by zecanard** [comment]
`right_option`

**Comment by dyarfaradj** [comment]
> `right_option`

@zecanard it's not the same, at least on Swedish keyboard. Having right_option and pressing 7-0 gives me these: |[]≈

Which is not the same as if it where Alt Gr which gives: {[]}

**Comment by dyarfaradj** [comment]
No updates regarding this?

**Comment by patzhang** [comment]
Any updates?

**Comment by dyarfaradj** [comment]
Nope no updates @patzhang

**Comment by tekezo** [comment]
Karabiner-Elements can do this by changing `right_option + 7` to shortcuts of `{` (e.g., `right_option + left_shift + 7`).

But creating custom keylayout is more easiler way.
There are apps which allows you to make a own keylayout.
https://software.sil.org/ukelele/
