### ISSUE TITLE
Is there any way to use mouse_motion_to_scroll with trackpad?

### ISSUE THREAD

**Issue by eret9616** [pqrs-org/Karabiner-Elements#2271]
Is there any way to use mouse_motion_to_scroll with magic trackpad,?

**Comment by nkgm** [comment]
I've been trying to get this to work with **Magic Trackpad 2** without success. Also tried @tekezo's `Change control + mouse motion to scroll wheel (rev 1)` with no luck. Is this meant to be a mouse-only thing?

**Comment by nkgm** [comment]
I'll go ahead and assume this isn't supported seeing that `Magic Trackpad 2` is grayed out on the list of devices:

![image](https://user-images.githubusercontent.com/5631881/85585989-2ce08180-b649-11ea-9b16-b894acfba8e2.png)

For anyone interested in good alternative, I was able to achieve excellent results with [Smart Scroll](https://www.marcmoini.com/sx_en.html)'s *Grab Scroll* option and a bit of wiring.
