### ISSUE TITLE
Keys repeat from time to time. Result: someethinng likke thiss

### ISSUE THREAD

**Issue by Nowaker** [pqrs-org/Karabiner-Elements#2274]
The title says it all. As I type my text normally, I'll see a problem like thhis fromm tiime to timme. Some keys repeat, as if they were pressed twice. Sometimes, they'll repeat after the next keypress, leading to a result like thihs (h repeated). The least frequent occurrence is when a key press does not registr (it actually happened here, I wanted to type "register"). All of these problems happen when I type quickly (I'd call it regular speed for anyone who's worked as a software developer for 15 years). Casual typing by a non-IT person won't trigger it. 

To summarize:

- repeat keypresses. Type: something, got: sometthing. (It happened 14 times while typing this bug report)
- repeat keypresses. Type: repeat, got: rerpeat. (It happened 3 times while typing this bug report)
- no keypress registered. Type: register, got: egister (It happened 2 times while typing this bug report)
- happens more often when typing fast (e.g. 15 years of IT experience, no need to look at the keyboard)

~~The problem does not exist when Karabiner is off. Or when it remains on under my account while someone else uses my laptop on their own account where Karabiner is off. Also, quitting Karabiner resolves the problem, and none of the described problems happen.~~ Quitting Karabiner doesn't help in any way. It still affects the typing, most likely because quitting Karabiner does not stop its processes (observer, grabber, etc). Restarting Karabiner fixes the problem for a couple minutes some time - the keys don't get repeated for some time, but it will come back later (after sleep? after user switch? some time period), and its frequency will increase over time.

It's also not caused by any native Mac system settings, like "key repeat" and "delay until repeat", as seen in:

![image](https://user-images.githubusercontent.com/611746/81492153-3b223c00-925b-11ea-9ba1-b0ccf81c61fe.png)

My config: https://gitlab.com/Nowaker/dotfiles-karabiner. My only customization is function keys - I don't do any regular key remapping.

![image](https://user-images.githubusercontent.com/611746/81492191-90f6e400-925b-11ea-9c40-4afca81d477e.png)

However, when I switch Karabiner to an empty profile with no modifications, it still happens.

The problem existed on my previous OSX Mojave but it signified a lot after upgrade to Cataalinaa (Spelling preserved to show what Karabiner did to my typing 😸)  to the point I'm affected by it all the time when working on chatting. It may also be related to Karabiner upgrade, as I bumped it from 12.7.x to 12.9.3.

**Comment by drye** [comment]
I've had this same exact issue ever since Catalina and it's driving me insane. It hadn't occurred to me to downgrade Karabiner, but downgrading to 1.7.5 did not fix the issue for me. Downgrading to 1.6.0, however, so far works without any noticeable keystroke repeats.

**Comment by Nowaker** [comment]
I've just **updaated** to 12.9.6 (beta) and it's still doing the same.

@drye Can you upvote my ticket visibility?

**Comment by Nowaker** [comment]
@tekezo How much would you charge me for fixing this for me and others?

**Comment by Nowaker** [comment]
In this test, while having the EventViewer on, I was pressing and holding a key for a second or two. I started **wiith** Q, then W, then E. And the event for E key was repeated twice. I did not press it twice, obviously.

```
type:key_down        code:20         name:q               misc:
type:key_up          code:20         name:q               misc:
type:key_down        code:26         name:w               misc:
type:key_up          code:26         name:w               misc:
type:key_down        code:8          name:e               misc:
type:key_up          code:8          name:e               misc:
type:key_down        code:8          name:e               misc:
type:key_up          code:8          name:e               misc:
```

Another example. I **wrotee** `i wonder why this shit is causing me problems` but it resulted in `i wonder why this shit is causing mee problems`.

```
type:key_down        code:12         name:i               misc:
type:key_up          code:12         name:i               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_down        code:26         name:w               misc:
type:key_up          code:44         name:spacebar        misc:
type:key_up          code:26         name:w               misc:
type:key_down        code:18         name:o               misc:
type:key_down        code:17         name:n               misc:
type:key_up          code:18         name:o               misc:
type:key_down        code:7          name:d               misc:
type:key_up          code:17         name:n               misc:
type:key_up          code:7          name:d               misc:
type:key_down        code:8          name:e               misc:
type:key_down        code:21         name:r               misc:
type:key_up          code:8          name:e               misc:
type:key_up          code:21         name:r               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_up          code:44         name:spacebar        misc:
type:key_down        code:26         name:w               misc:
type:key_up          code:26         name:w               misc:
type:key_down        code:11         name:h               misc:
type:key_up          code:11         name:h               misc:
type:key_down        code:28         name:y               misc:
type:key_up          code:28         name:y               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_up          code:44         name:spacebar        misc:
type:key_down        code:23         name:t               misc:
type:key_up          code:23         name:t               misc:
type:key_down        code:11         name:h               misc:
type:key_up          code:11         name:h               misc:
type:key_down        code:12         name:i               misc:
type:key_up          code:12         name:i               misc:
type:key_down        code:22         name:s               misc:
type:key_up          code:22         name:s               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_up          code:44         name:spacebar        misc:
type:key_down        code:22         name:s               misc:
type:key_down        code:11         name:h               misc:
type:key_up          code:22         name:s               misc:
type:key_down        code:12         name:i               misc:
type:key_up          code:11         name:h               misc:
type:key_up          code:12         name:i               misc:
type:key_down        code:23         name:t               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_up          code:23         name:t               misc:
type:key_up          code:44         name:spacebar        misc:
type:key_down        code:12         name:i               misc:
type:key_up          code:12         name:i               misc:
type:key_down        code:22         name:s               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_up          code:22         name:s               misc:
type:key_up          code:44         name:spacebar        misc:
type:key_down        code:6          name:c               misc:
type:key_up          code:6          name:c               misc:
type:key_down        code:4          name:a               misc:
type:key_up          code:4          name:a               misc:
type:key_down        code:24         name:u               misc:
type:key_up          code:24         name:u               misc:
type:key_down        code:22         name:s               misc:
type:key_up          code:22         name:s               misc:
type:key_down        code:12         name:i               misc:
type:key_down        code:17         name:n               misc:
type:key_up          code:12         name:i               misc:
type:key_up          code:17         name:n               misc:
type:key_down        code:10         name:g               misc:
type:key_up          code:10         name:g               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_up          code:44         name:spacebar        misc:
type:key_down        code:16         name:m               misc:
type:key_up          code:16         name:m               misc:
type:key_down        code:8          name:e               misc:
type:key_up          code:8          name:e               misc:
type:key_down        code:8          name:e               misc:
type:key_up          code:8          name:e               misc:
type:key_down        code:44         name:spacebar        misc:
type:key_up          code:44         name:spacebar        misc:
type:key_down        code:19         name:p               misc:
type:key_up          code:19         name:p               misc:
type:key_down        code:21         name:r               misc:
type:key_up          code:21         name:r               misc:
type:key_down        code:18         name:o               misc:
type:key_up          code:18         name:o               misc:
type:key_down        code:5          name:b               misc:
type:key_up          code:5          name:b               misc:
type:key_down        code:15         name:l               misc:
type:key_up          code:15         name:l               misc:
type:key_down        code:8          name:e               misc:
type:key_up          code:8          name:e               misc:
type:key_down        code:16         name:m               misc:
type:key_up          code:16         name:m               misc:
type:key_down        code:22         name:s               misc:
type:key_up          code:22         name:s               misc:
```

It's pretty much unusable. :-(

**Comment by Nowaker** [comment]
I guess I'll have to experiment with `hidutil` based key remapping. Maybe we **ddon't needd** Karabiner after all... This seems to work: https://apple.stackexchange.com/a/283253/269039

**Comment by tekezo** [comment]
It's a guessing answer because I'm not able to reproduce this issue on my machine.

The issue is generally caused by a delay of processing key events in Karabiner-Elements when the CPU load is high.
Unfortunately, Karabiner-Elements already uses most high process priority which allowed by macOS.
(It seems macOS restricts a process priority for third party process.)

Another possibility, if you are using anti-virus software, it may interrupts Karabiner-Elements process and causes the issue.
Trying other anti-virus software might solve the issue in this case.

**Comment by Nowaker** [comment]
Thanks for your reply, @tekezo!

> CPU load is high

**Thiis** isn't a case here. My CPU usage is 5% at the time of writing this **mesage**. Moreover, my old 2014 and 2015 MBP don't really have this issue and they're slow compared to my current 2018 MBP which scores 2x in single-core benchmark and **almosst** 4x multi-core.

> anti-virus software

I have a free version of MalwareBytes which does not have real-time protection. I **ddon't** believe it would be a problem. That said I **uniinstalled** it just to make sure. I've **cchecked** and it doesn't help.

Any other suggestions? Here's my `% ps aux|grep -i '[k]ara'` in **casse** it may help in any way.

```
root               147   0.3  0.0  4365868   5312   ??  Ss    7:54AM   0:37.07 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
root               145   0.1  0.0  4361436   4996   ??  Ss    7:54AM   3:05.06 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
nowaker           3442   0.0  0.1  4952228  17052   ??  S     7:34PM   0:00.19 /Library/Application Support/org.pqrs/Karabiner-Elements/Karabiner-Menu.app/Contents/MacOS/Karabiner-Menu
nowaker           3437   0.0  0.1  4920096  12244   ??  S     7:34PM   0:00.09 /Library/Application Support/org.pqrs/Karabiner-Elements/Karabiner-NotificationWindow.app/Contents/MacOS/Karabiner-NotificationWindow
nowaker           3409   0.0  0.1  4390608   9240   ??  S     7:34PM   0:00.66 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_console_user_server
root              3209   0.0  0.0  4357256   3004   ??  S     7:34PM   0:00.35 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_session_monitor
nowaker           3206   0.0  0.0  4356448   2204   ??  S     7:34PM   0:00.02 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
nowaker           3204   0.0  0.0  4349696   3272   ??  S     7:34PM   0:00.02 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
root               735   0.0  0.0  4349064   2800   ??  S     7:54AM   0:13.08 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_session_monitor
hania              732   0.0  0.0  4340064   1880   ??  S     7:54AM   0:00.13 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
hania              730   0.0  0.0  4349696   2528   ??  S     7:54AM   0:00.14 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
root               184   0.0  0.0  4355840   2076   ??  Ss    7:54AM   0:00.13 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_kextd
```

User `nowaker` is me and user `hania` is my **wifef**. **SShe** **doesns't** have Karabiner app running, therefore, not custom mappings. However, even after restart when only `nowaker` is logged in, and there's no Karabiner-related processes running **a**[s]`hania`, the problem still persists.


I've also stopped a **difefrent** application that listens on **keyprsses** **calleed** [MTMR](https://github.com/Toxblh/MTMR) but stopping **itt** didn't help, **a**[s] you can **seee**.

**Alsso** **[g]ot** rid of **[Sccroll Reversr](https://github.com/pilotmoon/Scroll-Reverser)**. Same thing. I feel like the more time I'm spending digging around, the more often the **poblem** occurs, lol. **Alsso** turned off **[Wittch](https://manytricks.com/witch/)**. I don't see anything **el[s]e** that **coudl** do anything remotely close to listening on keypresses. (And I use these programs on older MBPs too, except for MTMR).

**Comment by Nowaker** [comment]
And I'd like to provide an update on what I wrote in the issue description:

> The problem does not exist when Karabiner is off. Or when it remains on under my account while someone else uses my laptop on their own account where Karabiner is off. Also, quitting Karabiner resolves the problem, and none of the described problems happen.

Unfortunately, at some point, it **startedd** affecting me and other users even if Karabiner is off. Maybe a newer **versison** of Karabiner **changedd** the behavior and Karabiner processes still run? Here's my `ps aux | grep '[k]ara` **aftter** **stotpping** Karabiner:

```
root              3209   0.0  0.0  4357256   3000   ??  S     7:34PM   0:00.87 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_session_monitor
nowaker           3206   0.0  0.0  4356448   2204   ??  S     7:34PM   0:00.02 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
nowaker           3204   0.0  0.0  4349696   3272   ??  S     7:34PM   0:00.03 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
root               735   0.0  0.0  4349064   2800   ??  S     7:54AM   0:13.59 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_session_monitor
hania              732   0.0  0.0  4340064   1880   ??  S     7:54AM   0:00.14 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
hania              730   0.0  0.0  4349696   2528   ??  S     7:54AM   0:00.14 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
root               184   0.0  0.0  4355840   2076   ??  Ss    7:54AM   0:00.13 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_kextd
root               147   0.0  0.0  4360592   6264   ??  Ss    7:54AM   0:45.87 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
root               145   0.0  0.0  4360860   5384   ??  Ss    7:54AM   3:14.03 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
```

What's more, these proesses will stay even if I do `Misc` > `Uninstall Karabiner-Elements`. I tried **yesterdday**. I had to **xecute** `sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall_core.sh'` after using the UI for it to permanently disappear.

**Comment by Nowaker** [comment]
**BREAKING NEWS**: some of **thiis** problem is NOT a Karabiner problem. It's a physical problem! Even with Karabiner off, the problem still persists. What that really means is:

1. After **upgrae** to Catalina, Karabiner did in fact **causee** the problem as described in this **tiicket**. Stopping Karabiner would stop the problem from occurring. So this is indeed a problem - but it's not my problem any more.
2. At some point, **sttopping** Karabiner would no longer stop the issue from happening. This is an Apple problem, and **thhey** **admiit** that https://support.apple.com/keyboard-service-program-for-mac-notebooks and offer free fix.

I'll get my keyboard fixed and then report back afterwards if Karabiner is still causing any issues as originally **reoprted**.

CC @drye.

**Comment by drye** [comment]
I recently replaced my MacBook Pro 2018 with a new 2019 model and the issue has disappeared for me. I'm still running Karabiner, but have obviously reinstalled MacOS as well. At this point I suspect the hardware to have been the underlying issue.

**Comment by pthieu** [comment]
@Nowaker did you end up resolving this issue?
