### ISSUE TITLE
CTRL+Home and CTRL+End to top and bottom of page 

### ISSUE THREAD

**Issue by tsuliwaensis** [pqrs-org/Karabiner-Elements#2276]
How can I modify `ctrl+home` and `ctrl+end` to go to the top and bottom of a page like in Windows? I've tried the `PC-Style Home/End` complex modification, but that doesn't do it.

**Comment by sdondley** [comment]
The top and bottom of a web page? This can already be done with the "home" and "end" keys.

**Comment by tsuliwaensis** [comment]
I should have said "document" instead of "page".

I want to replicate the Windows behavior for `Home` and `End`

* `Home` - Beginning of line
* `End` - End of line
* `CTRL+HOME` - Top of document 
* `CTRL+END` - Bottom of document

I have the rule that changes `Home` and `End`, but I can't find a rule or figure out how to modify the last two.

**Comment by sdondley** [comment]
I believe you'll need to set up a complex modification the does Command-up_arrow and Command-down_arrow

**Comment by tsuliwaensis** [comment]
I added this rule, but it doesn't seem to register the `control` key press. What am I missing?

```
{
  "title": "Top of document",
  "rules": [
    {
      "description": "PC-Style Control+Home",
      "manipulators": [
        {
          "type": "basic",
          "description": "PC-Style Control+Home",
          "from": {
            "key_code": "home",
            "modifiers": {
              "mandatory": ["control"],
              "optional": ["any"]
            }
          },
          "to": [{
              "key_code": "up_arrow",
              "modifiers": [
                  "left_command"
              ]
          }]
        }
      ]
    }
  ]
}
```

**Comment by sdondley** [comment]
If you just want to be able to tap a modifier key once to trigger key presses, then you need to use the `to_if_alone` property, not the `to` property.

Refer to: https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-alone/

But to prevent the accidental triggering, you might want to consider using `to_if_held_down` instead: https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-held-down/

**Comment by tsuliwaensis** [comment]
I figured out the problem. I had another rule to make `Home` and `End` go to the beginning and end of the line and that conflicted with the _PC-Style Home/End_ rule that wasn't working for me. It looks like I can only have one or the other.

**Comment by thoelze1** [comment]
You can have multiple manipulators for the same key, but "[if there are multiple manipulators which change the same key, the manipulator placed at the top is applied and other manipulators are ignored.](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-evaluation-priority/)"

This is useful if you want, say, `home` to do one thing when pressed with `control` and to do a different thing when `control` isn't held. In this case, you would put the rule for `control`+`home` above the general rule for `home`.

**Comment by tsuliwaensis** [comment]
I can modify the `Home` key, but once I try to add either `control` or `right_control`, it stops working. I've tried `modifiers` and `simultaneous` without luck. What I am trying to capture is `Control+Home` pressed at the same time.

**Comment by tsuliwaensis** [comment]
> You can have multiple manipulators for the same key, but "[if there are multiple manipulators which change the same key, the manipulator placed at the top is applied and other manipulators are ignored.](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-evaluation-priority/)"
> 
> This is useful if you want, say, `home` to do one thing when pressed with `control` and to do a different thing when `control` isn't held. In this case, you would put the rule for `control`+`home` above the general rule for `home`.

It doesn't work like that for me. I have a rule that maps `home` to `a` and no matter where I put it on the list, the mapping is always applied.
