### ISSUE TITLE
Log events to a file?

### ISSUE THREAD

**Issue by setnone** [pqrs-org/Karabiner-Elements#2277]
Hello. I want to make a heatmap of my trackpad and keyboard usage.
Is there a way to output all grabbed events to a file?

**Comment by sdondley** [comment]
I would try searching google for "keystroke logger."

**Comment by tekezo** [comment]
I never add such feature to Karabiner-Elements.

You can observe events by yourself.
https://github.com/pqrs-org/osx-event-observer-examples
