### ISSUE TITLE
Request for a --get-variables option for cli

### ISSUE THREAD

**Issue by sdondley** [pqrs-org/Karabiner-Elements#2278]
I would like to be able to access the internal variables from the command line. Thanks.

**Comment by tekezo** [comment]
Read `/Library/Application Support/org.pqrs/tmp/karabiner_grabber_manipulator_environment.json`.

**Comment by sdondley** [comment]
OK, thanks. Do you know any command line utils that would make parsing and extracting the variables from the json in the file easy?

**Comment by sdondley** [comment]
Maybe this? https://stedolan.github.io/jq/

**Comment by sdondley** [comment]
Oh, wow, I just notice the bundle identifier in that file. This opens up interesting possibilities for hot keys that know which application the user is in.

**Comment by sdondley** [comment]
OK, got it. You do something like this with the `jq` command:

`jq .variables.hyper_space karabiner_grabber_manipulator_environment.json`
