### ISSUE TITLE
Have different keymaps for different _sites_ in a browser?

### ISSUE THREAD

**Issue by michaelwexler** [pqrs-org/Karabiner-Elements#2279]
Currently, Karabiner lets us customize keyevents by the app receiving the keypress with the bundle identifier, say org.mozilla.firefox.  Is there a way to know what **site** is currently active in the browser?  I ask because some keys are handled well by properly coded apps running in the browser, but general web pages may benefit from the changes.  So, we'd want to not only change the mapping for different osx apps, but even change the keymap depending on whether, say, docs.google.com is in the address bar.

A great example of this is Home and End:  Making these work like their PC versions is not too when replaced with, say, cmd arrows, and this helps most sites... but docs.google has some specific tweaks that mean we wouldn't need to remap.   

I don't know how the program detects what's running, so no idea if this is doable.

**Comment by sdondley** [comment]
You could trigger a simple apple script that gets the url of the current active window.

**Comment by sdondley** [comment]
Oh, the second part of this trick is to insert the url into a variable into karbiner with the karbiner_cli --set-variable option. Then you make the key command conditional on the url in the variable.

**Comment by michaelwexler** [comment]
Ok, did some research.  Thank you, @sdondley; I think you have the right approach; Applescript can actually get the URL of the current address bar from most major browsers with more or less code (easy on Chrome, bit more of a pita on the rest) and seems to be the easiest to implement.

However, getting the info into Karabiner is kind of harder.  You'd kind of need the applescript running continuously, communicating via the _cli command, and it's unclear to me what load that puts on the system.   New to OS X (MacOS), so still learning.
