### ISSUE TITLE
Second "to" directive getting ignored

### ISSUE THREAD

**Issue by sdondley** [pqrs-org/Karabiner-Elements#2280]
I have a modification that attempts to select tab 1 of safari after safari is opened (I have gmail pinned to tab 1). The script below works but the command-1 keystroke is ignored. It works when I type in in manually. I tried inserting a sleep in there but that didn't help. Any ideas?

``` 
   {
      "description": "tab-g to open Gmail",
      "manipulators": [
        {
          "from": {
            "key_code": "g",
            "modifiers": {
              "mandatory": [
                "right_command",
                "left_command",
                "right_control",
                "right_shift",
                "right_option"
              ]
            }
          },
          "to": [
            {
              "shell_command": "open -a 'Safari'; bash -c 'sleep 1.2'"
            },
            {
                    "key_code": "1",
                    "modifiers": [ "left_command" ],
                    "repeat": false
            }
          ],
          "type": "basic"
        }
      ]
    },
```

**Comment by sdondley** [comment]
Oddly, even this didn't work: `"shell_command": "open -a 'Safari'; bash -c 'sleep 1.5'; bash -c 'cliclick kd:cmd t:1'"`

It did work from the command line though. Maybe karabiner lacks some security permission?

At any rate, I had to solve this by calling an applescript. This is not ideal, however. Would love to know how to get this working with just bash and karabiner.

**Comment by thoelze1** [comment]
I'm assuming you have `tab` bound to `right_command`+`left_command`+`right_control`+`right_shift`+`right_option`?

When I try this modification with the physical modifiers (well, all physical modifiers except for `right_control` - I have `return` mapped to `right_control`, otherwise it wouldn't exist on my keyboard), both `to` targets trigger. Does it work for you when you use the physical modifiers?

**Comment by sdondley** [comment]
I didn't try that but I think I just found my answer. See https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/

Notice the Note there:

```
Note
The following keys are exclusive.
You cannot specify multiple items into one to entry.

key_code
consumer_key_code
pointing_button
shell_command
select_input_source
set_variable
mouse_key
```

**Comment by sdondley** [comment]
That note might not mean what I think it does. Here is an example where "to" has both "set_variable" and a "key_code" set and it works just fine:

```
    {
        "type": "basic",
        "from": {
            "key_code": "left_shift",
            "modifiers": {
                "optional": ["any"]
            }
        },
        "to": [
            {
                "set_variable": {
                    "name": "left_shift pressed",
                    "value": 1
                }
            },
            {
                "key_code": "left_shift"
            }
        ],
```
