### ISSUE TITLE
event_changed_if?

### ISSUE THREAD

**Issue by thoelze1** [pqrs-org/Karabiner-Elements#2282]
What does `event_changed_if` do?

The [documentation](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/event-changed/) is very short, and the only other reference to this condition that I've found in karabiner is in the [release notes](https://github.com/pqrs-org/Karabiner-Elements/releases). I've tried a few examples to see if `event_changed_if` does various things but I haven't been able to figure anything out.

**Comment by tekezo** [comment]
I added "Tip" to the documentation.
https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/event-changed/

**Comment by thoelze1** [comment]
Thank you!
