### ISSUE TITLE
Key remapping: what key is my key?

### ISSUE THREAD

**Issue by btgoodwin** [pqrs-org/Karabiner-Elements#2285]
I have a Keychron K6 and am finding the FN1 (Fn) and FN2 (??) keys are not easily used with my right hand and would like to move them left (so instead of right command, FN1, FN2, I would have FN1, FN2, right command).  The problem is I have no idea what FN2 maps to according to karabiner's nomenclature.

Is there a pane / status window somewhere that will show what key someone is pressing down to help do remaps?

**Comment by thoelze1** [comment]
[EventViewer](https://karabiner-elements.pqrs.org/docs/manual/operation/eventviewer/)

**Comment by btgoodwin** [comment]
Ah thanks! I knew it had to be there somewhere.  Interestingly, the key Fn1 has no response in that app.  Does that mean I cannot remap it at all?

**Comment by btgoodwin** [comment]
Unfortunately that's not an option (Show Keyboard Viewer) from that menu.  Never the less, thank you for pointing out the EventViewer!

**Comment by ZeliTheZealot** [comment]
@btgoodwin There is. It's one of the choices you can click near the bottom. It's always been there.

**Comment by btgoodwin** [comment]
Thanks!

**Comment by Gazoon007** [comment]
So there's no chance to remap Fn keys? I have the same issue with the author...

**Comment by MuhammedZakir** [comment]
> So there's no chance to remap Fn keys? I have the same issue with the author...

If your keyboard handles `Fn` key internally, there is no way to remap it using Karabiner (or any other apps for that matter). You can check it using EventViewer or on-screen keyboard (see @thoelze1's comment above).
