### ISSUE TITLE
Shift (hold) paren (press) — but long hold should not send a paren

### ISSUE THREAD

**Issue by ihodes** [pqrs-org/Karabiner-Elements#2294]
I am trying to emulate space cadet's shift / ( functionality, and I really like how the QMK firmware enables it. If you press and let go of shift quickly, it sends a `shift + )` or `9`. If you hold and press with another key/keys, it acts as a normal `shift`. If you hold for a bit and then let go, it will not send anything. This is nice if you accidentally hit shift when chording, or otherwise (it tends to happen a lot with me, and I can tell the difference between my QMK-firmware space cadet shift and the one I have enabled in Karabiner (see below configuration). Is there a way to get this to be a bit more QMK-like?

```
{
  "description": "Change left shift key to space cadet",
  "from": {
    "key_code": "left_shift",
    "modifiers": {"optional": ["any"]}
 },
 "to": [{"key_code": "left_shift"}],
 "to_if_alone": [{
     "key_code": "9",
     "modifiers": ["left_shift"]
 }],
 "type": "basic"
}
```

**Comment by thoelze1** [comment]
[to_if_alone docs](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-alone/)

**Comment by ihodes** [comment]
Thank you, I missed that!

**Comment by bakester14** [comment]
Hey @ihodes, longshot but I'm also navigating from a QMK keyboard to the internal macbook keyboard with karabiner. This is the first rule I'm struggling with writing on my own - I'm curious if you would mind sharing your configuration. To my eye, it's not clear what in the docs linked by @thoelze1 you missed. Thanks.
