### ISSUE TITLE
cannot connect with kernel extension

### ISSUE THREAD

**Issue by neileogrey** [pqrs-org/Karabiner-Elements#2296]
I know this has been an issue before but I've tried the proposed solutions in previous posts and cannot seem to get this issue resolved.

Problem: Karabiner-Elements stopped working recently (loads but none of the Change Keys are working) when I changed over from an old Macbook Air to new Macbook Pro via Time Machine. I get the message "cannot connect with kernel extension".

I had upgraded to Catalina on the old MBA prior to the transfer and had no issues. I've tried updating (although now I'm also getting an error and cannot update); I've restarted; I've uninstalled KE and reinstalled and restarted, all to no avail.

I do not have multiple users, so that's not the issue.

I'm new to Github and not a coder so help on a basic level is much appreciated! Thanks in advance.

Macbook Pro 2020
MacOS Catalina 10.15.4

**Comment by chaserogers** [comment]
similar issue here.  hopefully someone addressed this soon
