### ISSUE TITLE
Bug: to_if_held_down is canceled if another key is pressed

### ISSUE THREAD

**Issue by thoelze1** [pqrs-org/Karabiner-Elements#2298]
Consider the example from the [to_after_key_up docs](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-after-key-up/):
```
{
    "type": "basic",
    "from": {
        "key_code": "tab"
    },
    "to_after_key_up": [
        {
            "key_code": "tab"
        }
    ],
    "to_if_held_down": [
        {
            "key_code": "mission_control",
            "halt": true
        }
    ]
}
```
Given the following sequence of events:
- <kbd>TAB</kbd> key press
- Another key press within `to_if_held_down_milliseconds`
- <kbd>TAB</kbd> key release after `to_if_held_down_milliseconds`

`tab` is posted instead of  `mission_control`.

I'm using the [pre-release beta](https://github.com/pqrs-org/Karabiner-Elements/releases) on macOS Catalina 10.15.4

**Comment by aliusmiles** [comment]
Update: tested on latest beta, same issue.

**Comment by thoelze1** [comment]
Bump
