### ISSUE TITLE
USB mouse is recognised as multiple devices [possible conflict]

### ISSUE THREAD

**Issue by gc778** [pqrs-org/Karabiner-Elements#2300]
Here is how my mouse is recognised by KE when plugged in 
1] Keyboard (apple) - as a keyboard
2] Razer Lancehead - as a keyboard
3] Razer Lancehead - as a mouse

Vendor and product ids on 2] and 3] above are the same.

Neither simple nor complex modifications work. For instance I can't swap button4 with button1 nor can I get button1 + "some key" to get recognised as cmd + "some key". 

Any help/advice on this behaviour would be highly appreciated!?

P.S. 
Surprisingly Better Touch Tools does recognise my mouse and allows some simple modifications.

**Comment by aegwyng** [comment]
It is happening with my Razer Taipan, Just open KE Preferences, go to Devices and disable the "ghost" devices, so they won't create any conflict. I also recommend to disable the Apple Internal Keyboard so it will work as usual.

**Comment by gc778** [comment]
Thank you for the suggestion! 
I however already have all unwanted devices disabled/unticked in the KE -> Preferences -> Devices but unfortunately still no luck. I also tried to remove these "ghost" devices from the [karabiner.json] but this didn't yield the desired result either. 

I should probably mention that in the EventViewer -> Mouse Area my mouse buttons are recognised. Moreover simple modification of the form [from "a" to "button1"] only works if the "apple internal keyboard" is enabled whereas [from "button1" to "a"] never works. 

Perhaps Hammerspoon can also do the job yet it appears that there is some learning curve to it.

**Comment by amlynch** [comment]
@gc778 did you ever get a resolution to this issue? I'm encountering the same with a Logitech USB mouse; vendor_id and product_id are the same. I'm not sure if there's any way to edit these IDs, since they're presumably part of the product itself. 

(Main difference is I'm using Goku to edit Karabiner's setup.)

**Comment by gc778** [comment]
@amlynch No unfortunately this is still unresolved.
