### ISSUE TITLE
capslock + e to pageDown not working 

### ISSUE THREAD

**Issue by eret9616** [pqrs-org/Karabiner-Elements#2301]
```
{
      "description": "Change caps_lock+e to pageDown",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "e",
            "modifiers": {
              "mandatory": [
                "caps_lock"
              ]
            }
          },
          "to": [
            {
              "key_code": "page_down"
            }
          ]
        }
      ]
    }
```

this not working, and in eventviewer, i cant see misc in caps_lock or e
![image](https://user-images.githubusercontent.com/12445095/82873657-68fbc600-9f67-11ea-8abd-58f2dfc8bbf2.png)

is there any way to achieve this ? i tried to map caps_lock to f18, and f18 cant in misc either, how to do this?

**Comment by dennis-damico** [comment]
caps_lock isn't a modifier so i doubt it can be used in conjunction with another key as a modifier (though there are ways to have karabiner listen for keys pressed at the same time)

**Comment by ipatch** [comment]
you can setup a rule to enable a variable if caps_lock is toggled on/off and then press keys that would be mapped to something else, ie. so you'd enable caps_lock, set your variable, then a single press of the `e` key would act as pagedown.

this is something i'm still trying to wrap my head around as i'm trying to map `hypen` to `underscore` or `hyphen` with the `shift` flag when `caps_lock` is enabled, but haven't quite figure it out.

**Comment by eret9616** [comment]
1.set capslock to no action in system preference - keyboard
![image](https://user-images.githubusercontent.com/12445095/84094670-e75c6b80-aa2f-11ea-9165-461974bcaa5a.png)

2.mapped capslock to right_shift

3. then I use capslock(right_shift, its a modifier key now)+ e to work
