### ISSUE TITLE
Instructed to allow input monitoring permission to karabiner_grabber but not available

### ISSUE THREAD

**Issue by faunt** [pqrs-org/Karabiner-Elements#2302]
Only see `karabiner_observer` available. macOS 10.15.4

<img width="663" alt="Screenshot 2020-05-26 at 22 58 09" src="https://user-images.githubusercontent.com/436958/82949728-6370a100-9fa4-11ea-88e3-87bd712f899a.png">

**Comment by faunt** [comment]
Sorry, noticed there was in fact a second hanging dialog behind windows that first needed to action Open System Preferences as I’d done with karabiner_observer.

**Comment by tomjaguarpaw** [comment]
I also ran into this. As a new macOS user who is not used to the idea that essential windows can be obscured by other windows, could there be some way of making the situation more clear to the user?

(Thanks, by the way, for this great piece of software!)
