### ISSUE TITLE
broken "<>" key (azerty belgian keyboard layout) - Can't fix yet with Karabinder

### ISSUE THREAD

**Issue by philipdenys** [pqrs-org/Karabiner-Elements#2307]
The main issue is that the angle brackets have their own key (shift modifier is needed to switch between them).

I've tried to enter the country code with the 'virtual keyboard', it needs to confirm the layout of the keyboard with pressing the button next to the left shift key.
Unfortunately this is the button with broken angle brackets "<>" button.

**What I've tried so far:**

1. Used the complex-modifications tool  in Karabinder to create a key combination like fn + w (closest button combination). => no item found in the dropdown menu key selection (no keycode for angle brackets)

2. Even though the layout is very different from the qwerty, i still tried to make the combination with the key code "comma" with the shift modifier... no success.

my keyboard layout:
![image](https://user-images.githubusercontent.com/829155/83339717-d6de1f80-a2d0-11ea-88c5-7e3378060a8a.png)

**Comment by Lecta75** [comment]
Yep, same problems to QWERTY keyboard with Italian layout on Apple USB keyboard. This happens with all connected keyboards (just tried with a Trust USB keyboard).

the "angle brackets" key is swapped with the "slash and pipe" key just under the "ESC" key.

I also tried to update to latest beta. I'm running Catalina 10.15.5

**Comment by rodolfo-bocanegra-wl** [comment]
@philipdenys @Lecta75 did you guys find any workaround on this issue? I have a Spanish distribution keyboard with dedicated angle brackets keys but they print `|` and `°` :(

**Comment by MuhammedZakir** [comment]
Two solutions (which were already mentioned here):

1. Change country code of the virtual keyboard.
    - https://github.com/pqrs-org/Karabiner-Elements/blob/fdc9d542a6f17258655f595e4d51d1e26aa25d41/src/vendor/cget/cget/pkg/pqrs-org__cpp-hid/install/include/pqrs/hid/country_code.hpp#L34

2. Use EventViewer to get the key combo for angle brackets, `|` and `*` and then swap corresponding keys. To do that, you most probably will have to use complex modifications.

**Comment by MoiMorua** [comment]
I also had this issue, I only added a Virtual Keyboard with my specific distribution (ISO Europe, Latin America, Middle-East, and others, then after logging out the key worked again
![image](https://github.com/user-attachments/assets/3d909892-e146-4a60-9beb-3b99537a2f72)

**Comment by ltaupiac** [comment]
I had this issue with karabiner-elements 15.3 on a mac M4 and a french magic keyboard with keybard.
I found a workaround.
In virtual keyboard, I choose ANSI instead of ISO Europe.
The key mapping is respected, and the @/# key is not swapped with the </> anymore.
And Complex modification still works.
