### ISSUE TITLE
Karabiner not working on MacOS Catalina 10.15.5

### ISSUE THREAD

**Issue by jasnsy** [pqrs-org/Karabiner-Elements#2308]
Screenshots:
![image](https://user-images.githubusercontent.com/33563928/83348179-55de5280-a2e7-11ea-9e69-3ea3425118da.png)
![image](https://user-images.githubusercontent.com/33563928/83348185-655d9b80-a2e7-11ea-8049-e3552930e072.png)

**Comment by mcmillion** [comment]
Weirdly enough, I have two MBPs (one work, one personal) both on 10.15.5 with the same configuration and one works and one doesn't.

The one that works is a 16" MBP, the one that doesn't is an older 13" TB

**Comment by mcmillion** [comment]
Bumping to the latest beta (12.9.6) fixed it on the machine that wasn't working.

**Comment by alexandreMelloTW** [comment]
I worked for me after uninstall and install Karabiner 12.9.

**Comment by jasnsy** [comment]
Turns out it was a security flag that was setup to not allow Kext, been reverted and it's now working fine. Closing ticket!
