### ISSUE TITLE
"Incompatible with future version of macOS"

### ISSUE THREAD

**Issue by insasquatchcountry** [pqrs-org/Karabiner-Elements#2309]
I've been using this utility for years now and love it!

Today I got this message which linked me to [this page on Apple's website.](https://support.apple.com/en-us/HT210999)

![Screen Shot 2020-06-01 at 10 06 43 AM](https://user-images.githubusercontent.com/8946291/83440302-8e6e5100-a3f9-11ea-9a95-0ebab8b05e0c.jpg)

**Comment by tekezo** [comment]
I'm developing new DriverKit extension from legacy system extension.
I'll ship new release when the migration is finished. Please wait!
https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice

**Comment by gustavobittencourt** [comment]
Thank you so much, @tekezo!

**Comment by ssbarnea** [comment]
Any updates on this? Clearly stale bot wrongly closed it. You should configure it to close only with warning to avoid closing real bugs.

**Comment by offbyone** [comment]
Pretty sure this is still an issue.
