### ISSUE TITLE
KE v12.9.0 cannot working good on the 2020macbook pro 13' with the touchbar

### ISSUE THREAD

**Issue by hyperlau** [pqrs-org/Karabiner-Elements#2310]
It's a new laptop,I set the touchbar show the F1-F12 button.
When I installed the KE it's worked ok,but some minutes ago ,the Keyboard recognition program of the System Setting Program started automatically
<img width="616" alt="image" src="https://user-images.githubusercontent.com/4133461/83476020-3c453280-a4c2-11ea-8977-b6a86ec7a668.png">

,and the command-F1 shortcut is not recognized by the system.
I'm like to set command-F1 to let window minimize,but now I cannot set the shortcut in the Setting-Keyboard-shortcut-AppShort,when I press Command-F1,system recognized it to F1.
I tried reinstall KE,deleted the config dir,but not helpful.
The MacOS version is 10.15.5 (19F96)

**Comment by mesqueeb** [comment]
I have the same problem.
I just got the Macbook Pro 13' 2020 with touchbar.

The caps lock remap seems to work but cannot be used to launch alfred any more.
alfred does seem to recognise caps lock as control (as I set up) but not in combination with space.

I also always have that image as the person above.
