### ISSUE TITLE
KE no longer working after upgrade to macOS Catalina 10.15.5 (19F101)? Try Beta updates.

### ISSUE THREAD

**Issue by lemontheme** [pqrs-org/Karabiner-Elements#2311]
Following a patch update to macOS 10.15.5 (19F101), KE stopped working. The app launches and everything, and the EventViewer registers input; but the actual key modifications are no longer applied. First hiccup in over a year of rock-solid use. 

Anyway, for anyone facing the same issue, I found that enabling 'check for beta updates' in preferences/misc installs an updated version that *does* work. Now, installing from beta probably isn't something that should be generally encouraged, but if you're just looking for a quick fix, this is it.

**Comment by dixius99** [comment]
To make things more complicated, this does not seem to be a problem for all people. I have macOS 10.15.5 installed, and Karabiner Elements 12.9.0 continues to work fine.

**Comment by sdaza** [comment]
I have macOS 10.15.4, the beta version of KE, and I get this error: 

[2020-06-09 08:46:23.565] [info] [kextd] KextManagerLoadKextWithURL: kOSKextReturnDependencyLoadError

KE is not working at all :(

**Comment by kommen** [comment]
Can confirm that after updating to macOS 10.15.5 (19F101) KE 12.9.0 stopped working for me, and after installing KE 12.9.6 it is working again, exactly as @lemontheme described.

**Comment by tphalp** [comment]
I'm on macOS 10.15.5, and KE stopped working for me. Installing the beta (12.9.6) did not fix it for me, unfortunately. :(

The Log tab in KE Preferences just fills up with this message:

`[2020-06-19 17:06:05.846] [info] [kextd] KextManagerLoadKextWithURL: kOSKextReturnSystemPolicy
`

And this error appears in the Console app:

`org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000 failed security checks; failing.`

KE shows the notification to go into "Security and Privacy" in System Preferences to "Allow" the app/developer, but when I go into "Security and Privacy", there isn't anything to allow. I've followed the suggestion of rebooting my laptop in Safe Mode and installing/authorizing the app, but that doesn't work either. Same result--no option to "Allow".

**Comment by nomaded** [comment]
I am seeing the same behavior as @tphalp with 12.10.0. This is on a new-to-me MacBook Pro, with a clean install of Catalina 10.15.5. One thing that might be noteworthy is that this MBP is provided by my employer, so it has Jamf installed to also manage parts of the OS. I'm not sure what hooks Jamf have into Catalina to even guess if it might be causing this problem with allowing KE's kext permissions to work.

**Comment by tphalp** [comment]
That is a great point @nomaded about corporate software potentially managing part of the OS, and adding to the problem. My laptop is also a work-owned one, and they use SentinalOne to help manage hardware. I'm not sure if that is causing the issue or not. I did reach out to our helpdesk staff, and they didn't think it would, but they weren't 100% sure.

**Comment by nomaded** [comment]
I found a [solution](https://github.com/pqrs-org/Karabiner-Elements/issues/1701#issuecomment-536670667).

A duckduckgo search for "KextManagerLoadKextWithURL: kOSKextReturnSystemPolicy" turned up [an old issue from Jan 2019](https://github.com/pqrs-org/Karabiner-Elements/issues/1701), with the solution of:

"You can resolve this issue by running `spctl kext-consent add G43BCU2T37` in the **recovery mode**."

Where `G43BCU2T37` is the `team_id` for @tekezo, as referenced in [his post on the Apple Dev forums](https://developer.apple.com/forums/thread/79172#248518).
