### ISSUE TITLE
Docs: Add link to custom JSON rules documentation in "Use more complex rules" page

### ISSUE THREAD

**Issue by lukewlms** [pqrs-org/Karabiner-Elements#2320]
It's currently nearly impossible from the docs to figure out how to create a custom rule.  On the page that informs users they can create their own rules, there's absolutely no info on how to do that - only on how to download new ones from the internet.

This can be resolved really simply: just link to this page

https://karabiner-elements.pqrs.org/docs/json/

from this page:

https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-complex-modifications/

After lots of digging I was only able to find this info from this [closed GH thread](https://github.com/pqrs-org/Karabiner-Elements/issues/1225).  It would be a big usability gain to add that simple link!

Thanks for your work on this.

**Comment by kevin-meyers** [comment]
I had this same issue, I am only finding the link now because of this issue

**Comment by thomasahle** [comment]
The new page doesn't seem to explain where to store your own `custom_modifications.json`file.
