### ISSUE TITLE
Cannot use same key with different set of conditions

### ISSUE THREAD

**Issue by AdamJamil** [pqrs-org/Karabiner-Elements#2326]
When writing two manipulators that take in the same key, but will act differently based on different sets of conditions, the latter one is ignored. Can a feature be implemented that matches the conditions to the right manipulator?

**Comment by dPowNextdoor** [comment]
FYI I just created [this issue](https://github.com/pqrs-org/Karabiner-Elements/issues/2774) that would help solve the pain points you're experiencing. Feel free to comment/upvote to attract greater attention from the devs!
