### ISSUE TITLE
Add Key codes for swipe gestures

### ISSUE THREAD

**Issue by JohnRThomas** [pqrs-org/Karabiner-Elements#2330]
I would like to remap three finger swipe for a single application since it supports a back/forward hotkey, but does not support the mac os native swipe shortcut.

These events are NSEventTypeSwipe with a direction and number of fingers, should be something like swipe_3_right, swipe_2_up etc.

**Comment by huhu415** [comment]
have it  down？

**Comment by Raymo111** [comment]
@tekezo could we reopen this please

**Comment by JamIsJam88** [comment]
Has anyone found a way to add a complex modification to do macOS gestures?

**Comment by patster98** [comment]
Maybe I’m lowballing here or missunderstood the issue, but control+left/right arrow imitates the three finger swipe on MAC to switch desktops, and if you want the “mission control” three finger swipe up or down, just remap any key combo you like to the following in karabiner-elements:
`"apple_vendor_keyboard_key_code":”mission_control”`

You can either use control + up arrow too

**Comment by GreyAsteroid** [comment]
> Maybe I’m lowballing here or missunderstood the issue, but control+left/right arrow imitates the three finger swipe on MAC to switch desktops, and if you want the “mission control” three finger swipe up or down, just remap any key combo you like to the following in karabiner-elements: `"apple_vendor_keyboard_key_code":”mission_control”`
> 
> You can either use control + up arrow too

I believe this has more to do with applications treating a back/forward swipe gesture differently from a back/forward hotkey.

**Comment by aledomu** [comment]
Hi, still interested in this. I (we?) would like to be able to do the same mapping that SaneSideButtons does.
