### ISSUE TITLE
Caps lock to command+control+option+shift stop working

### ISSUE THREAD

**Issue by scottfwalter** [pqrs-org/Karabiner-Elements#2334]
I've had this issue for a while. I have the complex rule "Change copas_lock to command+control+option+shift" setup.  However its not working correctly.   I have a shortcut in keyboard maestro which is bound to command+control+option+shift+semicolon.

When I press capslock-semicolon nothing happens.  Well, my computer beeps.    It just changes the state of the capslock key from lowercase to uppercase.  Here is what the event viewer shows:

type:key_down        code:57         name:caps_lock       misc:
type:key_down        code:51         name:semicolon       misc:
type:key_up          code:51         name:semicolon       misc:
type:key_up          code:57         name:caps_lock       misc:

Any ideas?   I just upgraded to 12.10 to see if that resolves the issue but no luck.

**Comment by larsof54** [comment]
That shortcut is reserved for Apple. It makes a log of something or other.

You have to use another key with command+control+option+shift.

Most other keys work but there are a few that Apple uses.

LW

**Comment by scottfwalter** [comment]
I figured out the issue.  It didn't have to do with semicolon as that had worked before.   I looked under devices and it showed my Logitech keyboard listed twice:

Logitech K811 (Apple)
Logitech K811 (Unknown)

Logitech K811 (Apple) was selected.  I unselected Logitech K811 (Apple) and selected Logitech K811 (Unknown).  Once i did that everything started to work.
