### ISSUE TITLE
Karabiner does not see a custom json file

### ISSUE THREAD

**Issue by ruslaniv** [pqrs-org/Karabiner-Elements#2338]
I just created a custom json file and put it in the 
`/Users/myname/.config/karabiner/assets/complex_modifications/mine.json`
but Karabiner does not see it. So I ran it through online JSON validator - no errors. The logger in Karabiner shows no errors either. 
But another custom file I created, loads just fine. 
So how can I troubleshoot the problem of one file not being loaded?

**Comment by ruslaniv** [comment]
This is really strange, neither validator or Karabiner logger raised any errors, but after pasting rules one by one into a new file I did find an offending rule which did contain an error.

**Comment by sn0wyfall** [comment]
so that's where complex modifications go, thanks
