### ISSUE TITLE
Version 12.10.0 stop working for when installed.

### ISSUE THREAD

**Issue by ericklind** [pqrs-org/Karabiner-Elements#2341]
I recently upgraded to version 12.10.0 and it no longer works. I mostly use it for Remote Desktop and none of the keystrokes work. I tried downgrading, and that did not work. I upgraded again to 12.10.0 with no luck. I also tried the beta version of RDP and no change.
I even added my own simple rule to swap the window and command keys and it does not work.
I am using a MacBook Pro late 2015,  OSX 10.15.5

Please let me know what you need to help troubleshoot this issue.

**Comment by tjuerges** [comment]
Additional sample where there appears to be no problem:  almost same config (macOS 10.15.5, MacBook Pro Retina, 16 GB, Mid 2015) and upgraded an hour ago to 12.10.0.  No problems (Karabiner-Elements reports 12.10.0), but I have not rebooted the system yet.

**Comment by ericklind** [comment]
I rebooted a second time and things seem to be working as expected.

Cheers!

**Comment by tohvanah** [comment]
I'm having the same issue, the log shows:
`[2020-07-03 11:37:44.422] [info] [grabber] version 12.10.0
[2020-07-03 11:37:44.422] [info] [grabber] Exit since another process is running.`
After update it doesn't work. I can't restart right now, shouldn't have updated...
