### ISSUE TITLE
Can't disable keys

### ISSUE THREAD

**Issue by skyguz** [pqrs-org/Karabiner-Elements#2346]
Hi,
I'm une macOS X El Capitan 10.11.6 on a MacBook Pro mid-2009. I accidentally split some beer on my keyboard and I have 2 keys not functioning any more, ctrl left and "2". It's like they are always pressed. I've downloaded Karabiner Elements 11.6.0, that works on my system, and tried to disable these 2 keys, and it seems to work at the beginning. But it is very random, it rarely works, and I can't get why it sometimes works and sometimes not.
But anyway since a couple of days, it doesn't work at all, the keys are always pressed and Karabiner doesn't seem to be able to disable them.
I have tried to reboot the system several times, after having copy the configuration to system default. Nothing works.

Here is a line of the Launch EventViewer :
eventType:KeyDown         code:0x13       name:2               flags:Ctrl                               misc:
And it never stops...

Thanks for help

**Comment by dPowNextdoor** [comment]
A bit late, but maybe try `vk_none`?

```json
{
    "type": "basic",
    "from": {
        "key_code": "left_control"
    },
    "to": [
        {
            "key_code": "vk_none"
        }
    ]
}
```
