### ISSUE TITLE
[SOLVED] Use wildcard in bundle_identifiers (for use with Parallels VMs in Coherence mode)

### ISSUE THREAD

**Issue by mabam** [pqrs-org/Karabiner-Elements#2349]
Hello there!

Today I tried remapping a keyboard shortcut for all my Parallels VMs to execute a shell command. It does work fine if I specify the exact bundle IDs. However, while a VM is in Coherence mode its process name is always “WinAppHelper” and the bundle ID always begins with “com.parallels.winapp.”, the rest of the bundle ID is different for every VM. (If _not_ in Coherence mode the bundle ID is always ”com.parallels.desktop.console” of “prl_client_app” [which is the process name of Parallels Desktop.app]. The actual VM is then a window of that process).

This means that I will have to amend karabiner.json every time I create a new VM (or if a bundle ID changes for any other reason), and that the list under bundle_identifiers (one for every VM in coherence mode) would be quite long.

Isn’t there a way to remedy this by using a wildcard when defining “bundle_identifiers” like so: `"^com.parallels.winapp.*$"`?

It would also be an option to use the process name instead, but according to https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/ this doesn’t seem to be possible either.

Of course, any other suggestions are welcome as well.

(I’m using Karabiner Elements since quite a while now and it was always working perfectly. I’m amazed by the customisation and automation possibilities it offers. Thank your for your hard work!)

**Comment by mabam** [comment]
Actually, I’ve found the solution. It _is_ possible to use wildcards.

For my use case, and as reported at [https://translate.google.com/translate?sl=ko&tl=en&u=https%3A%2F%2Fdimag.ibs.re.kr%2Fhome%2Fsangil%2F2018%2Fmac-os-korean-input%2F%23comment-20](url), ”bundle_identifiers” has to read:
`"^com.parallels.winapp.[[:graph:]]*$"`

This works perfectly for me.

**Comment by mabam** [comment]
Is there a way to mark this issue as solved?
I don’t actually want to close it to keep it open for additional comments and questions.

**Comment by oakif** [comment]
You can still comment on issues after you close an issue. On GitHub the way to mark an issue as "solved" is to close it, although it would likely make sense to have a "solved" marking. Best you can do right now is to have someone assign you a "solved" tag
