### ISSUE TITLE
Legacy System Extension

### ISSUE THREAD

**Issue by rickysidhu022** [pqrs-org/Karabiner-Elements#2351]
Received the following pop-up error on my MacBook Pro 16 inch (2019) running MacOS Catalina (10.15.5):

"Existing software on your system loaded a system extension signed by "Fumihiko Takayama" which will be incompatible with a future version of MacOS. Contact the developer for support.
<img width="414" alt="Screen Shot 2020-07-13 at 6 21 07 PM" src="https://user-images.githubusercontent.com/62409253/87371145-96adc600-c539-11ea-8d0b-719e880d9d51.png">

**Comment by sdondley** [comment]
Dup: https://github.com/pqrs-org/Karabiner-Elements/issues/2309

**Comment by rickysidhu022** [comment]
> Dup: https://github.com/pqrs-org/Karabiner-Elements/issues/2309

My apologies. This was my first attempt at posting on GitHub. Will delete this issue if the option is available.

**Comment by sdondley** [comment]
You should see a button to close & comment on github at the bottom of this thread.
