### ISSUE TITLE
Touch Bar quarter step brightness, volume, and backlight increments not working when Karabiner is running

### ISSUE THREAD

**Issue by ruohola** [pqrs-org/Karabiner-Elements#2357]
Steps to reproduce:

- Have Karabiner open
- Press the arrow on the Touch Bar to view the full control strip
- Hold alt + shift and press brightness buttons -> brightness is adjusted incorrecly in full step increments
- Close Karabiner completely
- Hold alt + shift and press brightness buttons -> brightness is adjusted correctly in quarter step increments

Using Karabiner 12.10.0 on MacBook Pro 16" running macOS Catalina 10.15.5.
This is not a new issue and has been around for at least a year, only now realised that the issue happened because of Karabiner.

**Comment by oakif** [comment]
Confirmed that this happens to me as well.

**Comment by alfreedom** [comment]
Confirmed the issue to with karabiner v12.10.0

**Comment by panaut0lordv** [comment]
Funny thing is that it seems to work fine with external keyboard (even with Karabiner running).

**Comment by oakif** [comment]
I presume it's something to do with the Touch Bar. I believe it should also work fine on nTB Macs (although I'm not sure)

**Comment by oakif** [comment]
Seems to be fixed in the latest version of Karabiner

**Comment by ruohola** [comment]
@oakif I can confirm that the issue is fixed for me as well on Karabiner 13.0.0, I'll close this issue.
