### ISSUE TITLE
Apple MacBook Pro - unable to map fn->left_control

### ISSUE THREAD

**Issue by 123abceng** [pqrs-org/Karabiner-Elements#2359]
macOS Mojave, ver 10.14.6 - updated today 
Karabiner - updated today.
fn key can't be mapped to any other key...

**Comment by dhcmega** [comment]
I have the same problem. Have you found a solution? It's like karabiner is not detecting the button.

**Comment by faustobranco** [comment]
Me too... I have a Ducky one 2 TKL, and I can't identify the FN key, I want to map it to configure the fn + WASD keys.

**Comment by dhcmega** [comment]
@faustobranco It seems that the FN key modifies the code other keys send when pressed, so they are not actually sending a code them selves.
I have a Satechi keyboard that has a lock function (located on the Escape button) that set the FN as constantly pressed, if that helps you.

**Comment by faustobranco** [comment]
Tks @dhcmega,  I managed to get around the problem in another way, I changed the switches to my keyboard to the function key to work as "menu" so, in Karabiner I made the Simple Modification from "app" to "fn".
