### ISSUE TITLE
BUG? caps_lock and to_if_alone

### ISSUE THREAD

**Issue by alvaro-prieto** [pqrs-org/Karabiner-Elements#2364]
Hello! Why the first code fragment works while the second snippet doesn't? (only difference is "**_to_**" VS "**_to_if_alone_**"). Expected: caps_lock toggle if left_control pressed alone.

The following code does work (**_to_**):
```
{
    "from": {
        "key_code": "left_control",
        "modifiers": {
            "optional": [
                "caps_lock"
            ]
        }
    },
    "to": [
        {
            "key_code": "caps_lock"
        }
    ],
    "type": "basic"
},
```

The following code doesn't work (**_to_if_alone_**):

```
{
    "from": {
        "key_code": "left_control",
        "modifiers": {
            "optional": [
                "caps_lock"
            ]
        }
    },
    "to_if_alone": [
        {
            "key_code": "caps_lock"
        }
    ],
    "type": "basic"
},
```

**Comment by hsgrott** [comment]
Hello,

I had the same problem on MacOS. It seems that the operating system will not register a caps lock activation (deactivation is fine) if a key press/key release is sent too fast.

Adding `"hold_down_milliseconds": 80` to the `"to_if_alone"` clause solved the problem for me.

**Comment by alvaro-prieto** [comment]
It works like a charm! Thank you! Now I'm trying to realize how to add the hold_down_miliseconds in Goku, seems to be :hold_down_ms  but I'm struggling with it. If I achieve it I will post it here. Thank you @hsgrott  !!

**Comment by alvaro-prieto** [comment]
This is how it can be done in Goku

`[ :##left_control :left_command nil { :alone { :key :caps_lock   :hold_down_ms 80  } }]`
