### ISSUE TITLE
12.10 doesn't work with symlink-ed config

### ISSUE THREAD

**Issue by Huxpro** [pqrs-org/Karabiner-Elements#2368]
Prior to 12.10, I tend to config KE via a symlink:

```
ln -sf "$cwd/karabiner/karabiner.json" ~/.config/karabiner/karabiner.json
```

I found my KE is no more working after upgrading 12.10. It took me a while to figure out that it did not follow the symlink and will replace it to a default config.json. Manually copying one get my KE back to working.

I worried that I'm not the only person config KE via symlink and it probably breaks a lot of users.

**Comment by tekezo** [comment]
Read this page: https://karabiner-elements.pqrs.org/docs/manual/misc/configuration-file-path/#about-symbolic-link
