### ISSUE TITLE
check/remap duplicate keys?

### ISSUE THREAD

**Issue by jvanasco** [pqrs-org/Karabiner-Elements#2369]
My apple bluetooth keyboard died, and I am using an emergency backup I bought from Monoprice several years ago.

The bottom row of keys starts with: ctrl, windows, alt, backslash/pipe, spacebar

The backslash/pipe is problematic - it's a duplicate of the same key in the normal spot for US keyboards (above the enter key).  I can't disable this duplicate key in Karabiner without disabling the normal key.  

Is there a more low-level way in Karabiner to catch this keypress?  it is entirely possible the keyboard is sending the same signal for both keys, but I can't tell. 

also: Thank you SO MUCH for this software. My keyboard of choice was discontinued many years ago (Logitech k760), and Karabiner let me remap the non-US versions I was able to find on eBay into the US keyboard layout.

**Comment by MuhammedZakir** [comment]
> Is there a more low-level way in Karabiner to catch this keypress? it is entirely possible the keyboard is sending the same signal for both keys, but I can't tell.
It's not possible atm. You can use 'Karabiner-EventViewer' to inspect keyboard/mouse events.
