### ISSUE TITLE
macOS Catalina: map_to: application -> no context menu

### ISSUE THREAD

**Issue by muescha** [pqrs-org/Karabiner-Elements#2376]
### goal
- i try to have a shortcut to open a context menu like in windows with the context menu keyboard or <kbd>shift</kbd>+<kbd>F10</kbd>

### what i setup:
- i installed karabiner-elements
- i mapped the `caps_lock` to `application`
- i checked with Karabiner-EventViewer: when i hit caps lock i see application in the log

### what i see:
- nothing changes
- in the EventViewer: when i select a text and then i hit caps_lock then the selected text is removed

### what i expect:
- the context menu should open like when i open a context menu at the element selected (with curesor)

### environment
- macOS: Catalina 10.15.3 (19D76)
- karabiner-elements: 12.10.0

**Comment by muescha** [comment]
did i miss some setting to get it work?

**Comment by MuhammedZakir** [comment]
`application` does not work. Instead, use `button2` in `Mouse buttons`.

**Comment by dPowNextdoor** [comment]
FWIW If you map to `button2`, it'll only work when your mouse is over the element you're trying to open the context menu for. i.e. If your Finder has selected `FileA.txt` but your mouse is hovered over `FileB.txt`, it'll open the context menu for `FileB.txt`.

I would recommend mapping to a key combo that's internal to the OS (likely `Option+F2` on Mac). My external keyboard has a physical context menu button, so I used `application`, but you could probably change it to `caps_lock` instead. My config that works:

```json
{
    "description": "Context Menu button ('application' in Mac) fix",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "application"
            },
            "to": [
                {
                    "key_code": "f2",
                    "modifiers": [
                        "option"
                    ]
                }
            ]
        }
    ]
}
```

**Comment by nafarinha** [comment]
>  use `button2` in `Mouse buttons`.

For this to work as expected the mouse's `Secondary click` needs to be `Click Right Side` under `System Settings > Mouse`. If you set `System Settings > Mouse > Secondary click` to `Click Left Side` , use `button1` in `Mouse buttons` instead.

(Tested on macOS: Sonoma 14.7.4;  karabiner-elements: 15.3.0)
