### ISSUE TITLE
one conditions object for several manipulators.

### ISSUE THREAD

**Issue by whitemuu** [pqrs-org/Karabiner-Elements#2379]
{
        "description": "Auto pair parenthesis",
        "conditions": [
            {
                "bundle_identifiers": [
                    "org.gnu.Emac"
                ],
                "type": "frontmost_application_unless"
            }
        ],
        "manipulators": [
            {
                "from": {
                    "key_code": "9",
                    "modifiers": {
                        "mandatory": [
                            "shift"
                        ],
                        "optional": [
                            "any"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "9",
                        "modifiers": "shift"
                    },
                    {
                        "key_code": "0",
                        "modifiers": "shift"
                    },
                    {
                        "key_code": "left_arrow"
                    }
                ],
                "type": "basic"
            },
            {
                "from": {
                    "key_code": "open_bracket",
                    "modifiers": {
                        "mandatory": [
                            "shift"
                        ],
                        "optional": [
                            "any"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "open_bracket",
                        "modifiers": "shift"
                    },
                    {
                        "key_code": "close_bracket",
                        "modifiers": "shift"
                    },
                    {
                        "key_code": "left_arrow"
                    }
                ],
                "type": "basic"
            },
            {
                "from": {
                    "key_code": "open_bracket",
                    "modifiers": {
                        "optional": [
                            "any"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "open_bracket"
                    },
                    {
                        "key_code": "close_bracket"
                    },
                    {
                        "key_code": "left_arrow"
                    }
                ],
                "type": "basic"
            }
        ]
    }

Does Karabiner-Element have this feature?

**Comment by MuhammedZakir** [comment]
AFAIK, no! These [1][2] maybe useful i you wan to generate configs easily. It has an added benefit of easier maintenance too.

[1] https://github.com/pqrs-org/KE-complex_modifications/tree/master/src/json/ - a bit cumbersome for prototyping as you will have to remove that rule and add it again. Would have been nice if there was a refresh button.
[2] Goku - https://github.com/yqrashawn/GokuRakuJoudo

**Comment by dPowNextdoor** [comment]
FYI I just created [this issue](https://github.com/pqrs-org/Karabiner-Elements/issues/2774) that would help solve the pain points you've been discussing. Feel free to comment/upvote to attract greater attention from the devs!
