### ISSUE TITLE
can't delete Karabiner*

### ISSUE THREAD

**Issue by merkleID** [pqrs-org/Karabiner-Elements#2384]
luca:Applications root# whoami 
root

So,
having decided to remove it, I found out that

luca:Applications root# rm -rf Karabiner-Elements.app/
rm: Karabiner-Elements.app//Contents: Operation not permitted
rm: Karabiner-Elements.app/: Operation not permitted

and also
luca:Applications root# rm -rf Karabiner-EventViewer.app/
rm: Karabiner-EventViewer.app//Contents: Operation not permitted
rm: Karabiner-EventViewer.app/: Operation not permitted

as root I have no permission over the files.
I also deleted $HOME/.config/Karabiner as someone suggested, but still no luck in removing the app.
I also have to say that since I did a 
kextunload org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext
and rebooted, the system had an overall speed-bump, which is the main reason I am uninstalling Karabiner.

Any hint about uninstalling it?
Thank-you

**Comment by tekezo** [comment]
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/
