### ISSUE TITLE
shell_command not working

### ISSUE THREAD

**Issue by oleksii-haponiuk** [pqrs-org/Karabiner-Elements#2391]
When I try it with example (`open -a 'Safari.app'`), it works. But when I want to make it work with my window manager, e.g. `yabai -m window --focus next`, nothing happens, even though it works as expected when I execute it directly in terminal. I also tried execution with file (`"shell_command": "/bin/zsh ~/desktop/focus.zsh"`, where `focus.zsh` is a script with the same command), but it still doesn't work.

**Comment by babygau** [comment]
chances are you installed yabai using homebrew, you could try `/usr/local/bin/yabai .....`

**Comment by iSteeb** [comment]
(Presumably) same issue, but unsure of how to apply solution...
`"shell_command": "/opt/homebrew/bin/yt-dlp --format \"bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]\" $(pbpaste)  -o \"Downloads/%(title)s.%(ext)s\" --ffmpeg-location \"/opt/homebrew/bin/ffmpeg\""`

Command executes fine in terminal, but I can't even get an error output from the below, so I guess that means nothing is happening at all?

`                    "shell_command": "/opt/homebrew/bin/yt-dlp --format \"bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]\" $(pbpaste)  -o \"Downloads/%(title)s.%(ext)s\" --ffmpeg-location \"/opt/homebrew/bin/ffmpeg\" > capture.txt 2>&1"
`
