### ISSUE TITLE
Mouse button mapping doesn't work in Karabiner-Elements version 12.10.0

### ISSUE THREAD

**Issue by rpringadi** [pqrs-org/Karabiner-Elements#2394]
I did a `Simple Modifications` `For all devices`
from `button4` to `a`
from `button5` to `b`
Doesn't work.

I verified that Karabiner-EventViewer can detect my mouse button4 and mouse button5.

My env:
MacOS Mojave 10.14.6
Karabiner-Elements version 12.10.0

<img width="997" alt="Screen Shot 2020-08-14 at 11 06 35 AM" src="https://user-images.githubusercontent.com/2053877/90263959-626e4380-de1e-11ea-8c45-d6faf06c3cbf.png">

**Comment by zernyu** [comment]
Laptop auto-updated to macOS Catalina 10.15.6 last night. Running Karabiner-Elements 12.10.0.

No modifications are working for me; no keyboard mappings, no mouse mappings :'(

**Comment by kirintwn** [comment]
Is your mouse enabled in the Devices section of the Karabiner preferences?
I am able to remap my mouse with MacOS Mojave 10.14.6 & Karabiner-Elements version 12.10.0.

**Comment by rpringadi** [comment]
Thank you @kirintwn . My mouse is registering as two devices for some strange reason. After I put check mark for both, it works!
