### ISSUE TITLE
It looks doesnt work on big sur beta4

### ISSUE THREAD

**Issue by successc** [pqrs-org/Karabiner-Elements#2396]
mute , volume up , volume down doesnt worked

**Comment by baba1587** [comment]
so I have trouble to use it

**Comment by Changemin** [comment]
I Updated to beta karabinder version, but it's still not working on Big Sur beta

**Comment by lbibass** [comment]
It's broken. This is a known issue due to the way that MacOS changed the way the kernel level drivers operate. Don't upgrade to Big Sur if you want to use Karabiner-Elements at this time.

**Comment by Changemin** [comment]
Shall we wait for next update ?

**Comment by MuhammedZakir** [comment]
> Shall we wait for next update ?

You can see the current work here -- https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice.

**Comment by tekezo** [comment]
https://github.com/pqrs-org/Karabiner-Elements/issues/2331
