### ISSUE TITLE
Caps Lock turns on by itself when keyboard is connected

### ISSUE THREAD

**Issue by chunheisiu** [pqrs-org/Karabiner-Elements#2397]
I'm currently on macOS Catalina 10.15.6 and a Keychron K2 keyboard. Whenever the keyboard is connected using Bluetooth, the caps lock turns on by itself. I have tried turning off the "Manipulate LED" option under "Caps Lock LED" but nothing changes. Anyone having the same problem has a solution to this behavior?

**Comment by WalterDurkee** [comment]
I seem to have similar issue. Were you able to sort it out?

**Comment by chunheisiu** [comment]
Not really. I uninstalled it for the time being.

**Comment by troutio** [comment]
This is an issue for me also - RK68 keyboard, MacOS 21.1, KE 14.3.0
