### ISSUE TITLE
[Feature request] Map a key to another if conditions but to a third one if conditions are not met

### ISSUE THREAD

**Issue by damaru2** [pqrs-org/Karabiner-Elements#2403]
I would like to have another option, something like `to_if_not_conditions`
My use case:
I normally want caps_lock to be command outside of the terminal but want it to be control inside the terminal. With the current options one can only map caps_lock to one of them. It is possible to map caps_lock to command outside of the terminal for instance but then there is no option to map it to another key inside of the terminal, caps_lock is caps_lock if conditions are not met.
That is why I would love to be able to use something like the following 
```
{
                     "description": "escape to control in terminal but to command outside of terminal ",
                     "manipulators": [
                        {
                           "conditions": [
                              {
                                 "bundle_identifiers": [
                                    "^com\\.apple\\.Terminal$"
                                 ],
                                 "type": "frontmost_application_if"
                              }
                           ],
                           "from": {
                              "key_code": "caps_lock",
                              "modifiers": {
                                 "optional": [
                                    "any"
                                 ]
                              }
                           },
                           "to": [
                              {
                                 "key_code": "left_control"
                              }
                           ],
                           "to_if_not_conditions": [
                              {
                                 "key_code": "left_command"
                              }
                           ],
                           "to_if_alone": [    // Being compatible with the other options would be nice. Even better, although I don't need, it would be optimal to be able to select what happens if pressed alone and conditions are not met etc.
                              {
                                 "key_code": "escape"
                              }
                           ],
                           "type": "basic"
                        }
                     ]
                  },

```

**Comment by MuhammedZakir** [comment]
If conditions are not met for a key, KarabinerElements will look for the next rule for that key, until it either executes a matching rule or do nothing (if it couldn't find another rule or if the conditions for those rules were not met). So by adding another rule below the rule with conditions, you could essentially map the same key any number of times. Therefore, order of rules for a key will be general rules to more specific ones; from bottom to top.

**Comment by damaru2** [comment]
Mmmhh I tried adding a rule below but it wasn't working. Could it be because of the following? I had the to_if_alone -> escape then it matched that rule and then karabiner considered that it didn't need to see more rules but I had below the second rule which specified what to do when it is not pressed alone. If so, there is no way currently in which I can do that. Summary of my desired behavior:
```
caps_lock to ->
 left_control if pressed with another key in terminal
 left_command if pressed with another key outside of the terminal
escape if pressed alone.
```

**Comment by damaru2** [comment]
oh, it seems it was failing because instead of having both things inside the manipulators I had them in two separate rules
