### ISSUE TITLE
Touchbar is broken, how to remap fn + numeric keys for media control?

### ISSUE THREAD

**Issue by neodeo2** [pqrs-org/Karabiner-Elements#2407]
Hello,

my touchbar is broken. I want to remap the number keys to F Keys.
so i imported the rule "Fn+numeric keys to the F keys".

if i press "fn + 1" the karabiner - event viewer show me the right function = f1
but i want, that the result is = display brightness decrement. And this is not working.

can you explain how can i remap my fn + numeric keys for media control? (volume increment...)

thx

**Comment by babygau** [comment]
go to preference > keyboard shortcut> display to see which shortcuts are remaped to display brightness. chances are they are mapped to different shortcut

**Comment by neodeo2** [comment]
the are't different shortcuts. The MacOS Catalina is just new installed.

i tried external Keyboard, and the are working fine.

and i tried this one, but it doesn't work:
https://karabiner-elements.pqrs.org/docs/help/troubleshooting/kext-allow-button-does-not-work/

**Comment by babygau** [comment]
you could change your key to the following in `to event`

here is the [ref](https://github.com/pqrs-org/Karabiner-Elements/blob/141f74a4bf5e40bf9581d2035875e0698fa15ebd/src/apps/PreferencesWindow/Resources/simple_modifications.json#L607)
```
"consumer_key_code": "display_brightness_decrement"
"consumer_key_code": "display_brightness_increment"
"

**Comment by neodeo2** [comment]
thx i installed other rules:

fc660c Volume Rules fn+ up/down and
focusaperture control fn +command + up/down

thx for HELP :-)
