### ISSUE TITLE
Odd ACL / permission problems on remnants even on backup volumes?

### ISSUE THREAD

**Issue by ylluminate** [pqrs-org/Karabiner-Elements#2409]
Here is a peculiarity here that shouldn't be the case: When I have a backup of the system volume on another drive and attempt to remove some files that belong to Karabiner, they will not delete:

```
root@hostname /Volumes # rm -fr hostname_system_backup/private/var/folders/zz/zyx6234q6csfxvn_n0000000000000/T/.cs.ecfm.temp.dir.r5RRJZU/private/var/folders/zz/zyxyyzvq6csfxvn_n0000000000000/T/.cs.ecfm.temp.dir.r1RRJVU/Applications/Karabiner-EventViewer.app/Contents
rm: hostname_system_backup/private/var/folders/zz/zyx6234q6csfxvn_n0000000000000/T/.cs.ecfm.temp.dir.r5RRJZU/private/var/folders/zz/zyxyyzvq6csfxvn_n0000000000000/T/.cs.ecfm.temp.dir.r1RRJVU/Applications/Karabiner-EventViewer.app/Contents: Operation not permitted
```

Even after executing the following to strip ACLs / extended attributes, I still cannot `rm -fr` the folders:
```
sudo chmod -RN /Volumes/hostname_system_backup/private/var/folders/...
sudo xattr -c -r /Volumes/hostname_system_backup/private/var/folders/...
```

And 
```
sudo ls -leah -@ /Volumes/hostname_system_backup/private/var/folders/...
```
doesn't show any attributes left...

Additionally, uninstalling Karabiner Elements entirely and unloading the kext still doesn't help (and shouldn't since this is not on the system volume from whence it was loaded).  

What permission issue could be going on here?  Is there another way to strip ACLs / extended attribs beyond this?  Are there some permissions not showing up with the `ls` command above?

**Comment by tekezo** [comment]
Use chflags.

```shell
chflags nouchg,noschg Karabiner-Elements.app
chflags nouchg,noschg Karabiner-EventViewer.app
```

**Comment by ylluminate** [comment]
Thanks that seems to have solved the issue.
