### ISSUE TITLE
UK PC keyboard backslash problem

### ISSUE THREAD

**Issue by briandipalma** [pqrs-org/Karabiner-Elements#2412]
I have a UK PC keyboard and MacOS is unable to correctly handle the backslash/Grave Accent keys on the left hand side of the keyboard. Specifically it swaps them with each other.

Karabiner fixes the issue when they are pressed on their own:

```
       {
          "from": {
            "key_code": "grave_accent_and_tilde"
          },
          "to": {
            "key_code": "non_us_backslash"
          }
        }
```

but when used with control it doesn't seem to work.

I'm guessing I've made a mistake in my JSON config but I can't spot it. Anyone any idea?

```
         {
            "description": "Fix backslash",
            "manipulators": [
              {
                "from": {
                  "key_code": "grave_accent_and_tilde",
                  "modifiers": {
                    "mandatory": ["control"]
                  }
                },
                "to": [
                  {
                    "key_code": "non_us_backslash",
                    "modifiers": ["control"]
                  }
                ],
                "type": "basic"
              }
            ]
          }
```

I use this key combo for tmux.

**Comment by briandipalma** [comment]
I wonder if https://github.com/pqrs-org/Karabiner-Elements/issues/2352 is in someway linked?

**Comment by MuhammedZakir** [comment]
1. If you do not add modifiers in 'from' event, Karabiner will ignore it if you press *any* modifier key.
2. If you add `optional` modifier, Karabiner will ignore it if you press any modifier *not* mentioned in `optional`.
3. If you add `mandatory` modifier, Karabiner will manipulate that event *only* if *all* modifiers in mandatory is pressed.

So in your first config, it won't work if you press any modifier key. In second one, it will *only* work if you press control key. 

1. Works will all modifiers

```json
{
          "from": {
            "key_code": "grave_accent_and_tilde"
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": {
            "key_code": "non_us_backslash"
          }
        }
```

2. If control key is optional


```json
{
          "from": {
            "key_code": "grave_accent_and_tilde"
            "modifiers": {
              "optional": ["control"]
            }
          },
          "to": {
            "key_code": "non_us_backslash"
          }
        }
```

3. If `grave_accent_and_tilde` and `control` is pressed together, `non_us_backslash` and `control` is send. If `grave_accent_and_tilde` is pressed alone, send `non_us_backslash`.
```json
{
          "from": {
            "key_code": "grave_accent_and_tilde"
            "modifiers": {
              "mandatory": ["control"]
            }
          },
          "to": {
            "key_code": "non_us_backslash",
            "modifiers": ["control"]
          }
          "to_if_alone": [
            {
              "key_code": "non_us_backslash"
            }
          ]
}
```

4. You can mix 'optional' and 'mandatory'
```json
{
          "from": {
            "key_code": "grave_accent_and_tilde"
            "modifiers": {
              "mandatory": ["control"],
              "optional": ["caps_lock"]
            }
          },
          "to": {
            "key_code": "non_us_backslash",
            "modifiers": ["control"]
          }
          "to_if_alone": [
            {
              "key_code": "non_us_backslash"
            }
          ]
}
```

**Comment by briandipalma** [comment]
Thanks for the response. I'll give some of those a shot when I'm back at my work machine on Monday.

**Comment by marko999** [comment]
> ```
>   19                         "description": "Fix backslash",
>   20                         "manipulators": [
>   21                             {
>   22                                 "from": {
>   23                                     "key_code": 100,
>   24                                     "modifiers": {
>   25                                         "mandatory": [
>   26                                             "control"
>   27                                         ]
>   28                                     }
>   29                                 },
>   30                                 "to": {
>   31                                     "key_code":  "non_us_backslash",
>   32                                     "modifiers": [
>   33                                         "control"
>   34                                     ]
>   35                                 },
>   36                                 "type": "basic"
>   37                             }
>   38                         ]
>   39                     },
>   40                     {
>   41                         "description": "Fix grave accent",
>   42                         "manipulators": [
>   43                             {
>   44                                 "from": {
>   45                                     "key_code": 53,
>   46                                     "modifiers": {
>   47                                         "mandatory": [
>   48                                             "control"
>   49                                         ]
>   50                                     }
>   51                                 },
>   52                                 "to": {
>   53                                     "key_code": "grave_accent_and_tilde",
>   54                                     "modifiers": [
>   55                                         "control"
>   56                                     ]
>   57                                 },
>   58                                 "type": "basic"
>   59                             }
>   60                         ]
>   61                     }
> ```

This still doesn't work for me on macbook pro m1, Monterey 12.5
