### ISSUE TITLE
Cannot move left command to fn

### ISSUE THREAD

**Issue by emarcus-mavenoid** [pqrs-org/Karabiner-Elements#2413]
**My setup**

Three simple rules 

1. left_command -> fn
2. left_control -> left_command
3. fn -> left_control 

New macbook air with US input source on ISO nordic layout.

**The result**

1. left_command works as left_control (expected)
2. left_option doesn't work anymore, i.e. nothing happens when it's pressed (unexpected)
3. left_control words like left_command (unexpected)
4. neither fn nor left_control work like fn (unexpected)

If the third rule is omitted, then fn works like fn.

Simply switching left_command and fn seems to work.

**Comment by MuhammedZakir** [comment]
It's working for me! Are you using Catalina or Big Sur? Currently, Karabiner is incompatible with them.

**Comment by emarcus-mavenoid** [comment]
I guess that explains it, I'm using Catalina. Thanks for your fast reply!
