### ISSUE TITLE
Will Not Activate

### ISSUE THREAD

**Issue by tjluoma** [pqrs-org/Karabiner-Elements#2421]
_Report from Big Sur public beta 20A5364E (latest public beta as of 2020-09-09)_

Karabiner seems to be in some kind of crashing loop.

Here is a screenshot of the log:

<img width="1415" alt="karabiner-big-sur" src="https://user-images.githubusercontent.com/26965/92628180-69139d80-f29a-11ea-8011-c8784df39fc8.png">

Those error messages just keep repeating.

Here's a [Screencast](https://www.dropbox.com/s/54y10jjmorzumba/Karabiner-2020-09-09-at-12.41.49-PM.mov?dl=0) of the log next to macOS' preference pane for the keyboard.

You can see that the dropdown for an alternative keyboard appears very _very_ briefly as it flashes in the System Preferences window. I believe this shows that it is activating, but then immediately crashing.

I have tried rebooting my Mac and I have uninstalled and reinstalled Karabiner Elements.

**Comment by tekezo** [comment]
Thank you for feedback!
I released new version (12.93.0) which fixed a bug. Please confirm it.
https://karabiner-elements.pqrs.org/docs/macos-big-sur/

**Comment by lbibass** [comment]
> Thank you for feedback!
> I released new version (12.93.0) which fixed a bug. Please confirm it.
> https://karabiner-elements.pqrs.org/docs/macos-big-sur/

Confirmed to work on MacOS Big Sur Beta 6! Thanks so much!

**Comment by tjluoma** [comment]
Yes! This works. Thank you very much.
