### ISSUE TITLE
Legacy System Extension

### ISSUE THREAD

**Issue by rcanu** [pqrs-org/Karabiner-Elements#2422]
![image](https://user-images.githubusercontent.com/3313421/92678118-d5080b80-f357-11ea-8392-7bd0e3ba4844.png)
I'm using macOS Catalina 10.15.6

**Comment by tekezo** [comment]
There is an experiment build (v12.93.0) of Karabiner-Elements which is migrated to new DriverKit system from legacy system extensions.
https://karabiner-elements.pqrs.org/docs/macos-big-sur/

**Comment by rcanu** [comment]
Got it thanks!!!
