### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by successc** [pqrs-org/Karabiner-Elements#2424]
![image](https://user-images.githubusercontent.com/14857513/93165140-dbc6c200-f74d-11ea-85bb-3a86e54486fb.png)

**Comment by tekezo** [comment]
I cannot read the error message of hdiutil.
Could you put the message as plain text or English.

**Comment by successc** [comment]
......................................................................
......................................................................
......................................................................
......................................................................
...
Copy Files
Skip codesign
Create pkg
pkgbuild: Reading components from pkginfo/pkgbuild.plist
pkgbuild: Adding component at Applications/Karabiner-Elements.app
pkgbuild: Adding top-level preinstall script
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to Karabiner-Elements-12.93.1/Installer.pkg
productbuild: Wrote product to Karabiner-Elements-12.93.1/Karabiner-Elements.pkg
Sign with Developer ID
productsign: error: Could not find appropriate signing identity for “”.
Make Archive
hdiutil: create failed - 无可装载的文件系统
chmod: Karabiner-Elements-12.93.1.dmg: No such file or directory
make: *** [package] Error 1

**Comment by successc** [comment]
hdiutil: create failed - No mountable file system

**Comment by tekezo** [comment]
Thank you for information!

I cannot reproduce this issue, unfortunately.
Did you clone the repository info the external disk which is not APFS?
If so, move the file to the internal disk.

**Comment by successc** [comment]
yes ,  you are right
i place the another disk ,it's ok
