### ISSUE TITLE
esc key not working, only fn + esc.

### ISSUE THREAD

**Issue by mercurius0610** [pqrs-org/Karabiner-Elements#2433]
My mac is  MacBook Pro (15-inch, 2017). mac os is Catalina 10.15.6 .
After I install karabiner. Esc key always suddenly not working. But fn + esc is work. And I can  capture esc key  using karabiner-EventViewer. I tried to find some solutions in the community, such as bound escape to escape and  kill Siri process. but it does not work for me, please help me.

**Comment by mercurius0610** [comment]
Sorry, I found the problem, esc key was occupied by another app.

**Comment by subhodynamics** [comment]
how was this issue solved? I am facing the same.
