### ISSUE TITLE
Security & Privacy error on Big Sur

### ISSUE THREAD

**Issue by matisiekpl** [pqrs-org/Karabiner-Elements#2443]
Hello.
I'm installing Karabiner Elements 13.0.0 on Big Sur 20A5364e (Hackintosh setup with OpenCore and i5-4460, nvidia gt 710) and getting following error (message is in Polish, translated: "Error: There was an error in Security & Privacy preferences") :
![Zrzut ekranu 2020-10-4 o 16 25 59](https://user-images.githubusercontent.com/21008961/95018181-50f72a00-065e-11eb-9844-1191dc4161b7.png).
What can I do with this error?
I remember, that I've attempted to install old Karabiner Elements some time ago (which was not working, that time I read about missing support for Big Sur), but I've uninstalled it via button in app.

**Comment by tekezo** [comment]
This instruction might help you.
https://github.com/pqrs-org/Karabiner-Elements/issues/2331#issuecomment-689975776

**Comment by matisiekpl** [comment]
Everything works at Big Sur beta 9 update (20A5384c), closing...
