### ISSUE TITLE
restore initial mac factory configuration

### ISSUE THREAD

**Issue by iulian0512** [pqrs-org/Karabiner-Elements#2451]
hi, how can i reset the key configuration to factory defaults ? it is really messed up and its very hard to use my mac now, i uninstalled karabiner but i am stuck with the altered config. please help. mac os x catalina.

**Comment by tekezo** [comment]
Karabiner-Elements is not related if you uninstalled Karabiner-Elements from uninstaller.
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

It you did not used the built-in uninstaller, install Karabiner-Elements again, and uninstall it.

I guess your key is changed by another app.
It is useful to create new user to provide a clean environment to investigate the cause.
https://support.apple.com/guide/mac-help/set-up-other-users-on-your-mac-mtusr001/mac
