### ISSUE TITLE
Unable to modify keys for Microsoft Ergonomic Keyboard LXM-00001

### ISSUE THREAD

**Issue by alexpersian** [pqrs-org/Karabiner-Elements#2460]
I'm currently observing an issue with the new ergonomic keyboard from Microsoft where it isn't possible to edit the keys through Karabiner Elements. The keyboard shows up but is unselectable. I searched through recent issues to see if anyone else has encountered this but was unable to find anything specific to this keyboard. The wireless version of the ergonomic I was using before was recognized fine.

Here are some screenshots to show the behavior.
![image](https://user-images.githubusercontent.com/5446451/96018177-eb9ef800-0e18-11eb-9e43-c216638fccd2.png)

And here is the eventviewer showing details of the keyboard.
![image](https://user-images.githubusercontent.com/5446451/96018219-f8235080-0e18-11eb-821d-0ecbf8418b1a.png)

Thanks.

**Comment by MuhammedZakir** [comment]
Is modifications enabled for this device in `Preferences > Devices > Basic configuration`?

**Comment by alexpersian** [comment]
🤦 thanks, that is what I was missing. Closing this issue.

**Comment by LunaticoCR** [comment]
@alexpersian out of interest, I presume you referred to [this keyboard](https://www.microsoft.com/en-ie/p/microsoft-ergonomic-desktop/926gk79b71v9?activetab=pivot%3aoverviewtab) right?
Where you able to map all of its extra keys? (media, search, office, emoji, etc) I'm about to buy this keyboard and I'm curious if I'll be able to map all those extra keys with karabiner.

**Comment by kambala-decapitator** [comment]
@LunaticoCR it's this keyboard https://www.microsoft.com/en/accessories/products/keyboards/microsoft-ergonomic-keyboard?activetab=pivot:overviewtab (your link is dead)

just got it and trying to configure on macOS 12 + Karabiner v14.12. My observations so far:

- calculator and player/sound controls work out of the box
- the button between sound and player controls is invisible to Karabiner (not sure what it should do on Windows, open player perhaps)
- the "context menu" button is `application` in Karabiner
- the "programmable" 1-2-3 buttons (in top left) are simply Cmd+1 / Cmd+2 / Cmd+3
- the Office button is [left] Cmd+Alt+Shift+Ctrl
- the Emoji button is [left] Cmd+Alt+Shift+Ctrl+Space
- the Search button is rShift+lCmd+F21
- the Snap button is Cmd+Shift+s
- the "apps overview" button (Windows version of Mission Control) is Cmd+Tab
- the Lock button is Cmd+L

**Comment by LunaticoCR** [comment]
Yes, exactly that keyboard @kambala-decapitator . I have since bought two (home and office) and have the following complex modifications configured, and works great.
![image](https://user-images.githubusercontent.com/2124383/232470163-7b322da2-b420-4c67-9c06-2add9e26bd40.png)

**Comment by kambala-decapitator** [comment]
@LunaticoCR thanks! And your keys by default behave the same as for me?

btw so far I configured only Search->Spotlight and application->Globe. and [successfully] tested configuring Emoji key to open Emojis via BTT.

also opened issue about the undetectable "player" button: #3453

**Comment by LunaticoCR** [comment]
Yes they behave just as you describe @kambala-decapitator . Here's my complex modifications json file in case it helps you or anyone else stumbling upon this issue.
[Microsoft_Ergonomic_Desktop.json.zip](https://github.com/pqrs-org/Karabiner-Elements/files/11250505/Microsoft_Ergonomic_Desktop.json.zip)

**Comment by LunaticoCR** [comment]
Works for me @kambala-decapitator . I'm able to download the zip file on other browsers. Direct link is:
```
https://github.com/pqrs-org/Karabiner-Elements/files/11250505/Microsoft_Ergonomic_Desktop.json.zip
```

![image](https://user-images.githubusercontent.com/2124383/232538115-4619ed2a-c073-4076-8d55-8d4d3d142c18.png)

**Comment by LunaticoCR** [comment]
Oh that sucks! Sorry! Here you go.
[Microsoft_Ergonomic_Desktop.json.zip](https://github.com/pqrs-org/Karabiner-Elements/files/11252726/Microsoft_Ergonomic_Desktop.json.zip)

**Comment by kambala-decapitator** [comment]
now it's good, thanks a lot!

**Comment by eddified** [comment]
@LunaticoCR great work! I, too, have the same keyboard and have noticed the same mappings that you described here.
