### ISSUE TITLE
eject mapping works for Simple Modifications but not for Complex

### ISSUE THREAD

**Issue by PicoNano** [pqrs-org/Karabiner-Elements#2480]
Hi there 

I'm kind of new to Github so apologies if it's a breach of etiquette to open a new issue when an identical issue exists that's "gone stale"… 

My problem is identical to [this one](https://github.com/pqrs-org/Karabiner-Elements/issues/1681#issue-394472311). That is I can remap **"eject"** to some other key using simple modifications, but if I try do something complex it doesn't work. This is what I'm trying to achieve:

```
{
    "description": "Change caps_lock to command+control+option.",
    "manipulators": [
        {
            "from": {
                "key_code": "eject",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_command",
                    "modifiers": [
                        "left_control",
                        "left_option"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
},
```

Any help?

**Comment by MuhammedZakir** [comment]
Try changing `"key_code": "eject"` to `"consumer_key_code": "eject"`.

---

For me, on Mojave on MacBook Pro, Karabiner-Elements(v. 12.10.1) does not detect `eject` key. Neither simple modification nor complex modification works. Are you perhaps using an external keyboard?

**Comment by PicoNano** [comment]
Awesome, this worked perfectly , thanks for your help 💙
