### ISSUE TITLE
Asked to permit software from "Placeholder Developer"

### ISSUE THREAD

**Issue by iay** [pqrs-org/Karabiner-Elements#2483]
I have a couple of machines, both running macOS 10.5.7 and both previously running 13.0.0.

One machine upgraded to 13.1.0 in the expected way: when activating the new driver, an "Allow" button showed up and I was asked to authenticate the extension with the expected name.

The other machine has a number of drivers blocked. In this case, when I clicked on the "Allow" button in preferences, I was given a list of extension _developers_ instead of extension _names_. The Karabiner driver turned out to be the one labelled "Placeholder Developer", but I wasn't really happy clicking on that as it wasn't obviously what I wanted.

I'm guessing there's a field missing in a properties file somewhere or in the XCode configuration for the project.

**Comment by Mathijs-Bakker** [comment]
Same here

**Comment by tekezo** [comment]
https://github.com/pqrs-org/Karabiner-Elements/issues/2446#issuecomment-704625781
