### ISSUE TITLE
Developer shows up as Placeholder Developer in Security & Privacy Blocked

### ISSUE THREAD

**Issue by brian-nelson** [pqrs-org/Karabiner-Elements#2489]
The instructions mention Karabiner-DriverKit-VirtualHIDDevice, but the app shows up as Placeholder Developer.

I uninstalled and reinstalled several times to verify that this was Karabiner.

![Screenshot_10_31_20__10_01_AM](https://user-images.githubusercontent.com/8483547/97783939-a55bcf80-1b60-11eb-89c3-b3bda7c2270d.png)

My machine is running macOS Catalina, 10.15.7

**Comment by MuhammedZakir** [comment]
https://github.com/pqrs-org/Karabiner-Elements/issues/2446#issuecomment-704625781

**Comment by tekezo** [comment]
https://karabiner-elements.pqrs.org/docs/help/troubleshooting/placeholder-developer/
