### ISSUE TITLE
After the newest update, karabiner doesn't start anymore

### ISSUE THREAD

**Issue by yspreen** [pqrs-org/Karabiner-Elements#2490]
I noticed my keybindings were wrong. When I tried to check in the karabiner menu, I quickly learned that the app doesn't start anymore. In spotlight it says version 13.1.0. Neither the menu nor app open. The menubar item is gone too. I used the auto-updater.

**Comment by yspreen** [comment]
re-downloaded the installer, ran it again, it opened again.

The error I got was about an outdated driver. It told me to deactivate it and reboot. Afterward, everything works fine now.

**Comment by tekezo** [comment]
Sorry for inconvenience.

The manual driver update is required at the v13.1.0 update due to a limitation of macOS.
I avoid such manual update as possible in future updates.
