### ISSUE TITLE
Less/greater than

### ISSUE THREAD

**Issue by vasco-santos** [pqrs-org/Karabiner-Elements#2492]
Hey folks!

Really appreciate this project but with a mixture between latest MAC OS Catalina (10.15.7) and latest Karabiner (13.1.0) my previous configuration disappeared. I just used a simple mapping for my US external keyboard of:

- § => <
- ± => >

I could find the `grave_accent_and_tilde` + `non_us_backslash`, but the less/greater than key names do not exist anymore, or have a different name? I configured them in the past, but I could not manage to find them again.

Any help would be really helpful

**Comment by MuhammedZakir** [comment]
You will have to use complex modification to do that. Map
* `§`  to  `shift + comma`
* `±`  to  `shift + period`

**Comment by vasco-santos** [comment]
Thanks @MuhammedZakir !
