### ISSUE TITLE
Question: map 1 key to a control sequence?

### ISSUE THREAD

**Issue by Chris-Leeworthy** [pqrs-org/Karabiner-Elements#2499]
Hi this is a request for help rather than an issue I guess.  First off, thank you for a really useful application!

I'm running Karabiner-Elements 13.1.10 on Catalina 10.15.7.

I want to map a single key (keypad 0 for example) to do `Control-l` so I can have a single key to do terminal clear screen.

As I'm already using Karabiner-Elements to remap my caps-lock key to something useful, I thought it might be able to do this too, but I cannot find a way to do it.

Is there a way to do it, or is that not what Karabiner-elements is intended for?

**Comment by MuhammedZakir** [comment]
You will have to use complex modification for that. E.g.

```json
{
  "title": "keypad 0 -> ctrl+l",
  "rules": [
    {
      "description": "Keypad 0 -> ctrl+l",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "keypad_0",
            "modifiers": {
              "optional": ["caps_lock"]
            }
          },
          "to": [
            {
              "key_code": "l"
              "modifiers: ["control"]
            }
          ]
        }
      ]
    }
  ]
}
```

To learn, look at the document and other users' complex modifications.

* https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-complex-modifications/
* https://karabiner-elements.pqrs.org/docs/json/
* https://ke-complex-modifications.pqrs.org/ (site shown in 1st link - download/view others' modifications)

**Comment by Chris-Leeworthy** [comment]
That is brilliant!  Thank you for such a quick response.
