### ISSUE TITLE
Use of Keychron K2 ISO UK on MacOS Catalina

### ISSUE THREAD

**Issue by fatlazycat** [pqrs-org/Karabiner-Elements#2509]
Hi, using karabiner elements with a Keychron K2 ISO UK keyboard that turns up as unknown in karabiner elements.

The keys §± and `~ are swapped when running Karabiner elements. All other keys appear fine, such as £.

The only modification I'm using in KE is a complex -> change caps lock to command+control+option+shift

If I quit KE then the keyboard is correct.

Any ideas ?

Thanks

**Comment by MuhammedZakir** [comment]
Try https://github.com/pqrs-org/Karabiner-Elements/issues/1426#issuecomment-395689803. If it does not work, use EventViewer [1] to get the key code and swap them.

[1] `Karabiner-Elements Menu > Launch EventViewer` or Karabiner-EventViewer.app

**Comment by fatlazycat** [comment]
@MuhammedZakir Great thanks, worked perfectly. Thanks again !
