### ISSUE TITLE
Key combination working on built-in but not on Magic Keyboard (Wireless)

### ISSUE THREAD

**Issue by esimioni** [pqrs-org/Karabiner-Elements#2515]
This issue is very odd.
After many years using only the Macbook pro built in keyboard I have recently purchased an Apple Magic Keyboard (Model A1644).

There is a key combination that I use very often (software developer here): `Cmd + Shift + T`
That specific combination doesn't work on the wireless keyboard, but works on the built-in keyboard.
Another similar combination `Cmd + Shift + R` works on both!

Here are the event viewer results:

**Working (`Cmd + Shift + R`)**

Event type | Code | Name | Misc
---------- | ---- | ---- | ----
type:key_down    |    code:227   |     name:left_command  |  misc:flags left_command
type:key_down      |  code:225   |     name:left_shift   |   misc:flags left_command,left_shift
type:key_down     |   code:21    |     name:r        |       misc:flags left_command,left_shift
type:key_up       |   code:21       |  name:r          |     misc:flags left_command,left_shift
type:key_up      |    code:225     |   name:left_shift  |    misc:flags left_command
type:key_up      |    code:227    |    name:left_command  |  misc:

**Not working (`Cmd + Shift + T`): The key up and down in the middle are logged when I press `T` while holding `Cmd + Shift`**

Event type | Code | Name | Misc
---------- | ---- | ---- | ----
type:key_down      |    code:227     |     name:left_command   |   misc:flags left_command
type:key_down     |     code:225     |     name:left_shift    |    misc:flags left_command,left_shift
type:key_up        |    code:227     |     name:left_command   |   misc:flags left_shift
type:key_down     |     code:227     |     name:left_command   |   misc:flags left_command,left_shift
type:key_up       |     code:225    |      name:left_shift    |    misc:flags left_command
type:key_up      |      code:227      |    name:left_command   |   misc:

My configuration is targeting all devices, I didn't change anything after installing the wireless keyboard and I didn't try to assign keyboard specific configurations.

I'm on Big Sur 11.0.1 (20B29) and Karabiner Elements 13.1.1.

**Comment by MuhammedZakir** [comment]
I doubt this is a ghosting issue, but just in case, see if `t` is actually detected in `command+shift+t`.

https://drakeirving.github.io/MultiKeyDisplay/

**Comment by esimioni** [comment]
It is not detected, the behavior is the same as in the Event Viewer. When I press `t` it "releases" `command`, when I release `t` it shows `command` as pressed again, without ever releasing the actual `command` key.
When pressing `t` alone or with `shift` only it is detected normally (couldn't tell for `command + t` since it opens a browser tab).

**Comment by MuhammedZakir** [comment]
> It is not detected, the behavior is the same as in the Event Viewer. When I press `t` it "releases" `command`, when I release `t` it shows `command` as pressed again, without ever releasing the actual `command` key.
> When pressing `t` alone or with `shift`, it is detected normally (couldn't tell for `command + t` since it opens a browser tab).

You tried it without running Karabiner-Elements, right? If so, this is obviously something to do with the keyboard. Maybe it's faulty?

Have you tried `command+shift` with other keys instead of `t`? Is `command` the only key with problem? Have you tried `option/alt`, 'control` and `shift` (and `fn`, if you have one)?

P.S. If `command+t` open a new tab, that means it's working. :-)

**Comment by esimioni** [comment]
All other combinations I've tried so far are working normally, the problem is just `Cmd + Shift + T`

I have tried with Karabiner-Elements running, how can I try without it? I've tried now "Misc -> Quit Karabiner-Elements", but a simple test shows that my modifications are still being applied.
Do I have to uninstall it?

**Comment by esimioni** [comment]
I've made a lot of tests and it seems to be a ghosting issue with this specific keyboard model.

The problem happens when the physical keys `fn + left_shift + t` are pressed. With or without remappings, with or without Karabiner-Elements running.
No other combinations that I have tested have problems, including `fn + right_shift + t` or `fn + left_shift + <any number or letter>`.
Normally I have a modification `fn -> left_command` in place, that is why I initially thought it was related to the `left_command + left_shift + t` combination.
I tried with the built-in (ok) and with 2 Apple Magic Keyboards: Model A1644, problematic and model A1843, which works (they have `fn` keys in very different physical places).
The MacOS keyboard viewer helped a lot with the tests.

For now I'm giving up, even tried SMC and NVRAM resets (more than once).

Although the issue apparently has no relation whatsoever to Karabiner-Elements, I've found 2 unrelated issues in my tests:

1. When using the "Quit Karabiner-Elements" button "Function keys" and "Complex modifications" are gone, but "Simple modifications" remain in place.

2. Complex modifications list of rules in the UI shows only one rule, although I have 10 in the JSON, all of which are working properly.

If anyone with the same problem stumbles upon this thread and later finds a solution, please reply here or contact me, I'd love to have this shortcut back.

**Comment by MuhammedZakir** [comment]
I saw your reply, but I hadn't been able to use Mac for a while now and so can't do any tests. Sorry about that. I'll reply when I can access Mac and if nobody else has done it. :-)

>   *--snip--*
>     2. Complex modifications list of rules in the UI shows only one rule, although I have 10 in the JSON, all of which are working properly.
>  *--snip--*

UI will only show "title" and "description" of each rule. You probably added all the rules in 1 manipulator. If so, just split that into different rules.

```json
{
  "title": " shown ",
  "rules": [
    {
      "description": " shown ",
      "manipulators": [
        {
          "description": "not shown",
          ...
        }
      ]
    },
    {
      "description": " shown ",
      "manipulators": [{}]
    }
  ]
}
````

**Comment by esimioni** [comment]
In case anyone has this problem in the future, it is 100% confirmed that is a keyboard hardware issue.
I've switched to the new Magic Keyboard (with touch ID) and the problem is gone.
