### ISSUE TITLE
Only Working with Bluetooth Keyboard, not with USB

### ISSUE THREAD

**Issue by llaehn** [pqrs-org/Karabiner-Elements#2522]
Hi,

i have a Magic Keyboard and a USB Keybo ard (Cherry KS6000 Mac).
I would use the Cherry keyboard and the F Keys only work with Fn key.
I installed Karabiner Key and try to remap the F Keys but it doesnt work.

I try to reconnect my magic Keyboard and here the remapping works fine.

Why not with the usb keyboard?

br
lars

**Comment by MuhammedZakir** [comment]
Most keyboards do not send `Fn` key code, they map `Fn+Fx` internally and send the resulting key code. You can use EventViewer to check if KarabinerElements detect your keyboard's `Fn` key. See https://github.com/pqrs-org/Karabiner-Elements/issues/2371.

**Comment by llaehn** [comment]
Yes, you are right.
The fn key don't fire an event.
only on the bluetooth keyboard works the fn key as aspected.

thanks for your help

**Comment by MuhammedZakir** [comment]
You are welcome! Please close the issue if it's solved. :-)
