### ISSUE TITLE
Please update security policy

### ISSUE THREAD

**Issue by mozbeksymphony** [pqrs-org/Karabiner-Elements#2526]
https://github.com/pqrs-org/gh-pages-karabiner-elements.pqrs.org/security/policy is missing, is there a platform where security issues and vulnerabilities can be reported?

**Comment by tekezo** [comment]
Thank you for feedback!

I added a mail address to report vulnerabilities.
https://github.com/pqrs-org/gh-pages-karabiner-elements.pqrs.org/security/policy

**Comment by mozbeksymphony** [comment]
Thank you @tekezo!
