### ISSUE TITLE
How to Restrict a Complex Modification to a Particular Keyboard

### ISSUE THREAD

**Issue by Muirium** [pqrs-org/Karabiner-Elements#2529]
Seeing as I can't find this in the complex modifications documentation, I'll ask here.

What I'm trying to do is modify (and restore) the backslash key *only* on my MacBook Air's built in ISO UK keyboard. I'm used to American layout and I keep hitting that pesky \ when I mean to hit Return! I reassigned it to Enter (on the nonexistent keypad) using Karabiner's simple modifications feature. But what about when I really do need to hit backslash?

What I've done is make the following complex modification, which works well enough:

                    {
                    	                        "description": "Right Option + Backslash ⇨ Backslash",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "keypad_enter",
                                    "modifiers": {
                                        "mandatory": [
                                            "right_option"
                                        ],
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "backslash"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }

When I really want to press \ I just hold right Option. But here's the question: how do I limit this to just my built in keyboard? I use a bunch of mechanical keyboards too, and don't want to interfere with their ANSI layouts. So this modification while sweet on my laptop's built in keyboard will trip me up when I hook them up. I want to have Karabiner apply it smartly, just like it already does for simple modifications.

Hoping there's a bit of code I need to add to achieve this effect. Or else this issue is a feature request after all!

**Comment by MuhammedZakir** [comment]
https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/

**Comment by Muirium** [comment]
Ooh, nice one!

I might try it with `device_if` so I can limit it to strictly my [Mac's internal keyboard](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/). But you're right to point out the ISO trigger itself. 

I have a few ISO mechanical keyboards as well as my beloved ANSI ones, and I haven't noticed myself making the same backslash mistake on them before. Great to know Karabiner has the tools I need to fix my own mistakes!
