### ISSUE TITLE
Uninstall is a pain

### ISSUE THREAD

**Issue by n13** [pqrs-org/Karabiner-Elements#2530]
Please don't lock up the app like this

I had found and deleted the kext for Karabiner because it caused CPU issues in Big Sur - it causes kernelmanagerd to spike the CPU.

I had totally forgotten I installed this app but I found the kernel extension and deleted it

Later I tried to delete the app but it's locked, and spent a huge amount of time trying to unlock and delete it.

That's bad behavior, almost like malware.

I know the intentions were good and there was an uninstall script, but I had deleted that uninstall script when I deleted the extensin. 

So the only way I could delete it is eventually, reinstall the app, uninstall the app from within the app, and reboot. 

Not exactly user friendly.

**Comment by tekezo** [comment]
https://karabiner-elements.pqrs.org/docs/help/advanced-topics/lock-icon/#why-these-files-are-protected
