### ISSUE TITLE
Double tap to escape

### ISSUE THREAD

**Issue by giallu** [pqrs-org/Karabiner-Elements#2532]
I am trying to add a modification to emit Escape when I double tap the tilde key (on 60% keyboards this is often the same key, and I really need to have both handy).
I am not sure why this does not work, I also tried with an approach based on "from.simultaneous" but the result is the same: it seems karabiner always interpret a single press as a multi press, triggering the event so I am reporting this in the hope someone could confirm is this is a bug/missing feature or just me not understanding how it works :)

```{
      "description": "60% keyboards: Esc with double tap",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "grave_accent_and_tilde",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "escape"
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "tilde pressed",
              "value": 1
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "grave_accent_and_tilde",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "tilde pressed",
                "value": 1
              }
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "tilde pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "tilde pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    },
```

**Comment by MuhammedZakir** [comment]
Your complex modification seems correct. I suspect this is happening probably because when you experimented with it, you have set variable `tidle pressed` to `1`, and didn't set it to `0` when you were done. So when you press `tilde`, the first manipulator catches it and emits `escape`, but it never sets the variable to `0` as it's done by second manipulator. So you will only get `escape` when you press `tilde`. 

You can check if this is indeed the problem using `EventViewer > Variables` [1] and if it is, you can fix it either by restarting Karabiner-Elements (iirc), or using Karabiner cli [2] - `karabiner_cli --set-variables '{"tidle pressed":0}'`.

[1] `Karabiner-EventViewer.app` or `Karabiner-Elements menu > Launch EventViewer`.
[1] https://karabiner-elements.pqrs.org/docs/manual/misc/command-line-interface/

---

I think your modification does not work as you indented as it does not send `grave_accent_and_tilde` when you press it alone.

**Comment by giallu** [comment]
You are right on both accounts: I did reset the variable that was stuck on 1 (by the way, isn't it more failproof if I add another set_variable  to zero when I emit the `escape`?) and now the double tap works, but I am not able to get the `grave_accent_and_tilde` event... should I be able to add it here in the same modification?

**Comment by MuhammedZakir** [comment]
Depending on how fast you (can) type, you should fine tune `parameters.basic.to_delayed_action_delay_milliseconds`.

```json
{
  "description": "Tilde: double tap -> escape, single tap -> tilde",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "grave_accent_and_tilde",
        "modifiers": {
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "key_code": "escape"
        }
      ],
      "to_after_key_up": [
        {
          "set_variable": {
            "name": "tilde pressed",
            "value": 0
          }
        }
      ],
      "conditions": [
        {
          "type": "variable_if",
          "name": "tilde pressed",
          "value": 1
        }
      ]
    },
    {
      "type": "basic",
      "parameters": {
        "basic.to_delayed_action_delay_milliseconds": 250
      },
      "from": {
        "key_code": "grave_accent_and_tilde",
        "modifiers": {
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "set_variable": {
            "name": "tilde pressed",
            "value": 1
          }
        }
      ],
      "to_delayed_action": {
        "to_if_invoked": [
          {
            "set_variable": {
              "name": "tilde pressed",
              "value": 0
            }
          },
          {
            "key_code": "grave_accent_and_tilde"
          }
        ]
      }
    }
  ]
}
```

**Comment by MuhammedZakir** [comment]
Alternatively, if you are okay with holding down `tilde` for `escape`, you can try this -- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-after-key-up/#example. For this one, just like the above modification, you should set `basic.to_if_held_down_threshold_milliseconds` to a low value.

**Comment by giallu** [comment]
Thanks, now it works flawlessly. I also tested the "hold tilde for escape" method and it worked but I found it less convenient.
I am new to this 60% keyboards world and I am still trying to decide which input method works best for me. I use vi regularly so Esc is an essential key. On the other hand, the ~ is often used in command line arguments, and `` ` `` is useful for both windows navigation (Command+` moves you to the next window open of the same program) and entering accented letters: è à etc, I do them with a the Linux Compose equivalent, by typing in sequence Compose Key, letter, accent. 
By the way, thank you for all the help, I guess this may be closed now, do you want me to do it?

**Comment by MuhammedZakir** [comment]
> By the way, thank you for all the help, _[...]_

You're welcome! Glad to hear it worked! :-)

> _[...]_ I guess this may be closed now, do you want me to do it?

If there is nothing more, please close this.
