### ISSUE TITLE
Can't load the VirtualHIDDevice-Manager kext on macOS 11.2 dev seed

### ISSUE THREAD

**Issue by neilio** [pqrs-org/Karabiner-Elements#2548]
Not sure if this is a regression on macOS's side or an issue with Karabiner, but it's not possible to load the kext on yesterday's macOS 11.2 dev seed. I've tried a complete uninstall, reboot, and then reinstall but the kext refuses to load.

Happy to send over console or logging output if needed.

**Comment by Kilala-Z** [comment]
This problem is with me.

**Comment by nocategory** [comment]
`[warning] [virtual_hid_device_service] driver_version_ is mismatched: client expected: 10300, actual dext: std::nullopt` is pretty much the content of the log messages on the app, repeated many many times, maybe somewhat related to #2503 ?

**Comment by franciscorosso** [comment]
Same problem. I deactivate and reactivate the driver many times and it just doesnt work.

**Comment by claudiosv** [comment]
Same here! Also get the same log message as @nocategory. Happy to help in any way.

**Comment by tekezo** [comment]
Thank you for feedback!

I confirmed this issue on my machine.

It seems a macOS's kernelmanagerd issue which should be filed to Apple Bug Reporting.

```text
sysextd: Extension point com.apple.system_extension.driver_extension failed to start extension with identifier: org.pqrs.Karabiner-DriverKit-VirtualHIDDevice: Error Domain=kernelmanagerd.KMError Code=9 "(null)". Activating anyway.
```

We can confirm the log message by `log` command in Terminal.

```text
log show --predicate 'sender == "sysextd" or sender CONTAINS "org.pqrs"' --info --debug --last 1h
```

**Comment by neilio** [comment]
I'll fill a bug tomorrow when I'm back at my laptop. For what it's worth AdGuard has the same issue with its extension. Hopefully Apple fixes this one quickly.

**Comment by jspiro** [comment]
Filed one too. :-(

**Comment by rswail** [comment]
Submitted with the error from the log.

Wonder whether this line in the log output is relevant?

sysextd: request contains no authorizationref

Could it be related to gatekeeper notarization equivalent for kernel extensions?

**Comment by buzhidaoist** [comment]
Same issue -- if I want to file report through Feedback Assistant as well, what options exactly should I select, how should I describe / title the issue, and what should I include?  I'd love for this to get as quick attention and resolution as possible

**Comment by lihuishe** [comment]
is there a workaround? without certain keybinding it makes life miserable :(

**Comment by bigbangbear** [comment]
anyone can help。meet this problem too

**Comment by vegerot** [comment]
I am having the same issue

**Comment by vegerot** [comment]
> is there a workaround? without certain keybinding it makes life miserable :(

Probably not.  But you can file feedback using feedback assistant.  Make sure to attach similar logs to https://github.com/pqrs-org/Karabiner-Elements/issues/2548#issuecomment-747830664

**Comment by rswail** [comment]
My Feedback ticket is FB8944150 and it still shows recent similar reports as None.

Can people add their FB ticket numbers here and add mine to their FB ticket so that Apple can see that its happening more than once? :)

**Comment by jspiro** [comment]
FB8944105

**Comment by jspiro** [comment]
Would somebody that understands this well please recommend how we should report feedback to Apple? What fields to fill out and what to say?

**Comment by vegerot** [comment]
> My Feedback ticket is FB8944150 and it still shows recent similar reports as None.
> 
> Can people add their FB ticket numbers here and add mine to their FB ticket so that Apple can see that its happening more than once? :)

FB8948165

But you can also just link this GitHub issue

**Comment by tomlube** [comment]
ughhhhhhh this sucks so much. Karabiner is so useful :(

**Comment by tsuliwaensis** [comment]
@tekezo Have you filed a Radar? Not sure if sending a report through Feedback Assistant is the same thing. You may have to be a enrolled Apple Developer to file a radar though.

**Comment by vegerot** [comment]
I'm pretty sure Radar has been replaced by Feedback Assistant.  @tsuliwaensis how do I access the old Radar?

**Comment by jspiro** [comment]
Anyone figured out a workaround? Or is Apple trying to kill this extension?

**Comment by tomlube** [comment]
> Anyone figured out a workaround? Or is Apple trying to kill this extension?

looking more and more like they are trying to kill this, extremely depressing

**Comment by brodie-dog** [comment]
Had the same issue here... I found that disabling SIP fixed it for me.

1. Boot into Recovery
2. Then in Terminal: csrutil disable
3. Restart

**Comment by tsuliwaensis** [comment]
> I'm pretty sure Radar has been replaced by Feedback Assistant. @tsuliwaensis how do I access the old Radar?

I don't know. I just know that Apple Devs mention "filing a radar" when discussing bugs in Apple software

**Comment by tsuliwaensis** [comment]
> Had the same issue here... I found that disabling SIP fixed it for me.
> 
> 1. Boot into Recovery
> 2. Then in Terminal: csrutil disable
> 3. Restart

I really hate to resort to that.

**Comment by franciscorosso** [comment]
> Had the same issue here... I found that disabling SIP fixed it for me.
> 
> 1. Boot into Recovery
> 2. Then in Terminal: csrutil disable
> 3. Restart

This worked for me! I hope Apple fix this soon... Thanks for the workaround.

**Comment by tomlube** [comment]
> > Had the same issue here... I found that disabling SIP fixed it for me.
> > 
> > 1. Boot into Recovery
> > 2. Then in Terminal: csrutil disable
> > 3. Restart
> 
> This worked for me! I hope Apple fix this soon... Thanks for the workaround.

Can confirm this worked for me too.

**Comment by jspiro** [comment]
Frankly, if this works, then that will just have to be. So many of us can't live without the customizations we've become accustomed to for so many years. A testament to Karabiner's legacy that we'd disable our own protections to use it.

**Comment by jspiro** [comment]
Has anyone tried re-enabling csr after? I assume it won't work, but as Karabiner works again for me... nah, not worth the time to try it ;-)

**Comment by vegerot** [comment]
I'm curious if @tekezo has had any more time to look into this

**Comment by neilio** [comment]
Heads up if you disable SIP you won't be able to run iOS apps any more. I think it's related to Gatekeeper but I don't know for sure.

**Comment by jspiro** [comment]
Huh, that makes some sense. But catalyst apps like News keep working fine.

**Comment by tomlube** [comment]
> Has anyone tried re-enabling csr after? I assume it won't work, but as Karabiner works again for me... nah, not worth the time to try it ;-)

Uhhhh, I just tried it and it worked. Somehow.

**Comment by jspiro** [comment]
I bit and tried it. It does not work for me. I had to disable CSR again.

**Comment by tomlube** [comment]
Okay, just checked and it's still disabled, but I did enable it so not sure what happened there. Sorry.

**Comment by bigbangbear** [comment]
This worked for me!  Thanks

**Comment by l3osslunla** [comment]
> Had the same issue here... I found that disabling SIP fixed it for me.
> 
> 1. Boot into Recovery
> 2. Then in Terminal: csrutil disable
> 3. Restart

Thank you it's work!

**Comment by rswail** [comment]
Disabling SIP is not a fix. It is a temporary workaround. There should be no need to disable SIP.

The question is whether this problem applies to other extensions that applications try to load, ie is it specific to Karabiner?

**Comment by zjudmd1015** [comment]
Will this just be a temporary compatibility issue, or a permanent block by Apple?

**Comment by MuhammedZakir** [comment]
> Will this just be a temporary compatibility issue, or a permanent block by Apple? It doesn't make sense to block such a useful tool.

This is probably a bug rather than a block. At least, I hope so.

> For the csr workaround, is it dangerous to do so?

Read https://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/ and https://support.apple.com/en-us/HT204899.

It depends. I feel like it is "something is better than nothing" kind of thing and you should try to keep it enabled as much as possible. But, for me, it is an annoyance tbh. Because some apps I want can only be run if SIP is disabled. Frankly, for these kind of overly restrictive features, they should make it more customizable. For example, option to allow specified apps or processes to bypass certain restrictions. Apple's latest decisions are sadly very disappointing. I hope it doesn't become next Blackberry or Nokia. :-(

> Can I enable it later after I disable it?

Yes, you can. See the article I linked above.

**Comment by ttscoff** [comment]
>     1. Boot into Recovery
> 
>     2. Then in Terminal: csrutil disable
> 
>     3. Restart

Just a +1, disabling SIP worked for me as a temporary fix. Hoping the next dev seed from Apple makes this unnecessary...

**Comment by neilio** [comment]
Sadly, I just tested this in today's 11.2 developer beta and it's still not fixed. I keep getting the same issue when I launch Karabiner Elements where it complains that the driver's not loaded.

**Comment by vegerot** [comment]
That is unfortunate to hear.  Has anybody heard anything from the maintainers about if they have looked into this any more?

**Comment by jspiro** [comment]
@neilio Can you confirm the workaround continues to work?

@tekezo Could you coordinate a response to Apple–what report we should file, what information we should include? This should be done in the new beta, ideally. Let's fight back unless you've got a better way to handle it.

**Comment by neilio** [comment]
@jspiro I can't confirm as disabling SIP doesn't seem to work the same way on M1 Macs (like the Air I have) as it does on Intel Macs.

**Comment by yanzhang0219** [comment]
Disabling SIP is not an optimal solution because iOS apps will be disallowed with SIP disabled. I believe in the future there will be more restrictions if SIP is disabled.

**Comment by jspiro** [comment]
I confirm that disabling SIP continues to work in the latest beta. On Intel Macs.

For me, I don't care about iOS apps, but obviously that'll change in a few years. We need guidance and coordination from @tekezo.

**Comment by jspiro** [comment]
Okay, since no one else is doing this, here's what I am submitting. I recommend others submit the same, and refer to my ticket.

<img width="949" alt="Screenshot 2021-01-14 at 5 48 36 PM" src="https://user-images.githubusercontent.com/232896/104670529-dc864b00-5690-11eb-8d1a-40a38e6ddb52.png">

Title: Karabiner-Elements Kernel Extension Still Not Working from last two betas
Area: IOKit
Type: Crash
Desc: ```Followup of tickets FB8944105, FB8944150, FB8948165

Starting with last beta, continuing with this beta, Karabiner-Elements Kernel extension no longer starts all of a sudden, despite them being rewritten to be compliant. `csrutil disable` restores functionality, so the team should look at what changes were introduced in the previous beta in that area. See https://github.com/pqrs-org/Karabiner-Elements/issues/2548.

sysextd: Extension point com.apple.system_extension.driver_extension failed to start extension with identifier: org.pqrs.Karabiner-DriverKit-VirtualHIDDevice: Error Domain=kernelmanagerd.KMError Code=9 "(null)". Activating anyway.```

**Comment by tsuliwaensis** [comment]
I submitted Feedback: FB8971084

**Comment by rswail** [comment]
Updated logs from Big Sur 11.2 Beta 2:

default	16:06:01.371486+1100	kernelmanagerd	sysextd delegate will-start extension: org.pqrs.Karabiner-DriverKit-VirtualHIDDevice (1.0.0/1.0.0)
default	16:06:01.371571+1100	sysextd	starting extension org.pqrs.Karabiner-DriverKit-VirtualHIDDevice via owning category
default	16:06:01.371846+1100	kernelmanagerd	sysextd delegate start extension: org.pqrs.Karabiner-DriverKit-VirtualHIDDevice (1.0.0/1.0.0)
default	16:06:01.414823+1100	sysextd	Extension point com.apple.system_extension.driver_extension failed to start extension with identifier: org.pqrs.Karabiner-DriverKit-VirtualHIDDevice: Error Domain=kernelmanagerd.KMError Code=9 "(null)". Activating anyway.
default	16:06:01.414871+1100	sysextd	changing state of extension org.pqrs.Karabiner-DriverKit-VirtualHIDDevice to activated_enabled.
default	16:06:01.414917+1100	sysextd	extension G43BCU2T37 org.pqrs.Karabiner-DriverKit-VirtualHIDDevice (1.0.0/1.0.0) advancing state from activated_enabling to activated_enabled
default	16:06:01.668585+1100	sysextd	request contains no authorizationref

Updated my FB8944150

**Comment by ttscoff** [comment]
Thanks for the template @jspiro, added FB8971550.

**Comment by tsuliwaensis** [comment]
Beta 13.1.6 was just released. Haven't enabled SIP yet to find out if this bug is fixed. The release notes didn't say anything about it though

**Comment by shaolin405mi16** [comment]
Now 13.1.0 runs fine with Big Sur 11.2 RC here.

**Comment by kitora** [comment]
Now works fine with Big Sur 11.2 👍

**Comment by rswail** [comment]
Can confirm that problem appears to be resolved in Big Sur macOS 11.2 (20D53) with v13.1.9 of Karabiner. I've updated my FB.

**Comment by tekezo** [comment]
I confirmed Big Sur 11.2 RC fixed this issue.

**Comment by junkboy0315** [comment]
Fixed on v13.1.9 + Mac OS 11.2 RC

**Comment by neilio** [comment]
Yes! It's fixed. Hallelujah. Closing.

**Comment by vegerot** [comment]
@tekezo just wondering if you ever looked into what caused this

**Comment by mycarrysun** [comment]
I know this was closed already but I'm getting the same error on Big Sur 11.2.3 and Karabiner 13.3.9

**Comment by rswail** [comment]
I noticed it failing on a beta 2 release but then working again on beta 3 and now beta 4

**Comment by Kisielu** [comment]
I am sad to inform that I also experience this problem, with Big Sur 11.4 and Karabiner 13.4.0

**Comment by atjbramley** [comment]
Also noticing this on Big Sur 11.5.2 - simple key bindings still work but the eventviewer does not register keystrokes - only mouse actions.
