### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by mike-lloyd03** [pqrs-org/Karabiner-Elements#2549]
Is there a way to get a build of this for Linux? I have been using Karabiner for Mac for about a year now and I have gotten very used to the "Vi mode (D as Trigger Key)" modification. In fact, I don't know if I can live without it.

If there's no way to get a Linux build of this, are there any similar alternatives I can use?

**Comment by MuhammedZakir** [comment]
Karabiner Elements is strictly a mac app. It won't work in other OS.

 > If there's no way to get a Linux build of this, are there any similar alternatives I can use?

I use "kmonad". One of the main reason is it's flexibility and it's a cross-platform app! If you only use Linux (and want a simple GUI app), see Key Mapper [2]. Using it is very easy, but (I think) it does not support binding keys to shell commands/scripts. Alternatively, a geeky way: https://www.linuxuprising.com/2019/11/how-to-bind-mouse-buttons-to-keyboard.html.

[1] https://github.com/david-janssen/kmonad#features
[2] https://github.com/sezanzeb/key-mapper

**Comment by pdelfino** [comment]
I am really liking Karabiner and I would like to have it on my Linux machine (running NixOS). 

Apparently, on Linux you can get it to do the same thing with a combination of xmodmap, setxkbmap and xcape (but it's fiddly).

**Comment by mike-lloyd03** [comment]
When I opened this issue a few years ago, I didn't really grasp what it was I was asking. Now I understand that this would basically require writing a whole new application to interface with either the archaic X display server or the newer Wayland. There would be no simple way to do this. 

That being said, you can certainly achieve most of what you can do in Karabiner using xmodmap/xkbcomp and xcape. It's a bit more of a learning curve but I think it's given me a better understanding of how Xorg works.
