### ISSUE TITLE
Error message loads up when I try to use it

### ISSUE THREAD

**Issue by totalktoapropress1** [pqrs-org/Karabiner-Elements#2559]
It hasn't happened before, but every time Karabiner Elements is opened, there's an error message like this:
![Screen Shot 2020-12-27 at 8 14 47 AM](https://user-images.githubusercontent.com/76651992/103171615-ad13b980-481b-11eb-9c54-a9a79b31a58a.png)I've tried everything that was said in the alert, but nothing happens. Does anyone know why that is?

**Comment by tomlube** [comment]
Newest build of MacOS Big Sur broke it, no known fix right now.

**Comment by totalktoapropress1** [comment]
Oh, Okay. Thank you!
