### ISSUE TITLE
M1 Apple Silicon support without Rosetta

### ISSUE THREAD

**Issue by LinusU** [pqrs-org/Karabiner-Elements#2561]
Currently it seems like I need to install Rosetta in order to install/user Karabiner Elements.

<img width="688" alt="Screenshot 2020-12-28 at 14 19 48" src="https://user-images.githubusercontent.com/189580/103216990-c00bb400-4917-11eb-965e-768fc5f2ef3a.png">

It would be nice to have a native arm64 build

**Comment by tekezo** [comment]
duplicated #2534

**Comment by LinusU** [comment]
Sorry, I only searched for "arm" and "silicon" 🤦
