### ISSUE TITLE
trying to use the caps_lock key for multiple modifications

### ISSUE THREAD

**Issue by jimmy-e** [pqrs-org/Karabiner-Elements#2563]
I am using my Karabiner complex modifications to map my caps_lock key to my escape key.

I want to create a new complex modification that maps to the `command + left arrow` shortcut, and I want to do this using the caps_key. However, my new rule does not seem to be working at all. What do I need to change to get this mapping to work? Thanks!

```
        "rules": [
          {
            "description": "caps_lock => escape",
            "manipulators": [
              {
                "from": {
                  "key_code": "caps_lock"
                },
                "to": [
                  {
                    "key_code": "escape"
                  }
                ],
                "type": "basic"
              }
            ]
          },
          {
            "description": "command + shift + caps_lock + j => command + left",
            "manipulators": [
              {
                "from": {
                  "key_code": "j",
                  "modifiers": {
                    "mandatory": [
                      "command",
                      "shift",
                      "caps_lock"
                    ]
                  }
                },
                "to": {
                  "key_code": "left_arrow",
                  "modifiers": {
                    "mandatory": [
                      "command"
                    ]
                  }
                },
                "type": "basic"
              }
            ]
          },
        ]
```

**Comment by jspiro** [comment]
I'm bad at this syntax, but this is what I got working to use capslock for escape and to trigger F13 (for iTerm): ```"complex_modifications": {
        "parameters": {
          "basic.simultaneous_threshold_milliseconds": 50,
          "basic.to_delayed_action_delay_milliseconds": 500,
          "basic.to_if_alone_timeout_milliseconds": 1000,
          "basic.to_if_held_down_threshold_milliseconds": 500,
          "mouse_motion_to_scroll.speed": 100
        },
        "rules": [
          {
            "manipulators": [
              {
                "description": "Press command+caps_lock produces F13",
                "from": {
                  "key_code": "caps_lock",
                  "modifiers": {
                    "mandatory": [
                      "command"
                    ]
                  }
                },
                "to": [
                  {
                    "key_code": "f13"
                  }
                ],
                "type": "basic"
              },
              {
                "description": "Press caps_lock produces escape, hold is cmd",
                "type": "basic",
                "from": {
                  "key_code": "caps_lock",
                  "modifiers": {
                    "mandatory": [],
                    "optional": [
                      "any"
                    ]
                  }
                },
                "to_if_alone": [
                  {
                    "key_code": "escape"
                  }
                ],
                "to_if_held_down": [
                  {
                    "key_code": "left_command"
                  }
                ],
                "parameters": {
                  "basic.to_if_alone_timeout_milliseconds": 300,
                  "basic.to_if_held_down_threshold_milliseconds": 0
                }
              }
            ]
          }
        ]
      },```

**Comment by MuhammedZakir** [comment]
I maybe wrong, but I think your modification does not work because when you press `caps lock`, the first rule is triggered. You can solve it by either moving 2nd rule to the top or by pressing `shift` or `command` before `caps lock`.

You should probably add `caps_lock` to `from.optional.modifiers` in your first rule, otherwise you won't be able to use `escape` key when `caps lock` is enabled.

**Comment by jspiro** [comment]
I'm just sharing what I did that affects the same key in multiple modes. It's either helpful or it's not. I can only tell you that it has worked for me. I cobbled together from looking at lots of other unrelated examples as well.

**Comment by MuhammedZakir** [comment]
The problem is with your second rule. You can see these errors if you go to `Karabiner-Elements Preferences > Log`.

1. There is no `optional` or `mandatory` in `to.modifiers`. Change it to

```
                "to": {
                  "key_code": "left_arrow",
                  "modifiers": [
                      "command"
                    ]
                },
```

2. In JSON, comma after last item is invalid. There is one after your second rule.

**Comment by jimmy-e** [comment]
> The problem is with your second rule. You can see these errors if you go to `Karabiner-Elements Preferences > Log`.
> 
> 1. There is no `optional` or `mandatory` in `to.modifiers`. Change it to
> 
> ```
>                 "to": {
>                   "key_code": "left_arrow",
>                   "modifiers": [
>                       "command"
>                     ]
>                 },
> ```
> 
> 1. In JSON, comma after last item is invalid. There is one after your second rule.

awesome, thanks for the help!
