### ISSUE TITLE
Short code "Sleep display by pressing fn+ return" stopped working in Big Sur

### ISSUE THREAD

**Issue by BlueCrystal01** [pqrs-org/Karabiner-Elements#2573]
By holding down "fn" + hitting "return" the display should go to sleep mode. It worked in older karabiner and mac version but stopped working under newest karabiner and big sur.

If I hit fn+return the display goes in sleep mode but after releasing the fn or return key the macbook wakes up again. 

Can some expert please help me with the code? (After hitting and releasing the fn+return buttons the macbook should go and stay in sleep mode.) 

Thank you very much in advance!

The old code which stopped working in newest karabiner and big sur:

{
                        "description": "Sleep Display: Fn + Return",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "return_or_enter",
                                    "modifiers": {
                                        "mandatory": [
                                            "fn"
                                        ],
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "power",
                                        "modifiers": [
                                            "left_control",
                                            "left_shift"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },

**Comment by BlueCrystal01** [comment]
Can anyone give me a hint what I've to change?

**Comment by MuhammedZakir** [comment]
Have you tried latest beta version? Your complex modification works for me using latest beta version on Big Sur v11.0.1. One problem is that, because any key press or cursor movement will turn on display, you will have to release `fn` and `enter` quickly. I think this is what's happening to you.

**Comment by MuhammedZakir** [comment]
Try this:

```
                  {
                    "description": "Sleep Display: Fn + Return",
                    "manipulators": [
                      {
                        "from": {
                          "simultaneous": [
                            {
                              "key_code": "fn"
                            },
                            {
                              "key_code": "return_or_enter"
                            }
                          ],
                          "simultaneous_options": {
                            "key_up_when": "all"
                          }
                        },
                        "to_after_key_up": [
                          {
                            "key_code": "power",
                            "modifiers": [
                              "left_control",
                              "left_shift"
                            ]
                          }
                        ],
                        "type": "basic"
                      }
                    ]
                  },
```

---

What this does is,
1. make sure key up events are sent only when we release *all* keys, rather than *any* key.
    * for that we use `from.simultaneous` and set `key_up_when` in `simultaneous_options` to `all`.
2. send `to` event after key up event.
    * we use `to_after_key_up`.

The reason we have to use `from.simultaneous` is because `to_after_key_up` only takes `from` key in to consideration. To also include `fn`, we have to use it as a `from` key instead of modifier key and `from.simultaneous` is the only way to do that.

**Comment by BlueCrystal01** [comment]
@ MuhammedZakir, thank you very much for your help, I much appreciate it! :)

Your "simultaneous code" works fine :).  

I'm looking for a way to make Karabiner send the sleep-display command only after releasing the fn key (which is the last pressed down key). In other words Karabiner should send the sleep-display command only after the fn key is released so the display wouldn't be activated again.

My code works indeed if I release both keys very, very fast (thank you for the hint, I didn't knew that ;). On my old MBP with Mojave my code always worked: if I released the keys very slow it worked, too (this way is what I'm looking for).

**Comment by MuhammedZakir** [comment]
> My code works indeed if I release both keys very, very fast (thank you for the hint, I didn't knew that ;). On my old MBP with Mojave my code always worked: if I released the keys very slow it worked, too (this way is what I'm looking for).

First, we have to know whether this problem is related to KE or Big Sur. But, sadly, I don't know anything about this.

> [...] if I released the keys very slow it worked, too (this way is what I'm looking for).

With the complex modification rule I posted above, I was able to release keys _very_ slowly. Did it not work for you?

**Comment by BlueCrystal01** [comment]
Yes it did work for me. Thank you very much for your help!! :-)

**Comment by MuhammedZakir** [comment]
> Yes it did work for me. Thank you very much for your help!! :-)

You're welcome! :-) Please close this issue if there is no more issue.
