### ISSUE TITLE
Can modifications be application specific?

### ISSUE THREAD

**Issue by nstefi** [pqrs-org/Karabiner-Elements#2583]
I am using a full size external keyboard connected to my MacBook Pro.
I am trying to set up to use Windows style shortcuts, and I found a rule that converts Ctrl+Home to Cmd+Up arrow.
This works fine in a text editor like Sublime Text, but it doesn't work in Microsoft Word for Mac.
I found out that in Microsoft Word for Mac the keyboard shortcut to jump to beginning of the document is Cmd + Fn key + Left arrow. Unfortunately that combination didn't work in Sublime Text, only Word.
Would it be possible to have a modification that could map Ctrl+Home to Cmd + Fn key + Left arrow only if I have Word open and map to Cmd+Up arrow anywhere else?
Thank you.

**Comment by MuhammedZakir** [comment]
You can use `frontmost_application_if`/`frontmost_application_unless`[1] to limit modification to specific apps. E.g. https://github.com/pqrs-org/KE-complex_modifications/blob/a1c2d9f3aa61aba94845a101bf16b75477178a5c/public/json/alacritty.json#L18-L25

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/

**Comment by nstefi** [comment]
Thanks.
So I already imported a package of rules from Internet, it was called "Windows shortcuts on macOS". This had a rule called:
> Ctrl+Home, Ctrl+Shift+Home => Cmd+Up arrow, Cmd+Shift+Up arrow (Move cursor to beginning of file with and without selection)

The Ctrl+Home doesn't work in Word.
I see that it has this section (there are double backslashes, but I see github shows only 1):
> "bundle_identifiers": [
                                "^com\\.apple\\.Terminal$",
                                "^com\\.googlecode\\.iterm2$",
                                "^co\\.zeit\\.hyper$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.microsoft\\.rdc\\.macos$"
                            ],
                            "type": "frontmost_application_unless"

So these apps are excluded, right, and I would add this for Word?:
> "bundle_identifiers": [
                                "^com\\.apple\\.Terminal$",
                                "^com\\.googlecode\\.iterm2$",
                                "^co\\.zeit\\.hyper$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.microsoft\\.rdc\\.macos$",
                                "^com\\.microsoft\\.Word$"
                            ],
                            "type": "frontmost_application_unless"

Then I need a separate rule that defines it for Word only, as something like this?:
Ctrl+Home => Cmd + Fn key + left_arrow

**Comment by nstefi** [comment]
OK, I figured out, I did what I said earlier and it worked.
I was also able to combine them into 1 rule with multiple manipulators that works in text editors like Sublime Text and Word too.
Here is the solution for Ctrl+Home:
`{
            "description": "Ctrl+Home, Ctrl+Shift+Home => Cmd+Up arrow, Cmd+Shift+Up arrow (Move cursor to beginning of file with and without selection)",
            "manipulators": [
                {
                    "conditions": [
                        {
                            "bundle_identifiers": [
                                "^com\\.apple\\.Terminal$",
                                "^com\\.googlecode\\.iterm2$",
                                "^co\\.zeit\\.hyper$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.microsoft\\.rdc\\.macos$",
                                "^com\\.microsoft\\.Word$"
                            ],
                            "type": "frontmost_application_unless"
                        }
                    ],
                    "from": {
                        "key_code": "home",
                        "modifiers": {
                            "mandatory": [
                                "control"
                            ],
                            "optional": [
                                "shift"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "up_arrow",
                            "modifiers": [
                                "command"
                            ]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "bundle_identifiers": [
                                "^com\\.microsoft\\.Word$"
                            ],
                            "type": "frontmost_application_if"
                        }
                    ],
                    "from": {
                        "key_code": "home",
                        "modifiers": {
                            "mandatory": [
                                "control"
                            ],
                            "optional": [
                                "shift"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_arrow",
                            "modifiers": [
                                "command",
                                "fn"
                            ]
                        }
                    ],
                    "type": "basic"
                }
            ]
        },`

**Comment by nstefi** [comment]
This is for Ctrl+End:
`{
            "description": "Ctrl+End, Ctrl+Shift+End => Cmd+down arrow, Cmd+Shift+down arrow (Move cursor to end of file with and without selection)",
            "manipulators": [
                {
                    "conditions": [
                        {
                            "bundle_identifiers": [
                                "^com\\.apple\\.Terminal$",
                                "^com\\.googlecode\\.iterm2$",
                                "^co\\.zeit\\.hyper$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.microsoft\\.rdc\\.macos$",
                                "^com\\.microsoft\\.Word$"
                            ],
                            "type": "frontmost_application_unless"
                        }
                    ],
                    "from": {
                        "key_code": "end",
                        "modifiers": {
                            "mandatory": [
                                "control"
                            ],
                            "optional": [
                                "shift"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "down_arrow",
                            "modifiers": [
                                "command"
                            ]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "bundle_identifiers": [
                                "^com\\.microsoft\\.Word$"
                            ],
                            "type": "frontmost_application_if"
                        }
                    ],
                    "from": {
                        "key_code": "end",
                        "modifiers": {
                            "mandatory": [
                                "control"
                            ],
                            "optional": [
                                "shift"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_arrow",
                            "modifiers": [
                                "command",
                                "fn"
                            ]
                        }
                    ],
                    "type": "basic"
                }
            ]
        },`

**Comment by MuhammedZakir** [comment]
You're welcome! Please close this issue if your problem is solved. :-)
