### ISSUE TITLE
Posting `tab` multiple times while `left_command` is staying pressed 

### ISSUE THREAD

**Issue by panyushov** [pqrs-org/Karabiner-Elements#2584]
Hello, is there any way to map the following behavior to a single button in Karabiner? 

<img width="512" alt="AppSwitcher" src="https://user-images.githubusercontent.com/15730945/104856573-c0461080-5913-11eb-8382-ca539cbcd94f.png">

I want to use the app switcher in the macOS by pressing only one button instead of cmd+tab. But to do so I need to keep the `left_command` pressed while continuously posting the `tab` button as many times as I want to advance in the swticher. 

I tried to use the `to_delayed_action` in the following way: 

```JSON
{
  "manipulators": [
    {
      "from": {
        "key_code": "caps_lock"
      },
      "to": [
        {
          "key_code": "left_command",
          "hold_down_milliseconds": 500
        },
        {
          "key_code": "vk_none"
        }
      ],
      "to_delayed_action": {
        "to_if_invoked": [
          {
            "key_code": "tab"
          }
        ]
      },
      "parameters": {
        "basic.to_delayed_action_delay_milliseconds": 200
      },
      "type": "basic"
    }
  ]
}
```

but unfortunately, the `tab` key is getting posted 200ms after the `left_command`  KEY_UP event finishes (so 500ms + 200ms after the initial KEY_DOWN event). 
Is there any alternative way I can implement what I want? Thank you

**Comment by MuhammedZakir** [comment]
- Press 'Z' to show app-switcher.
    * Suppose `Z` is the key.
    * You want app-switcher to be shown indefinitely?
- Pressing `Z` again advances the selector in app-switcher.

Is this what you want to do? If so, I have a couple of questions:

1. How will you quit app-switcher? i.e. when to release `command` button?
2. What about going backwards in app-switcher?

**Comment by panyushov** [comment]
1. The main thing about the app-switcher in the macOS is that once I press the `command` then I press and release the `tab` once, while I'm holding `command` it will stay on. 
My goal is to simulate the hold of the `command` button for let's say 2 seconds. Then send KEY_DOWN and KEY_UP of the `tab` key in the range of [0s; 1s], this will advance me to 1 position in the app-switcher. 
At this point, the app-switcher will stay on for the rest of 2 seconds hold period and I can decide if to press 'z' again, therefore, advancing again in the app-switcher of 1 position, or just wait until `command` will get released and the app-switcher will fade.

2. For now I'm just interested in going always forward. I think in the future I may add some right-hand reachable key (like `j`) that with the combination of `z` will let me move backward (so `j` will translate in the `shift` modifier). First, need to think better about the ergonomics of this solution.

**Comment by MuhammedZakir** [comment]
Is app switcher shown if you use below config and press `tab` in 500ms?

```
{
  "manipulators": [
    {
      "from": {
        "key_code": "caps_lock"
      },
      "to": [
        {
          "key_code": "left_command",
          "hold_down_milliseconds": 500
        },
        {
          "key_code": "vk_none"
        }
      ],
      "type": "basic"
    }
  ]
}
```

**Comment by panyushov** [comment]
Interesting, it isn't shown. I even tried to extend the 500ms hold down period thinking I'm not fast enough to press the `tab` key but still nothing.
I assume macOS sees hold down events from karabiner and physical `tab` key press as two different events and doesn't interpret them together to show the app switcher.

**Comment by MuhammedZakir** [comment]
> Interesting, it isn't shown. I even tried to extend the 500ms hold down period thinking I'm not fast enough to press the `tab` key but still nothing.
> I assume macOS sees hold down events from karabiner and physical `tab` keypress as two different events and doesn't interpret them together to show the app switcher.

I see! The only way atm is to use AppleScript to "hold" `command` key. Can you try below code in Script Editor? After running code, press `tab` within 1 second and see if app switcher is shown.

```
tell application "System Events" to key down command
delay 1
tell application "System Events" to key up command
```

If this works, you can wrap this in a shell script and execute it when a key is pressed.

```
"shell_command": "osascript -e 'tell application \"System Events\" to key down command' -e 'delay 1' -e 'tell application \"System Events\" to key up command"
```

**Comment by panyushov** [comment]
It works! I think I'm gonna stick with this solution for now. Thank you very much for your help.
