### ISSUE TITLE
Can't activate driver

### ISSUE THREAD

**Issue by mkielarv2** [pqrs-org/Karabiner-Elements#2596]
I have successfully used KE previously but after last reboot karabiner asked to reload the driver. Previously I had same issue and instructions to deactivate and activate driver worked as it should. Now however when I click deactivate it says success, but after restart when I click activate it shows `Activation was failed. (error:1)` I tried to reboot a few more times, changed version of KE to 13.0.0 and to beta build, but the problem persists.

When I use CLI it shows the following error:
```
$ ./Karabiner-VirtualHIDDevice-Manager activate
activation of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is requested
request of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is failed with error: The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 10.)
```

MacOS version 10.15.7

**Comment by Splaktar** [comment]
The new 13.3.1 beta update started working for me.

**Comment by dirn** [comment]
I get the exact same error on macOS 11.2.3 using both 13.3.0 and the 13.3.9 beta.

**Comment by miaachan** [comment]
able to activiate driver but the driver alert prompt wont go away & log keeps prompting
`[timestmap] [warning] [virtual_hid_device_service] driver_version_ is mismatched: client expected: 10300, actual dext: std::nullopt`

mbp16 2019 10.15.7

**Comment by mycarrysun** [comment]
Still getting this in May 2020 on macos 11.3.1 and Karabine 13.4.4... any updates?

**Comment by mkielarv2** [comment]
Updated to MacOS 11.4 and Karabiner 13.4.0, problem is still there. I have tried to activate driver a few times with no luck.

**Comment by RoyTrudell** [comment]
I'm also having this issue.

**Comment by foxale** [comment]
Same here, Big Sur 11.4

**Comment by gilzellner-wix** [comment]
Same here, 10.15.7

**Comment by Rovango** [comment]
same here, macos 11.4, KE 13.5.0

**Comment by gilzellner-wix** [comment]
So I only use Karabiner for some super simple changes, so i can use my windows\linux Das keyboard
I discovered that this exists in macOs natively now, so i don't need karabiner anymore
Located under System Preferences > Keyboard > Modifier Keys  and make sure you have the right keyboard selected in the top dropdown.

![image](https://user-images.githubusercontent.com/79847081/124453260-de9fab80-dd8f-11eb-82d6-9d420771c867.png)

**Comment by menchauser** [comment]
Same here. Karabiner 13.5.0, macOS BigSur 11.4

**Comment by yamrodriguez** [comment]
Same here. Karabiner 13.5.0, macOS BigSur 11.4

**Comment by vlad2135** [comment]
I have the same problem, but in my case I'm 90% sure reason is my IT security department is blocking driver form installation. Is there any way to confirm this fact, or find a workaround and activate the driver manually, or from command-line?

**Comment by tsuyo** [comment]
For whom having "CrowdStrike Falcon" enabled by your IT in your system (like me), most likely the issue would be resolved by removing this. To check if this is the case, run the following command
```
$ systemextensionsctl list
```
and see if the output has "com.crowdstrike.falcon.Agent (xxx/xxx) Agent [activated enabled]" line. If you see this, https://github.com/pqrs-org/Karabiner-Elements/issues/2876#issuecomment-975541172 might resolve the issue.

**Comment by menchauser** [comment]
Yes, in my case it was CrowdStrike Falcon and our IT guys helped me to fix it

**Comment by cammil** [comment]
Is there any update on this? I cannot activate my driver, and I keep getting the warning. Karabiner doesn't work any more after updating it.

**Comment by mycarrysun** [comment]
Anyone else here with Carbon Black being managed by their company? I've asked the IT guys multiple times if it could be Carbon Black but nothing shows up in the logs but I'm still skeptical

**Comment by CampAsAChamp** [comment]
> Yes, in my case it was CrowdStrike Falcon and our IT guys helped me to fix it

What did you ask your IT guy(s) btw? I have Falcon on my work computer but not sure what I have to do to get Karabiner up and running. I saw the reply above but want to double check before I go do something drastic to my work computer.

**Comment by menchauser** [comment]
> What did you ask your IT guy(s) btw? 

I've described to them the issue with activating the driver and sent them the error from system logs I found: `sysextd: Reasons for denying extension with teamID teamID("G43BCU2T37"), org.pqrs.Karabiner-DriverKit-VirtualHIDDevice
are: ["extension\'s teamID and identifier are not in the list of allowed extensions"]`. IT engineer told me that he "pushed new system extensions" and that made it work.

**Comment by josebolos** [comment]
For those of you that are experiencing this problem because the installation of system extensions is blocked by an IT MDM tool, a description of the settings that may need to be changed can be found at https://github.com/pqrs-org/Karabiner-Elements/issues/2636#issuecomment-870819772

**Comment by huynhj93** [comment]
> > What did you ask your IT guy(s) btw?
> 
> I've described to them the issue with activating the driver and sent them the error from system logs I found: `sysextd: Reasons for denying extension with teamID teamID("G43BCU2T37"), org.pqrs.Karabiner-DriverKit-VirtualHIDDevice are: ["extension\'s teamID and identifier are not in the list of allowed extensions"]`. IT engineer told me that he "pushed new system extensions" and that made it work.

To get the exact log, please run this in your terminal `log show --predicate 'sender == "sysextd" or sender CONTAINS "org.pqrs"' --info --debug --last 1h` as specified in https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/blob/main/DEVELOPMENT.md

**Comment by nejmeijer** [comment]
Closing this because this seems to be a problem with external software rather than KE.

**Comment by trianta2** [comment]
I ran into this issue as well, likely due to a policy change pushed by my company.

Thankfully I only need simple mappings. [This comment](https://github.com/pqrs-org/Karabiner-Elements/issues/3082#issuecomment-1137009173) lead me to [this website](https://hidutil-generator.netlify.app/) which uses macOS-native `hidutil` to map arbitrary keys. Everything's working again, without Karabiner Elements.
