### ISSUE TITLE
how to delete org.pqrs.Karabiner-DriverKit-VirtualHIDDevice

### ISSUE THREAD

**Issue by Asilent** [pqrs-org/Karabiner-Elements#2616]
I had uninstalled Karabiner-Elements.But when I check process, I found org.pqrs.Karabiner-DriverKit-VirtualHIDDevice still running. I can't kill it.

**Comment by tekezo** [comment]
The process is still running even if you restart macOS?

**Comment by Asilent** [comment]
> The process is still running even if you restart macOS?
Yes. Although I use "sudo kill -9 pid", it will restart with a new pid.

**Comment by Asilent** [comment]
> Is the process still running even if you restart macOS?
> 
> Note:
> The process is launched by macOS DriverKit, and the process should be killed by macOS when the driver is deactivated during Karabiner-Elements uninstallation.
> If the process is running after deactivation, it's a macOS issue.

Yes. Although I use "sudo kill -9 pid", it will restart with a new pid.

**Comment by tekezo** [comment]
Thank you for confirmation!

I hope retrying the uninstallation of DriverKit driver solves the issue.
Please follow the steps:

1.  Reinstall Karabiner-Elements to install DriverKit driver manager to uninstall it.
2.  Execute the following command that is described in this page.
    https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

```shell
bash '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/scripts/uninstall/deactivate_driver.sh'
```

3.  Confirm `org.pqrs.Karabiner-DriverKit-VirtualHIDDevice` is killed.
4. Execute the following command.

```shell
sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall.sh'
```

**Comment by Asilent** [comment]
> Thank you for confirmation!
> 
> I hope retrying the uninstallation of DriverKit driver solves the issue.
> Please follow the steps:
> 
> 1. Reinstall Karabiner-Elements to install DriverKit driver manager to uninstall it.
> 2. Execute the following command that is described in this page.
>    https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/
>    The command will uninstall the DriverKit driver.
> 
> ```shell
> bash '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/scripts/uninstall/deactivate_driver.sh'
> ```
> 
> 1. Confirm `org.pqrs.Karabiner-DriverKit-VirtualHIDDevice` is killed.
> 2. Execute the following command.
>    The command will uninstall remaining part of Karabiner-Elements.
> 
> ```shell
> sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall.sh'
> ```

Crash...When I try to commit `bash '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/scripts/uninstall/deactivate_driver.sh'` this command, my system immediately restart with pink screen.Although I use the GUI to uninstall, it gets the same result.

**Comment by tekezo** [comment]
Hmm, it's an annoying macOS issue...

Until Apple fixes the system crash, the only way to solve the problem, though tedious, is to follow the steps:

1.  Disable SIP to prepare to use `systemextensionsctl reset`.
    https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
2.  Execute `systemextensionsctl reset`. This command purges installed DriverKit driver.
3.  Enable SIP again.
4.  Uninstall Karabiner-Elements.

**Comment by Asilent** [comment]
> Hmm, it's an annoying macOS issue...
> 
> Until Apple fixes the system crash, the only way to solve the problem, though tedious, is to follow the steps:
> 
> 1. Disable SIP to prepare to use `systemextensionsctl reset`.
>    https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
> 2. Execute `systemextensionsctl reset`. This command purges installed DriverKit driver.
> 3. Enable SIP again.
> 4. Uninstall Karabiner-Elements.

It works.Thanks.
