### ISSUE TITLE
+ and * get replaced with ` and ´on German keyboard layout 

### ISSUE THREAD

**Issue by kasti0** [pqrs-org/Karabiner-Elements#2625]
without adding any modification Karabiner Elements replaces +/* with ´/` on my German keyboard layout (the standard German with äüö)
device: MacBook Air M1
macOS: 11.2
karabiner version testet with: latest release and beta
what I tried so far: reinstalling Karabiner multiple times, completely resetting my keyboard type.

**Comment by MuhammedZakir** [comment]
You can temporarily fix it by remapping those keys.

**Comment by kasti0** [comment]
I tried to but it just doesn't work, unfortunately, because the + and * just don't exist on what ever layout Karabiner applies to my keyboard. I thought it would be the American layout but that's not the case

**Comment by clemensbartz** [comment]
I cannot reproduce this issue on my M1BP, macOS 11.2.1, Karabiner 13.3.1 with German layout.

Can you please post a screenshot similar to the one I am posting down below. You can enable the keyboard flag under Keyboard -> Input Sources in the system settings.
<img width="1001" alt="Bildschirmfoto 2021-02-12 um 11 23 13" src="https://user-images.githubusercontent.com/8080309/107757033-4bed6a00-6d25-11eb-920e-335f9893d6fc.png">

**Comment by kasti0** [comment]
@clemensbartz In these screenshots it looks alright but still confuses the buttons and I actually can't type plus or the star symbol right now.
first picture is without karabiner installed second picture with (no difference). I also include a video of the behavior, I hope you can see when I press the plus key it inserts a ´(I had to shorten and compress the video).
<img width="786" alt="without KE" src="https://user-images.githubusercontent.com/49281774/107764607-c53e8a00-6d30-11eb-9aaa-6813f3db0bbb.png">
<img width="1021" alt="with KE" src="https://user-images.githubusercontent.com/49281774/107764611-c8d21100-6d30-11eb-8866-6ca46e09aefa.png">


[with KE-video.mov.zip](https://github.com/pqrs-org/Karabiner-Elements/files/5971577/with.KE-video.mov.zip)

**Comment by kasti0** [comment]
Is there any way to completely remove Karabiner Elements? because even after de-installing it it seems to remember simple modifications I made. maybe I just need to completely reset it

**Comment by clemensbartz** [comment]
You can eliminate if Karabiner is really the culprit by disabling the checkbox in front of "Apple Internal Keyboard".

I would go with a reset of the config first, as the uninstall script does not delete that.

After you quit Karabiner Elements by going to the "Misc" tab and selecting "Quit Karabiner-Elements", you delete the config directory. Open a terminal and type `rm -rf ~/.config/karabiner/`. Next, you can open Karabiner again. That should have reset the config.

If you wanted to uninstall it, under the "Misc" tab there is also an "Uninstall Karabiner-Elements" button. Make sure to shutdown your system completely afterwards or typing `osascript -e 'tell application "System Events"' -e 'shut down' -e 'end tell'` in the terminal.

**Comment by kasti0** [comment]
deleting the profile and restarting fixed it. thank you!
