### ISSUE TITLE
Cannot find "·" in the list

### ISSUE THREAD

**Issue by Timzhouyes** [pqrs-org/Karabiner-Elements#2629]
Hello team,
I am a guy who use a Chinese input, and when I push button "\`" it will give me the input "·", so I want to rebind it to "\`" to use typora easily. But I can only find "grave_accent_and_tilde" in the list which is "\`", but cannot find "·" in the list, could u help me which key is "·" in the list? Thanks!

**Comment by MuhammedZakir** [comment]
You can find key code using EventViewer. [1]

[1] `Karabiner-EventViewer.app` or `Karabiner-Elements manu > Launch EventViewer`.

**Comment by Timzhouyes** [comment]
@MuhammedZakir Hello Muhammed, I tried, but it is still "grave_accent_and_tilde", the same name as "\`", so cannot distinguish them by the name. Do I have other solutions? Thanks

**Comment by MuhammedZakir** [comment]
Karabiner-Elements has some problems with other layouts. This is also related to that. For now, can you open on-screen keyboard and see whether it shows "grave accent" or "middle dot" for that button?

**Comment by Timzhouyes** [comment]
![image](https://user-images.githubusercontent.com/20654060/107913910-42ba0280-6f9c-11eb-8e61-ffc8730b573d.png)

hello, u can see that I input 3 middle dot in the on-screen keyboard, but it only showed mouse click. Thanks for ur help again @MuhammedZakir

**Comment by MuhammedZakir** [comment]
But, the keyboard shown is not using Chinese input, right?

I am using Linux atm, so I can't do any tests now. I will try it when I can access one. For now, I can't help you much. If you can wait, someone else may help you on this. :-)

**Comment by Timzhouyes** [comment]
@MuhammedZakir This is the Chinese input, and thanks for your helping! I will wait for other guys to give me some tips :) Hope a good day!

**Comment by MuhammedZakir** [comment]
You're welcome! :-)

Can you try running below command in terminal and see if `tilde` is shown?

```
osascript -e 'tell application "System Events" to keystroke "~"'
```

If it does not works, try

```
osascript -e 'tell application "System Events" to key code 50 using shift down'
```

If it works, you can use complex modification to run this shell command when `grave_accent_and_tilde` is pressed.

**Comment by Timzhouyes** [comment]
Both works, thank so much for your help!
