### ISSUE TITLE
Feature request: Manipulator condition "frontmost_window_title"

### ISSUE THREAD

**Issue by svicalifornia** [pqrs-org/Karabiner-Elements#2631]
I would like to limit some manipulators to invoke only when a specific window of an application is frontmost. When any other window of the app is frontmost, I would like to prevent these manipulators from having effect.

Keyboard Maestro has this feature, and it would be really helpful to have it in Karabiner-Elements as well.

**Comment by MuhammedZakir** [comment]
https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/
