### ISSUE TITLE
13.3.0 会导致m1 macbook pro 无法正常关机或正常重启，求高手点解？

### ISSUE THREAD

**Issue by starwu** [pqrs-org/Karabiner-Elements#2633]
m1 macbook pro安装后，重启或关机mac时候，会直接开机，并弹出非法强制关机的错误提示，将Karabiner-Elements卸载后，就恢复正常了。

我安装的版本为：13.3.0

求高手点解？

**Comment by DotIN13** [comment]
Duplicate of #2607

**Comment by jinglepp** [comment]
我也有同样的问题。m1 macbook pro安装13.3.0后，关机会自动重启然后报kernal panic，卸载后才可以正常关机。还好mbp不用经常关机，现在凑合着在用。不知道什么时候可以修复这个问题。

**Comment by KyleHKT** [comment]
> 我也有同样的问题。m1 macbook pro安装13.3.0后，关机会自动重启然后报kernal panic，卸载后才可以正常关机。还好mbp不用经常关机，现在凑合着在用。不知道什么时候可以修复这个问题。

M1 mac mini
目前我暂时解决办法是13.3.5 beta，关机/重启前退出软件就不会报告内核崩溃，不退出软件就崩溃！
算是一个临时解决办法，但是还是很苦恼。

**Comment by Langze6** [comment]
我也发现了这个问题，我购买的M1处理器笔记本第一次开机就安装了Karabiner-Elements，我使用了1个周每次关机都出现了粉色屏幕，然后自动开机，必须要在登陆前点击关机是正常的，这个问题很严重，我甚至怀疑是我的MacBook Pro出现了质量问题，但最后我使用安全模式进入系统发现不会出现此问题，我开始排查所有App最后终于定位到了Karabiner-Elements，我是一名Java开发工程师，我做了两个小时的测试，确定Karabiner-Elements在M1芯片的MacBook Pro 关机会出现粉色屏幕，并会自动开机提示系统出现BUG，我的系统版本号是Big Sur 11.2.2 (20D80) 请重视这次反馈！！！
