### ISSUE TITLE
12.10.0: Apple internal keyboard / trackpad is ignored temporarily until {"key_code":"t"} is pressed.

### ISSUE THREAD

**Issue by frumbert** [pqrs-org/Karabiner-Elements#2640]
I am on Mojave.

![Screen Shot 2021-02-24 at 3 57 47 pm](https://user-images.githubusercontent.com/592257/108949827-3e3acb80-76b9-11eb-9aa8-cc839a64d22a.png)

I sleep my MBP and then close the lid. I then connect HDMI and keyboard and wake my MBP in clamshell mode. It then shows:

![Screen Shot 2021-02-24 at 3 57 13 pm](https://user-images.githubusercontent.com/592257/108949920-675b5c00-76b9-11eb-8dbc-b15a5ece177d.png)

1.

There is **NO WAY** to dismiss this. It is even present in full screen apps. You MUST quit then relaunch.

2.

The "t" key on my MBP is _physically broken_ and _can not be pressed_. I can't do as it says anyway.

3.

This is a redundant message anyway since the MBP is already in clamshell mode and the internal keyboard and trackpad are disabled anyway.

**Comment by frumbert** [comment]
Months later, still the same.

When the lid is opened, the key is considered to be pressed dozens of times a second. Using an external keyboard is tricky since there is a 1 second delay when I pres hte t key before it ytpes hte letter so that mos titmes you can see hte t is being triggered afetr ohter letters are pressed. I lef thtem in so you can see hte problem. the problem is speciifc ot hte letter.  I am also unable to type a capital t as it ignores the caps lock setting - here I have caps lock on and type hte top row.

`QWERtYUIOP`

Here is the advanced device setting. all other settings are default.

![Screen Shot 2021-06-25 at 1 46 59 pm](https://user-images.githubusercontent.com/592257/123366874-53b6f800-d5bc-11eb-9411-22c453c193bd.png)

**Comment by frumbert** [comment]
aah the old "mark complete even though its not fixed" trick.

**Comment by orcinus** [comment]
Except in my case i'm getting it for *every key press* for some reason.

**Comment by SeyedParsa** [comment]
The same problem here! While my left shift is broken and is down all the time, the app asks me to press the key!

**Comment by florian1984** [comment]
Same issue on MacOS 13, had to deactivate internal keyboard....:

![image](https://user-images.githubusercontent.com/12068197/201012570-bf5bb8ce-d97f-4412-af4d-79d4beab6baa.png)

**Comment by alana314** [comment]
+1 Also getting this on a macbook air M1

**Comment by flypenguin** [comment]
is that a duplicate of #1848, or indeed something else?
