### ISSUE TITLE
Remap f5 and f6 back to keyboard backlight brightness control

### ISSUE THREAD

**Issue by mikeyhew** [pqrs-org/Karabiner-Elements#2645]
I just got a new M1 Macbook Air, and they changed a few of the function keys. F5 and F6 now toggle Dictation and Do Not Disturb instead of adjusting the keyboard backlight. I installed karabiner-elements (version 13.3.0) via homebrew, and these are the default mappings that I see for the function keys:

<img width="1112" alt="Screen Shot 2021-02-28 at 12 29 07 PM" src="https://user-images.githubusercontent.com/6751033/109427542-dc33dc00-79c0-11eb-9cb0-429f4252fe20.png">

Is there a mapping I can set that will give me the old behaviour of keyboard backlight brightness increase/decrease for f5/f6? There were some called illumination_decrement/increment and illumination_down/up that looked promising, but if I pick them, all that happens when I hit the mapped key is this image comes up on my screen:

<img width="200" alt="Screen Shot 2021-02-28 at 12 34 00 PM" src="https://user-images.githubusercontent.com/6751033/109427653-5fedc880-79c1-11eb-8887-6fa2502d409e.png">

**Comment by MuhammedZakir** [comment]
Use `illumination_down/up`.

> [...] if I pick them, all that happens when I hit the mapped key is this image comes up on my screen:
> 
> < img alt="Screen Shot 2021-02-28 at 12 34 00 PM" width="200" src="https://user-images.githubusercontent.com/6751033/109427653-5fedc880-79c1-11eb-8887-6fa2502d409e.png">

AFAIK, this happens when you try to increment/decrement backlight at morning.

**Comment by MuhammedZakir** [comment]
> > at morning
> 
> Is that a typo? Why would the time of day have anything to do with it?
> 
> I checked today and noticed it works! Well, sometimes it works, and sometimes I get the no_entry_sign. Right now it's not working, but a few minutes ago it worked. No idea what causes it to work and not work

You're lucky! I can't remember the last time it worked for me at morning. I know it's weird. But, for me, adjusting keyboard backlight **always** works after evening. Whereas, at morning, almost all of the times, it does not work; I get the same error as yours.

**Comment by mikeyhew** [comment]
I think it's the "adjust keyboard brightness in low light" setting. It works fine if I disable it.

<img width="780" alt="Screen Shot 2021-03-02 at 12 15 21 PM" src="https://user-images.githubusercontent.com/6751033/109687801-9bb79800-7b51-11eb-87fe-6d9347314314.png">

**Comment by mikeyhew** [comment]
Closing since this fixed it for me:

- disable the "adjust keyboard brightness in low light" setting
- map f5 to illumination_down, f6 to illumination_up

**Comment by MuhammedZakir** [comment]
Thanks for the info! :-)

**Comment by adeds** [comment]
> Closing since this fixed it for me:
> 
> * disable the "adjust keyboard brightness in low light" setting
> * map f5 to illumination_down, f6 to illumination_up

this is not working on my external keyboard (Keychron K3) with MBP 2020 Intel

**Comment by AHBICJ** [comment]
> > Closing since this fixed it for me:
> > 
> > * disable the "adjust keyboard brightness in low light" setting
> > * map f5 to illumination_down, f6 to illumination_up
> 
> this is not working on my external keyboard (Keychron K3) with MBP 2020 Intel

do you fix this?

maybe keychron not fire f5 f6 event, consider read following anwser? for short,  long press FN+K+C for 3s.

https://www.reddit.com/r/Keychron/comments/f1gey0/issues_with_f5f6_respecting_fn_key/

looks like this page has the answer: https://www.keychron.com/pages/firmware-for-k1-v2-v3-keyboards

> New factory default function under the Mac system is that the F1~F12 functions (except F5/F6) can be adjusted inside the Mac system. The F5/F6 defaults to the backlight adjustment function. After long press FN+K+C for 3s, the keyboard will flash 3 times, then the function of F5/F6 will switch to the normal F5/F6 function under Mac system, and the keyboard backlight control will adjust to FN+F5/F6. And vice versa.
> 

https://stackoverflow.com/questions/66797978/function-keys-f5-and-f6-not-working-properly-on-macos-when-using-keychron-keyboa

**Comment by 7hr1LL** [comment]
> Closing since this fixed it for me:
> 
> * disable the "adjust keyboard brightness in low light" setting
> * map f5 to illumination_down, f6 to illumination_up

confirm this solved the issue for me on my MBP M4 Ultra
