### ISSUE TITLE
Is there any shortcut to disable Karabiner temporarily?

### ISSUE THREAD

**Issue by eret9616** [pqrs-org/Karabiner-Elements#2649]
As the title says, sometimes I want to disable shortcut temporarily, e.g I'm operating in a VM, Is there any way to achieve this?

**Comment by brttbndr** [comment]
You could create another profile that doesn't have any modifications configured. Then switch to that profile when you want to temporarily disable shortcuts.

https://karabiner-elements.pqrs.org/docs/manual/operation/profiles/

You can use the `karabiner_cli` to switch profiles at the command line. If you want to get fancy, you could have a complex config that uses a hotkey to switch to your "empty" profile, and have that profile contain only that same hotkey to switch back to your default.

https://karabiner-elements.pqrs.org/docs/manual/misc/command-line-interface/

**Comment by zoomstarr** [comment]
> You could create another profile that doesn't have any modifications configured. Then switch to that profile when you want to temporarily disable shortcuts.
> 
> https://karabiner-elements.pqrs.org/docs/manual/operation/profiles/
> 
> You can use the `karabiner_cli` to switch profiles at the command line. If you want to get fancy, you could have a complex config that uses a hotkey to switch to your "empty" profile, and have that profile contain only that same hotkey to switch back to your default.
> 
> https://karabiner-elements.pqrs.org/docs/manual/misc/command-line-interface/

hey I'm new to using karabiner and I know this is old but is there any way to explain in a easier way to to understand or a link to a already existing code to make a hotkey to turn on and off the rest of the hotkeys

**Comment by zoomstarr** [comment]
never mind had my friend who codes figure it out with me for anyone who wants a way to do this first go into profiles in the karabiner elements profiles it should be on the left of your screen under virtual keyboard and create a new profile then go into each profile and press complex modifications and press the add you own rule modification delete everything that's in the text box and add

{
    "description": "option+tab to enable keybinds",
    "manipulators": [
        {
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "mandatory": [
                        "option"
                    ]
                }
            },
            "to": [
                {
                    "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'me'"
                }
            ],
            "type": "basic"
        }
    ]
}

 for each profile but in the shell command link replace me with the name of your profile and you can change what button to turn it off by changing the stuff at the top of the code from option to whatever you want and tab to whatever you want let me know if you have any questions and I can trouble shoot with you

**Comment by clins777** [comment]
# overview

Problem: how to disable karabiner temporarily?
Solution: have a `vanilla` profile without any settings and switch to it via keyboard shortcut

# how to

Setup two profiles so you can switch between them and add the following complex modification for each of them. For this example I'm using `main` and `vanilla` profiles.

## in the `main` profile

```
{
    "description": "switch to 'vanila' profile",
    "manipulators": [
        {
            "from": {
                "key_code": "o",
                "modifiers": {
                    "mandatory": [
                        "left_shift"
                    ]
                }
            },
            "to": [
                {
                    "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'vanilla'"
                }
            ],
            "type": "basic"
        }
    ]
}
```

## in the `vanilla` profile

```
{
    "description": "switch to 'main' profile",
    "manipulators": [
        {
            "from": {
                "key_code": "o",
                "modifiers": {
                    "mandatory": [
                        "left_shift"
                    ]
                }
            },
            "to": [
                {
                    "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'main'"
                }
            ],
            "type": "basic"
        }
    ]
}
```

Now you can switch between profiles by pressing `left shift + o`. of course you probably dont want this to be your shortcut so be my guest to change it to whatever makes sense for your environment

## Notes

- I'm using version `14.13.0`
