### ISSUE TITLE
[feature request] CLI command to *read* variable, as well as set variable

### ISSUE THREAD

**Issue by slippycheeze** [pqrs-org/Karabiner-Elements#2651]
### what?
I'd like to be able to read the value of a variable, as well as set it, using the CLI.  

### how I imagine it working
```
] '/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --set-variables '{"first": 1}'
] '/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --set-variables '{"second": 2, "third": 3}'
] '/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --get-variables
{"first": 1, "second": 2, "third": 3}
```

That is: when you make the call it simply dumps the entire set of variables as currently known, as a JSON object.  

### why?
I use a dvorak keyboard layout on a qwerty physical keyboard via the macOS input method, not through karabiner-elements.  This is largely because I sometimes need to share the machine with other people, and being able to switch mode through the platform UI is nicer.

I also have a Yubikey, which is used in "act like a keyboard, type a one-time password string" mode.  This is also remapped by the OS input method, which is unfortunate.  It'd be nice if it wasn't, but so it goes.

To work around that I have karabiner-elements remap the yubikey input from dvorak characters to qwerty characters, but only if the input method is dvorak.  This works correctly, and the key is fully usable for me regardless of selected input method.

I'd like to be able to disable yubikey input by default, and use a menubar applet to toggle it on for a few seconds when I need to use it.  The UI for that is trivial enough, and I can use a karabiner variable changed through `--set-variables` to turn yubikey input on and off.

What I'd like to do, though, is to *read* the value of my variable when the applet starts, so I can show the current state correctly.  Since the applet will almost certainly restart more often than karabiner-elements, reading back the current value makes the most sense to me.

An alternative is to reset the state when the applet starts, but that is less nice than asking karabiner-elements—and it would also make it harder to have an "internal" toggle for the state in karabiner-elements that works together with the applet.

**Comment by tekezo** [comment]
You can get variables from `/Library/Application Support/org.pqrs/tmp/karabiner_grabber_manipulator_environment.json`.

**Comment by slippycheeze** [comment]
@tekezo thanks.  reading from that file is, to me, sufficient to achieve my goals.  I appreciate your feedback.

If you consider the issue closed, I'm happy with that.  I don't need the CLI to do the work, just some reasonably stable API or whatever, and that file is enough for me.

**Comment by ssmooncoder** [comment]
is there a way to save variables with the value being a string?

currently the only option is an int

**Comment by pritam12426** [comment]
Can we use the command `'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --set-variables` to  add a new `Add predefined rule`?

If not is there any another way to directly add a new predefined rule in **karabiner-elements**

<img width="1102" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/84720825/0dcaedc8-0e15-4265-b6e6-5b9290f8b5ff">

**Comment by nejmeijer** [comment]
@ssmooncoder Please consider submitting a new issue if you problem is still relevant.
