### ISSUE TITLE
How to set the execution interval between multiple key_codes？

### ISSUE THREAD

**Issue by GanZhiXiong** [pqrs-org/Karabiner-Elements#2664]
For example, the following code has a time interval between 'a' and 'bc' of 900 milliseconds, but I do not know how to set the time interval between 'b' and 'c'?

```json
      {
        "type": "basic",
        "from": {
          "key_code": "1"
        },
        "to": [{
          "key_code": "a"
        }],
        "to_delayed_action": {
          "to_if_invoked": [{
              "key_code": "b"
            },
            {
              "key_code": "c"
            }
          ]
        },
        "parameters": {
          "basic.to_delayed_action_delay_milliseconds": 900
        }
      }
```

**Comment by GanZhiXiong** [comment]
@MuhammedZakir
Do you know how to solve this problem? No one responded for four days.
I guess you should know and look forward to your reply！
😀😀

**Comment by GanZhiXiong** [comment]
@kozo2   @rys   @sitaktif    @gaomd
😂😂Sorry to bother you, but this problem has been bothering me for a long time. I've tried many things and failed, and I really want to know the answer.

Looking forward to your reply！
Thank you very much!

**Comment by MuhammedZakir** [comment]
Between `b` and `c`, will you press any other key? If not, you could try `hold_down_milliseconds`[1]. You can add a modifier key in between `b` and `c` and use `hold_down_milliseconds` option to set your interval. The downside is this will only work if you don't press any other key.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/hold-down-milliseconds/

**Comment by jvansant** [comment]
> [1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/hold-down-milliseconds/

Adding hold-down-milliseconds to the first "too quick" keystroke did the trick for me. Thanks!
