### ISSUE TITLE
karabiner.json fails to parse: cannot use erase() with array

### ISSUE THREAD

**Issue by rbalicki2** [pqrs-org/Karabiner-Elements#2669]
Hi,

I downgraded to 12.95.4, because karabiner refused to open at some point on Catalina.

The advice in https://github.com/pqrs-org/Karabiner-Elements/issues/2473 had me downgrade to 12.10, however, I could not get it to detect any events when built from source. But, I had a 12.95 installer lying around. Now, Karabiner-Elements loads, detects events, etc. However, it refuses to parse my existing karabiner.json file (https://pastebin.com/DL1FjpLq), which was a valid karabiner JSON as far as I know. Key part of the logs:

```
[2021-03-25 23:42:17.753] [error] [grabber] parse error in /Users/robertbalicki/.config/karabiner/karabiner.json: [json.exception.type_error.307] cannot use erase() with array
```

(full logs here https://pastebin.com/D2VkR1Zj).

Is there any way to know why my karabiner.json is invalid?

Thank you!

**Comment by rbalicki2** [comment]
Closing, because one of the backups in ~/.config/karabiner/automatic_backups was valid!

**Comment by jessepeterman** [comment]
I'm having this issue with most recent version, and wiping the karabiner.json doesn't seem to fix it. Old backups aren't working either. It's when I run the cli command `karabiner_cli --select-profile "Default profile"` with one of my created profiles.

**Comment by agronskiy** [comment]
@jessepeterman I'm hitting the same, have you by any chance found a solution?

**Comment by jessepeterman** [comment]
Unfortunately I wasn't able to find any workarounds. I had to downgrade to the previous major version for it to start working again.

**Comment by pagict** [comment]
i've met this error when applying a new-version-generated(14.+) configuration to a older application(12.10.0).
after investigation through the code, this is because the  `to` in `fn_function_keys`, new version defined it as array of objects, while the older version expect to be an object.

once removing the squared brackets in the `fn_function_keys::to`, the error has gone.

hope it helps.
