### ISSUE TITLE
Mac computers with Apple silicon (M1) causes kernel panic with "pmap_tte_remove: non-zero pagetable refcount" error

### ISSUE THREAD

**Issue by tekezo** [pqrs-org/Karabiner-Elements#2672]
This issue was caused by an issue of macOS Big Sur kernel on Apple Silicon that is caused by using DriverKit.
Karabiner-Elements is using DriverKit and the usage invokes the kernel issue and causes kernel panic, and there was no practical workaround to avoid the issue.

However, this macOS problem has been fixed in macOS Big Sur 11.3 Beta!

There is no panics on M1 macs with the latest beta of macOS Big Sur.
https://beta.apple.com/sp/betaprogram/

**Comment by ijoseph** [comment]
Impressive that you were able to find the specific error — out of curiosity, which log file was it hidden in?

**Comment by Fentanyll** [comment]
Any info if Karabiner is working good on the released version of MacOS Bigsur 11.3? Ill download karabiner if its all good now.

**Comment by nealeyoung** [comment]
Seems to be working for me.

**Comment by nickdavies791** [comment]
Big Sur 11.3 is now released out of beta and Karabiner has had no issues thus far for me @Fentanyll

**Comment by anthony-khong** [comment]
FYI, a few people in the other issue thread (#2607) are reporting the same problem with Big Sur 11.3: https://github.com/pqrs-org/Karabiner-Elements/issues/2607#issuecomment-827262709

I think I'll wait for more confirmation before installing Karabiner on my M1 machine!

**Comment by ejsuncy** [comment]
I'm not sure if this is the same issue, but I can't even get the deactivate-reactivate cycle to work. 

After deactivating, I see "Driver was successfully deactivated"

After restarting and clicking activate, the error message appears below the Activate button: "Activation was failed (error: 1)". 

Brand new M1 Macbook, tried the following software versions: Karabiner 13.4.0, 13.3.0, 13.1.0, beta on Big Sur 11.2, Big Sur 11.3, Big Sur 11.4 Beta 

I've verified that my Startup Disk Security is set to Reduced via Recovery Mode.

No Console app Crash Reports

Calling activate from terminal, I get this error message:

```
/Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager activate
activation of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is requested
request of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is failed with error: The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 10.)
```


Checking the system extension list:
```
systemextensionsctl list
1 extension(s)
--- com.apple.system_extension.network_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	DE8Y96K9QP	com.cisco.anyconnect.macos.acsockext (4.9.04053/4.9.04053)	Cisco AnyConnect Socket Filter Extension	[activated enabled]
```

I don't see anything about karabiner.

system.log errors when searching for "org.pqrs":

```
Apr 30 14:19:45 Dans-MacBook-Pro com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.org.pqrs.Karabiner-Elements.Preferences.4708658.4708672(503)> [1166]
Apr 30 14:27:01 Dans-MacBook-Pro com.apple.xpc.launchd[1] (application.org.pqrs.Karabiner-Elements.Preferences.4708658.4708672[60133]): Service exited due to SIGKILL | sent by loginwindow[372]
Apr 30 14:27:01 Dans-MacBook-Pro com.apple.xpc.launchd[1] (application.org.pqrs.Karabiner-Menu.4708630.4708641[1058]): Service exited due to SIGKILL | sent by loginwindow[372]
Apr 30 14:27:01 Dans-MacBook-Pro com.apple.xpc.launchd[1] (org.pqrs.karabiner.NotificationWindow[1047]): Service exited due to SIGKILL | sent by loginwindow[372]
Apr 30 14:27:01 Dans-MacBook-Pro com.apple.xpc.launchd[1] (org.pqrs.karabiner.karabiner_console_user_server[879]): Service exited due to SIGKILL | sent by loginwindow[372]
Apr 30 14:28:49 Dans-MacBook-Pro com.apple.xpc.launchd[1] (org.pqrs.karabiner.NotificationWindow): This service is defined to be constantly running and is inherently inefficient.
Apr 30 14:28:49 Dans-MacBook-Pro com.apple.xpc.launchd[1] (org.pqrs.karabiner.karabiner_session_monitor): This service is defined to be constantly running and is inherently inefficient.
Apr 30 14:28:49 Dans-MacBook-Pro com.apple.xpc.launchd[1] (org.pqrs.karabiner.karabiner_console_user_server): This service is defined to be constantly running and is inherently inefficient.
Apr 30 14:29:06 Dans-MacBook-Pro com.apple.xpc.launchd[1] (org.pqrs.karabiner.agent.karabiner_observer): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
```

**Comment by nicksergeant** [comment]
@ejsuncy just as a side note / heads up, I think there's a separate issue for the disable/enable cycle failing on Big Sur: https://github.com/pqrs-org/Karabiner-Elements/issues/2636. I'm experiencing the same thing as well.

**Comment by ejsuncy** [comment]
@nicksergeant thanks, I actually switched to hammerspoon for my use case, works no problem

**Comment by chinleo** [comment]
Version 11.4 (20F71)  still has the issue , every reboot , crashed with pink screen.
delete `.Karabiner-VirtualHIDDevice-Manager.app`  can resolve it.
