### ISSUE TITLE
Cannot map command+backspace to delete_forward

### ISSUE THREAD

**Issue by lamaledetta** [pqrs-org/Karabiner-Elements#2721]
Hello, 
I want to delete a file in finder using delete_forward physical key. Under mac, to delete file you need to press command+backspace.
I put this together but it doesn't work. Any clue?
Thanks in advance

{
    "title": "Remap DEL_FWD to DELETE",
    "rules": [
        {
            "description": "Remap DEL_FWD to DELETE",
            "manipulators": [
                {
                    "from": {
                        "key_code": "delete_forward",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "delete_or_backspace",
                            "modifiers": {
                                "mandatory": [
                                    "right_command",
                                    "left_command"
                                ]
                            }
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
    ]
}

**Comment by MuhammedZakir** [comment]
1. There are no `mandatory` and `optional` fields in `to.modifiers`. Correct code is `modifiers: ['command']`. You can see this error in `Karabiner-Elements Preferences > Log`.
2. Add a modifier once, in your case, either `command` or `left_command` or `right_command`. Generally, modifier name without left/right is enough. [1]

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/modifiers/

**Comment by lamaledetta** [comment]
I am sorry, I cannot fix it. 

`{
    "title": "Remap DEL_FWD to DELETE",
    "rules": [
        {
            "description": "Remap DEL_FWD to DELETE",
            "manipulators": [
                {
                    "from": {
                        "key_code": "delete_forward"
                    },
                    "to": [
                        {
                            "key_code": "delete_or_backspace",
                            "modifiers": {
                                "mandatory": [ "command" ],
                                "optional": [ "any" ]
                            }
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
    ]
}

`

I'm getting same error than before here:

> [2021-05-24 09:26:27.969] [error] [grabber] karabiner.json error: `to` entry error: `modifiers` error: json must be array or string, but is `{"mandatory":["command"],"optional":["any"]}`

What am I missing?
Thank you guys for the help.

**Comment by MuhammedZakir** [comment]
Like I said, there is no `mandatory` or `optional` field in `to.modifiers`.

```json
{
    "title": "Remap DEL_FWD to DELETE",
    "rules": [
        {
            "description": "Remap DEL_FWD to DELETE",
            "manipulators": [
                {
                    "from": {
                        "key_code": "delete_forward"
                    },
                    "to": [
                        {
                            "key_code": "delete_or_backspace",
                            "modifiers": [ "command" ]
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
    ]
}
```

**Comment by lamaledetta** [comment]
It works now, thank you a lot, sorry for the inconvenience

**Comment by Defite** [comment]
> ```json
> {
>     "title": "Remap DEL_FWD to DELETE",
>     "rules": [
>         {
>             "description": "Remap DEL_FWD to DELETE",
>             "manipulators": [
>                 {
>                     "from": {
>                         "key_code": "delete_forward"
>                     },
>                     "to": [
>                         {
>                             "key_code": "delete_or_backspace",
>                             "modifiers": [ "command" ]
>                         }
>                     ],
>                     "type": "basic"
>                 }
>             ]
>         }
>     ]
> }
> ```

Sorry, but this doesn't work at all.

**Comment by SilentFlute** [comment]
right now at v15.3.0, i use this, and it worked:
```
{
  "description": "use del to delete",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "delete_forward"
      },
      "to": [
        {
          "key_code": "delete_or_backspace",
          "modifiers": [ "left_command" ]
        }
      ]
    }
  ]
}
```
i want to use `Delete` to move file to trash can, not `Cmd+Backspace`, and this config above met my requirements
