### ISSUE TITLE
remapping stopped after updating to big sur 11.4

### ISSUE THREAD

**Issue by ctf0** [pqrs-org/Karabiner-Elements#2730]
is simply remap `§` to **`** & heres my current setup

<img width="1112" alt="Screen Shot 2021-05-27 at 4 15 51 PM" src="https://user-images.githubusercontent.com/7388088/119842536-0d13a680-bf07-11eb-9dbf-c319dcc6861c.png">

device: macbook pro m1

**Comment by DanMHammer** [comment]
I am also experiencing this issue. I juse K-E to remap the keys on my windows keyboard to match mac keyboards. I tried even just testing remapping "1" to "2", and it doesn't work.

I have:

1. Uninstalled and Reinstalled KE
2. Removed karabiner_grabber and karabiner_observer in Privacy and added them back
3. Tried the beta

**Comment by ikakaxi** [comment]
> 我也遇到这个问题。我 juse KE 重新映射我的 windows 键盘上的键以匹配 mac 键盘。我什至尝试过测试将“1”重新映射到“2”，但它不起作用。
> 
> 我有：
> 
> 1. 卸载并重新安装 KE
> 2. 删除了隐私中的 karabiner_grabber 和 karabiner_observer 并将它们添加回来
> 3. 试过测试版

thank,It works

**Comment by benwoodward** [comment]
I had this issue, uninstalling and reinstalling fixed it.

**Comment by ctf0** [comment]
i found the issue, u cant have 2 opposite keybindings added, so in the screenshot case u should either use the first key or the second key, having both wont work as expected.
