### ISSUE TITLE
Swapping caps lock and escape with 'frontmost_application_if' conditional does not work

### ISSUE THREAD

**Issue by dabaci** [pqrs-org/Karabiner-Elements#2737]
I am trying to have caps lock and escape exchanged when I'm in the terminal. I have following rule:

```json
"rules": [
                    {
                        "description": "Swap caps_lock and escape",
                        "manipulators": [
                            {
                                "conditions": [
                                    {
                                        "bundle_identifiers": [
                                            "com.apple.Terminal"
                                        ],
                                        "type": "frontmost_application_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "caps_lock"
                                },
                                "to": [
                                    {
                                        "key_code": "escape",
                                        "repeat": true
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "conditions": [
                                    {
                                        "bundle_identifiers": [
                                            "com.apple.Terminal"
                                        ],
                                        "type": "frontmost_application_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "escape"
                                },
                                "to": [
                                    {
                                        "key_code": "caps_lock",
                                        "repeat": false
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
```
When I'm not in the terminal, everything works as it should. However, when I'm in the terminal, `escape` only acts as `caps_lock` when caps lock is off, and `caps_lock` only acts as `escape` when caps lock is off. In all other cases, each key acts as it would normally. For example, if I start with caps lock off, typing

```
escape
escape
escape
caps_lock
caps_lock
caps_lock
```
outputs
```
caps_lock
escape
escape
caps_lock
escape
escape
```
instead of 
```
caps_lock
caps_lock
caps_lock
escape
escape
escape
```

**Comment by MuhammedZakir** [comment]
That's because you haven't added `caps_lock`/`any` in `from.modifiers.optional` [1]. Normally, I add `caps_lock` to `from.modifiers.optional` if I want that modification to work even when caps lock is on, and add `any` to it, if I want that modification to work regardless of the modifier keys pressed/enabled. For this modification, I recommend adding `any`, as some terminals and cli apps have `shift/ctrl/alt + esc` shortcuts.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/#frommodifiersoptional

**Comment by dabaci** [comment]
> That's because you haven't added `caps_lock`/`any` in `from.modifiers.optional` [1]. Normally, I add `caps_lock` to `from.modifiers.optional` if I want that modification to work even when caps lock is on, and add `any` to it, if I want that modification to work regardless of the modifier keys pressed/enabled. For this modification, I recommend adding `any`, as some terminals and cli apps have `shift/ctrl/alt + esc` shortcut.
> 
> [1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/#frommodifiersoptional

Should this go under the manipulator mapping `caps_lock` to `escape`, the one mapping `escape` to `caps_lock`, or both?

**Comment by MuhammedZakir** [comment]
> Should this go under the manipulator mapping `caps_lock` to `escape`, the manipulator mapping `escape` to `caps_lock`, or both?

Both. Otherwise, the other one won't work when caps lock is on.

**Comment by dabaci** [comment]
This worked, thank you.
