### ISSUE TITLE
Remapped key doesn't pass to next rule when using complex modifications

### ISSUE THREAD

**Issue by colossatr0n** [pqrs-org/Karabiner-Elements#2742]
I have a rule (rule A) in which I've remapped `caps_lock` to set a variable flag if held down or to `escape` if pressed alone. 

There's a second rule (rule B) that remaps `escape` to set other variables. 

In the UI the rules are ordered such that rule A is above rule B. 

I expect the following chaining to happen when I press `caps_lock` by itself:

>`caps_lock -> escape -> set other variables`

This doesn't work for some reason. I may just be confused about the documentation of input source evaluation.

I tried a simple modification by binding `caps_lock` to `escape` through the UI, and pressing `caps_lock` results in the expected outcome. 

Do complex rules not pass remapped keys to the next complex rule? Is there a way to accomplish this?

**Comment by MuhammedZakir** [comment]
> Do complex rules not pass remapped keys to the next complex rule? [...]

No, it doesn't. It only applies a single complex modification, and does not chain multiple modifications. 

Related: https://karabiner-elements.pqrs.org/docs/manual/misc/event-modification-chaining/

---

> [...] Is there a way to accomplish this?

Why don't you move setting variables in rule B to when caps lock is held down in rule A? Why the need for a redirection there?

**Comment by colossatr0n** [comment]
Thank you for the response. The reason for the redirection is that rule B has a complex system of manipulators set up to set these variables given certain conditions, as it's used for vim emulation. Rule A is more for general purpose uses, unrelated to vim emulation.

**Comment by Diaoul** [comment]
Ah that's too bad. I wanted to combine using a different layout (base rule) but use the remapped keys in the next rules.

e.g. I remap `f` to `t` (Colemak) then `Control+t` to `Command+t` (new tab)
