### ISSUE TITLE
fn_function_keys can't map to modifer keys

### ISSUE THREAD

**Issue by eret9616** [pqrs-org/Karabiner-Elements#2743]
![image](https://user-images.githubusercontent.com/12445095/121801570-8ed73400-cc6a-11eb-8ca7-773af0f5b361.png)

![image](https://user-images.githubusercontent.com/12445095/121801557-81ba4500-cc6a-11eb-9705-0ec266febb3d.png)

Mapped function key f1 to command+ a, but in viewer this not work as expected.

Am I doing sth wrong or spelling error?

**Comment by MuhammedZakir** [comment]
You can't put it there. You have to put it in `rules` in `complex_modifications` in `karabiner.json` file. If you have more than one profile, make sure it is inserted in the correct one.

[1] https://karabiner-elements.pqrs.org/docs/json/root-data-structure/#complex_modifications-in-karabinerjson--profiles
