### ISSUE TITLE
Clock delayed actions after key up (not after pressed)?

### ISSUE THREAD

**Issue by lizyn** [pqrs-org/Karabiner-Elements#2746]
I'd like to change the behavior of `Tab` key when held down, as well as set a variable after the key is up, which unset itself **certain milliseconds after the key is up** (This is the hard part. I don't think this can be done by `to_delayed_action`, correct me if I'm wrong). Is there a way to achieve these?

**Comment by MuhammedZakir** [comment]
https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-held-down/
https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-delayed-action/

**Comment by lizyn** [comment]
@MuhammedZakir thanks for your help, I was aware of these two manipulator. The `to_delayed_action` doesn't satisfy my need since it starts clocking as soon as the `from` key is pressed, not after it is up. Maybe I should make this clearer both in the title and the description.

**Comment by MuhammedZakir** [comment]
You could execute a shell command [1][2] in `to_after_key_up` [3].
```
karabiner_cli --set-variables '{varName: 1}'; sleep 0.1; karabiner_cli --set-variables '{varName: 0}';
```

which means, set `varName` to `1`. sleep 100ms and unset `varName`.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/shell-command/
[2] https://karabiner-elements.pqrs.org/docs/manual/misc/command-line-interface/
[3] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-after-key-up/

**Comment by lizyn** [comment]
@MuhammedZakir Thank you! I think that will solve my problem. Never thought `karabiner_cli` could be this useful.

**Comment by IChaneton** [comment]
Hi @MuhammedZakir! I'm very interested in your solution too, but not quite sure I'm getting to it. Would you mind showing it in a Karabiner Modification example?
Thanks!
