### ISSUE TITLE
Question: Is it possible to add tab key on hold as a HyperKey?

### ISSUE THREAD

**Issue by jaideeprana** [pqrs-org/Karabiner-Elements#2748]
The functionality that I am looking for the ability where if I single press tab key it acts like a tab key but on hold it acts like a hyper key.

**Comment by MuhammedZakir** [comment]
E.g. https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/#post-escape-if-left_control-is-pressed-alone

**Comment by jaideeprana** [comment]
Thanks @MuhammedZakir, that resolved the issue for me :)
