### ISSUE TITLE
karabiner does not respect symlinks

### ISSUE THREAD

**Issue by Grazfather** [pqrs-org/Karabiner-Elements#2751]
I symlink my _karabiner.json_ to my dotfiles repo.

When I make a change to the settings, however, karabiner removes the symlink and replaces it with a file with the new settings, when it should follow the symlink and write the new settings there.

**Comment by paulschuberth** [comment]
Did you try linking the entire directory? It works fine for me.
![Screenshot 2021-06-23 at 15 36 30](https://user-images.githubusercontent.com/14339594/123106743-30b00b00-d439-11eb-9d54-5a87219f29f6.png)

**Comment by MuhammedZakir** [comment]
https://karabiner-elements.pqrs.org/docs/manual/misc/configuration-file-path/

**Comment by Grazfather** [comment]
@paulschuberth Yep that works, I just would rather just link the file and thought it was worth mentioning.
@MuhammedZakir thanks for the pointer to the documentation. I assume, then, there's a good reason for that, in which case we could close this issue.

**Comment by MuhammedZakir** [comment]
> @MuhammedZakir thanks for the pointer to the documentation.

You're welcome. :-)

> [...] I assume, then, there's a good reason for that, in which case we could close this issue.

Karabiner watches config directory for changes in config files. As symlinks do not "change" when you update the main file, Karabiner won't be able to automatically reload the config. Unless there is a simple way to add support for symlinks without causing additional problems, **I**, personally, don't think it's worth it.

**Comment by Grazfather** [comment]
Yep that makes sense, though I hadn't thought of it. The issue here was that karabiner trashes the symlink, which could maybe be considered a bug, but I already fixed my dotfiles to use a dir anyway. https://github.com/Grazfather/dotfiles/commit/fc38705693a59aedbd18b993f99c95c39c7de786

**Comment by MuhammedZakir** [comment]
FWIW, you could try hardlinking `karabiner.json` file. I haven't tried it, but it should work.

**Comment by Grazfather** [comment]
It should, but you can't put hardlinks in git, so that defeats the purpose.

**Comment by MuhammedZakir** [comment]
> It should, but you can't put hardlinks in git, so that defeats the purpose.

i didn't know that. But, it looks like latest versions do support hardlink? See https://stackoverflow.com/a/9322283.

**Comment by Grazfather** [comment]
Weird, I wonder how that can be, since the file wouldn't have the same inode on every system.

Either way, I just use a symlink to a dir now :).
