### ISSUE TITLE
Lock key on M1 iMac (base model) doesn't remap

### ISSUE THREAD

**Issue by 0jg** [pqrs-org/Karabiner-Elements#2765]
I don't see an option to remap the Lock key on the new M1 iMac keyboard (base model, without Touch ID). Mapping the "Eject" key appears to disable this key, but any remapping does not work.

(aside: I swear nobody at Apple has ever tested this keyboard with the Lock key—it's so easy to hit it when trying to delete something).

**Comment by luizkowalski** [comment]
Probably duplicated of https://github.com/pqrs-org/Karabiner-Elements/issues/2731

**Comment by 0jg** [comment]
> Probably duplicated of #2731

Yep, didn’t spot that issue! I will close this one.
