### ISSUE TITLE
Enable the "Hack for the bug of Mac OS X" checkbox. - Where is the setting?

### ISSUE THREAD

**Issue by sdr0x07b6** [pqrs-org/Karabiner-Elements#2767]
Command+Shift causes the `DLE` metacharacter to be entered. I don't want to type it.
Upon further investigation, it seems that Carabiner has a setting to fix this.

Enable the "Hack for the bug of Mac OS X" checkbox. (Japanese)

But I can't find this setting anywhere.
Where can I find this setting?

- Karabiner-Elements 13.5
- macOS 11.4

**Comment by MuhammedZakir** [comment]
There is no such setting in Karabiner-Elements. You will have to write complex modifications to fix it. See https://karabiner-elements.pqrs.org/docs/json/.

**Comment by sdr0x07b6** [comment]
@MuhammedZakir

Thank you for pointing this out.

I'm having trouble with `DLE` meta characters frequently when using a text editor.
The problem has not been solved yet, but the title of this issue itself has been solved, so I will close it.

Thank you.
