### ISSUE TITLE
Can I pay someone to write a single remapping for me?

### ISSUE THREAD

**Issue by mckennagene** [pqrs-org/Karabiner-Elements#2781]
I will send $50 on Venmo to anyone who can give me a way to make my MacBook Pro have ctrl-d be the forward delete function? (like it is in bash, gmail, etc). I see a number of remapping "suites" out there that do lots of key mappings including this one, but I want just this one and not all the others. I've tried to do it myself, but I got frustrated and ran out of time.

**Comment by MuhammedZakir** [comment]
Notes:
1. I haven't tested this. So when you import this, see if there is any errors in `Karabiner-Elements Preferneces > Log`. 
2. This will work even if caps lock is on. If you don't want that, remove `optional` field and also remove comma at the end of `mandatory` field.

To import this:
1. Save this in `~/.config/karabiner/assets/complex_modifications/control_d_to_forward_delete.json`.
2. Import it - `Karabiner-Elements Preferences > Complex Modifications`.
```
{
  "title": "Ctrl+d -> forward delete",
  "rules": [{
    "description": "Ctrl+d -> forward delete",
    "manipulators": [{
      "type": "basic",
      "from": {
        "key_code": "d",
        "modifiers": [{
          "mandatory": ["control"],
          "optional": ["caps_lock"]
        }]
      },
      "to": [{
        "key_code": "delete_forward"
      }]
    }]
  }]
}
```

**Comment by mckennagene** [comment]
Thank you! 

I got it added into Karabiner Elements, and then restarted Karabiner-Elements just to be sure. 

It isn't working for me, but let me explain how i'm testing. 

The main "app" I'm trying to get this to work in is Word for Web (Office 365) running in Chrome browser. Even with this change added to Karabiner Elements, Word for Web still won't support this. However, I can't fully rule out that Word for Web, among it's many many deficiencies, is doing something to break this. 

So I'm trying to test another way as well. There are many other apps where, even without Karabiner, ctrl-d is forward delete already (Word desktop, terminal (zsh), gmail, google docs, textedit, slack ... ). 

So what I tried to do is change your rule to make ctrl-d be just capital D. 
 "to": [{
        "key_code": "D"
      }]

With that rule in place, all of the apps that supported ctrl-d=>forward_delete already, remained unchanged. ctrl-d in those apps was still forward-delete, not "D", so it seems to me the rule isn't having any impact.

any thoughts, or additional tests I could try?

**Comment by MuhammedZakir** [comment]
> 2021-07-29 09:07:08.119] [error] [grabber] karabiner.json error: from error: modifiers error: json must be object, but is [{"mandatory":["control"],"optional":["caps_lock"]}]

It's not working because of this error. Try this:

```
{
  "title": "Ctrl+d -> forward delete",
  "rules": [{
    "description": "Ctrl+d -> forward delete",
    "manipulators": [{
      "type": "basic",
      "from": {
        "key_code": "d",
        "modifiers": {
          "mandatory": ["control"],
          "optional": ["caps_lock"]
        }
      },
      "to": [{
        "key_code": "delete_forward"
      }]
    }]
  }]
}
```

**Comment by MuhammedZakir** [comment]
> So what I tried to do is change your rule to make ctrl-d be just capital D.
> "to": [{
> "key_code": "D"
> }]

If you want capital/shifted characters, you will have to do:

```
"to": [{
  "key_code": "d",
  "modifiers": ["shift"]
}]
```

**Comment by mckennagene** [comment]
It works! You are awesome. Thank you. Please email me mckennagene at gmail  and we can arrange how I can pay you.

**Comment by MuhammedZakir** [comment]
> It works! You are awesome. Thank you. Please email me mckennagene at gmail and we can arrange how I can pay you.

https://karabiner-elements.pqrs.org/docs/pricing/ :-)

\* Be careful if someone sends you an emal asking it. That's not me!

**Comment by mckennagene** [comment]
Ok, I sent $50 to support the project. Thanks again!
