### ISSUE TITLE
caps_lock lag?

### ISSUE THREAD

**Issue by kennir** [pqrs-org/Karabiner-Elements#2782]
There was about a half-second lag every time I clicked CAPs on internal keyboard, The keyboard doesn't respond during this time. 

My OS: Big Sur 11.5
Karabiner-elements:  13.5.0

Thanks

**Comment by kennir** [comment]
Hi @Infra1515 

I notice that the CPU usage of NotifyWindow becomes extremely high after I press caps_lock, It's very strange

**Comment by kennir** [comment]
It's gone after I upgrade macOS to 11.5.1

**Comment by Infra1515** [comment]
> It's gone after I upgrade macOS to 11.5.1

Glad its sorted for you as well,
all the best.

**Comment by kennir** [comment]
Thanks a lot
