### ISSUE TITLE
Shortcut for function keys checkbox 

### ISSUE THREAD

**Issue by shtreifling** [pqrs-org/Karabiner-Elements#2783]
Hi! Is there a way to add a shortcut for function keys checkbox in _Karabiner-Elements Preferences -> Function Keys_?

<img width="436" alt="image" src="https://user-images.githubusercontent.com/18242330/127776265-93eb0c34-127a-4ad7-b66d-6651981d3b22.png">

My user case:

When i press fn key my   '**u**' button become 4, my '**i**' button become 5 etc.
basically I emulate a Num Pad on MacBook keyboard when i press fn key.

Sometimes I have to introduce a lot of numbers and will be very helpful to have this shortcut on this checkbox in Karabiner-Elements Preferences. It will be like **Num Lock button** on long keyboards.
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/18242330/127776666-dafb9e5e-10e4-4a7e-9d38-62dd3bafa84f.png">

Thanks

**Comment by MuhammedZakir** [comment]
From what I understand, that setting only effects function keys (`F1`, `F2`, ...). You does not need to fiddle with that setting for your indented usage.

**Comment by shtreifling** [comment]
You misunderstood me. @MuhammedZakir 

I created my own function keys with Karabiner. 
example:

Fn + j -> 1
Fn + k -> 2
Fn + k -> 3
Fn + u -> 4
Fn + i -> 5
Fn + o -> 6
Fn + / -> +
Fn + ; -> -
Fn + p -> *
Fn + 0 -> ÷

this will give me something like this 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/18242330/127781267-2f1d276e-adf7-460d-aaab-3facae847466.png">

and this checkbox will give me ability NOT TO HOLD **Fn** button when i need to use my numeric Fn keys
it will act like num lock button
<img width="444" alt="image" src="https://user-images.githubusercontent.com/18242330/127781318-5d8e28e8-53a0-46ee-bdbd-8a1c9a35eb06.png">

Or maybe someone can give me an advice how to turn on Fn keys and turn off with some default MacOs shortcuts or scripts

**Comment by MuhammedZakir** [comment]
Okay, I get it now. Have you tried sticky modifier key option [1]? Mapping `fn` to `sticky fn` should work.

[1] https://karabiner-elements.pqrs.org/docs/help/how-to/sticky-modifier-key/

**Comment by shtreifling** [comment]
@MuhammedZakir 

Is don't work as is expected.

Now is:
1. Press [Fn] key (sticky [Fn] is on)

2. Press one letter 

3. Sticky [Fn] becomes off

Expected:

1. Press [Fn] key (sticky [Fn] is on)

2. Press one letter 

3. Sticky [Fn] is still on
 
4. Press second letter

...

Press 1. Press [Fn] key (sticky [Fn] is off)

Would you have some recommendation?

**Comment by MuhammedZakir** [comment]
I thought it will "stick" until that modifier is tapped again (I haven't used it).

You can use variables to achieve it.
```
{
  "description": "Use Fn to toggle number layer",
  "manipulators": [
    {
      "type": "basic",
      "conditions": [{
        "type": "variable_if",
        "name": "fn-number-layer",
        "value": 1
      }],
      "from": {
        "key_code": "fn",
        "modifiers": {
          "optional": ["caps_lock"]
        }
      },
      "to_if_alone": [{
        "set_variable": {
          "name": "fn-number-layer",
          "value": 0
        }
      }]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "fn",
        "modifiers": {
          "optional": ["caps_lock"]
        }
      },
      "to_if_alone": [{
        "set_variable": {
          "name": "fn-number-layer",
          "value": 1
        }
      }]
    }
  ]
}
```

**Comment by MuhammedZakir** [comment]
1. I have added `caps lock` to `from.optional.modifiers` to make it work when `caps lock` is on. You can remove it if you don't want that.
2. `to_if_alone` will make it work only when you press it alone (a la tapping). If you want to type numbers while holding `fn` (e.g. when you just want to type 1 or 2 numbers), then replace `to_if_alone` block with these in second manipulator:
```
"to": [
  {
    "set_variable": {
      "name": "fn-number-layer",
      "value": 1
    }
  },
  {
    "key_code": "fn"
  }
],
"to_after_key_up": [{
  "set_variable": {
    "name": "fn-number-layer",
    "value": 0
  }
]],
"to_if_alone": [{
  "set_variable": {
    "name": "fn-number-layer",
    "value": 1
  },
  "halt": true
}]
```

**Comment by MuhammedZakir** [comment]
Check the doc for detailed explanations:

- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-alone/
- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-after-key-up/
- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/halt/
- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/set-variable/
- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/variable/

**Comment by clemsam** [comment]
I admit to not having read all above posts – but have used an AppleScript/shell-command/osascript for a long time to toggle "function" in System Preferences. Like that:
    
                        {           "description": "  Toggles  fn  >  Ctrl-Cmd-Alt-K =====================================================================================",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "k",
                                    "modifiers": {
                                        "mandatory": [
                                            "control",
                                            "command",
                                            "option"
                                        ]
                                    }
                                },
                                "parameters": {
                                    "basic.to_delayed_action_delay_milliseconds": 1000
                                },
                                "to": [
                                    {
                                        "shell_command": "osascript -e 'tell application \"Karabiner-Elements\" to activate'"
                                    }
                                ],
                                "to_delayed_action": {
                                    "to_if_invoked": [
                                        {
                                            "shell_command": "osascript -e 'tell application \"System Events\"\n click radio button \"Function keys\" of tab group 1 of window \"Karabiner-Elements Preferences\" of application process \"Karabiner-Elements\"\n click checkbox 1 of tab group 1 of window \"Karabiner-Elements Preferences\" of application process \"Karabiner-Elements\"\n quit application  \"Karabiner-Elements\"\n end tell'"
                                        }
                                    ]
                                },
                                "type": "basic"
                            }
                        ]
                    },

**Comment by MuhammedZakir** [comment]
> is anyway to map a shortcut toggle this function on and off
> for example ctrl+j can turn on and off this function
> `![image](https://user-images.githubusercontent.com/13769444/149484773-ca006f5d-fb12-4d30-94e6-612b1bb8a1c4.png)`
> `![image](https://user-images.githubusercontent.com/13769444/149484828-ebb81c10-363f-4633-9f38-f4b963a38bc5.png)`

You could do it with AppleScript. I haven't tried it, so can't help you on that part.
