### ISSUE TITLE
Using multiple of the same device, each with different device IDs

### ISSUE THREAD

**Issue by sundeepgupta** [pqrs-org/Karabiner-Elements#2800]
I have two foot pedals plugged in and they are being combined into a single device. 

Devices JSON from EventViewer:
```json
  {
        "device_id": 4295312946,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": true,
        "is_pointing_device": true,
        "location_id": 336789504,
        "product_id": 57382,
        "transport": "USB",
        "vendor_id": 6790
    },
    {
        "device_id": 4295350768,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": true,
        "is_pointing_device": true,
        "location_id": 337788928,
        "product_id": 57382,
        "transport": "USB",
        "vendor_id": 6790
    },
```

The `device_id`s are different but the app is showing them as a single device:
<img width="1112" alt="Screen Shot 2021-08-25 at 3 31 54 PM" src="https://user-images.githubusercontent.com/2365037/130853279-e804b692-16fa-45a0-aa8c-d2f9cd3b3a72.png">

I was hoping to use each foot pedal independently so I could assign a different key to each. Is that possible? 

I'm on version 13.5.0 (latest as of now).

**Comment by MuhammedZakir** [comment]
You don't need to `repeat` flag in `to` event as its default value is `true`.

---

1. Make sure the the rule works without `location_id`.
2. If the rule works, make sure the `location_id` is correct.

**Comment by sundeepgupta** [comment]
I tried adding the most basic complex modification, and it's not working. I tried quitting and relaunching the app and EventViewer but that didn't help. What am I doing wrong? 

```json
{
    "description": "test",
    "manipulators": [
        {
            "from": {
                "key_code": "B"
            },
            "to": [
                {
                    "key_code": "fn"
                }
            ],
            "type": "basic"
        }
    ]
}
```
[karabiner.json 2.zip](https://github.com/pqrs-org/Karabiner-Elements/files/7093361/karabiner.json.2.zip)

**Comment by MuhammedZakir** [comment]
```
                "key_code": "B"
```

It's `b`, not `B`.

**Comment by sundeepgupta** [comment]
🤦 I'm not sure how that became an uppercase `B`. Thank you. 

Also, I got it working. I noticed the values for `location_id`, `product_id`, and `vendor_id` needed to be integers. The web tool is making them strings. Is this a known issue? Otherwise, happy to put together a separate issue concerning this.

**Comment by sundeepgupta** [comment]
I've been trying to use the pedals this morning which are mapped to `left_control` and `right_command`. They work fine individually, but when I press them together, the second pedal doesn't register. 

On the keyboard, when I press the two keys together this shows up in EventViewer:
![image](https://user-images.githubusercontent.com/2365037/132562779-35117626-47f0-4251-a0ce-ec03f4eed475.png)

But with the pedals, when I press both of them together, this shows up:
![image](https://user-images.githubusercontent.com/2365037/132563972-25ab431a-8130-4e62-bbd8-00e31fbb0a0d.png)


It seems that when one of the pedals is pressed, the custom mapping for the other pedal is ignored. 

Further, what is also strange is that it also broke holding down `left_control` on the keyboard while pressing the right pedal (`right_command`). When I use the same combination in the reverse order though it works:
![image](https://user-images.githubusercontent.com/2365037/132563912-36141aeb-250c-466d-a445-3068506e8a5c.png)

**Comment by MuhammedZakir** [comment]
Have you added `any` to `from.modifiers.optional`[1]? If you haven't, `b` won't be manipulated when you press it while a modifier is held.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/#with-modifiersoptional

---

> Also, I got it working. I noticed the values for `location_id`, `product_id`, and `vendor_id` needed to be integers. The web tool is making them strings. Is this a known issue? Otherwise, happy to put together a separate issue concerning this.

Issues about the web tool doesn't belong here as it is not created/maintained by Karabiner dev.

**Comment by sundeepgupta** [comment]
> Have you added `any` to `from.modifiers.optional`[1]? If you haven't, `b` won't be manipulated when you press it while a modifier is held.
> 
> [1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/#with-modifiersoptional
> 

This makes everything work. Many thanks! I'm starting to get a better feel for the config now. 🙏 

> Issues about the web tool doesn't belong here as it is not created/maintained by Karabiner dev.

Got it - I see there's already an open issue regarding this actually: https://github.com/genesy/karabiner-complex-rules-generator/issues/22

**Comment by MuhammedZakir** [comment]
You're welcome! :-)

If your issue is solved, please close this. :-)
