### ISSUE TITLE
Touch ID lock button doesn't work

### ISSUE THREAD

**Issue by LikoZ1** [pqrs-org/Karabiner-Elements#2805]
macOS version: 12.0 beta 6
Karabiner version: latest
(You can confirm the version in “Misc & Uninstall” tab in Karabiner Preferences.)
Your Mac hardware: iMac 24" 
Your keyboard hardware: Magic keybaord with touch ID and numeric keypad

lock button does not work. and no option to assign it.

**Comment by chavyleung** [comment]
Same here!

macOS version: 11.5.2
Karabiner version: 13.6.0
Your Mac hardware: MacBook Pro (15-inch, 2018)
Your keyboard hardware: Magic keybaord (New) **without** touch ID

**Comment by LikoZ1** [comment]
any update??
please fix this issue....
also would be nice: delete as move to trash without disabling the delete white renaming
backspace as folder up without disabling backspace while renaming.
enter as open but not while renaming.
text direction (aligned left for english and aligned right for right to left languages)

**Comment by tekezo** [comment]
I supported Touch ID at v13.7.2.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by chavyleung** [comment]
> I supported Touch ID at v13.7.2.
> Please confirm the latest beta version.
> 
> How to upgrade to the latest beta version:
> ![Check for beta updates](https://camo.githubusercontent.com/f0d3dcebbd2e46b18b8d57821e1acbbdabaaf6d9135b707a2667d2e00ccd7f0e/68747470733a2f2f6b61726162696e65722d656c656d656e74732e707172732e6f72672f646f63732f6d616e75616c2f6f7065726174696f6e2f636865636b2d666f722d757064617465732f696d616765732f6b61726162696e65722d656c656d656e74732d636865636b2d666f722d757064617465732d626574614032782e706e67)

Didn't works

macOS version: 11.6
Karabiner version: 13.7.2
Your Mac hardware: MacBook Pro (15-inch, 2018)
Your keyboard hardware: Magic keybaord (New) without touch ID

**Comment by tekezo** [comment]
@chavyleung 
Thank you for feedback!

The recent update does not support the models without Touch ID.
We will need information about your device to support it.
Please be patient as we prepare a way to investigate.

**Comment by LikoZ1** [comment]
Thank you for the update. but there are still issues. the screen goes black from time to time and also slows the system. regularay, when pressing the lock/touch id button the system locks and shows all the users login screen. with this update, after a while, when pressing lock button thr screen goes black and returns, not locking. I am also using bettertouchtool. Let me know if there could be a conflict. Right now, the only thing I need from Karabiner is to set the left control to be as left command.

**Comment by tekezo** [comment]
@LikoZ1 
Thank you for your confirmation!

I improved the Touch ID behavior at v13.7.4.
Please confirm the latest beta again.

Detail:
Karabiner-Elements emulate the behavior of pressing Touch ID by software due to the limitations of macOS.
I was missing the screen lock behavior because I mistakenly thought it was sleep only.

**Comment by tekezo** [comment]
@chavyleung

I need your device information to support it.
Could you show me events when you press Touch ID?
You can confirm the events as follows.

- Upgrade Karabiner-Elements to v13.7.4.

- Disable Magic Keyboard in Karabiner-Elements Preferences > Devices tab.
<img width="1000" alt="Screen Shot 2021-09-24 at 23 16 08" src="https://user-images.githubusercontent.com/659178/134691479-dfa8e672-2691-48fa-a5b5-ee141f49482f.png">

- Open EventViewer. <https://karabiner-elements.pqrs.org/docs/manual/operation/eventviewer/>

- Press any keys and confirm the events are shown in Main tab.
<img width="1100" alt="Screen Shot 2021-09-24 at 23 16 14" src="https://user-images.githubusercontent.com/659178/134691852-3f958ddc-277d-493a-bd9a-b100a32ac91b.png">

- Press Touch ID and show me the result. The Touch ID events are shown in Main tab or Unknown Events tab.
<img width="1100" alt="Screen Shot 2021-09-24 at 23 14 57" src="https://user-images.githubusercontent.com/659178/134692276-caa7a926-29f2-4ae9-aefd-038fa9ed40cf.png">

**Comment by chavyleung** [comment]
@tekezo
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/29748519/134693157-c691ee2d-793f-47c2-a0e1-3ca8a5b38f90.png">

**Comment by tekezo** [comment]
@chavyleung
I believe Lock key on Magic Keyboard without Touch ID is supported at v13.7.5.
Please confirm the latest beta version.

**Comment by chavyleung** [comment]
@tekezo 
It works, thanks a lot.

😘😘😘

**Comment by CodeBear228** [comment]
It works ! Amazing Karabiner Group 😘

**Comment by hoeni** [comment]
Is there any magic required? I have Monterey (12.0.1) with Karabiner-Elements 14.3.0 and a new Apple Magic Keyboard (without Numkeys, US-Layout, without TouchID), but the lock key does not produce any input, neither in the "Main" tab nor in the "Unknown Events" Tab.

I would desperately like to remap that key, because I accidentally log myself out twice an hour, by hitting it 🙃

**Comment by akxcv** [comment]
Hello! I have an M1 iMac 24' with a Touch ID keyboard, and Touch ID doesn't work after installing Karabiner-Elements 14.3.0.

**Comment by mabam** [comment]
Hi!
Same here. I’m using Karabiner Elements 14.10.0 on an M1 MacBookPro18,1 running Ventura 15.1. The Touch ID doesn’t produce any input here either (EventViewer doesn’t show a thing about that key).

**Comment by clarkewd** [comment]
Thank you so much for your work on Karabiner Elements. It's amazing even if this issue cannot be fixed.

I just wanted to add that I am having a similar issue as mabam. With `14.11.0` I can remap the lock key on an external keyboard ( "Apple Magic Keyboard with Touch ID") but not on the builtin "Apple Internal Keyboard" of an M1 Macbook Pro.

For the external keyboard I use this in the json config:

    "from": {
        "consumer_key_code": "menu"
    }

But with `Karabiner-EventViewer` no events show when I press the lock button. The computer locks and there are no events after unlocking. This also includes the `Unknown Events` tab.

Let me know if I can send more information to help.

**Comment by mabam** [comment]
There seems to be a workaround. Can’t test it myself anytime soon though (the M1 MacBook is my brother’s):

In Terminal, enter
```
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0xC00000040, "HIDKeyboardModifierMappingDst":0x700000066}]}'
```
to map the Touch ID to the Power Button.

This can be automated using a Launch Agent (on user level) or Launch Daemon (on system level). See
https://www-heise-de.translate.goog/ratgeber/Tipp-Touch-ID-Button-des-MacBooks-als-vollwertige-Power-Taste-verwenden-7308927.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp
for full info.

Then, Karabiner should be able to grab it as Power Button.

**Comment by clarkewd** [comment]
Wow, thanks @mabam! After running the key no longer locks the mac (good step!) but I'm not seeing any events show up in `Karabiner-EventViewer`. I'll do a little research and see if maybe I need to set the `HIDKeyboardModifierMappingDst` to something else. Thank you!!

**Comment by clarkewd** [comment]
Even though it doesn't show up in the event viewer the remap does work. If I set it to a letter key it will type that letter. However, I have set it to `F18` as suggested in [this post](https://www.naseer.dev/post/hidutil/), the from value being `0xC00000040` and the to value being `0x70000006D` and then in my application I set the hotkey as F18 so this works fine for what I wanted it to do. Thanks very much @mabam for pointing me in the right direction :)

**Comment by mabam** [comment]
Good you made it work for you!

And since you found out it doesn’t enable Karabiner to grab the key, there’s no need for me to test anymore. Good to know though.

**Comment by J0HAN85** [comment]
@mabam Tnx! I remapped my Touch ID butten to F13 and used BetterTouchTool to active my screensaver!

**Comment by DominikMroz** [comment]
> @mabam Tnx! I remapped my Touch ID butten to F13 and used BetterTouchTool to active my screensaver!

Hey @J0HAN85 - Can you list out the exact steps of how you did this?
