### ISSUE TITLE
Even after deleting, the panel panic came.

### ISSUE THREAD

**Issue by chaehuiseon** [pqrs-org/Karabiner-Elements#2807]
After installing your software, the panel panic came. so deleted it. but this panel panic is still occuring.

I have a m1 macbook 16ram 256gb macos bigsur

**Comment by tekezo** [comment]
Did you uninstall Karabiner-Elements using uninstaller?
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

If so, your kernel panic is caused by another reason.
Please send a bug report to Apple.
https://github.com/pqrs-org/Karabiner-Elements/issues/2809

**Comment by seathasky** [comment]
Had the same issue myself, had to reinstall macOS from scratch to fix this. I don't reccomend using Karabiner in it's current state with the latest version of Big Sur

**Comment by chaehuiseon** [comment]
> Had the same issue myself, had to reinstall macOS from scratch to fix this. I don't reccomend using Karabiner in it's current state with the latest version of Big Sur

Thank you for sharing  how to solve. I also solved it by reinstalling macOS.

**Comment by seathasky** [comment]
pqrs really needs to post warnings about this that it's not compatible with Big Sur. Btw, I updated to Monterey and it works fine, just heads up @chaehuiseon
