### ISSUE TITLE
Pass through keys?

### ISSUE THREAD

**Issue by NeighNeighNeigh** [pqrs-org/Karabiner-Elements#2808]
Hey guys, 

Wondering it's at all possible in KE to _pass through_ the keys when performing an action?
For example, could I set up `from: command+F19` `to: button1`
but pressing `command+F19` will still send the original `command+F19`, but also send `button1`?

**Comment by MuhammedZakir** [comment]
No. You will have to explicitly send that.

```
"to": [
  {
    "key_code": "f19",
    "modifiers": "command
   },
  {
    "pointing_button": "button1"
  }
]
```

**Comment by NeighNeighNeigh** [comment]
Ah damn, I thought this may have been a cheeky way to remap a standard key (with or without modifiers) to include a mouse press while held.

**Comment by MuhammedZakir** [comment]
As `to` events are always send, you can add keys you're modifying to `to` and mouse buttons to `to_if_held_down`. Of course, this is a bit cumbersome if there are lots of such keys -- in that case, I recommend you to use a script (e.g. Ruby [1]) to generate a config.

[1] E.g. https://github.com/pqrs-org/KE-complex_modifications/blob/main/src/json/yubikey_disable_keystrokes.json.rb. You can also browse other configs there for inspiration. You can greatly simplify your config by using Ruby helper library - https://github.com/pqrs-org/KE-complex_modifications/tree/main/src/lib.

**Comment by NeighNeighNeigh** [comment]
Ooo that first suggestion sounds perfect for my needs as I only have about 6 keys that need this functionality! You have no idea how much of a relief this is, thank you!

**Comment by NeighNeighNeigh** [comment]
Oh damn, so close! I tested this and it sends the standard key, but releases it before the mouse button is pressed. I need them to be held down together. 

Here's my code

```json
{
	"title": "MouseKey test",
	"rules": [{
		"description": "MouseKey test - remaps F16 to spacebar + button1",
		"manipulators": [

			{
				"type": "basic",
				"from": {
					"key_code": "f16"
				},
				"parameters": {

					"basic.to_if_held_down_threshold_milliseconds": 0
				},
				"to": [{
					"key_code": "spacebar"
				}],
				"to_if_held_down": [{
					"pointing_button": "button1"
				}]
			}





		]
	}]
}
```

**Comment by MuhammedZakir** [comment]
What you want is not possible. Use AppleScript -- key down spacebar, left click, and key up spacebar, or use HammerSpoon to achieve that.

**Comment by NeighNeighNeigh** [comment]
Okay yeah thank you, this was where we ended up in the other thread. Sorry, I just thought I may have worked out a tricky way around using another tool. Your solution here is actually useful for some of my other keys, so thank you for your help.
