### ISSUE TITLE
Issue with running karabiner_cli to emulate passthrough mode

### ISSUE THREAD

**Issue by ksrb** [pqrs-org/Karabiner-Elements#2810]
# Preface
I'm trying to emulate passthrough mode using 2 profiles and a bash script and have a working setup see [this comment](https://github.com/pqrs-org/Karabiner-Elements/issues/1977).

The setup in the comment works but uses `open` and will spawn a terminal, I would prefer to use `sh` to have the script run in the background but there is an issue.

# Problem
When running `karabiner_cli --select-profile` in a shell script through `shell_command` karabiner is only able to see a single profile. 

This can be seen with the following setup that uses the `--list-profile--names` command with 2 profiles:

**karabiner.json**
```json
{
    "from": {
        "simultaneous": [
            {
                "key_code": "tab"
            },
            {
                "key_code": "escape"
            }
        ]
    },
    "to": [
        {
            "shell_command": "sh ~/list-profile-names > ~/log.txt"
        }
    ],
    "type": "basic"
}
```
Setup at least 2 profiles and run the above with <kbd>tab</kbd> + <kbd>ESC</kbd>

**~/list-profile-names**
```bash
#!/usr/bin/env bash

karabiner_cli="/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli"
"$karabiner_cli" --list-profile-names
```
In `~/log.txt` `--list-profile-names` is only showing 1 profile (the current one) for me.

**Comment by MuhammedZakir** [comment]
`shell_command` is run using `sh`, so you don't need to add that yourself.

```
"shell_command": "~/list-profile-names > ~/log.txt"
```

Does this solve your problem? If not, which version are you using?

**Comment by ksrb** [comment]
Actually never tried running without `sh` but seems like it's been fixed by latest release https://github.com/pqrs-org/Karabiner-Elements/releases/tag/v13.7.0.

**Comment by MuhammedZakir** [comment]
FYI: if the `shell_command`'s exit code is non-zero, latest KE version will log the output. You can view them in the `Log` tab.
