### ISSUE TITLE
bug: `shell_command` is partly broken in 13.6.0

### ISSUE THREAD

**Issue by babygau** [pqrs-org/Karabiner-Elements#2812]
@tekezo, after updating to 13.6.0, `shell_command` is not working properly as previous 13.5.0. 
To be more specific, all of my `yabai` command is now asked for `env USER` which is already set. I switch back to the last 13.5.0 and this weird problem is gone and all of my `shell_command` working as expected.

<img width="1663" alt="Screen Shot 2021-09-05 at 4 09 53 pm" src="https://user-images.githubusercontent.com/1514823/132122085-ed93f877-e87b-449c-829a-c9ef928f5616.png">

<img width="1663" alt="Screen Shot 2021-09-05 at 3 52 53 pm" src="https://user-images.githubusercontent.com/1514823/132122082-dd234417-dd3a-45c7-be5f-c7d7fb0de035.png">

**Comment by johnnypea** [comment]
Having the same issue. Thanks.

**Comment by tekezo** [comment]
Thank you for feedback!
I fixed this issue at v13.6.1. Please confirm the latest beta version.

How to upgrade Karabiner-Elements to the latest beta version:
<https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/>

**Comment by babygau** [comment]
@tekezo many thanks for instant response. I could confirm that the bug is fixed with new beta version 🎉

**Comment by dreyks** [comment]
weirdly, i'm seeing this behaviour in 14.4.0. I'm opening an IDE through shell_command and it doesn't get anything in the `PATH`
