### ISSUE TITLE
Can't invert brackets ()

### ISSUE THREAD

**Issue by locksoft** [pqrs-org/Karabiner-Elements#2814]
I'm trying to swap some symbol keys, as my keyboard is in a different language.

As an example I want that, when I press shift-9 (that currently types a closed bracket ")"), it actually trigger the shift-8.
But my rule is completely ignored. This is what I've added to .json file:

{
                        "description": "( su tastiera USA",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "9",
                                    "modifiers": "shift"
                                },
                                "to": [
                                    {
                                    "key_code": "8",
                                    "modifiers": "shift"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },

What am I mistaking?

Thanks.

**Comment by locksoft** [comment]
Edit: I think I've solved this way (but I'm still not sure why the previous one doesn't work):

                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "9",
                                    "modifiers": {
                                      "mandatory": [
                                        "shift"
                                      ]
                                    }
                                  },
                                  "to": [
                                    {
                                      "key_code": "8",
                                      "modifiers": [
                                        "shift"
                                      ]
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "from": {
                                    "key_code": "0",
                                    "modifiers": {
                                      "mandatory": [
                                        "shift"
                                      ]
                                    }
                                  },
                                  "to": [
                                    {
                                      "key_code": "9",
                                      "modifiers": [
                                        "shift"
                                      ]
                                    }
                                ],
                                "type": "basic"
                            }

**Comment by locksoft** [comment]
Also, is it possible to use this method to add unexacting symbols? I don't know why but Big Sur doesn't add the "«" quoting symbol when I press option-1, while it adds the "»" when I press shift-option-1.
I can't find anyware a key_code for "«".

**Comment by MuhammedZakir** [comment]
First one didn't work because `from.modifiers` is incorrect. You can see the error in `Krabiner-Elements Preferences > Log`. In `from`, `modifiers` is an object with two keys - `optional`, and `mandatory`, whose values are a list of modifiers. Whereas, in `to`, `modifiers` is a list of modifiers. See the doc -- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/.

---

> Also, is it possible to use this method to add symbols that aren't in the keyboard?

No. (but see below.)

> I don't know why but Big Sur doesn't add the "«" quoting symbol when I press option-1, while it adds the "»" when I press shift-option-1.

If the keyboard layout you use has `«`, then you can insert it by pressing the corresponding keys. For instance, you will get `»` if you press `shift+option+1`, unless you have mapped `shift+option+1` to something else, or are using it as keyboard shortcut, You can check which symbols your keybaord layout supports using on-screen keyboard. It is also helpful to get the correct key combination to insert a symbol.

> I can't find anywhere a key_code for "«".

Karabiner deals with keycodes of a keyboard and how they get interpreted depends on macOS. Also, general keyboards doesn't have those symbols. That's why, you will have to also press `option` to access those special symbols.

**Comment by locksoft** [comment]
Thanks for your answer. I'm very new to Karabiner and I'm not good with coding, so I'm still learning. :)

https://i.postimg.cc/wjMdxb0D/Schermata-2021-09-08-alle-16-12-45.png

https://i.postimg.cc/XvxHZVqJ/Schermata-2021-09-08-alle-16-14-52.png

The weird thing is that MacOS correctly show the first three symbols on the keyboard (under numbers 1,2 and 3) but there's no way to type them, even if I use the virtual keyboard.
I don't think that key combination is already taken by another command as nothing happens when I press it.

**Comment by MuhammedZakir** [comment]
I suspect you haven't focused on an input field [1] when you typed them (so you couldn't "see" the symbols you typed), or you didn't press correct key combination. I haven't used Italiano keyboard layout, but have used others and I'm able to type the symbols using them.

If, for some reason, you are still not able to type them, please post a screen record of you typing in EventViewer input field while a virtual keyboard is shown.

[1] a field where you can type.

**Comment by locksoft** [comment]
Here's the video:

http://www.lemonskin.net/io/[MEDIA]/video/Keyboard.mp4

How you can see, the key press is recognized, but Big Sur doesn't do anything.

**Comment by MuhammedZakir** [comment]
From what I can see, some keyboard shortcuts are interfering. Have you checked keyboard shortucts in  System Preferences?

**Comment by locksoft** [comment]
Yes, it's what I think too. I've checked keyboard shortcuts and no one has that key combination.
I've also tested other keyboard but nothing changes.

**Comment by MuhammedZakir** [comment]
Np. :-D

If your issue is solved, please close this. :-)

**Comment by locksoft** [comment]
Sure, thanks again.
