### ISSUE TITLE
How to map a Apple keyboard key combo to the PC Pause/Break key?

### ISSUE THREAD

**Issue by halloleo** [pqrs-org/Karabiner-Elements#2820]
What is Karabiner's  key code / key string for the Pause/Break key on a PC keyboard?

I do not have a keyboard like that (I have only a narrow Apple keyboard), so I cannot use the EventViewer.

Also, is there somewhere a list of all keycodes?

Many thanks for any pointers!

**Comment by MuhammedZakir** [comment]
It's plausibly `pause`.

You can find keycodes from the list of keys you get when you add new modification in Simple Modification. The data used is available here -- https://github.com/pqrs-org/Karabiner-Elements/blob/main/src/apps/PreferencesWindow/Resources/simple_modifications.json.

**Comment by halloleo** [comment]
Thanks for this. Great list.

(PS: Can't get Pause/Break keyfor Ctrl-Alt-Break to work in my VMWare as on a PC, but there are many other potential layers where things go wrong...)
