### ISSUE TITLE
One to (3)Many (single-modifer) with Simultaneous output

### ISSUE THREAD

**Issue by adamras** [pqrs-org/Karabiner-Elements#2831]
Good evening, all.
I am attempting to output three keystrokes that happen at the same time.  The issue that I am having is that each keystroke that I am attempting to automate is pressed and released one at a time.  I have attempted to use "simultaneous" in the to: but it was not havin' that.  Anyway, any wisdom would be appreciated.  Thanks.  
What I have so far is:
```
"rules": [
                    {
                        "description": "Simultaneously press",
                        "manipulators": [
                            {
                                "from": {
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    },
                                    "simultaneous": [
                                        {
                                            "key_code": "equal_sign"
                                        },
                                        {
                                            "key_code": "delete_or_backspace"
                                        }
                                    ]
                                },
                                "to": [
                                    {
                                        "key_code": "s"
                                    },
                                     {
                                        "key_code": "e"
                                    },
                                     {
                                        "key_code": "x"
                                    },
                                     {
                                        "key_code": "vk_none"
                                    }
                                   
                                    ],
                                "type": "basic"
```

**Comment by MuhammedZakir** [comment]
Not possible using (only) Karabiner. Try send those events using AppleScript (replace `to` events with):
```json
{
  "shell_command: "osascript -e 'tell application \"System Events\"' -e 'key down \"s\"' -e 'delay 0.1' -e 'key down \"e\"' -e 'delay 0.1' -e 'key down \"x\"' -e 'delay 0.1' -e 'key up \"x\"' -e 'delay  0.1' -e 'key up \"e\"' -e 'delay 0.1' -e 'key up \"s\"' -e 'end tell'"
}
```

Note:
1. You may have to increase the delay to `0.2` or more if `0.1` is not sufficient.
2. This may not work because `key down <key>` may not work with non-modifier keys.

**Comment by adamras** [comment]
> Not possible using (only) Karabiner. Try send those events using AppleScript (replace `to` events with):
> 
> ```json
> {
>   "shell_command": "osascript -e 'tell application \"System Events\"' -e 'key down \"s\"' -e 'delay 0.1' -e 'key down \"e\"' -e 'delay 0.1' -e 'key down \"x\"' -e 'delay 0.1' -e 'key up \"x\"' -e 'delay  0.1' -e 'key up \"e\"' -e 'delay 0.1' -e 'key up \"s\"' -e 'end tell'"
> }
> ```
> 
> Note:
> 
> 1. You may have to increase the delay to `0.2` or more if `0.1` is not sufficient.
> 2. This may not work because `key down <key>` may not work with non-modifier keys.

Thank you very much for the reply.   I appreciate the information.  I'll give it a try and report back.

**Comment by adamras** [comment]
> Not possible using (only) Karabiner. Try send those events using AppleScript (replace `to` events with):
> 
> ```json
> {
>   "shell_command": "osascript -e 'tell application \"System Events\"' -e 'key down \"s\"' -e 'delay 0.1' -e 'key down \"e\"' -e 'delay 0.1' -e 'key down \"x\"' -e 'delay 0.1' -e 'key up \"x\"' -e 'delay  0.1' -e 'key up \"e\"' -e 'delay 0.1' -e 'key up \"s\"' -e 'end tell'"
> }
> ```
> 
> Note:
> 
> 1. You may have to increase the delay to `0.2` or more if `0.1` is not sufficient.
> 2. This may not work because `key down <key>` may not work with non-modifier keys.

That works fantastically.  I, of course, being a goof decided to use something "funny" as the example of keys I wants to press concurrently thinking that it would be simple to swap in the real ones I wanted to use.  One of the keys that I wanted to hit is the delete key.  That doesn't appear to work using "key press" but instead I will have to attempt to work in key code 51.  
Anyway, I wanted to report back to say that your example worked great.  non-modifer keys and all.

**Comment by MuhammedZakir** [comment]
> [...] That doesn't appear to work using "key press" but instead I will have to attempt to work in key code 51.

I think you can do `key down <key_code>`, or `key down (key code <key_code>)`.

**Comment by nejmeijer** [comment]
Closing this in favour of #2842.
