### ISSUE TITLE
Multiple "to.shell_command" are invalid in v13.7.0

### ISSUE THREAD

**Issue by oniatsu** [pqrs-org/Karabiner-Elements#2833]
Multiple "to.shell_command" are invalid in v13.7.0.
Is this what you intended?

For example:
```json
{
    "from": {
        "key_code": "any key"
    },
    "to": [
        {
            "shell_command": "some command"
        },
        {
            "shell_command": "some command"
        }
    ],
    "type": "basic"
}
```

In the previous version, the multiple command were valid.

**Comment by oniatsu** [comment]
The last shell_command is only valid.
```json
        {
            "shell_command": "some command" // NOT work
        },
        {
            "shell_command": "some command" // work
        }
```

**Comment by tekezo** [comment]
The new behavior is intended.
I changed this behavior to prevent remaining slow shells command in the queue.

Please combine multiple commands into one shell_command.

```shell
    "to": [
        {
            "shell_command": "foo && bar"
        },
```

**Comment by oniatsu** [comment]
Thank you for your response. I understand.
