### ISSUE TITLE
[Feature Request] Remap 'lock' key on apple imac keyboard

### ISSUE THREAD

**Issue by mal567** [pqrs-org/Karabiner-Elements#2837]
It would be great if Karabiner could remap the 'lock' key (furthest top right key) on magic keyboard that ships with M1 iMac. 

There does not currently seem to be any option to select this key for remapping.

**Comment by MuhammedZakir** [comment]
Have you seen https://github.com/pqrs-org/Karabiner-Elements/issues/2805?

**Comment by mal567** [comment]
No hadnt seen that but the update does the trick! Thanks!
