### ISSUE TITLE
Logical "or"

### ISSUE THREAD

**Issue by Muirium** [pqrs-org/Karabiner-Elements#2838]
Hi folks,

I have some "launcher" scripts I use in Karabiner for various apps and frequently used documents. The one I include here is pressed with the adjacent mods: Fn + Control + Option + Command and the 2 key. All these launchers of mine are the same mods, just triggering on a different alphanumeric.

They work great on my MacBook Air's built in keyboard. But I also like my classic mechanical keyboards, which don't have Apple's "fn" key (or indeed a convenient spot to add it down there). So for them I'd like to use the Shift key. This is an awkward chord to press on my Mac's internal keyboard though, so really I want:

Fn + Control + Option + Command **OR** Shift + Control + Option + Command in my "from": statement.

Must I duplicate all my rules? I tried using two different "from": statements like this, which resulted in no parse errors, but only fires on the "shift" version of the rule, the original "fn" version is now ignored.
```
{
	"title": "Launchers",
	"rules":
	[
		{
			"description": "👩🏻‍💻 Fn / Shift + Ctrl + Option + Command + 23ADBSW ⇨ Launchers",
			"manipulators": [
				{
				"description": "👩🏻‍💻 Fn / Shift + Ctrl + Option + Command + 2 ⇨ Scrivener 2021",
				"type": "basic",
					"from": {
						"key_code": "2",
						"modifiers": {
							"mandatory": [
											"fn",
											"control",
											"option",
											"command"
										 ]
						}
					},
					"from": {
						"key_code": "2",
						"modifiers": {
							"mandatory": [
											"shift",
											"control",
											"option",
											"command"
										 ]
						}
					},
					"to": [
						{
							"shell_command": "open '/Users/john/Documents/2021.scriv/2021.scrivx'"
						}
					]
				},
```
So, is there a way to perform a logical "or" in Karabiner's "from": statements? Or should I copypasta my way to a less elegant solution?

Duplicating everything isn't so bad. I just want to know if I'm missing something artful, first.

**Comment by MuhammedZakir** [comment]
"or" in `from` is not available. You'll have to duplicate them.

In JSON or similiar formats, if you use same key more than once, generally the latter will overwrite former and in the end, only the last one will be available.

**Comment by Muirium** [comment]
Fair enough. I guessed this would be the case, just wanted to be sure I wasn’t missing a neat trick. Thanks for the explanation Muhammed!
