### ISSUE TITLE
[Feature request] Add --select-next-profile command

### ISSUE THREAD

**Issue by Dimentium** [pqrs-org/Karabiner-Elements#2844]
Hi!

Is it possible - to add --select-next-profile, or something like --select-profile %next% to karabiner-cli for cycling profile switching?
Now I map one hotkey in each profile to select next by name and it works.

Thank you!

**Comment by Dimentium** [comment]
Hi!

Is it possible - to add --select-next-profile, or something like --select-profile %next% to karabiner-cli?
Now I map one hotkey in each profile to select next by name and it works.

Thank you!

**Comment by nejmeijer** [comment]
Closing this feature request in favour of #2937. The workaround described in #3878 might be of interest for the time being.
