### ISSUE TITLE
Remap à (a-grave) to Enter

### ISSUE THREAD

**Issue by trebaud** [pqrs-org/Karabiner-Elements#2847]
Hi :wave: 

I got a CA french mac keyboard and I would like to remap the à (a-grave) key to Enter. I've been looking through your documentation for a way to do this, but I didn't find anything. Thank you!

**Comment by MuhammedZakir** [comment]
What does EventViewer [1] show when you press that key?

[1] Karabiner-EventViewer.app or `Karabiner-Elements menu > Launch EventViewer`.

**Comment by trebaud** [comment]
Thank you I found a way , I mapped it to the code of `\` which is the map a a-grave in english keyboards
