### ISSUE TITLE
Installing Karabiner-Elements disable some keys at 14-inchi M1 Pro Japanese keyboard layout

### ISSUE THREAD

**Issue by lilpacy** [pqrs-org/Karabiner-Elements#2868]
Installing Karabiner-Elements and allowing karabiner_grabber to monitor input make some keys disabled at 14-inchi M1 Pro Japanese keyboard layout without any Karabiner-Elements configurations.

1. Allow monitor input in Security & Pirvacy
![Screen Shot 2021-10-30 at 17 09 57](https://user-images.githubusercontent.com/26163436/139525660-e8beca14-5e88-4a73-a2cd-5a63a111c811.png)

2. And then these two keys gonna be disabled (cannot type _ and ¥ even if I push down these keys)
![420px-KB_Japanese_Mac_-_Apple_Keyboard_(MB869JA) svg](https://user-images.githubusercontent.com/26163436/139525436-4567b8b7-c225-4f63-897d-93dd4424765b.png)

3. But they are recognized at Karabiner-EventViewer as international1 and international3 key code
![](https://user-images.githubusercontent.com/26163436/139525841-577e072f-5ea4-45d0-a1c2-82e0b4ef5148.png)

Perhaps, there are more disabled key. But I haven't find them yet.

**Comment by lilpacy** [comment]
[Additional Information]

OS: macOS Monterey MacBook Pro
Chip: Apple M1 Pro
Version: Karabiner-Elements 13.7.0

And now, I found that other keys like [ and ] are mixed in some way.

**Comment by tekezo** [comment]
Does this issue happen with built-in keyboard?
If so, I'll add workaround for this issue.

For other keys, it depends macOS keybaord type configuration.
Please confirm your keyboard type configuration is correct.
https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-keyboard-type/

**Comment by lilpacy** [comment]
> Does this issue happen with built-in keyboard?

Yes. This issue happened with built-in keyboard. 

I tried it out, and then the problem disappeared. 

Thank you so much for your adding the workaround!!

**Comment by tekezo** [comment]
I haven't added workaround for this issue yet, so if the problem has disappeared, then either Karabiner-Elements is disabled, or this was a temporary problem on macOS.

If this issue recurs for any reason, please show me the built-in device information (screen shot of Devices tab as follows)
https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-devices/

**Comment by lilpacy** [comment]
> Please confirm your keyboard type configuration is correct.

I guess my macbook's type configuration was not correct. (Note I didn't change any type configuration after I started using the macbook. So does enabling Karabiner-Elements automatically change type configuration to not JIS? But I don't know the details.)

> If this issue recurs for any reason, please show me the built-in device information (screen shot of Devices tab as follows)

Now, I can type any keys so comfortably with Karabiner-Elements and built-in/external keyboard as other macbook that I used before even when I restart the macbook. But I can show you my built-in device information as a reference. Thank you so much.

![Screen Shot 2021-10-30 at 23 17 06](https://user-images.githubusercontent.com/26163436/139537041-0a91431f-2879-40fd-aefa-be10b76898f6.png)

**Comment by lilpacy** [comment]
Here is more specific workaround.
Changing to country code to 45 solved the problem fyi.
I really appreciate your big support.  
  

![Screen Shot 2022-05-08 at 18 20 56](https://user-images.githubusercontent.com/26163436/167289870-bee32f9a-72a5-4bf1-9417-abd1630eae9a.png)
