### ISSUE TITLE
Unexpected Application Launch in v14.0.0

### ISSUE THREAD

**Issue by moriwang** [pqrs-org/Karabiner-Elements#2871]
I noticed a feature v14.0.0 added.
> Supported application launcher keys (Mail, Browser, Calculator, etc.) which are belong to HID Consumer Usage Page and Application Launch Buttons Usage.

I programmed a complex modification to switch input method when I press F12(keyboard icon) on K810, the keycode was `eject`.
![ezgif-7-478125dcda23](https://user-images.githubusercontent.com/9151525/139706219-c88963e0-5928-4ae1-9bba-76fd4fe5d539.gif)
 
Works fine before v14.0.0. But now it opens calculator and switch input method at the same time for me. Quite annoying.

Is there any method to disable or override the new feature?

And here's my config file. Github can't upload json file, so I changed it to txt file.
[karabiner.txt](https://github.com/pqrs-org/Karabiner-Elements/files/7454604/karabiner.txt)

**Comment by tekezo** [comment]
Thank you for feedback!
Please try to disable al_calculator.

<img width="1000" alt="Screen Shot 2021-11-02 at 10 01 26" src="https://user-images.githubusercontent.com/659178/139770257-4ab50392-28d2-4453-a278-99de3ccc7d8a.png">

**Comment by moriwang** [comment]
> Thank you for feedback! Please try to disable al_calculator.

It works. Thanks a lot.
