### ISSUE TITLE
"ioreg -l" hangs with karabiner-elements version 14.2.0

### ISSUE THREAD

**Issue by mad00314** [pqrs-org/Karabiner-Elements#2882]
I started using the Band-in-a-Box application.
This application internally calls "ioreg -l".
Then "ioreg -l" process hang (process's cpu 100%. I can't kill it.)

I use the macOS Monterey (version 12.0.1) on Mac mini (2018).
karabiner-elements version 13.7 0 : no problem
version 14.2.0 and 14.2.2 : "ioreg -l" => hang.
("ioreg" => no problem)

Would you like to reproduce it?
Can "ioreg -l" be executed correctly with the latest version 14.2.0 or 14.2.2 ?

**Comment by mad00314** [comment]
my keyboard hardware: RealForce Compact (Topre Corporation)

**Comment by tekezo** [comment]
#2883
