### ISSUE TITLE
No way to use default mapping for function keys?

### ISSUE THREAD

**Issue by DBZFYAM** [pqrs-org/Karabiner-Elements#2884]
I often switch between external keyboards (Logitech MX Keys at home and an Apple Keyboard with numpad at work). Installed Karabiner to switch a few keys on the Logitech, but by default it also remaps the function keys which means the mute, volumen up and volume down for example aren't set correctly. For example:

Config in Karabiner:
f10 = mute
f11 = volume down
f12 = volume up

However the Logitech has this setup:
f10 = next song
f11 = mute
f12 = volume down
f13 = volume up (key doesn't specify f13 on the key itself by the way)

But as there is no config for f13, I can't map them back to the original keyboard layout. 

So I lose the ability to mute and to decrease volume. What kind of helps is turning on "Use all F keys as standard function keys", but then I have to press the FN key to get the media keys (while I would want the media keys to be the default and when pressing FN, it should switch to F1 keys etc.)

Does anyone know how to get around this?

**Comment by MuhammedZakir** [comment]
In Simple modifications, select your logitect keyboard in devices drop-down list and remap `f10`-`f13` to what you want.

**Comment by DBZFYAM** [comment]
I tried to do that indeed but the settings only go up to F12 so then the icons on the keyboard don’t match with the media functions

**Comment by MuhammedZakir** [comment]
That shouldn't be the case. In "Simple modifications", in `function keys` category in `from` keys, there should be upto `f20`, and in `to` keys, upto `f24`.

**Comment by DBZFYAM** [comment]
Ah completely looked at the wrong tab haha, thank you very much! Seems to work perfectly now!
