### ISSUE TITLE
Is it possible to recognize the text being entered, and can it be used as a condition?

### ISSUE THREAD

**Issue by hicaicai** [pqrs-org/Karabiner-Elements#2888]
I have set many letter combinations to trigger but it conflicts with some words, I don't particularly want to change other letter combinations because it's not particularly convenient, so I'm asking if it's possible to not trigger while I'm typing text,Or type text and leave it for a certain amount of time before it triggers

**Comment by MuhammedZakir** [comment]
It is not possible to detect that. But, you can do what you want by setting some variable or switching to another profile without those remappings before typing. Then, undo that when you finish typing. It's not what you wanted as you will have to do them manually.

**Comment by hicaicai** [comment]
Thank you for your reply, I also thought of a way, similar to your method.
