### ISSUE TITLE
Old mapping seem to be persistent

### ISSUE THREAD

**Issue by Shrulik** [pqrs-org/Karabiner-Elements#2893]
I used to have a mapping of CTRL -> CMD and the other way around, which I run sometimes when using a particular app. 

 I now want to do this per app and know it is possible in karabiner-elements, but it seems the old mapping is somehow "stuck". I uninstalled and reinstalled the app, I made sure ~/.config/karabiner/karabiner.json is empty except for the default mapping of F1 and so on. 'ctrl' or 'cmd' don't appear in the file, yet this mapping is still enforced whenever I open the app.

What do I do ?

**Comment by MuhammedZakir** [comment]
Did you remap them in System Preferences? There is an option to remap modifiers for keboards in System Preferences.

See if there is any rule in Simple Modification for your devices (go through devices list one by one).

**Comment by Shrulik** [comment]
Yes,  thank you. That was the issue. Karabiner defines a new virtual keyboard that doesn't share the modification I made at the macOS level to the modifiers.
