### ISSUE TITLE
Why is optional caps_lock required for the from key_code?

### ISSUE THREAD

**Issue by elkind00** [pqrs-org/Karabiner-Elements#2899]
I recently created a very simple from/to keymap using complex modifications (while figuring out how to create a condition for a keyboard type), and this was the "from" portion:

```
  "from": {
    "key_code": "hyphen"
  },
```
My simple keymapping didn't work.  I had to add the caps_lock as an optional modifier before it would work:

```
  "from": {
    "key_code": "hyphen",
    "modifiers": {
      "optional": [
        "caps_lock"
      ]
    }
  },
```

Though it worked, interestingly if I hold down the caps_lock key the mapping stops working and the hyphen is produced.  I use KE to swap caps_lock/left_control, so I temporarily removed that mapping but the problem persisted, now with the original caps_lock key.

I'm trying to understand why the optional caps_lcok modifier is required and why when you press it the mapping stops working.

**Comment by elkind00** [comment]
I'd really appreciate if someone could comment.  It would help to know if this is just a minor oddity of Karabiner Elements or if this is something that I'm misunderstanding.

**Comment by elkind00** [comment]
Still interested in understanding this one.

**Comment by MuhammedZakir** [comment]
Are you saying that if you didn't add `caps_lock` to `from.modifier.optional`, that modification won't work even when `caps_lock` is off? The expected behavior without `from.modifiers` is that the modification should work if no modifier is held down.

**Comment by elkind00** [comment]
Yes, that's correct, the modification didn't work without caps_lock in from.modifier.optional, but before replying to you I decided to reverify the behavior by enabling my test rule again and it is now working.  I see a new version of Karabiner-Elements was installed on March 1.

Thanks for getting back to me.  Sorry I didn't think to retest first.

**Comment by elkind00** [comment]
I fear the possibility of user error since no one else reported this, but I think it was a recent release that fixed this.
