### ISSUE TITLE
Karabiner is not working. Help.

### ISSUE THREAD

**Issue by g7-bit** [pqrs-org/Karabiner-Elements#2917]
I am using an external keyboard.
I have allowed permission in permission in privacy settings. have included both grabber and viewer in input section.
karabiner viewer is showing entered keys.

Adding even simple modification keys it does not do anyting.

I am unable to remap any key.

Help!!!!

**Comment by kogaba** [comment]
I think providing the version and os version you are using, would be not a bad idea...

**Comment by g7-bit** [comment]
I am on MacOs 12.0.1 Monterey, using latest using latest Karabiner-Elements 14.3.0

**Comment by g7-bit** [comment]
> I think providing the version and os version you are using, would be not a bad idea...

I'am using macOs 12.0.1 Monterey, Using latest Karabiner-elements 14.3.0

**Comment by g7-bit** [comment]
> I think providing the version and os version you are using, would be not a bad idea...

help
