### ISSUE TITLE
Unable to type grave accent mark

### ISSUE THREAD

**Issue by iseykim** [pqrs-org/Karabiner-Elements#2943]
Using ARM Mac, macOS Monterey. Karabiner Elements latest version

I cannot type the backtick (grave accent key). It comes out as §. I've deleted all the configurations, made new profiles but unable to type ` without exiting Karabiner.

§ and holding shift and grave gives me ±

**Comment by Muirium** [comment]
Could be this:

https://github.com/pqrs-org/Karabiner-Elements/issues/2961

**Comment by iseykim** [comment]
@Muirium that fixed it!

**Comment by iseykim** [comment]
I put Karabiner-Elements Preferences > Virtual keyboard > Country Code: 1. 

Fixed the issue.

**Comment by Muirium** [comment]
This may be one of those things Karabiner needs in its manual.
