### ISSUE TITLE
Build From Source Fail

### ISSUE THREAD

**Issue by tami5** [pqrs-org/Karabiner-Elements#2978]
Hey @tekezo. Thanks for such an amazing tool.

I'm trying to build from source but the build fail. I followed the steps mentioned in the [README.md#steps](https://github.com/pqrs-org/Karabiner-Elements/blob/e3fd1e70235fa9595e1e7da5ce0a8409a995e591/README.md#steps).

### Requirements installed with their version:

- xz: `5.2.5`
- xcode-select `2392`
- xcodegen `2.25.0`
- cmake: `3.22.1`

### User Environment:
- macos: 12.1
- chip: m1

### Expected: 
Karabiner-Elements-VERSION.dmg in the current directory.

### Actual:

Full log: https://pastebin.com/djXHsHGx

### Question 

Is there a requirement I'm missing or a patch I need to apply. Thanks

**Comment by tekezo** [comment]
Thank you for feedback!

That's an unfamiliar error.
Are you using Xcode version 13.2.1 (13C100)?

**Comment by tami5** [comment]
Yah exactly, my version is my Xcode is `Version 13.2.1 (13C100)`. hmmm maybe something todo with CMake installation method? I've installed it using nixpkgs.

For comparison:
[cmake brew formula](https://github.com/Homebrew/homebrew-core/blob/8d3b6253520220ae29ab58d9a1f1d6be9267f11f/Formula/cmake.rb)
[cmake nix derivation](https://github.com/NixOS/nixpkgs/blob/6c4b9f1a2fd761e2d384ef86cff0d208ca27fdca/pkgs/development/tools/build-managers/cmake/default.nix)

**Comment by tekezo** [comment]
cmake is used only in tests.

The expected output is as follows:

```shell
cd src/lib/libkrbn
make clean all

rm -fr *.xcodeproj
rm -fr build
xcodegen generate
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/tekezo/Karabiner-Elements/src/lib/libkrbn/krbn.xcodeproj
xcodebuild -configuration Release -alltargets SYMROOT="/Users/tekezo/Karabiner-Elements/src/lib/libkrbn/build"
```

But yours 

```shell
make -C ../../../lib/libkrbn
xcodegen generate
   Generating plists...
   Generating project...
   Writing project...
created project at $BASEDIR/src/lib/libkrbn/krbn.xcodeproj
No "base" settings found
No "debug config" settings found
No "release config" settings found
No "macOS" settings found
xcodebuild -configuration Release -alltargets SYMROOT="$BASEDIR/src/lib/libkrbn/build"
```

Are you using old version of Karabiner-Elements?

**Comment by tami5** [comment]
> Are you using old version of Karabiner-Elements source code?

Nah I just cloned the rpeo on my machine as follow up for debugging I making for a nix derivation to build karabiner. 

Does having karabiner installed already on my machine already may cause this odd problem?

**Comment by tekezo** [comment]
xcodegen does not output `created project` instead of `Created project`.
https://github.com/yonaskolb/XcodeGen/search?q=created+project

Are you using modified xcodegen?

**Comment by tami5** [comment]
> xcodegen does not output `created project` in your log instead of `Created project`.
> 
> https://github.com/yonaskolb/XcodeGen/search?q=created+project
> 
> 
> 
> Are you using modified xcodegen?

Oh sorry this just me while trying to make sense of the logs, Made to lower case by mistake I'm sure.

My version of xcodegen is 2.25.0 built from source. What version are you using maybe current master has breaking changes?

**Comment by tekezo** [comment]
> What version are you using

I'm using xcodegen 2.25.0 installed by `brew install xcodegen`.

Continuous Integration build also uses the same version.
https://github.com/pqrs-org/Karabiner-Elements/blob/main/.github/workflows/ci.yml

It seems xcodegen failed to generate properly xcodeproj as far as the follwoing messages which are only in your logs.

```
created project at $BASEDIR/src/lib/libkrbn/krbn.xcodeproj
No "base" settings found
No "debug config" settings found
No "release config" settings found
No "macOS" settings found
```

Could you try rebuild your xcodegen with options which are used in brew?
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/xcodegen.rb

**Comment by tami5** [comment]
> Could you try rebuild your xcodegen with options which are used in brew?
> https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/xcodegen.rb

I have somewhat identical installation method. 
https://github.com/tami5/system/commit/0fd74a82f5637d999d43c860ab63d3096a4b318e

> It seems xcodegen failed to generate properly xcodeproj as far as the following messages which are only in your logs.

You ware right, After building xcodegen locally, the project built successfully 🤕🤕. 
other than: `productsign: error: Could not find appropriate signing identity for “”.` The dmg file did get produced. 

Sandbox build environments are a big thing in nix, I just wonder what is it xcodegen was trying to get from user environment to be working properly.

Thanks so much @tekezo and sorry for the headache that is caused entirely on my part.
