### ISSUE TITLE
Complex behavior configuration with combination of: alone, hold, double-clicked

### ISSUE THREAD

**Issue by sleepymalc** [pqrs-org/Karabiner-Elements#3016]
Hi, I'm currently configuring my own remapping, and I come up with the following:
```json
{
	"description": "Right Shift as Delete if alone",
	"manipulators": [
		{
			"from": {
				"key_code": "right_shift",
				"modifiers": {
					"optional": [
						"any"
					]
				}
			},
			"parameters": {
				"basic.to_if_held_down_threshold_milliseconds": 1
			},
			"to": [
				{
					"key_code": "right_shift",
					"lazy": true
				},
				{
					"set_variable": {
						"name": "right_shift pressed",
						"value": 1
					}
				}
			],
			"to_if_alone": [
				{
					"key_code": "delete_or_backspace"
				}
			],
			"to_if_held_down": [
				{
					"key_code": "right_shift"
				}
			],
			"to_delayed_action": {
				"to_if_invoked": [
					{
						"set_variable": {
							"name": "right_shift pressed",
							"value": 0
						}
					}
				],
				"to_if_canceled": [
					{
						"set_variable": {
							"name": "right_shift pressed",
							"value": 0
						}
					}
				]
			},
			"type": "basic"
		}
	]
},
{
	"description": "double Right Shift as delete",
	"manipulators": [
		{
			"type": "basic",
			"from": {
				"key_code": "right_shift"
			},
			"conditions": [
				{
					"type": "variable_if",
					"name": "right_shift pressed",
					"value": 1
				}
			],
			"to_if_held_down": [
				{
					"key_code": "delete_or_backspace"
				}
			]
		}
	]
}
```
Basically, I want to achieve the following:
1. If hold, then capitalize things I typed as usual.
2. If alone, then delete one char.
3. If double-clicked **and** hold, then keep deleting until I release.

Seems like the above configuration is not supported by the app. Now, with the first part, I can achieve 1. and 2., while for the third part, when I first press the right shift, the variable is correctly set as 1, but the double-clicked event just doesn't function right. Any helps?

**Comment by MuhammedZakir** [comment]
KE uses the first matched rule. In this case, the first rule will always be executed when you press `shift`. Either add a condition to first rule to _not_ trigger it when the variable `right_shift pressed` is `1`, or (better IMO) move your second rule above the first one.

**Comment by sleepymalc** [comment]
@MuhammedZakir Ahh, that makes sense. Now I'm going to tune the parameter to let it works smoother.
