### ISSUE TITLE
Using mouse button as shift modifier

### ISSUE THREAD

**Issue by adrianroe** [pqrs-org/Karabiner-Elements#3018]
I am trying to use my mouse buttons 4 & 5 as shift (or control) modifiers for keyboard input, so that I can press a mouse button and then e.g. qwert to get QWERT.

I've registered these as "Simple modifications" but if I open e.g. a terminal, hold either of the buttons and then type is see the unmodified character.  I'm on Monterey 12.2.1

Karabiner Event Viewer reports exactly the same events if I hold the mouse button down and type as if I hold an actual shift button and type, but the modifier does not seem to apply to the keypress...

![image](https://user-images.githubusercontent.com/399913/155546883-982e7b1c-04df-414d-8d72-849d997689a7.png)

**Comment by Bashwy** [comment]
the simple modifications are kinda weka and yeah it doesn't work, it does if you add it as a complex modification though. add this into your json file https://pastebin.com/7hLsDBND

**Comment by adrianroe** [comment]
Many thanks for the response Bashwy.  I've tried the complex modification route, also with no success.  My karabiner.json with your pastebin entry is [here](https://gist.github.com/adrianroe/054c2e2ffe9e09f5a7efb64c39b3f8e3) in case I've done anything obviously wrong...

Thanks again for your help - much appreciated!

**Comment by adrianroe** [comment]
That did the trick (changing the devices tab settings)!  Many thanks @MuhammedZakir @Bashwy for your help.
