### ISSUE TITLE
Not detecting Razer Blackwidow V3 Mini over bluetooth

### ISSUE THREAD

**Issue by dill0wn** [pqrs-org/Karabiner-Elements#3025]
This keyboard has several modes:
Wired, Bluetooth (with 3 pairable devices), and 2.4Ghz dongle.

When USB connected, Karabiner successfully detects this keyboard a separate device in the device dropdown. However, Karabiner does not detected when connected via bluetooth. Global modifications "For all devices" also do not apply to this keyboard.

I believe this is the relevant information (I grabbed from System Information): 

```
Bluetooth Controller:
  Address:	F8:FF:C2:4C:A6:0A
  State:	On
  Chipset:	BCM_4364B3
  Discoverable:	Off
  Firmware Version:	v75 c4195
  Product ID:	0x0001
  Supported services:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  Transport:	UART
  Vendor ID:	0x004C (Apple)
Paired Bluetooth Devices:
  BlackWidow V3 Mini:
  Address:	EC:FA:5E:BF:3F:5C
  Connected:	Yes
  Vendor ID:	0x1532
  Product ID:	0x0272
  Services:	0x400000 < BLE >
```

I'm on macOS 12.2.1,  Karabiner Elements 14.4.0.

**Comment by adriel** [comment]
Did you check that it's recognising it in the Karabiner-EventViewer app?

**Comment by dill0wn** [comment]
Looks like it works now in 14.6.0
