### ISSUE TITLE
"thinkpad keyboard 2" issue when using Bluetooth

### ISSUE THREAD

**Issue by hellobpm** [pqrs-org/Karabiner-Elements#3029]
Hello,

I'm using the "thinkpad keyboard 2" keyboard.
And connected to the MacBook via Bluetooth.
In this case, the combination "left shift + left option(alt) + right arrow" does not work.

Confirmed that "right arrow" key event while holding "left shift + left option(alt)" does not appear in Karabiner-EventViewer.

Same for both MacBooks.
- macbook pro intel
- MacBook Air m1

Is it possible to solve the problem?

**Comment by MuhammedZakir** [comment]
Does it work when Karabiner-Elements is not running? Quit KE and see whether EventViewer shows "left_shift+left_option+right_arrow" when pressed.

**Comment by hellobpm** [comment]
Running Karabiner-EventViewer after Karabiner-Elements is closed doesn't work either.
This only works if both Karabiner-Elements and Karabiner-eventViewer are killed.

**Comment by MuhammedZakir** [comment]
When you mention "closed", do you mean "quit" or just closing the KE window?

> This only works if both Karabiner-Elements and Karabiner-eventViewer are killed.

If so, this is probably a bug and is out of my hand.

**Comment by MuhammedZakir** [comment]
Can you create a new profile, activate it and try pressing `left_shift+left_option+right_arrow`? Also, how many devices does KE show for you keyboard in Devices tab?

**Comment by hellobpm** [comment]
After testing, the problem is now clear.
This seems to be a problem with the keyboard itself, independent of Karabiner-Elements.
On "Thinkpad keyboard 2" bluetooth connection, "left_shift + left_option + right_arrow" combination does not work regardless of Karabiner-Elements launch/exit.
Again, the combination "left_shift + left_option + right_arrow" does not work on a Bluetooth connection, not on a USB dongle connection on a "Thinkpad keyboard 2".
Thank you for responding to help us find the cause of the problem.
I'll close the issue.

**Comment by hellobpm** [comment]
After testing, the problem is now clear.
This seems to be a problem with the keyboard itself, independent of Karabiner-Elements.
On "Thinkpad keyboard 2" bluetooth connection, "left_shift + left_option + right_arrow" combination does not work regardless of Karabiner-Elements launch/exit.
Again, the combination "left_shift + left_option + right_arrow" does not work on a Bluetooth connection, not on a USB dongle connection on a "Thinkpad keyboard 2".
Thank you for responding to help us find the cause of the problem.
I'll close the issue.
