### ISSUE TITLE
New icons proposal

### ISSUE THREAD

**Issue by Zabriskije** [pqrs-org/Karabiner-Elements#3031]
Hi folks, it's my first time on GitHub so I'm sorry if this is the wrong way to propose things.
Anyway, the existing icons have an old feeling for me, so I've made new ones.

<img width="256" src="https://user-images.githubusercontent.com/101254295/159171455-93cbcee9-5e67-4c3c-99ea-1696beff368f.png">

Original files (PNG + ICNS): [Karabiner.zip](https://github.com/pqrs-org/Karabiner-Elements/files/8311618/Karabiner.zip)

**Comment by iandundas** [comment]
Nice, they look good. No replies up to now - you might possibly get more traction if you were open a pull request.
