### ISSUE TITLE
Feature request: Scripted activation of Complex Modifications

### ISSUE THREAD

**Issue by bland328** [pqrs-org/Karabiner-Elements#3034]
After deployment of a new or modified file to `/Users/username/.config/karabiner/assets/complex_modifications/`, it would be wonderful if there were a scriptable, non-GUI method to add new rules, and to remove and re-add changed rules.

It is fairly straightforward to create a workflow which distributes updated Complex Modifications files, but I find no way to actually activate those rules, other than manually doing so from the `Karabiner-Elements` app or piecing together some sort of fragile GUI automation.

If I'm wrong, and there's already such a way, I hope someone will point me in the right direction!

**Comment by tekezo** [comment]
I also find this part somewhat cumbersome, but it's challenging to implement.
I've made improvements by allowing direct edits from the GUI and supporting enable/disable toggling, but if you want more advanced features, you'll need to use tools like generators on your own.
I close it for now.
