### ISSUE TITLE
Logi Options+ doesn't detect mx keys keyboard when used by Karabiner

### ISSUE THREAD

**Issue by golimpio** [pqrs-org/Karabiner-Elements#3047]
When Karabiner is running, Logi Options+ won't recognise MX Keys Mini keyboard as a Logitech Keyboard.  So, all Logi Options+ settings won't apply for the keyboard as it's like it doesn't exist.

**Comment by MuhammedZakir** [comment]
> _[...]_ So, all Logi Options+ settings won't apply for the keyboard as it's like it doesn't exist.

What if Karabiner-Elements is started after settings of Logi Options+ are applied? I thiink that's the only solution for this.

**Comment by MuhammedZakir** [comment]
> There is one issue unfortunately, but this isn't related to Karabiner, Logi Options+ is a beta product and it's very unstable, its daemon restarts several times per day, and as you can imagine, the workaround won't work for longer. I can't use the normal/stable version of Logi Option since it doesn't support the MX Keys Mini.

If the daemon is running as a `launchd` service, then you may able to tweak it restart KE. If there is a way to run a command from Logi Options+ or when it is started, then restart KE using it. If nothing works, then you will have to do _the ugly way_ -- run a background script to watch for daemon reloads and restart KE when that happens.

> Anyway, I thought that the original keyboard would still be active and the Karabiner keyboard would be an additional keyboard for the system, if this is the case, I don't follow why Logi Options+ can't see the keyboard.

That won't work. First of all, KE has to use the same ids used by the keyboard it captures - product id, vendor id and all other ids that are used by these apps to recognize devices. Secondly, it has to "forward" all device-configuration events to the original device. The problem, as you can guess, is that different keyboards may use different ways to do that and to support all or even some of these is nearly impossible.

So I think what you want most probably won't happen. But, I might be wrong as I am not familiar with this.

**Comment by golimpio** [comment]
@MuhammedZakir  Thank you very much for your time and to explain some concepts about how it works.  You gave me some good ideas for workarounds, so I'm closing this issue because it seems that Karabiner is working as it was design to, and I should focus on the Logi Options+ bugs and workaround.  Thanks again!

**Comment by adriandmitroca** [comment]
@golimpio just faced the very same issue now, have you find out any workaround?

**Comment by golimpio** [comment]
> @golimpio just faced the very same issue now, have you find out any workaround?

Unfortunately I haven't.  I'm still facing the same issue.

**Comment by adriandmitroca** [comment]
I ended up with uninstalling Karabiner Elements and replacing the mapping I needed via bash script. Full details can be found here: https://mic-kul.com/2020/01/25/mx-keys-remap-right-alt/

**Comment by degecko** [comment]
I forgot I had Karabiner installed and I've spent a few hours trying to figure out why Logi Options+ wasn't seeing my new keyboard. I'm still confused as to why disabling Karabiner works, but thanks for creating this issue.

**Comment by svallory** [comment]
> I ended up with uninstalling Karabiner Elements and replacing the mapping I needed by bash script. Full details can be found here: https://mic-kul.com/2020/01/25/mx-keys-remap-right-alt/

Can you repost your script? The link is broken :/

**Comment by golimpio** [comment]
I don't remember exactly when it was fixed, but recently I haven't experienced any issues. I'm running Karabiner-Elements 14.10.1 and Logi 1.29.6100.

Running macOS Ventura 13.0.1 (22A400)

**Comment by svallory** [comment]
Thanks @adriandmitroca ! It was working for me. I was actually interested in seeing your script to see if I can somehow remap the `insert`, `numlock` and `fn` keys that karabiner does not detect :)
