### ISSUE TITLE
How should I bind Microsoft Bluetooth Keyboard Office key? ( = left_cmd + left_option + left_shift + left_control)

### ISSUE THREAD

**Issue by RonAmihai** [pqrs-org/Karabiner-Elements#3060]
I'm using [Microsoft Bluetooth Keyboard](https://www.microsoft.com/en-ww/accessories/products/keyboards/microsoft-bluetooth-keyboard?activetab=overview%3aprimaryr2) and trying to bind the Office key (the one to the left of the emoji key) to open the launchpad. 

I've already succeeded to bind the emoji key ( = left_cmd + left_option + left_shift + left_control + space), but I'm failing to bind the office key ( = left_cmd + left_option + left_shift + left_control). 
 
Karabiner EventViewer gave the combination above for that key, always by that given order.
How should I bind that combination to open the launchpad?

**Comment by MuhammedZakir** [comment]
Did you try complex modifications?

https://karabiner-elements.pqrs.org/docs/json/

**Comment by RonAmihai** [comment]
> Did you try complex modifications?
> 
> https://karabiner-elements.pqrs.org/docs/json/

Indeed, as follows: 
```
{
        "description": "[ LEFT_CMD + LEFT_OPTION + LEFT_SHIFT + LEFT_CONTROL + SPACE ] to open Emoji",
        "manipulators": [
            {
                "from": {
                    "key_code": "spacebar",
                    "modifiers": {
                        "mandatory": [
                            "left_command",
                            "left_option",
                            "left_shift",
                            "left_control"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "spacebar",
                        "modifiers": [
                            "left_command",
                            "left_control"
                        ]
                    }
                ],
                "type": "basic"
            }
        ]
    },
{
        "description": "[ LEFT_CMD + LEFT_OPTION + LEFT_SHIFT + LEFT_CONTROL ] to open Launchpad",
        "manipulators": [
            {
                "from": {
                    "key_code": "left_shift",
                    "modifiers": {
                        "mandatory": [
                            "left_command",
                            "left_option",
                            "left_control"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "spacebar",
                        "modifiers": [
                            "left_command",
                            "left_control"
                        ]
                    }
                ],
                "type": "basic"
            }
        ]
}
```

The emoji key bindings work perfectly, but the launchpad key bindings do not. No matter which of the four keys is the key code...

**Comment by MuhammedZakir** [comment]
1. The key sequence you get when you press office key is always the same, right?
2. Move those into a new profile and try again. This is is to check if any other stuff is interfering with it.
3. Use `left_control` as `key_code` instead of `left_shift` and add `left_shift` to `from.modifiers.mandatory`. May or may not work.

**Comment by RonAmihai** [comment]
> 1. The key sequence you get when you press office key is always the same, right?
> 2. Move those into a new profile and try again. This is is to check if any other stuff is interfering with it.
> 3. Use `left_control` as `key_code` instead of `left_shift` and add `left_shift` to `from.modifiers.mandatory`. May or may not work.

That actually worked! Thanks! 

For everyone interested, this is my final configuration (I wasn't needed to put it in a separate profile file):
```
{
        "description": "[ LEFT_CMD + LEFT_OPTION + LEFT_SHIFT + LEFT_CONTROL ] to open Launchpad",
        "manipulators": [
            {
                "from": {
                    "key_code": "left_control",
                    "modifiers": {
                        "mandatory": [
                            "left_command",
                            "left_option",
                            "left_shift"
                        ]
                    }
                },
                "to": [
                    {
                        "apple_vendor_keyboard_key_code": "launchpad"
                    }
                ],
                "type": "basic"
            }
        ]
}
```
