### ISSUE TITLE
why is the colon key assigned to the key code "quote"? And how to know the actual key code of "quote"?

### ISSUE THREAD

**Issue by kay-adamof** [pqrs-org/Karabiner-Elements#3061]
## why is the colon key assigned to the key code "quote"?

In JIS keyboard:

- pressed the "colon" key 
- checked out the key code by Karabiner ElementViewer
- found out it shows "quote"

I think the key code should be shown as "colon", not "quote".

## how to know the actual key code of "quote"?

I'd like to assign "j" key to "quote". But  the key code of "quote" is not shown in Karabiner ElementViewer because of reason above. And in addition, the input of "quote" via "shift 7"  shows "{key_code:7, flags:left_shift}". So there is no way to know the key code of "quote".

how do I know  the actual key code of "quote" ?

**Comment by MuhammedZakir** [comment]
Whatever you get in EventViewer is what you use. In your case, if you want to remap "colon", you use "quote". If you want to remap "quote", you use `shift+7`. For latter, you will have to use complex modification.

**Comment by kay-adamof** [comment]
Thank you for your replying. I understand what you say. 
This issue is related to other problems that occurs on my own situation. But it was fixed by my self.
Sorry for closing this issue.

**Comment by kay-adamof** [comment]
Thank you for your replying. I understand what you say.
This issue is related to other problems that occurs on my own situation. But it was fixed by my self.
Sorry for closing this issue.
