### ISSUE TITLE
Does karabiner support emulating this behavior?

### ISSUE THREAD

**Issue by nzl-thu** [pqrs-org/Karabiner-Elements#3066]
Hi, does karabiner support emulating this behavior? 
For example, when f4 is pressed down, it sends control+i to system. And **control is kept pressed** when f4 is not released(so it's now emulating a modifier key). And when f4 is released, control key is also released.
This behavior is pretty useful for switching windows & applications. But I haven't figured out how to achieve this. Any ideas?
Thanks.

**Comment by MuhammedZakir** [comment]
Are you looking for something like this[1]?

[1] https://github.com/pqrs-org/Karabiner-Elements/issues/2799#issuecomment-906588811

**Comment by nzl-thu** [comment]
Hey, it's very close to what I wanted. But is it possible to make it faster? I've tried using smaller(or even zero) `basic.to_if_alone_timeout_milliseconds` and `basic.to_if_held_down_threshold_milliseconds`, but there's still a noticeable time gap between pressing the key and the expected behavior.
And when tab key is pressed alone and released instantly, can it also map to command+tab **instantly**?
Thanks a lot!

**Comment by nzl-thu** [comment]
For example, logi mouse's button has this behavior when the customizable button is mapped to command+tab, which I loved a lot.  
When the button is pressed and released quickly, it switches between most recently used applications on mac. 
When the button is pressed and kept held down, it emulates cmd+tab(with command held down). So it's now showing the active applications and I can navigate between them easily using left_arrow & right_arrow keys.

**Comment by MuhammedZakir** [comment]
The problem here is that we are using a shell script to execute AppleScript to achieve this as KE doesn't have a native way to do this. There is an option to compile AppleScript using `osacompile` iirc (see `man osascript`); this might give you a little more speed. But it would still not be as fast as you may expect.

---

To send `command+tab` when pressed alone, add `"modifiers": ["command"],` between `key_code` and `halt` inside `to_if_alone`.

---

Can you try this?

```json
{
  "title": "tab => Command+tab",
  "rules": [{
    "description": "tab => command+tab",
    "manipulators": [{
      "type": "basic",
      "from": {
        "key_code": "tab",
        "modifiers": {
          "optional": "caps_lock"
        }
      },
      "to": [{
        "shell_command": "osascript -e 'tell application \"System Events\"' -e 'key down command' -e 'keystroke tab' -e 'end tell'"
      }],
      "to_after_key_up": [{
        "shell_command": "osascript -e 'tell application \"System Events\" to key up command'"
      }]
    }]
  }]
}
```

If it is still not fast enough, replace `to` and `to_after_key_up` with
```
      "to": [
        {
          "shell_command": "osascript -e 'tell application \"System Events\" to keystroke tab'"
        },
        {
          "key_code": "command"
        }
      ]
```

If this doesn't works, add `sleep 0.05;` at the start of the `shell_command`. You may have to increase/decrease `0.05` for this to work properly. Note: `0.05` means 50 milliseconds.

**Comment by nzl-thu** [comment]
Hey, what about this? Inspired by your answer, I simplified a little bit. And found this worked pretty well for me.
```
        {
          "type": "basic",
          "from": {
            "key_code": "tab"
          },
          "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "left_command"
              ]
            },
            {
              "key_code": "left_command"
            }
          ]
        }
```

**Comment by MuhammedZakir** [comment]
Does that work? Does the app switcher stays shown when the `tab` is held down? If it works, then that's perfect. ;-)

**Comment by nzl-thu** [comment]
Yes, it is. And maybe this issue can be closed. Thanks a lot for your help!

**Comment by MuhammedZakir** [comment]
> Yes, it does.

Nice!

> And maybe this issue can be closed.

You can do it yourself. :-)

> Thanks a lot for your help!

You're welcome!
