### ISSUE TITLE
Bug: `select_input_source` switches to quickly

### ISSUE THREAD

**Issue by chrisgrieser** [pqrs-org/Karabiner-Elements#3085]
The goal of this modification is switch to the US keyboard solely for the `[` character event and then switch back. (This is necessary for some cases concerning vim emulators, as those emulators do not accept a `[` triggered via `alt+5`.)

So I tried the following for `to`, but it basically switches too quickly. Instead of `[`, it sends `+`, as the `select_input_source` switches too quickly, so that the wrong key gets send out.

I confirmed this by leaving out the second `select_input_source` , in which case the `[` first sends out the wrong key, but then does switch correctly and sends out the right key subsequently.

Some sort of sequential processing of the `to` array elements, or a delay element could solve this?
 
```json
"to": [
	{
		"select_input_source": {
			"input_source_id": "^com\\.apple\\.keylayout\\.US$"
		}
	},
	{
		"key_code": "close_bracket"
	},
	{
		"select_input_source": {
			"input_source_id": "^com\\.apple\\.keylayout\\.ABC-QWERTZ$"
		}
	}
]
```

**Comment by MuhammedZakir** [comment]
Use `hold_down_milliseconds`[1] to create a delay.

```
{
  "key_code": "vk_none",
  "hold_down_milliseconds": 100
}
```

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/hold-down-milliseconds/

**Comment by chrisgrieser** [comment]
ah indeed, it took me a bit to tweak the right delay value, but this seems to make it work:
```json
{
	"type": "basic",
	"from": { "key_code": "semicolon" },
	"to": [
		{"select_input_source": {"input_source_id": "^com\\.apple\\.keylayout\\.US$"} }
	],
	"to_if_held_down": [
		{ "key_code": "semicolon" }
	],
	"to_after_key_up": [
		{"select_input_source": {"input_source_id": "^com\\.apple\\.keylayout\\.ABC-QWERTZ$"} }
	],

	"parameters": {
	    "basic.to_if_held_down_threshold_milliseconds": 20
	}
}
```

**Comment by MuhammedZakir** [comment]
A better one is:
```json
{
	"type": "basic",
	"from": { "key_code": "semicolon" },
	"to": [
		{ "select_input_source": {"input_source_id": "^com\\.apple\\.keylayout\\.US$"} },
		{ "key_code": "semicolon" }
	],
	"to_after_key_up": [
		{"select_input_source": {"input_source_id": "^com\\.apple\\.keylayout\\.ABC-QWERTZ$"} }
	]
}
```

If `semicolon` is send before `US` layout is selected, then add a delay between them.
```
{
	"type": "basic",
	"from": { "key_code": "semicolon" },
	"to": [
		{ "select_input_source": {"input_source_id": "^com\\.apple\\.keylayout\\.US$"} },
    { "key_code": "vk_none", "hold_down_milliseconds": 30 },
		{ "key_code": "semicolon" }
	],
	"to_after_key_up": [
		{"select_input_source": {"input_source_id": "^com\\.apple\\.keylayout\\.ABC-QWERTZ$"} }
	]
}
```

**Comment by chrisgrieser** [comment]
thank you 😊
