### ISSUE TITLE
set variable value to text string?

### ISSUE THREAD

**Issue by TemporaryEfx** [pqrs-org/Karabiner-Elements#3089]
I'd like to set a variable value to a text string. The _Reference Manual_ appears to contain conflicting info about whether this ought to be possible. Clarification about the intended behavior would be much appreciated!

==Details==
The manual page for [to.set_variable](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/set-variable/) clearly indicate strings are permitted. However, the page for [variable_if, variable_unless](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/variable/) seems to indicate otherwise. See attached screenshots below.

In practice, Karabiner simply treats the following rule as non-existent (i.e. pressing the "x" key returns the letter "x" and does not set the variable to the value). 

```
      "rules" : [ {
        "description" : "variable to string",
        "manipulators" : [ {
          "from" : {
            "key_code" : "x"
          },
          "to" : [ {
            "set_variable" : {
              "name" : "i_am_text",
              "value" : "string"
            }
          } ],
          "type" : "basic"
        } ]
      } ]
```

**Screenshot 1** ⮕ value shown as string
---
![image](https://user-images.githubusercontent.com/61758330/168926748-c7a48ba7-5468-4730-9641-e545825adc24.png)

**Screenshot 2** ⮕ value NOT shown as string 
---
![image](https://user-images.githubusercontent.com/61758330/168926914-48dbcd42-679e-4a88-b472-1126c9738f16.png)

**Comment by j-f1** [comment]
See #3091
