### ISSUE TITLE
caps_lock complex modification works on one Mac but not another

### ISSUE THREAD

**Issue by emmglee** [pqrs-org/Karabiner-Elements#3093]
I installed Karbiner-Elements on my Mac Studio then modified the config file per an old blog that created a way to use the Caps Lock key for command+control+option+shift.  Didn't work.  Then I learned that the latest version had this rule built in.  I did a clean install on my MacBook Air and it works perfectly.

I've tried uninstalling the app several ways then reinstalling on my MacBook Studio and it still doesn't work.  I've disabled the Caps Lock key in System Preferences and enabled everything in Security and Privacy.  I can't figure out what else to try.

**Comment by MuhammedZakir** [comment]
General debugging steps:
1. Is input modification enabled in Devices tab?
2. Check Log tab for any error.
3. What does EventViewer show when pressing `caps_lock` both before and after remapping it?
4. Does a simple modification work? E.g. `caps_lock` to `fn`.

**Comment by emmglee** [comment]
Thank you for your quick reply.    Between posting this question and now, I stumbled on the Devices tab.    On my MBA, the internal keyboard was enabled by default.    My Mac Studio uses a USB keyboard.    That was not enabled by default.    When I enabled the keyboard, it worked perfectly.
  

  
Thanks!
  

  
Mike
  
  
  
  
  
  
  

  
  
>

**Comment by MuhammedZakir** [comment]
You're welcome! :-) In Devices tab, does it show both keyboard and mouse icons for your USB keyboard? That maybe the cause. Because, IIRC, keyboards are enabled by default; mouses aren't.

Regardles, I think this can be closed?

**Comment by emmglee** [comment]
Yes, both mouse and keyboard are shown.    I activated the keyboard only.    Yes, please close the ticket.    I'm amazed at getting such good and quick help on a Saturday!
  

  
Thanks again,
  

  
Mike
  
  
  
  
  
  
  

  
  
>

**Comment by MuhammedZakir** [comment]
I am not an admin. You can do it yourself. :-)

**Comment by emmglee** [comment]
LOL :-) I'm new around here. Will do.
  
​
