### ISSUE TITLE
(Request) Add beep sound after keypress

### ISSUE THREAD

**Issue by arihid** [pqrs-org/Karabiner-Elements#3100]
This means to emulate Windows' funtion "Switch Key" which play beep sound after caps, num, or scroll lock pressed. I often accidentally pressed caps lock so this little feature will be a great help. Yes, there is an external solution, but I prefer a built-in solution if available.

**Comment by arihid** [comment]
> I prefer a notification instead as I find beep sound annoying. Regardless, it is trivial to implement this using complex modificaton.

Oh I never know I can do that! I might add the notification toast as well while I'm at it. But how can I invoke a notification toast?
Sorry if I asked too much, I have no programming skill. Thank you.

**Comment by MuhammedZakir** [comment]
> But how can I invoke a notification toast?

Example `shell_command`s:
1. `osascript -e 'display notification \"Caps Lock\" with title \"Key Pressed\"'`.
2. (I prefer this) `osascript -e 'display notification \"\" with title \"Caps Lock pressed\"'`

You can test these commands from terminal. It is recommended to test these before using them in complex modifications. Note that you will have to remove backslashes(`\`) from above commands when executing them in terminal.

FYI, you can get these easily by searching! Use related keywords and then append "from command line". In this case, the **a** search term is "macos notification from command line".

**Comment by MuhammedZakir** [comment]
The above rule *looks* correct to me. A simple way to check whether the above rule works is to change the keycode in `to` to some other keycode; for instance, `a`. Then import that rule and open EventViewer[1] and see if you get, in this case `a`, when you press `caps_lock`/`num_lock`.

Note: I think it is better to add `any` to `from.modifiers.optional`, so that the rule will work even when caps lock is on or while other modifiers are held.

> Oh, and I didn't add scroll lock keypress to the rules. I haven't found any reference to the keycode.

You can use EventViewer[1] to find the correct keycode.

> Thank you and sorry if I keep bothering you.

No problem!

[1] Karabiner-EventViewer.app or KE menu > Launch EventViewer.

---

I don't know how much you know, so... general info:

1. The above JSON should be savied in `~/.config/karabiner/assets/complex_modifications/someFile.json`.
2. After saving, the rules can be imprted from KE pereferences > complex modifications > Add rule.
3. If the rule isn't shown after importing, check Log tab. There maybe errors in it.
4. When importing multiple rules, only the first matched rule will be triggered. So make sure no other complex modification remaps the keys you are trying to remap.
    - If you already have many rules, it is better to create a new profile and import your new config into it. If your config works in a new profile, but not in your existing profile, this means the rules in the new config conflicts with the rules in your existing profile. This makes it easy to narrow down the problems.
5. You will have to remove existing rule from complex modifications when trying to (re-)import that rule again (e.g. after making changes).

**Comment by arihid** [comment]
Thank you. My rules are running properly now. I used `sound name` parameter from `display notification` instead of playing external file for "Show a notification toast and play beep sound when caps/num lock is pressed." rule. I can't excecute `osascript -e 'display notification sound name ""'` to achieve sound notification without invoking the notification, so I have to use `ffplay`. According to [this](https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW12) documentation the `sound name` is a parameter refering to sound files in `System/Library/Sounds`. I still haven't implemented the scroll lock because I don't have the physical keyboard for that. It's fine for now.

Here is my updated code.
```bash
{
  "title": "Emulate \"Use Toggle Keys\" on MacOS.",
  "rules": [
    {
      "description": "Play beep sound when caps/num lock is pressed.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "caps_lock",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "/usr/local/bin/ffplay -autoexit -nodisp -loglevel quiet ~/.beep.mp3"
            },
            {
              "key_code": "caps_lock"
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "keypad_num_lock",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "/usr/local/bin/ffplay -autoexit -nodisp -loglevel quiet ~/.beep.mp3"
            },
            {
              "key_code": "keypad_num_lock"
            }
          ]
        }
      ]
    },
    {
      "description": "Show a notification toast when caps/num lock is pressed.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "caps_lock",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'display notification \"You just pressed Caps lock.\" with title \"Key pressed\"'"
            },
            {
              "key_code": "caps_lock"
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "keypad_num_lock",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'display notification \"You just pressed Num lock.\" with title \"Key pressed\"'"
            },
            {
              "key_code": "keypad_num_lock"
            }
          ]
        }
      ]
    },
    {
      "description": "Show a notification toast and play beep sound when caps/num lock is pressed.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "caps_lock",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'display notification \"You just pressed Caps lock.\" sound name \"\" with title \"Key pressed\"'"
            },
            {
              "key_code": "caps_lock"
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "keypad_num_lock",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'display notification \"You just pressed Num lock.\" sound name \"\" with title \"Key pressed\"'"
            },
            {
              "key_code": "keypad_num_lock"
            }
          ]
        }
      ]
    }
  ]
}
```
