### ISSUE TITLE
Mouse4 and Mouse5 modification is not working

### ISSUE THREAD

**Issue by QAthulhu** [pqrs-org/Karabiner-Elements#3106]
I'm trying to map mouse4 and mouse5 to switching desktops. I've imported modifications from the site and have tried writing my own, but none of them worked. I've tried creating a simple modification as well but still not working. Currently, mouse4 causes tab switching in Sublime, while mouse5 opens mission control. I've tried closing Karabiner and the same thing happens, which means this is what macos defaults to for the mouse buttons. So the Karabiner modifications aren't working at all.

Here is the modification code I got from the import and the one I've written. I've tried looking at other imported modifications that do the same thing and they all have the same code. So something else is blocking this from happening

```
"manipulators": [
                            {
                                "from": {
                                    "pointing_button": "button5"
                                },
                                "to": [
                                    {
                                        "key_code": "left_arrow",
                                        "modifiers": "left_control"
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "from": {
                                    "pointing_button": "button4"
                                },
                                "to": [
                                    {
                                        "key_code": "right_arrow",
                                        "modifiers": "left_control"
                                    }
                                ],
                                "type": "basic"
                            }
```

**Comment by MuhammedZakir** [comment]
Is input modification enabled for your mouse in KE preferences > Devices ?

**Comment by QAthulhu** [comment]
Yes they also show up on the EventViewer as pointing_button mouse4 and mouse5

**Comment by MuhammedZakir** [comment]
I only have basic 3-buttons mouse, so can't really do any tests myself.

Some debugging steps I would do:

1. Move this modification to a new profile to get a clean environment for debugging.
    - You may have to enable input modification for your mouse in the new profile.
2. Check if the `modifiers` in `to` events is causing problem.
    - Remap `button4` to, for example, `a`.
3. Check Log tab. It might contain some useful info.
    - Unlikely for this case, but just check anyway.

If nothing works, then this is most probably a bug in KE.

**Comment by QAthulhu** [comment]
Solved it. The mouse was listed as two devices, one a mouse and the other a keyboard. I enabled both, then created a "simple modification" under the mouse version of the device
```
"devices": [
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": false,
                        "is_pointing_device": true,
                        "product_id": 102,
                        "vendor_id": 7847
                    },
                    "ignore": false,
                    "manipulate_caps_lock_led": false,
                    "simple_modifications": [
                        {
                            "from": {
                                "pointing_button": "button5"
                            },
                            "to": [
                                {
                                    "key_code": "right_arrow",
                                    "modifiers": "left_control"
                                }
                            ]
                        },
                        {
                            "from": {
                                "pointing_button": "button4"
                            },
                            "to": [
                                {
                                    "key_code": "left_arrow",
                                    "modifiers": "left_control"
                                }
                            ]
                        }
                    ]
                },
```

**Comment by zaaaaaww** [comment]
> Solved it. The mouse was listed as two devices, one a mouse and the other a keyboard. I enabled both, then created a "simple modification" under the mouse version of the device
> 
> ```
> "devices": [
>                 {
>                     "disable_built_in_keyboard_if_exists": false,
>                     "fn_function_keys": [],
>                     "identifiers": {
>                         "is_keyboard": false,
>                         "is_pointing_device": true,
>                         "product_id": 102,
>                         "vendor_id": 7847
>                     },
>                     "ignore": false,
>                     "manipulate_caps_lock_led": false,
>                     "simple_modifications": [
>                         {
>                             "from": {
>                                 "pointing_button": "button5"
>                             },
>                             "to": [
>                                 {
>                                     "key_code": "right_arrow",
>                                     "modifiers": "left_control"
>                                 }
>                             ]
>                         },
>                         {
>                             "from": {
>                                 "pointing_button": "button4"
>                             },
>                             "to": [
>                                 {
>                                     "key_code": "left_arrow",
>                                     "modifiers": "left_control"
>                                 }
>                             ]
>                         }
>                     ]
>                 },
> ```

Hi QAthulhu, I wish I could understand what you're saying as I reallyyyyyy want to map my mouse button 4 and 5 to become Command and Ctrl :((( Could you please elaborate it for me pleaseeee? Thank you very much QAthulhu!!!

**Comment by QAthulhu** [comment]
@zaaaaaww open Karabiner, go to Devices. For me, my keyboard was listed their twice as both a Keyboard and a Mouse. I then edited the karabiner preferences with the modification I posted.

**Comment by alimoeeny** [comment]
In my case, I just needed to go to devices and enable "Modify events" for my particular mouse. I know, it's silly I didn't think of it before hand. Hope this helps someone.
