### ISSUE TITLE
How to let simultaneously pressed keys behave like a modifier?

### ISSUE THREAD

**Issue by rschmidtner** [pqrs-org/Karabiner-Elements#3133]
I want `a + spacebar` (simultaneously pressed) to behave like `left_shift + left_control + left_option` (simultaneously pressed). What I mean with "behave" in this context is: If I define a rule like `left_shift + left_control + left_option + h -> left_arrow`, I want it to be triggered by pressing `a + spacebar` simultaneously and then pressing `h` (not simultaneously with `a` and `spacebar`, but afterwards and while `a + spacebar` are still being pressed).

To be specific: 
This rule maps `left_shift + left_control + left_option + h` to `left arrow`. It works fine by itself.

```json
{
    "description": "hyper + h -> left_arrow",
    "manipulators": [
        {
            "type": "basic",
            "description": "hyper + h -> left_arrow",
            "from": {
                "key_code": "h",
                "modifiers": {
                    "mandatory": [
                        "left_shift",
                        "left_control",
                        "left_option"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_arrow"
                }
            ]
        }
    ]
}
```
It also works in combination with this rule. That is, I can press `caps_lock`, hold it, and then press `h` to get an `left_arrow`.

```json
{
    "description": "caps_lock -> hyper",
    "manipulators": [
        {
            "type": "basic",
            "description": "caps_lock -> hyper",
            "from": {
                "key_code": "caps_lock"
            },
            "to": [
                {
                    "key_code": "left_shift",
                    "modifiers": [
                        "left_control", 
                        "left_option"
                    ]
                }
            ]
        }
    ]
}
```
However, it does not work in combination with the rule below. On its own the below rule works as expected. If I press `spacebar + a` the event viewer tells me that it is mapped to `left_shift + left_control + left_option`. However, if I press`spacebar + a`, hold it, and then press`h` I get nothing.
```json
{
    "description": "spacebar + a -> hyper",
    "manipulators": [
        {
            "type": "basic",
            "description": "spacebar + a -> hyper",
            "from": {
                "simultaneous": [
                    {
                        "key_code": "a"
                    },
                    {
                        "key_code": "spacebar"
                    }
                ]
            },
            "to": [
                {
                    "key_code": "left_shift",
                    "modifiers": [
                        "left_control",
                        "left_option"
                    ]
                }
            ]
        }
    ]
}
```

**Comment by MuhammedZakir** [comment]
Can you post the EventViewer's output of `spacebar`+`a`+`h`?

**Comment by rschmidtner** [comment]
When I press `spacebar + a` I get this output (while holding it pressed)

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/67690427/180140770-2d060ccf-99f6-4386-b18c-0fe39219d6cf.png">
If I then press `h` (while still holding `spacebar + a` pressed) nothing changes in the EventViewer. 
<br><br>
After I release `spacebar + a` three new key presses are added in the EventViewer, so that I end up with this as the final result.

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/67690427/180140688-af567a1d-bc49-4db8-be35-f6470db77796.png">

**Comment by MuhammedZakir** [comment]
> If I then press `h` (while still holding `spacebar + a` pressed) nothing changes in the EventViewer.

If `h` is detected, an event for either `h` or `left_arrow` should be printed there.

Remove `spacebar`+`h` rule, open on-screen keyboard, and check whether the system detects `spacebar`+`a`+`h` combo. You may also turn off event modification for your device in Karabiner-Elements to see whether that makes any difference.

**Comment by rschmidtner** [comment]
Oh man. I hit some really strange edge case. For unknown reasons the letters `a`, `s`, `d`, `f`, `g`, `j`, `k` and `l` of the middle keyboard row (and only those!) are not recognized together with the key `h` (and only `h`!) while `spacebar` is being hold down. That is holding `spacebar + h` and then pressing `[asdfgjkl]` does not work, as well as holding `spacebar + [asdfgjkl]` and then pressing `h` does not work (MacBook Pro, built in keyboard). All other scenarios (`spacebar + [zxcv...]` + `h` ) work. Bad luck that `spacebar + a` + `h` was my first try :D Thanks for your help!

**Comment by MuhammedZakir** [comment]
You're welcome!

That indeed was a bad luck! :-D If you can find another MacBook Pro, see if you can reproduce this ghosting behavior on it. If you can't, it maybe better to take yours to a service centre. A bad key is like a virus, other keys will start to behave strangely at some point.

**Comment by rschmidtner** [comment]
Will check at a collegues MacBook. Thanks for the advice.
