### ISSUE TITLE
Disable build-in keyboard not woking in 12.5

### ISSUE THREAD

**Issue by jason5ng32** [pqrs-org/Karabiner-Elements#3136]
After upgrading system to 12.5 and Karabiner to 14.5, Disableing build-in keyboard not working anymore. Modifications still works well.

**Comment by tekezo** [comment]
I cannot reproduce this issue.
Could you show me `Devices` and `Devices > Advanced` tab in Karabiner-Elements Preferences?

**Comment by JulianLian** [comment]
I run into the same issue. It worked fine before update and I didnot change any configuration.
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/16442407/181140569-ca9e417f-489e-43f1-8cfe-5c8124328f30.png">

**Comment by jason5ng32** [comment]
@tekezo 

<img width="1140" alt="Device" src="https://user-images.githubusercontent.com/1546290/181143188-142dc460-edb4-4427-bb1f-50849834a6a9.png">
<img width="1151" alt="DA" src="https://user-images.githubusercontent.com/1546290/181143199-e3623d8d-c4a6-445a-95e1-e9c4a3b2df07.png">

**Comment by JulianLian** [comment]
Uninstall and re-install does not help.

**Comment by n-kenneth** [comment]
I got the same issue after upgrading to 12.5 and getting the 14.5 version.

**Comment by tekezo** [comment]
Thanks, I succeeded to reproduce this issue when the built-in keyboard is not event modification target.
I'll fix this issue soon.

**Comment by tekezo** [comment]
I've fixed this issue at the latest beta version (v14.5.1).
Could you confirm it?

How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by JulianLian** [comment]
@tekezo Thank you for your efforts. Back to normal with v14.5.1.

**Comment by jason5ng32** [comment]
> I've fixed this issue at the latest beta version (v14.5.1). Could you confirm it?
> 
> How to upgrade to the latest beta version: ![Check for beta updates](https://camo.githubusercontent.com/f0d3dcebbd2e46b18b8d57821e1acbbdabaaf6d9135b707a2667d2e00ccd7f0e/68747470733a2f2f6b61726162696e65722d656c656d656e74732e707172732e6f72672f646f63732f6d616e75616c2f6f7065726174696f6e2f636865636b2d666f722d757064617465732f696d616765732f6b61726162696e65722d656c656d656e74732d636865636b2d666f722d757064617465732d626574614032782e706e67)

Yes, you've fixed it.
Thank you very much.
