### ISSUE TITLE
Internal Apple Keyboard not detected correctly on M2 Macbook Air

### ISSUE THREAD

**Issue by raynehk14** [pqrs-org/Karabiner-Elements#3139]
I've migrated from a MBP 2019 with Migration Assistant and it seems that Karabiner does not detect the `Internal Apple Keyboard` devices correctly.  It (with the trackpad) shows up as `No product name (Apple)` with `Vendor Id: 0` and `Product Id: 0`

<img width="813" alt="image" src="https://user-images.githubusercontent.com/3069750/181680732-7c1ca569-52c2-4c6d-8931-2037c229d25e.png">

and this is what the devices show up as in Karabiner-EventViewer

<img width="375" alt="image" src="https://user-images.githubusercontent.com/3069750/181681175-c30b8919-27da-49cb-8fae-852812041700.png">

Modify Event still works normally, but the Disable Built-in Keyboard feature doesn't work, presumably cause Karabiner does not detect it as the built-in keyboard.  I have tried uninstalling Karabiner, deleting the config folder and reinstalling it, but it does not fix the issue.

**Comment by n-kenneth** [comment]
I have the exact same issue on M2 Macbook Pro

**Comment by tekezo** [comment]
Thank you for feedback!

I've release v14.6.0 just now which has `Treat as a built-in keyboard` feature.
Please try this feature since it may take time to improve the M2 keyboard detection.

https://karabiner-elements.pqrs.org/docs/manual/configuration/disable-built-in-keyboard/#configure-the-built-in-keyboard-detection

**Comment by n-kenneth** [comment]
@tekezo Thanks!, the feature is now working on M2 macbook pro after updating to v14.6.0

**Comment by raynehk14** [comment]
Thanks for the quick fix!  `Treat as a built-in keyboard` addresses the issue and functionally it works as if it's detecting it correctly.

**Comment by andrewplummer** [comment]
I might be missing something but I don't see "Treat as built-in keyboard" on 14.8.0. I'm having the same issue with the new MacBook Air M2. Note that the MBP 14" seems to detect OK.

**Comment by tekezo** [comment]
@andrewplummer The M2 MacBook Air built-in keyboard is recoginzed as built-in keyboard without `Treat as built-in keyboard`  since v14.8.0.

Let me know the following informations if disable built-in keyboard feature does not work on your machine.

- `Devices > Advanced` setting on Preferences
- `Devices` on Karabiner-EventViewer

**Comment by andrewplummer** [comment]
Actually the issue I was having is I was trying to swap fn and control AND use the rule "Change Ctrl + h/j/k/l to Arrows". This works on the new MBP but for some reason on the Air:

- Left fn works as control = OK
- Real Ctrl key + h/j/k/l = OK
- Fn key + h/j/k/l = NG

This might be a rule precedence thing? Anyway I found a (very obvious) solution, I'm simply using "Change Fn + h/j/k/l to Arrows" instead and it works fine!

**Comment by writezhe** [comment]
Hi there, I have a similar issue to the original. I migrated from M1 laptop to an M2 Macbook Air and keyboard-specific rules aren't working for me on the built-in Apple keyboard. I've tried both v14.8.0 and the beta (v14.8.2), as well as reinstalling Karabiner Elements (though my profile settings were kept).

Here are some details on what I see. It seems that it's correctly recognizing that it's a built-in keyboard, but the simple modifications I've added (see at the bottom) aren't being recognized unless I make them global rules.

_- Devices > Advanced setting on Preferences_

<img width="625" alt="image" src="https://user-images.githubusercontent.com/591893/185212602-a0c39823-e8e9-4a76-a55c-97936f130ba7.png">

_- Devices on Karabiner-EventViewer_

> [
    {
        "device_id": 4294969261,
        "is_built_in_keyboard": true,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": true,
        "is_pointing_device": false,
        "location_id": 161,
        "manufacturer": "Apple",
        "transport": "FIFO"
    },
    {
        "device_id": 4294969318,
        "is_built_in_pointing_device": true,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": false,
        "is_pointing_device": true,
        "location_id": 161,
        "manufacturer": "Apple",
        "transport": "FIFO"
    }
]

_- Simple modifications I've added for built-in keyboard_

<img width="811" alt="image" src="https://user-images.githubusercontent.com/591893/185213105-ad25557b-6ed7-4a02-b6f5-54f70a0b984d.png">

==
Much appreciated for this and all the work in general! My apologies if I missed something simple.

**Comment by cvcore** [comment]
> Hi there, I have a similar issue to the original. I migrated from M1 laptop to an M2 Macbook Air and keyboard-specific rules aren't working for me on the built-in Apple keyboard. I've tried both v14.8.0 and the beta (v14.8.2), as well as reinstalling Karabiner Elements (though my profile settings were kept).
> 
> Here are some details on what I see. It seems that it's correctly recognizing that it's a built-in keyboard, but the simple modifications I've added (see at the bottom) aren't being recognized unless I make them global rules.
> 
> _- Devices > Advanced setting on Preferences_
> 
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/591893/185212602-a0c39823-e8e9-4a76-a55c-97936f130ba7.png">
> 
> _- Devices on Karabiner-EventViewer_
> 
> > [
> > {
> > "device_id": 4294969261,
> > "is_built_in_keyboard": true,
> > "is_karabiner_virtual_hid_device": false,
> > "is_keyboard": true,
> > "is_pointing_device": false,
> > "location_id": 161,
> > "manufacturer": "Apple",
> > "transport": "FIFO"
> > },
> > {
> > "device_id": 4294969318,
> > "is_built_in_pointing_device": true,
> > "is_karabiner_virtual_hid_device": false,
> > "is_keyboard": false,
> > "is_pointing_device": true,
> > "location_id": 161,
> > "manufacturer": "Apple",
> > "transport": "FIFO"
> > }
> > ]
> 
> _- Simple modifications I've added for built-in keyboard_
> 
> <img alt="image" width="811" src="https://user-images.githubusercontent.com/591893/185213105-ad25557b-6ed7-4a02-b6f5-54f70a0b984d.png">
> 
> == Much appreciated for this and all the work in general! My apologies if I missed something simple.

Same issue here, as a temporary solution I also have to set the simple modification rules for the internal keyboard for macbook air m2 in 'for all devices'.

**Comment by STRML** [comment]
Same issue here with an M2 Air, device-specific rules do not work but "For all devices" does. This makes simple fn <-> ctrl modification difficult if you also use a bluetooth keyboard from time to time.

**Comment by y0rune** [comment]
I do not have `Treat as built-in keyboard` in the Apple internal keyboard on MacBook Pro with M2. 
I tried to change the `right_command` and `right_option`.

My configuration:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/10187235/191587993-83dea457-86e5-485f-888c-6bc138284756.png">
<img width="824" alt="image" src="https://user-images.githubusercontent.com/10187235/191588033-c7d09049-2a8f-4a8f-b0e4-eb4d0a39592c.png">
<img width="797" alt="image" src="https://user-images.githubusercontent.com/10187235/191588105-b210b05d-0ad0-4aab-8817-47bd0c3ab8f6.png">

**Comment by cvcore** [comment]
Judging from the above 4 replies, I think the issue is common for M2 Macbook Air. 
Shall we reopen this? @raynehk14 @tekezo

**Comment by tekezo** [comment]
The simple modifications issue fixed at the latest beta version (v14.9.3).

How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by STRML** [comment]
Thanks, I can confirm that official 14.10.0 has fixed the issue on my M2 Air.

**Comment by y0rune** [comment]
Yup in the version 14.10.0 in the MacBook Pro with M2 is working fine. Thank You!
