### ISSUE TITLE
Not more than 16 mouse buttons are detected

### ISSUE THREAD

**Issue by cheezycroque** [pqrs-org/Karabiner-Elements#3141]
**Description :** 
mouse with more than 16 buttons can map the first 16 buttons, but not more.
The remaining buttons are not usable.

**Steps to reproduce :** 
1. install karabiner
2. have a mouse with more than 16 buttons, ie : Logitech G600
3. try to map button 17 (or up)

**Actual result :** 
the mapping does not work, pressing buttons over 16 are not even detected using the event viewer

**Wanted result :** 
mapping button 17 and over should work

**Environment :** 
Karabiner 14.5.0

**Comment by tekezo** [comment]
I would like to know because I don't have Logitech G600, will the data show up in Unknown Events after button 17?

<img width="1100" alt="Screen Shot 2022-08-01 at 12 55 32" src="https://user-images.githubusercontent.com/659178/182069352-2565299e-5933-467f-aad3-8ef03412973e.png">

**Comment by cheezycroque** [comment]
no, pressing buttons over 16 are not even detected using the event viewer.  16 works, but not 17 and up

**Comment by tekezo** [comment]
Thank you, interesting.
I ordered G600 just now to confirm this issue.

**Comment by cheezycroque** [comment]
Oh wow !  That shows a lot of commitment !  I am impressed !

**Comment by cheezycroque** [comment]
New info : 
I installed and uninstalled the Logitech software that seems useless, and since then, Karabiner seems to have rediscovered the mouse for a second time.  There are 2 devices now in the karabiner config, a G600 mouse, and a G600 keyboard.  Since then, the buttons over 16 are seen by the even viewer, but the third mouse button which was visible by event viewer is not anymore.
So it looks like this bug might be related to a bad driver ?
Screenshot :  https://www.flickr.com/photos/ericconstantineau/52257870285/sizes/l/

**Comment by tekezo** [comment]
Basically, Karabiner-Elements does not work with third vendor drivers.
About the third mouse button, EventViewer shows the modified event. Is it changed in Karabiner-Elements?

**Comment by cheezycroque** [comment]
how do we control the driver, is there a way to force the rediscovery of the device ?

for the third mouse button, i do not understand the question, what is a modified event ?  When I opened the bug, the third button was showing something in event viewer, but now, nothing is shown when I click it.

**Comment by cheezycroque** [comment]
More info : the third mouse button is not visible in the "Main" tab of the event viewer, but it is seen in the "unknown events" tab.
value:73014444064    HID usage: 65408,128
value:73014444032    HID usage: 65408,128
value:73014444033    HID usage: 65408,128
value:73014444032    HID usage: 65408,128

**Comment by tekezo** [comment]
I've confirmed G600 works well with the following configuration:

- The factory resetted Logitech G600 (Resetted with G Hub on Windows)
    - On-board memory mode: Off
![g600](https://user-images.githubusercontent.com/659178/182580098-81cb7163-d888-4af8-89c2-e9569569e050.png)
- Without any Logitech driver on macOS.
- Then, mouse button 1-5 works as is, G6 as G-Shift, G7 and G8 as mode button, G9-G20 as keyboard

We can change G9 button as follows:

<img width="1100" alt="Screen Shot 2022-08-03 at 19 01 57" src="https://user-images.githubusercontent.com/659178/182581963-5f5ebbe7-4d10-494c-b98f-ed2adac38762.png">
.

**Comment by tekezo** [comment]
I guess your G600 has on-board memory setting. 
You can recognize these key in Karabiner-Elements by setting the button configuration to generic keys in G-Hub.

**Comment by cheezycroque** [comment]
Ok, looking into it...

**Comment by cheezycroque** [comment]
It works, so this was not a bug, it was simply a logitech configuration issue !  ありがとうございます！
