### ISSUE TITLE
Question: is it recommendable to re-store key modifiers to default before using the software? 

### ISSUE THREAD

**Issue by pdelfino** [pqrs-org/Karabiner-Elements#3151]
Hi,

Congrats for the work. This software looks pretty neat.

1 - I have already changed my modifier keys in System Preferences.

<img width="412" alt="Screen Shot 2022-08-01 at 10 43 22" src="https://user-images.githubusercontent.com/7698207/182704098-0a56ae2b-ad83-4205-a4f2-d2fb096bf052.png">

Should I restore to the default before trying Karabiner-elements?

2 - I am also using this [Alt Tab software]( https://github.com/lwouis/alt-tab-macos)

Any chance of collision? Should I disable it?

Thanks

**Comment by MuhammedZakir** [comment]
Hello! :-)

> 1 - I have already changed my modifier keys in System Preferences.
> 
> `<img alt="Screen Shot 2022-08-01 at 10 43 22" width="412" src="https://user-images.githubusercontent.com/7698207/182704098-0a56ae2b-ad83-4205-a4f2-d2fb096bf052.png">`
> 
> Should I restore to the default before trying Karabiner-elements?

They are ignored when using Karabiner-Elements. See the "note" in https://karabiner-elements.pqrs.org/docs/manual/misc/event-modification-chaining/.

> 2 - I am also using this [Alt Tab software](https://github.com/lwouis/alt-tab-macos)
> 
> Any chance of collision? Should I disable it?

AFAIK, there is no problem using both.

**Comment by pdelfino** [comment]
Thank you! Closing the issue
