### ISSUE TITLE
§ and ~ swapped on ISO keyboard

### ISSUE THREAD

**Issue by miquecg** [pqrs-org/Karabiner-Elements#3155]
Hi,

After installing Karabiner my keyboard was correctly identified as ISO by keyboard assistant and both keys worked correctly. Later I've checked virtual keyboards tab and noticed that there was no choice for any country code, so I've picked ISO again for country 0.

On this MBP I'm using English US and Spanish, my regional settings are Spanish and keyboard phisical layout is ISO.

Relate issue: https://github.com/pqrs-org/Karabiner-Elements/issues/1365

Karabiner 14.6.0
macOS 12.5

**Comment by miquecg** [comment]
The fix was simple. Changing virtual keyboard layout to ANSI despite being ISO actually. I guess it has to do with my language choice for the system.

**Comment by AshConnolly** [comment]
Just ran into this issue with 15.3.0. Had to switch to ANSI
