### ISSUE TITLE
Keys Del, Home, End, PgUp, PgDn are invisible on MX mechanical 

### ISSUE THREAD

**Issue by alkalim** [pqrs-org/Karabiner-Elements#3156]
Hi! Not sure if this is a configuration problem or a bug, but Karabiner doesn't see keys Del, Home, End, PgUp, PgDn on my Logitech MX mechanical mini. These keys are also invisible in EventViewer. Is this a known issue? How should I approach this problem?

**Comment by MuhammedZakir** [comment]
> These keys are also invisible in EventViewer.

Not even in "uknown events" in EventViewer?

**Comment by alkalim** [comment]
> Not even in "uknown events" in EventViewer?

I didn't know about "Unknown events", but just checked - no, not even there 😕

**Comment by MuhammedZakir** [comment]
1. Is a keyboard-related Logitech software running?
2. Does your keyboard have on-board memory?

Either of these could interfere and create issues.

**Comment by alkalim** [comment]
Yes, I run Logitech Options+ and can confirm that these keys are visible without that software installed (checked on another Mac with the same keyboard). I believe the most (or at least significant part) of Logitech MX keyboard users run this software. Should Karabiner Elements support such configuration (if it's technically possible) or this is supported by design and case closed?

**Comment by MuhammedZakir** [comment]
If I am right, the issue is with Logitech Options+ (LO+). I don't think KE can do anything about this.

Have you tried running KE after LO+, or running LO+ after KE? For some stuff, order matters.

You can also check the Log tab in KE to see if there is any useful info.

**Comment by alkalim** [comment]
Thanks for the suggestions. Both LO+ and KE are registered as global launch agents so there is no straightforward way to manage the order. I need to decide which one to keep :)

**Comment by rumbin** [comment]
@alkalim Have you found any solution for this issue?

**Comment by alkalim** [comment]
Sadly, no.

**Comment by pmunin** [comment]
it does not matter which order you start/restart/install daemons/apps of Karabiner vs LogiOptions+. The LogiOptions+ always overrides Karabiner 👎 The only way to make HOME END PGDOWN PGUP visible for Karabiner is to uninstall LogiOptions+ or  disable it in MacOs Settings/Privacy&Security/Input Monitoring.
![image](https://github.com/pqrs-org/Karabiner-Elements/assets/7120440/41efd0a9-1833-42ac-bf21-b1e9381faff2)
