### ISSUE TITLE
Feature: Support `is_built_in_keyboard` in `device_if`, `device_unless` of Complex Modifications

### ISSUE THREAD

**Issue by dayflower** [pqrs-org/Karabiner-Elements#3166]
It would be great if we can write complex modification rules for internal keyboard only (or except internal keyboard) easily.

Background:
I sometimes write complex modification rules that behaves differently on internal and external keyboard.
I've used `vendor_id` and `product_id` to detect whether the target device is internal or not, but I cannot get `vendor_id` and `product_id` for recent M2 MBA/MBP, you know.
If `is_built_in_keyboard` (defined in https://github.com/pqrs-org/Karabiner-Elements/blob/1ffa362/src/share/device_properties.hpp#L358) could be appled to `identifiers` rule (as written in https://github.com/pqrs-org/Karabiner-Elements/blob/1ffa362/src/share/device_properties.hpp#L358), it would work and be straight-forward for writing rules.

**Comment by tekezo** [comment]
`is_built_in_keyboard` is available since the latest beta version. (v14.8.2)
Please confirm it.

How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by dayflower** [comment]
Seems to work in my environment with Beta version.

Thanks for implementing this feature so quickly!
