### ISSUE TITLE
Selectively Swapping Modifiers in a Complex Rule

### ISSUE THREAD

**Issue by Muirium** [pqrs-org/Karabiner-Elements#3169]
Hey folks,

I use many different keyboards with my Mac. ([Keyboard nerd](https://deskthority.net/viewtopic.php?f=7&t=25461)!) Naturally, I want the Mac order of modifier keys—with Command closest to the spacebar on both sides—on all of my boards. Many of them are programmable, so I do this internally. But I have three USB native keyboards with the wrong (PC standard) sequence, which I'd like to correct with a Complex Rule so I don't have to fiddle around manually making 4 Simple Rules for each of them (and all future additions).

I made this list of device and vendor id's for my various keyboards:
```
Keyboard			Vendor_id	Product_id
MacBook Air internal		1452		641
Apple Bluetooth alu		1452		570

Mac mods already in effect:
HHKB white on USB		65261		16962
HHKB black on USB		65261		16962
HHKB white on Bluetooth		0		0
HHKB black on Bluetooth		205		102
Kishsaver with Pandrew's QMK	1153		2
Beamspring with Pandrew's QMK	1153		2
IBM AT with Pandrew's QMK	1153		2
NMB RT8255C+ with internal TMK	65261		7150
Alps64 with TMK			65261		25700
SSK with Soarer on Colossus	5824		1149
TMK PS/2 Converter		65261		7150
TMK ADB Converter		65261		2779

PC modifier keys:
Topre Realforce 87u		2131		273
Coolermaster Novatouch		9494		39
Filco Majestouch 2 TKL		1241		17733
```
Only those last three (currently) need Command and Option swapped. I've had a rule for remapping Caps Lock to Right Control for ages, so I tried the same technique, but using device_if to check for the correct hardware:
```
{
  "title": "⌨️ Other Keyboard Specific Rules",
  "description": "All non-programmable USB keyboards get individual customisation here (sadly doesn't work)",
  "type": "device_if",
  "rules": [
    {
      "description": "⌨️ Macintosh Mods",
      "manipulators": [
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "left_option",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_command"
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "left_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_option"
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "right_option",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_command"
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "right_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_option"
            }
          ],
          "type": "basic"
        }
      ]
    }
```
Much to my frustration, this does not work. What I get instead, typing on the Filco here (vendor_id: 1241) is Control-Command-Command-Space-Option-Command-fn-Control instead of my desired Control-Option-Command-Space-Command-Option-Fn-Control. I have no Simple Rules for this (or generic) keyboards to conflict with, and I've checked System Preferences to ensure it is set to defaults as well.

What's going on? Are my rules stepping on top of each other in sequence? How should I do this?

Incidentally, System Preferences > Keyboard > Modifier Keys… is not playing well with Karabiner either. I tried setting the modifier order there (it's much faster than Simple Modifications in Karabiner, as Sys Prefs takes two rules per keyboard instead of 4, acting symmetrically). But then I found Karabiner (in its default settings, version 14.8.0, running on Monterey 12.5 on M1) overriding those remaps back to the PC sequence. Very strange all round.

I'd prefer to do this as a single Complex Rule, instead of all that mousing, so I can apply it easily on every Mac I use (and beta OS version testing, etc.). Reconstructing things every time with mouse clicks aplenty is a nightmare I strongly wish to avoid.

**Comment by Muirium** [comment]
More details:

When I plug in a PC-layout keyboard for the first time, Karabiner and macOS agree its modifier keys are the wrong way around. The bottom row goes Control Command Option Spacebar Option Command Control.

When I disable Karabiner's Modify Events slider for the new keyboard and manually swap around its Command and Option keys in System Preferences > Keyboard, it works immediately.

But when I re-enable Karabiner on that keyboard, Karabiner swaps them back around to the wrong order again! Event Viewer shows this immediately. I keep it running as I toggle the slider.

The only reliable way for me to get the Mac modifier sequence on a PC keyboard is to spell it out in Karabiner's Simple Modifications manually for that specific keyboard as well.

I'd much rather do this in complex rules, using device_if instead of doing it by hand every time.

**Comment by MuhammedZakir** [comment]
There is a wrong line after `description`. Maybe that's causing the problem? Check Log tab, which should show errors in your config.

> Incidentally, System Preferences > Keyboard > Modifier Keys… is not playing well with Karabiner either.

It won't work. Of the keyboards managed by KE, the only one you can modify is "Karabiner Virtual Keyboard".

**Comment by Muirium** [comment]
Thanks again Muhammed. I took out the offending line. No errors in my log file now, but the rule does not work as desired. Here's the current file, with two rules: one for swapping the modifiers on all 3 USB PC keyboards I listed in the opening post. And a second rule specifically for the Realforce's Application key; which only it has.

```
{
  "title": "⌨️ Other Keyboard Specific Rules",
  "description": "All non-programmable USB keyboards get individual customisation here (sadly doesn't work)",
  "rules": [
    {
      "description": "⌨️ Macintosh Mods",
      "manipulators": [
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "left_option",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_command"
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "left_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_option"
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "right_option",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_command"
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 1241
                },
                {
                  "vendor_id": 2131
                },
                {
                  "vendor_id": 9494
                }
              ]
            }
          ],
          "from": {
            "key_code": "right_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_option"
            }
          ],
          "type": "basic"
        }
      ]
    },
    {
      "description": "⌨️ Realforce",
      "manipulators": [
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 2131
                }
              ]
            }
          ],
          "from": {
            "key_code": "application"
          },
          "to": [
            {
              "apple_vendor_top_case_key_code": "keyboard_fn"
            }
          ],
          "type": "basic"
        },
        {
          "conditions": [
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 2131
                }
              ]
            }
          ],
          "from": {
            "key_code": "scroll_lock",
            "modifiers": {
              "mandatory": [
                "shift"
              ]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "numeric_keypad_mode",
                "value": 1
              }
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
```
With these rules active, and with macOS System Preferences > Keyboard > Modifier keys set to default values for the Coolermaster NovaTouch (vendor ID 9494), and no Simple Modifications set for this keyboard, I still get the bad sequence: Control Command Command Spacebar Option Command Control. Left_command is duplicated on the left of the keyboard, while right_option and right_command remain in the wrong order, which my rule is intended to flip. I don't know what's going on!

**Comment by MuhammedZakir** [comment]
I am also not sure what's wrong here.

1. I presume you have enabled input modification for all your devices? Some devices show up as 2 devices.

2. Does modification work if you don't use conditions?

3. Note that KE uses the first matched manipulator in `karabiner.json`. Have you tested it using a blank/new profile?

**Comment by Muirium** [comment]
Good tip re: trying a new profile. With a clean "Testing" profile, with only the Mac modifier rules enabled, the Realforce is working just now when the very same rule was producing the same bad modifier order just before. This is with device_if active, so my other, Mac native keyboard remains correctly unmodified. There must be something conflicting in my many rules with this particular one. Perhaps I can get the fix I want by simply promoting it higher in Karabiner's complex rules list. I'll try that.

**Comment by Muirium** [comment]
Done. And it's working a beaut. Thanks Muhammed! I've got all three offending (USB native + PC layout) keyboards connected simultaneously, and they now all have the correct modifier order, thanks to the rule above. Just as I wanted. Sweet! Case closed, thanks to you.
