### ISSUE TITLE
how to use "Ignore bouncing (chattering) events" setting 

### ISSUE THREAD

**Issue by someblue** [pqrs-org/Karabiner-Elements#3176]
Sorry, I'm not sure is it the right place to look for help.

I cannot find the "Ignore bouncing (chattering) events" setting, released in 10.5.0 ([released note](https://karabiner-elements.pqrs.org/docs/releasenotes/#karabiner-1050)). My version is 12.9.0. But I cannot find the entrance to this settings. And I cannot find document about how to use it. Where can I adjust this settings? Thanks for any help!

**Comment by MuhammedZakir** [comment]
"Karabiner" (old/obsolete version) and "Karabiner-Elements" (recent versions) are different. KE don't have many features that were in Karabiner.

**Comment by someblue** [comment]
> "Karabiner" (old/obsolete version) and "Karabiner-Elements" (recent versions) are different. KE don't have many features that were in Karabiner.

Thanks for your explaination. Is there any plan that KE add this feature?

**Comment by nejmeijer** [comment]
Closing this since this question seems to apply to the old Karabiner instead of KE.
