### ISSUE TITLE
How can I hide karabiner-elements on Dock?

### ISSUE THREAD

**Issue by avatar-lavventura** [pqrs-org/Karabiner-Elements#3178]
`Karabiner-Elements` keeps showing up in the docker.

I want to  hide karabiner-elements on Dock, how can I do it?

**Comment by MuhammedZakir** [comment]
Is it just the icon, or is the app "opened"? If it's former, there is an option to remove from Dock be right-clicking it. Have you tried that? If it's latter, see https://karabiner-elements.pqrs.org/docs/help/troubleshooting/preferences-window-shown-at-login/.

**Comment by avatar-lavventura** [comment]
When I remove it still will Karabiner runs on the start-up?
