### ISSUE TITLE
Remapping section sign (§) and plus-minus (±) stopped working

### ISSUE THREAD

**Issue by gonzus** [pqrs-org/Karabiner-Elements#3179]
I have been using this complex modification for months with my M1 and an external logi keyboard. Yesterday I updated the OS (company policy, unavoidable) and this modification now behaves weirdly.

https://ke-complex-modifications.pqrs.org/#section_sign_to_backtick

The remapped key still successfully generates backtick and tilde, but pressing `Command-backtick` simply does not work and does nothing. I noticed almost immediately because this is a combination I use all the time (to cycle among all the windows of the current application). If I use the other, original backtick key, it does cycle the windows.

I tried fully removing Karabiner, rebooting and reinstalling -- no change.

Please let me know what other information might be relevant for this issue. Thanks!

**Comment by MuhammedZakir** [comment]
If I am understand you correctly: if you want remapping of section key to tilde to work with all modifiers, a better way is to add `any` to `from.modifiers.optional`. This way, you don't to add different manipulators for each modifier.

```json
  {
      "description": "Remap section sign (§) from British Keyboard to US's backtick + plus minus (±) to tilde (~)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "non_us_backslash"
            "modifiers": {
              "optional": [ "any" ]
            }
          },
          "to": [
            {
              "key_code": "grave_accent_and_tilde"
            }
          ]
        }
      ]
  }
```

**Comment by MuhammedZakir** [comment]
If that is not what you want, can you eloborate on what you want vs what is happening? Preferable, with output of Karabiner-EventViewer.

**Comment by gonzus** [comment]
I think I ended up fixing it by doing exactly what you said: I got rid of the complex modification, and added a simple modification for that keyboard only, which maps `non_us_backslash` to `grave_accent_and_tilde`. It works now!

Thanks for your suggestion. Cheers!
