### ISSUE TITLE
karabiner won't read new files in /complex_modifications folder

### ISSUE THREAD

**Issue by internet-dog** [pqrs-org/Karabiner-Elements#3188]
hello! been using karabiner for a few years now with mostly simple mods. extremely new to github, extreme novice with coding etc etc. so please be gentle 😅

recently bought a dinky little bluetooth keyboard for a full custom hotkey board, tested one or two rules using gene sy's generator- all worked fine. i set up the full rules json doc, but when i try to add them by pasting the json file into the complex mods folder, they don't show up in the app. tried restarting, rebooting, reinstalling; nothing seems to work. wondering if there's something wrong in my code that i don't know better about to fix but no errors show up in the log either so i'm a bit lost!

running karabiner 14.8.0 on os 12.5.1 and karabiner 13.7.0 on os 10.15.7.

thanx heaps if you can help!!

[cshotkeys.txt](https://github.com/pqrs-org/Karabiner-Elements/files/9392340/cshotkeys.txt)

**Comment by internet-dog** [comment]
that's what i mean-- they don't show up when i go to the add rule screen. nothing shows up as an error in the log either.


<img width="1162" alt="Screen Shot 2022-08-23 at 9 03 57 am" src="https://user-images.githubusercontent.com/111545140/186034636-9e384d8a-4bed-43ed-9d68-ef3cfe9a6f6b.png">
<img width="1128" alt="Screen Shot 2022-08-23 at 9 06 31 am" src="https://user-images.githubusercontent.com/111545140/186034667-02ba2e9b-13ba-4725-9be2-e5f644b103c0.png">

**Comment by internet-dog** [comment]
wait, i figured it out! there was a stray comma at the end of the last rule 😅 my bad. thanks anyway

**Comment by MuhammedZakir** [comment]
No problem! :-) If you use a good editor, you can at least avoid syntactic mistakes like this.
