### ISSUE TITLE
function key changes the input source

### ISSUE THREAD

**Issue by kwangsungjun** [pqrs-org/Karabiner-Elements#3203]
macOS 12.5, macbook pro 16" (2021)

without adding any rules, just right after installing the karabiner, pressing the function key alone changes the input source. I check the event viewer, there is nothing else than:

```
 {
    "type": "down",
    "name": {"apple_vendor_top_case_key_code":"keyboard_fn"},
    "usagePage": "255 (0x00ff)",
    "usage": "3 (0x0003)",
    "misc": "flags fn"
  },
  {
    "type": "up",
    "name": {"apple_vendor_top_case_key_code":"keyboard_fn"},
    "usagePage": "255 (0x00ff)",
    "usage": "3 (0x0003)",
    "misc": ""
  },
```

**Comment by MuhammedZakir** [comment]
Related: #3092

**Comment by kwangsungjun** [comment]
Thanks. Changing "Press 🌐 to 'Change Input Source'" to "Press 🌐 to 'Do Nothing'" worked out for me.
