### ISSUE TITLE
ZMK board not been recognized properly

### ISSUE THREAD

**Issue by xbladesub** [pqrs-org/Karabiner-Elements#3236]
I have keyboard with nice nano v2 controllers, using ZMK firmware. Some reason this keyboard not been properly recognized by karabiner:

<img width="719" alt="Screen Shot 2022-09-26 at 1 49 28 PM" src="https://user-images.githubusercontent.com/45129790/192202744-44240af1-d31f-45d6-96a3-dbd11c4e8fe9.png">

So I can't disable my built-in MacBook keyboard while my bluetooth zmk board is connected.
Is there any solution for this? 

(btw everything is fine with my second wired board which uses qmk)

**Comment by tekezo** [comment]
Does this issue still happen with the latest release (v14.10.0)?

**Comment by xbladesub** [comment]
> Does this issue still happen with the latest release (v14.10.0)?

Yes, I'm using 14.10.0

**Comment by tekezo** [comment]
Can you set the VID or PID on the ZMK side to isolate the cause of the problem, whether it is because the Vendor ID or Product ID is not taken or other causes?

**Comment by xbladesub** [comment]
> Can you set the VID or PID on the ZMK side to isolate the cause of the problem, whether it is because the Vendor ID or Product ID is not taken or other causes?

specifying PID and vendor id didn't fix the issue. Built-in keyboard still responds to key presses

**Comment by xbladesub** [comment]
@tekezo Also vendor id and PID are displayed correctly if one side off the board is connected via cable to laptop (new instance of keyboard appeared with correct PID and VID). Otherwise, if connected only with bluetooth, it displays 0,0. Doesn't work in both cases, if connected via cable/bluetooth

**Comment by tekezo** [comment]
Thank you for your confirmation, hmm, I need to see log messages to investigation.
Could you show me the log messages at you connect your keyboard?
You can get the log messages by "Copy to pasteboard" button in Log tab.
https://karabiner-elements.pqrs.org/docs/manual/operation/log/

**Comment by xbladesub** [comment]
Solved this. The problem was not in karabiner-elements but in ZMK project. For those who got same problem - use this branch of ZMK - https://github.com/petejohanson/zmk/tree/ble/gatt-dis-config-improvements

**Comment by ReFil** [comment]
These fixes have now been merged into zmk main, so you shouldn't need to use that branch anymore
