### ISSUE TITLE
New versions periodically reset variables that were set

### ISSUE THREAD

**Issue by nikitavoloboev** [pqrs-org/Karabiner-Elements#3256]
Noticed this many times. Confirmed by multiple people from inside [Karabiner group](https://t.me/+UDlL5H7VIwAVK0_7).

This started happening recently so it's a regression in one of the versions. @tekezo

**Comment by rdavison** [comment]
This is happening to me too.

**Comment by rdavison** [comment]
I don't know if there's a correlation, but every time it happens, and I check the logs, I see "Check for updates...", which is a periodic check. Could it be the case that something about that is causing it to reset the variables?

**Comment by rdavison** [comment]
I downgraded my version of Karabiner from v14.10.0 to v14.9.0 and it seems the issue has gone away. So it was likely a recent regression.

**Comment by rdavison** [comment]
I guess I spoke too soon. Even on v14.9.0 I seem to be having variable reset issues. However, it seems that every time it happens, I get a little popup saying something along the lines of "karabiner is disabled until you press $someKey again". When I press the requested key, then it reactivates karabiner, but all my variables are reset.

I don't have a screenshot of it. If I can get one later I'll update this comment.

**Comment by rdavison** [comment]
It also seems to happen after `grabber_client error: Connection reset by peer`.

**Comment by rdavison** [comment]
I kept having issues with >= 14, so I downgraded again to 13.7.0. I've been using it for over an hour, and I haven't seen any variable resets. I also restructured my complex modifications to avoid requiring some variables to be set all the time, so if/when the variables do reset, they don't impact my work so much.

**Comment by nikitavoloboev** [comment]
@tekezo would be super nice if you can take a look at this for next version. I stopped using variables because it's such an issue now of never being able to rely on them. 😿

Thanks.

**Comment by tekezo** [comment]
If you are doing things like restarting console_user_server periodically, you will see this symptom.
Could you show log messages when the variable reset?

**Comment by nikitavoloboev** [comment]
> If you are doing things like restarting console_user_server periodically

I am not doing it. 

I am not sure how I can share you the logs as it happens at random times. I will try to keep the console open when I switch to variable and try see when the switch occurs.

The thing is I only know when I activate a binding that is set to the variable so I will need to use that keybinding often, without variable set it won't trigger.

**Comment by nikitavoloboev** [comment]
@tekezo This is a very annoying regression. Is there anything else I can provide to help resolve this issue?

**Comment by nikitavoloboev** [comment]
Okay for me with 14.10.10 this issue seemed to have gone away.

I will close this issue and reopen if it reappears. 

@rdavison do try update to latest beta, maybe it helps you solve the variable reset issue too.
