### ISSUE TITLE
Caps Lock key light permanently on (aesthetic issue only)

### ISSUE THREAD

**Issue by bruno-robert** [pqrs-org/Karabiner-Elements#3284]
I have some advanced modifications that bind the caps lock key to instead act as a modifier key when held or the escape key when tapped.

This still works great. But whenever I lock and unlock my mac, the caps lock key will be on.
The caps lock itself is off. The modifications work fine. It's only the light that stays on permanently until I turn of the modifications and press the caps lock key twice.

Specs:
- 13 inch M1 macbook pro (2020) with touch-bar.
- MacOS Ventura 13.0 (22A380).
- Karabiner Elements 14.10.0

**Comment by lharri73** [comment]
I also have this issue. I have mapped (left_shift + right_shift) mapped to caps_lock and caps_lock mapped to esc. Using my key binding to toggle caps lock on and then back off turns the light off (for me, pressing left_shift + right_shfit twice).

**Comment by blksith0** [comment]
Capslock -> super
Light always on.

**Comment by hez** [comment]
Also having this issue, usually if I wake the computer and hit capslock as soon as I have unlocked the machine.

**Comment by wmstack** [comment]
Same I do have modification to replace caps-lock with escape and am finding the light on. With the new release of Sonoma sometimes I find the new caps-lock indicator under the cursor as well.

**Comment by munro** [comment]
@bruno-robert maybe more of a work around—but in macOS Settings > Keyboard > Keyboard Shortcuts > Modifier Keys, I set "Caps Lock" key set to "No Action" (I set this on all devices to be safe).  The key mappings I have in Karabiner Elements still works fine—but it turns off the Caps Lock fixs the pesky issue where the light is stuck on (happens if I use capslock+shortcut before Karabiner Elements is fully launched at login).

It's weird, it seems like it shouldn't be an issue, I have "Manipulate caps lock LED" turned on in Karabiner Elements, so you would think it would turn it off—but anyways this fix has been working for me!

**Comment by bruno-robert** [comment]
> @bruno-robert maybe more of a work around—but in macOS Settings > Keyboard > Keyboard Shortcuts > Modifier Keys, I set "Caps Lock" key set to "No Action" (I set this on all devices to be safe). The key mappings I have in Karabiner Elements still works fine—but it turns off the Caps Lock fixs the pesky issue where the light is stuck on (happens if I use capslock+shortcut before Karabiner Elements is fully launched at login).
> 
> It's weird, it seems like it shouldn't be an issue, I have "Manipulate caps lock LED" turned on in Karabiner Elements, so you would think it would turn it off—but anyways this fix has been working for me!

This seems to work for me and is a satisfactory solution.

**Comment by EmpathyZeroed** [comment]
> [@bruno-robert](https://github.com/bruno-robert) maybe more of a work around—but in macOS Settings > Keyboard > Keyboard Shortcuts > Modifier Keys, I set "Caps Lock" key set to "No Action" (I set this on all devices to be safe). The key mappings I have in Karabiner Elements still works fine—but it turns off the Caps Lock fixs the pesky issue where the light is stuck on (happens if I use capslock+shortcut before Karabiner Elements is fully launched at login).
> 
> It's weird, it seems like it shouldn't be an issue, I have "Manipulate caps lock LED" turned on in Karabiner Elements, so you would think it would turn it off—but anyways this fix has been working for me!

Also switching back and forth current keyboard in the same menu helps to reset currently enabled Caps Lock LED without reboot
