### ISSUE TITLE
[Feature Request] Increase "simultaneous_threshold_milliseconds" upper threshold limit (current limit 1000ms)

### ISSUE THREAD

**Issue by dkzsys** [pqrs-org/Karabiner-Elements#3322]
Hi KE community, 

First of all, shout out for this great tool! It makes my day on Mac much more productive, especially on a non-Mac native keyboard:)

I have a request please: to increase the upper threshold limit for "simultaneous_threshold_milliseconds" setting - to say 5000 ms, or any user defined value/no limit (if feasible considering other implications).

It appears that the current upper threshold limit is 1000 (ms); I can use a larger number in json config file but it's bound by the default upper limit. 

My use case is app launcher - press down 2 keys simultaneously to launch an app. For example, hold down ";" and "1" to launch KE, as shown in snippet at the end of the post. 

My challenge is that as I start growing the list of shortcuts, sometimes it takes me more than 1 second to recall the shortcut for a specific app. "simultaneous_threshold_milliseconds"  allows me to have that processing delay after the 1st key is pressed down.  And I need it to be more than 1000ms to compensate for my processing delay and usage pattern.

MacOS: 12.5
KE Version: v14.10.0

Cheers!

```json
{
    "type": "basic",
    "from": {
        "simultaneous": [
            {
                "key_code": "semicolon"
            },
            {
                "key_code": "1"
            }
        ],
        "simultaneous_options": {
            "key_down_order": "strict",
            "key_up_order": "strict_inverse",
            "to_after_key_up": [
                {
                    "set_variable": {
                        "name": "launcher_mode_;",
                        "value": 0
                    }
                }
            ]
        },
        "modifiers": {
            "mandatory": [],
            "optional": [
                "any"
            ]
        }
    },
    "to": [
        {
            "set_variable": {
                "name": "launcher_mode_;",
                "value": 1
            }
        },
        {
            "shell_command": "open -a 'Karabiner-Elements'"
        }
    ],
    "parameters": {
        "basic.simultaneous_threshold_milliseconds": 1000
    }
}
```

**Comment by dkzsys** [comment]
Thankful for KE being open source. Found the parameter in code, tweaked and compiled it. 

Updated it to 5000 (ms), and work like a charm!

![image](https://user-images.githubusercontent.com/39715311/205416975-3eb3486f-da80-4f19-ac34-b3de18cdf6ab.png)

**Comment by crasm** [comment]
I'm writing some complex modifications to get my Razer Tartarus V2 to work on macOS like how it used to work on Windows, and having an upper limit that's higher makes it possible to have a behavior like the "hyper" function with Razer Synapse.

1000ms is enough for basic combinations, but is there any technical reason why this number can't be 10s or even 100s?

**Comment by dkzsys** [comment]
> 1000ms is enough for basic combinations, but is there any technical reason why this number can't be 10s or even 100s?

Both 10s and 100s are less than the default upper bound basic.simultaneous_threshold_milliseconds; therefore they can be set without any code update. (I haven’t checked the code for a very very long time, assuming there was no reduction on default)

To my knowledge, it really just depends on your preference on the key combination "sensitivity" - to find the balance of preventing mis-trigger the key combo vs having enough time to trigger the key combo.

**Comment by crasm** [comment]
That wasn’t a typo on my part. By 10s I meant 10000ms and by 100s I meant 100000ms. I just didn’t want to type out all the zeros.

If the 5000ms upper limit has been working for you, I may try to submit a PR to update the default value to 10000ms.

**Comment by dkzsys** [comment]
Oh sorry, I mis-read you original post. I have tried updated the code to use 10000ms (10 seconds) as default, and it worked fine.

**Comment by tekezo** [comment]
Keys pressed simultaneously need to suppress the original key events. To achieve this, key events need to be delayed by the simultaneous press threshold. 
For example, if the threshold is set to 10 seconds, a 10 second delay will occur. To prevent the keyboard from becoming unusable when inappropriate parameters are specified, the maximum value is limited to 1000ms.

**Comment by dkzsys** [comment]
> Keys pressed simultaneously need to suppress the original key events. To achieve this, key events need to be delayed by the simultaneous press threshold. For example, if the threshold is set to 10 seconds, a 10 second delay will occur. To prevent the keyboard from becoming unusable when inappropriate parameters are specified, the maximum value is limited to 1000ms.

I'll use my use case as an example. Currently, I have updated the upper bound threshold for basic.simultaneous_threshold_milliseconds to 5000 (5 seconds). I use ";" + another key to launch a specific app.
- When I press ";", I can have up to 5 seconds to think/react which other key I need to press to launch the corresponding app.
- If I wait for more than 5 seconds, I'll get (repeating) ";;;;;;;"  as the output.
- If I press and release ";", I'll get just ";", as expected.

I'm happy for the outcome. 

The only challenge I have is when I type too fast, those key combinations get triggered as I couldn't release the key quick enough. But that's all together a different issue of the opposite nature.
