### ISSUE TITLE
Karabiner app replace "<>" key with "^°" key

### ISSUE THREAD

**Issue by brainstorm82** [pqrs-org/Karabiner-Elements#3323]
On my german key board the keys for <> and ^° are switched with no obvious reason.
When I terminate the Karabiner app those keys are back to normal again.

Mac OS: 13.0.1 (22A400)
Device: Mac Book Pro 16 (2021)
Keyboard Settings: 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/16865609/205487963-cd091ace-4a12-4eef-8bd1-0cfcfc9d93db.png">

**Comment by kallekj** [comment]
Same for me but with a Swedish keyboard, the '<>' and '§°' button is switched.

MacOS: 13.2
Device: MacBook Pro M1 Pro 14" 2021
Keyboard settings: Swedish
Virtual keyboard: No difference between '---' and ISO (Europe, Latin America, Middle-East, and others).

If I disable modify events, the keyboard map is correct.

**Comment by gforien** [comment]
Same for me with a French PC layout on my mac. When I launch Karabiner, the <> and ² are swapped.

I fixed it by
- setting the Karabiner virtual keyboard as **ANSI** (even if my physical keyboard is **ISO**)
- restarting Karabiner

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/7701186/218946721-9784456f-68b6-4cdc-ab94-19f7209d454b.png">

MacOS: 12.4
MacBook Pro M1 Pro (16", 2021)
Karabiner 14.11.0

**Comment by heebj** [comment]
Same for me. When I select ISO as virtual keyboard type it actually acts as ANSI keyboard and vice versa.  

macOS version: macOS 14.2.1
Karabiner version: Karabiner-Elements 14.13.0
Your Mac hardware: M1 MacBook Pro 2021
Your keyboard hardware: Internal MacBook Keyboard
