### ISSUE TITLE
Karabiner above other apps (e.g. doesn't allow Excel shortcuts)

### ISSUE THREAD

**Issue by mrbartuss** [pqrs-org/Karabiner-Elements#3326]
Hi,

I've just downloaded Karabiner. The only thing I wanted to achieve was to replace right option and command. Unfortunately, the app also changed fn keys. For example in Excel I cannot use F4 for absolute references. It seems Karabiner is above other apps. How can I change it?

Many thanks,
Bartłomiej

**Comment by Jendker** [comment]
Swapping right option and command works just fine for me. Do you mean that originally you were using F1, F2 without fn key and it doesn't work anymore?

**Comment by Jendker** [comment]
Are you running Ventura? In this case maybe this issue will be relevant: https://github.com/pqrs-org/Karabiner-Elements/issues/3321

**Comment by mrbartuss** [comment]
I’ve just reinstalled the app, created a new profile and deleted the first one. It seems now everything works :)
