### ISSUE TITLE
[feature request] Completely disable multitouch extension

### ISSUE THREAD

**Issue by ysBach** [pqrs-org/Karabiner-Elements#3347]
I recently found out "karabiner_grabber" starts to use certain amount of CPU resources immediately after when I put my finger on the trackpad.
I never use multitouch extension with karabiner, and I do not want to add this overhead to my mac when I don't use keyboard but only trackpad.

Can I completely turn multitouch extension off?

**Comment by tekezo** [comment]
In Karabiner-Elements v15.0.0, the startup method was changed so that the multitouch extension won't start at all unless explicitly enabled.
