### ISSUE TITLE
Keyboard input not being recognized

### ISSUE THREAD

**Issue by r357** [pqrs-org/Karabiner-Elements#3370]
After updating to 14.11.0 I noticed my bindings don't work with Keychron K3.
The issue seems to be that the input device is not even listed in Karabiner. Config file contains my settings, but these are not shown in Karabiner since the keyboard is not being recognized as an input device (even though I'm typing this on it right now).

Tried common remedies, but none work. 
This shows up in the Karabiner logs:

```
[2023-01-14 10:24:08.421] [info] [console_user_server] version 14.11.0
[2023-01-14 10:24:08.537] [info] [console_user_server] on_console_changed: on_console:true
[2023-01-14 10:24:08.540] [info] [console_user_server] grabber_client is started.
[2023-01-14 10:24:08.540] [error] [console_user_server] grabber_client connect_failed: Connection refused
[2023-01-14 10:24:09.612] [error] [console_user_server] grabber_client connect_failed: Connection refused
[2023-01-14 10:24:10.621] [error] [console_user_server] grabber_client connect_failed: Connection refused
... repeat every second. 
```
Any recommendations on a fix?

**Comment by r357** [comment]
Potentially this? 
#3267

**Comment by MaWel8** [comment]
Hi,
I had exactly the same issue, in my case my bindings didn't work for neither my external keyboard, nor the internal keyboard on my MacBook.  
Reinstalling Karabiner-Elements fixed the problem for me.

The GUI-based uninstaller from within the application just threw an error message, but the bash script for uninstalling seemed to work: (official docs)[https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/]

I reinstalled using brew, but I think installing from the homepage should work the same.


Regarding #3267, before reinstalling the application, the `.sock` file was missing from the `user/501/grabber_client/` directory (the directory was just empty). So, I assume that the missing file was the part that may broke the application.

**Comment by r357** [comment]
Thank you! Confirming the following worked:

1. Uninstall using the bash script for uninstalling: [official docs](https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/)
2. Reinstall.

The old configuration was already there and working on first start-up.
