### ISSUE TITLE
Finder actions doesn't work like expected

### ISSUE THREAD

**Issue by vyskoczilova** [pqrs-org/Karabiner-Elements#3402]
Hi!

Such a great app, but in some contexts, the shortcuts affects each other when they shouldn't:

I use several actions from this one: https://ke-complex-modifications.pqrs.org/json/finder.json

- Use Return as Open
- Use F2 as Rename
- Use Delete as Move to Trash
- Use Backspace to go to the Previous Folder

It's awesome, but the problems emerge when I try to rename a file:

- When I try to delete or backspace one of the parts of the name - nothing happens first, and sometimes it ends in the trash
- When I overwrite the text (which is sometimes not what I want to do - if you've got the suffix "copy," you just might delete it and add something else) and hit enter to save it, I get the file open.

Could you help with this? Or how to prevent them from this behavior when editing the file name? Thanks a lot

**Comment by i-amdroid** [comment]
Hi @vyskoczilova , I had the same issue. This recipe solved the issues https://ke-complex-modifications.pqrs.org/#finder_improved_navigation

**Comment by vyskoczilova** [comment]
Hi! Fantastic fix, thanks a lot!
