### ISSUE TITLE
How to map ±§ key

### ISSUE THREAD

**Issue by tewodroswondimu** [pqrs-org/Karabiner-Elements#3414]
I tried several mapping but was unable to get ±§ key to map to something else. It is on a mac magic key right before the "1" key on the number row.

**Comment by bradhowes** [comment]
There seems to be a configuration that does this here -- https://ke-complex-modifications.pqrs.org
Search for "section sign"

**Comment by tewodroswondimu** [comment]
Thanks @bradhowes, that was a lot of help. 

For others who faced the same issue. Although there were a limited number of choices available in terms of rules I could import for that key, I was able to look at the JSON and find that the 
     ±§ is labeled **non_us_backslash** under 'Controls and Symbols'. 
 Voila, I am able to map to any key.

**Comment by mngyuan** [comment]
For future reference you can also use the Karabiner EventViewer which come with Elements to see keycodes of what keys you're pressing, which is how I mapped this key recently when I ran into the same issue.
