### ISSUE TITLE
mouse mapping not work

### ISSUE THREAD

**Issue by keyp-dev** [pqrs-org/Karabiner-Elements#3516]
![image](https://github.com/pqrs-org/Karabiner-Elements/assets/11256291/1b669d45-7d00-4f93-8a31-44aee99183a4)

<img width="561" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/11256291/d87e533f-c8cb-4eb7-9c84-5af347489a87">
<img width="826" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/11256291/009ab6d5-86b7-4524-a2c6-8326e81687cf">

**Comment by tekezo** [comment]
https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-devices/

**Comment by keyp-dev** [comment]
> https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-devices/

thx
