### ISSUE TITLE
Bug: System default configuration not working when setting input source condition

### ISSUE THREAD

**Issue by rasulomaroff** [pqrs-org/Karabiner-Elements#3524]
Karabiner has _"System default configuration"_ setting that allows to use any key mappings before login. It works, **but partially**.

I use 2 keyboard layouts and Colemak is my main English layout. The thing is that key mappings that use the input source condition are not working before login at all.

<img width="504" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/80093436/627fdd4c-9780-48cb-96fe-245b25dbbec6">

Then I decided to remap just US layout to be Colemak, but it affects my second layout and totally messes it.

**My main question is** - Is it a bug that source conditions are not working before login or expected behavior? Restriction from the Apple side to read that information before login?

**Comment by rasulomaroff** [comment]
I would like to emphasize that I'm talking about **before login** event (when I restart my mac or when I log out). If I just lock the screen, then input source key mappings work as expected.

**Comment by tekezo** [comment]
It's expected behavior.
Detecting the status of the input source requires an agent process running with user privileges, but the login screen does not allow the agent to be started, so it does not work.
