### ISSUE TITLE
Broken by update from 13.4 to 13.4.1

### ISSUE THREAD

**Issue by dactylo** [pqrs-org/Karabiner-Elements#3527]
Immediately after upgrading to 13.4.1, Karabiner stopped working.

I've already tried the things here:
https://karabiner-elements.pqrs.org/docs/help/troubleshooting/stopped-working-after-macos-update/

Rebooted several times, reinstalled twice. Granted permissions under Privacy&Security after each reinstall.

The rules in my `.config/karabiner/karabiner.json` are still there, and I see items for them under Complex Modifications, but they have no effect.

Am I the only one?

**Comment by anderscarling** [comment]
For me, what worked was:

1. Uninstalling Karabiner (using the uninstaller script).
2. Removing the relevant lines from Privacy & Security (not just disabling them).
3. Installing Karabiner.
4. Adding back permissions in Privacy & Security (as prompted by Karabiner).
5. Rebooting.

No events was captured by Karabiner until after that final reboot.

**Comment by dactylo** [comment]
I could swear I did that order of events among others, but that seems to work, at least this time.

Thanks!
