### ISSUE TITLE
To avoid the delay when using "to_if_alone"

### ISSUE THREAD

**Issue by ewos** [pqrs-org/Karabiner-Elements#3538]
Hello KE community,

I have a question and would be grateful if someone could help me.

I am using "to_if_alone" and "to_if_held_down" to assign 2 functions to one key, and it works fine. However, "to_if_alone" requires a short delay. When I try to do something like below, I normally can't type the "q" properly at normal typing speed. I  usually get "inuiry" instead of "inquiry" and I have to wait a little bit to type "q" to ensure it registers correctly.

```
"type": "basic",
"from": {
	"key_code": "q",
	"modifiers": {
		"optional": [
			"caps_lock"
		]
	}
},
"parameters": {
	"basic.to_if_alone_timeout_milliseconds": 250,
	"basic.to_if_held_down_threshold_milliseconds": 250
},
"to_if_alone": [
	{
		"key_code": "q"
	}
],
"to_if_held_down": [
	{
		"key_code": "6",
		"repeat": false
	}
]
```

I thought I could solve this by working with variables, but I couldn't figure out how.

I noticed that I don't experience this delay if I use "to" instead of "to_if_alone". However, this causes an issue where I get "q6" when I hold down "q". Of course, this behavior is reasonable.

In the end, I resorted to something like the following, and while it behaves mostly how I want it to, it's rather ridiculous.

```
"type": "basic",
"from": {
	"key_code": "q",
	"modifiers": {
		"optional": [
			"caps_lock"
		]
	}
},
"parameters": {
	"basic.to_if_alone_timeout_milliseconds": 250,
	"basic.to_if_held_down_threshold_milliseconds": 250
},
"to": [
	{
		"key_code": "q",
	}
],
"to_if_held_down": [
	{
		"key_code": "delete_or_backspace",
	},
	{
		"key_code": "6",
		"repeat": false
	}
]
```

Could someone please tell me the proper way to do this?

Thank you.

**Comment by bintoro** [comment]
Basically, there seems to be a slight delay in processing both `to_if_alone` and `to_after_key_up`. If the configured key and another key are pressed in rapid succession, `to_if_alone` loses the first event completely (doesn’t even show up in the event viewer), whereas `to_after_key_up` causes the events to arrive in the wrong order.

The issue has been discussed in #1667. There’s also a solution provided.

You need to do two things:
- Duplicate the `to_if_alone` event as a `to_delayed_action.to_if_canceled` event. This will handle cases where `to_if_alone` is too slow.
- Add `"halt": true` to both `to_if_alone` and `to_if_held_down` to prevent the delayed action from triggering when the keypress has already been handled by either of these two.

```json
{
  "type": "basic",
  "from": {
    "key_code": "q",
    "modifiers": {
      "optional": [
        "caps_lock"
      ]
    }
  },
  "parameters": {
    "basic.to_if_held_down_threshold_milliseconds": 250
  },
  "to_if_alone": [
    {
      "key_code": "q",
      "halt": true
    }
  ],
  "to_delayed_action": {
    "to_if_canceled": [
      {
        "key_code": "q"
      }
    ]
  },
  "to_if_held_down": [
    {
      "key_code": "6",
      "repeat": false,
      "halt": true
    }
  ]
}
```

**Comment by ewos** [comment]
Wow, it worked perfectly! Thank you for sharing the solution with me. It's really clear, practical, and straightforward.

**Comment by NeighNeighNeigh** [comment]
> Basically, there seems to be a slight delay in processing both `to_if_alone` and `to_after_key_up`. If the configured key and another key are pressed in rapid succession, `to_if_alone` loses the first event completely (doesn’t even show up in the event viewer), whereas `to_after_key_up` causes the events to arrive in the wrong order.
> 
> The issue has been discussed in #1667. There’s also a solution provided.
> 
> You need to do two things:
> 
> * Duplicate the `to_if_alone` event as a `to_delayed_action.to_if_canceled` event. This will handle cases where `to_if_alone` is too slow.
> * Add `"halt": true` to both `to_if_alone` and `to_if_held_down` to prevent the delayed action from triggering when the keypress has already been handled by either of these two.
> 
> ```json
> {
>   "type": "basic",
>   "from": {
>     "key_code": "q",
>     "modifiers": {
>       "optional": [
>         "caps_lock"
>       ]
>     }
>   },
>   "parameters": {
>     "basic.to_if_held_down_threshold_milliseconds": 250
>   },
>   "to_if_alone": [
>     {
>       "key_code": "q",
>       "halt": true
>     }
>   ],
>   "to_delayed_action": {
>     "to_if_canceled": [
>       {
>         "key_code": "q"
>       }
>     ]
>   },
>   "to_if_held_down": [
>     {
>       "key_code": "6",
>       "repeat": false,
>       "halt": true
>     }
>   ]
> }
> ```

Hey firstly thanks so much for this solution it is very helpful. Just wondering if there's a way to handle either of these two cases?

1) In the above example if I press and hold W it will output 6-down then immediately 6-up. But is there a way to keep 6 held down until I release the key and then send 6-up?

2) is there a way to send a _different_ after up if the key was held long enough to trigger the to_if_held_down action?
