### ISSUE TITLE
Switch MacOS input type when connecting/disconnecting a keyboard?

### ISSUE THREAD

**Issue by SuperFola** [pqrs-org/Karabiner-Elements#3547]
Hi there!

I was looking for a way to automatically do some actions when connecting a keyboard to my Mac ; I found how to disable the builtin keyboard when I connect my external keyboard, but I was hoping to be able to automatically switch the input source.

I found this snippet, but from what I read in the docs, it always expect some kind of additional `from` bloc, defining a keyboard event to rebind a key to the layout switching behaviour?
```
{
    "to": [{
        "select_input_source": {
            "language": "^en$",
            "input_source_id": "com.apple.keylayout.ABC"
        }]
    }
}
```

Is there a way to automatically switch to ABC (engligh) when connecting a keyboard and to FR (french) when disconnecting it?

**Comment by ManeLippert** [comment]
**Hello @SuperFola**,

after investigating the documentation I came up with the following complex modification to "automate" the language switching. It changes to the desired keyboard layout if you press any key on the external keyboard and switch back to the internal keyboard preset layout. You could also change the identifier (e.g. ```vendor id``` or ```product id```)  for the device, if you want to change a specific external keyboard. Maybe this helps you out in your problem.

The only drawback with this method is that you have to press a key on the keyboard and then the language switches. You can not just write immediately in the other language. If someone knows how I could switch the language and write simultaneously, please write!

### Sources
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/select-input-source/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/select-input-source/)
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/)
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/any/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/any/)
- [https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/input-source/](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/input-source/)

```json
{
    "title": "Dynamic Keyboard Layout",
    "rules": [
        {
            "description": "Change keyboard layout on external keyboard to, e.g. English US, after pressing any button and back to, e.g. German DE, after pressing any button on the built-in keyboard.",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "any": "key_code"
                    },
                    "to": [
                        {
                            "select_input_source": {
                                "input_source_id": "com.apple.keylayout.US",
                                "language": "en"
                            }
                        }
                    ],
                    "conditions": [
                        {
                            "type": "input_source_if",
                            "input_sources": [
                                {
                                    "language": "de"
                                }
                            ]
                        },
                        {
                            "type": "device_if",
                            "identifiers": [
                                {
                                    "is_built_in_keyboard": false
                                }
                            ]
                        }
                    ]
                },
                {
                    "type": "basic",
                    "from": {
                        "any": "key_code"
                    },
                    "to": [
                        {
                            "select_input_source": {
                                "input_source_id": "com.apple.keylayout.German",
                                "language": "de"
                            }
                        }
                    ],
                    "conditions": [
                        {
                            "type": "input_source_if",
                            "input_sources": [
                                {
                                    "language": "en"
                                }
                            ]
                        },
                        {
                            "type": "device_if",
                            "identifiers": [
                                {
                                    "is_built_in_keyboard": true
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by SuperFola** [comment]
Thanks a lot for your comment, I will try that!

**Comment by jdeniau** [comment]
Hi ! 

I'm interested too, and did include @ManeLippert script with one small modification : 
My use case is to use a TypeMatrix dvorak keyboard.

The change I made is to use the `vendor_id` instead of `"is_built_in_keyboard": false` as I want to use dvorak only if I plug an external keyboard that is a typematrix one only.

```json
{
  "title": "Dynamic Keyboard Layout",
  "rules": [
    {
      "description": "Switch to dvorak if a typematrix keyboard is used, and switch back to FR for built-in keyboard.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "any": "key_code"
          },
          "to": [
            {
              "select_input_source": {
                "input_source_id": "com.apple.keylayout.Dvorak",
                "language": "en"
              }
            }
          ],
          "conditions": [
            {
              "type": "input_source_if",
              "input_sources": [
                {
                  "language": "fr"
                }
              ]
            },
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 7764
                }
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "any": "key_code"
          },
          "to": [
            {
              "select_input_source": {
                "input_source_id": "com.apple.keylayout.French",
                "language": "fr"
              }
            }
          ],
          "conditions": [
            {
              "type": "input_source_if",
              "input_sources": [
                {
                  "language": "en"
                }
              ]
            },
            {
              "type": "device_if",
              "identifiers": [
                {
                  "is_built_in_keyboard": true
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

```

A possible evolution (that does not seems to exist) may to have a triggered event when a keyboard is plugged on unplugged.

It seems that there is a triggered event because the event viewer on the "devices" tab is updated "live", but I do not know how to detect that in the script.

https://github.com/pqrs-org/Karabiner-Elements/assets/1398469/e62339cf-b8ec-4b58-97bb-5d0f5c65e2e2

**Comment by jdeniau** [comment]
You are right, the second evolution would be the better. This way it will handle the native keyboard even if another keyboard is plugged in

**Comment by ManeLippert** [comment]
@jdeniau the underlining problem for your suggestion is that karabiner elements register the key stroke in the previous language, then it does the language switch, but does not translate the keycode into the new language and type it in the previous language. So we have to manage somehow the "translation" process.

**Comment by SuperFola** [comment]
Thanks, the suggested solution works for me!

I forgot to come back to this issue, sorry for being this late.
