### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by HalfWhitt** [pqrs-org/Karabiner-Elements#3568]
Is there any way to use Karabiner to modify input from game controllers (e.g. PlayStation, XBox, 8bit Do)? If so, how?

If not:
 - I suppose I'd like to request it as a feature. I don't know how feasible it would be to add.
 - It would probably clarify matters to mention specifically in the documentation that game controller input is *not* supported.

**Comment by tekezo** [comment]
It doesn't support changing game controller events while keeping them as game controller events, but recent versions of Karabiner-Elements allow you to remap gamepad buttons to key events and use the sticks for mouse movement.
(However, this is limited to DirectInput devices; there are no plans to support XInput at this time.)

**Comment by llemonhelpp** [comment]
Where is the option to remap gamepad buttons? There doesn't seem to be any options to select gamepad buttons in the Simple Modifications section.
