### ISSUE TITLE
標準にはないキーのリマッピング

### ISSUE THREAD

**Issue by kingtosh** [pqrs-org/Karabiner-Elements#3571]
EventViewerで以下のように取得されるキーを、別のキーにリマッピングもしくはイベントを割り当てたいのですがどのようにしたらよろしいのでしょうか？

 "name": {"key_code":"(number:176)"},
 "usagePage": "7 (0x0007)",
 "usage": "176 (0x00b0)",
 "misc": ""

consumer key codeに記入してもダメでした。
よろしくお願いします。

**Comment by tekezo** [comment]
Specifing the raw value should work.

```
{
    "from": {
        "key_code": 176
    }
}
```

https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/#investigate-key-names

**Comment by kingtosh** [comment]
ありがとうございました！
