### ISSUE TITLE
Latest Karabiner Elements driver update breaks inserting symbols in VSCode 

### ISSUE THREAD

**Issue by nikitavoloboev** [pqrs-org/Karabiner-Elements#3595]
Updated to latest VSCode and updated the driver.

<img width="835" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/f1ca0cb4-05f0-4794-b7fb-60f8b0f1695a">

Now I have a massive regression where in VSCode with Karabiner on, I can't enter some characters.

<img width="415" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/4eb579a4-66fa-435d-a8e7-d779a8b8db13">

Above image is perfect example. With karabiner elements quit, when I type `the` as above, it works.

With karabiner elements on, it will always eat the `h` character no matter what.

I can replicate this 100% of times and its a massive issue as I can't type properly now now that I updated to latest Karabiner. 

I also at first opened issue in VSCode issue tracker: https://github.com/microsoft/vscode/issues/192707

But it seems now the issue is fully on Karabiner Elements and its new driver.

Please help resolve this regression.

I initially noticed it when I tried to enter my `console.log()` binding with karabiner. From this config

```
{
  "global" : {
    "ask_for_confirmation_before_quitting" : true,
    "check_for_updates_on_startup" : true,
    "show_in_menu_bar" : true,
    "show_profile_name_in_menu_bar" : false,
    "unsafe_ui" : false
  },
  "profiles" : [ {
    "complex_modifications" : {
      "parameters" : {
        "basic.simultaneous_threshold_milliseconds" : 30,
        "basic.to_delayed_action_delay_milliseconds" : 0,
        "basic.to_if_alone_timeout_milliseconds" : 80,
        "basic.to_if_held_down_threshold_milliseconds" : 50
      },
      "rules" : [ {
        "description" : "test",
        "manipulators" : [ {
          "from" : {
            "key_code" : "a"
          },
          "to" : [ {
            "key_code" : "c"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "n"
          }, {
            "key_code" : "s"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "e"
          }, {
            "key_code" : "period"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "g"
          }, {
            "key_code" : "9",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "0",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "left_arrow"
          } ],
          "conditions" : [ {
            "name" : "dot-mode",
            "value" : 1,
            "type" : "variable_if"
          } ],
          "type" : "basic"
        }, {
          "type" : "basic",
          "parameters" : {
            "basic.simultaneous_threshold_milliseconds" : 250
          },
          "to" : [ {
            "set_variable" : {
              "name" : "dot-mode",
              "value" : 1
            }
          }, {
            "key_code" : "c"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "n"
          }, {
            "key_code" : "s"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "e"
          }, {
            "key_code" : "period"
          }, {
            "key_code" : "l"
          }, {
            "key_code" : "o"
          }, {
            "key_code" : "g"
          }, {
            "key_code" : "9",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "0",
            "modifiers" : [ "left_shift" ]
          }, {
            "key_code" : "left_arrow"
          } ],
          "from" : {
            "simultaneous" : [ {
              "key_code" : "period"
            }, {
              "key_code" : "a"
            } ],
            "simultaneous_options" : {
              "detect_key_down_uninterruptedly" : true,
              "key_down_order" : "strict",
              "key_up_order" : "strict_inverse",
              "key_up_when" : "any",
              "to_after_key_up" : [ {
                "set_variable" : {
                  "name" : "dot-mode",
                  "value" : 0
                }
              } ]
            }
          }
        } ]
      } ]
    },
    "devices" : [ {
      "disable_built_in_keyboard_if_exists" : false,
      "fn_function_keys" : [ ],
      "identifiers" : {
        "is_keyboard" : true,
        "is_pointing_device" : false,
        "product_id" : 834,
        "vendor_id" : 1452
      },
      "ignore" : false,
      "manipulate_caps_lock_led" : true,
      "simple_modifications" : [ ],
      "treat_as_built_in_keyboard" : false
    }, {
      "disable_built_in_keyboard_if_exists" : false,
      "fn_function_keys" : [ ],
      "identifiers" : {
        "is_keyboard" : false,
        "is_pointing_device" : true,
        "product_id" : 834,
        "vendor_id" : 1452
      },
      "ignore" : true,
      "manipulate_caps_lock_led" : false,
      "simple_modifications" : [ ],
      "treat_as_built_in_keyboard" : false
    }, {
      "disable_built_in_keyboard_if_exists" : false,
      "fn_function_keys" : [ ],
      "identifiers" : {
        "is_keyboard" : true,
        "is_pointing_device" : false,
        "product_id" : 34304,
        "vendor_id" : 1452
      },
      "ignore" : false,
      "manipulate_caps_lock_led" : true,
      "simple_modifications" : [ ],
      "treat_as_built_in_keyboard" : false
    } ],
    "fn_function_keys" : [ {
      "from" : {
        "key_code" : "f1"
      },
      "to" : [ {
        "consumer_key_code" : "display_brightness_decrement"
      } ]
    }, {
      "from" : {
        "key_code" : "f2"
      },
      "to" : [ {
        "consumer_key_code" : "display_brightness_increment"
      } ]
    }, {
      "from" : {
        "key_code" : "f3"
      },
      "to" : [ {
        "apple_vendor_keyboard_key_code" : "mission_control"
      } ]
    }, {
      "from" : {
        "key_code" : "f4"
      },
      "to" : [ {
        "apple_vendor_keyboard_key_code" : "spotlight"
      } ]
    }, {
      "from" : {
        "key_code" : "f5"
      },
      "to" : [ {
        "consumer_key_code" : "dictation"
      } ]
    }, {
      "from" : {
        "key_code" : "f6"
      },
      "to" : [ {
        "key_code" : "f6"
      } ]
    }, {
      "from" : {
        "key_code" : "f7"
      },
      "to" : [ {
        "consumer_key_code" : "rewind"
      } ]
    }, {
      "from" : {
        "key_code" : "f8"
      },
      "to" : [ {
        "consumer_key_code" : "play_or_pause"
      } ]
    }, {
      "from" : {
        "key_code" : "f9"
      },
      "to" : [ {
        "consumer_key_code" : "fast_forward"
      } ]
    }, {
      "from" : {
        "key_code" : "f10"
      },
      "to" : [ {
        "consumer_key_code" : "mute"
      } ]
    }, {
      "from" : {
        "key_code" : "f11"
      },
      "to" : [ {
        "consumer_key_code" : "volume_decrement"
      } ]
    }, {
      "from" : {
        "key_code" : "f12"
      },
      "to" : [ {
        "consumer_key_code" : "volume_increment"
      } ]
    } ],
    "name" : "goku",
    "parameters" : {
      "delay_milliseconds_before_open_device" : 1000
    },
    "selected" : true,
    "simple_modifications" : [ {
      "from" : {
        "key_code" : "caps_lock"
      },
      "to" : [ {
        "key_code" : "escape"
      } ]
    } ],
    "virtual_hid_keyboard" : {
      "country_code" : 0,
      "indicate_sticky_modifier_keys_state" : true,
      "mouse_key_xy_scale" : 100
    }
  } ]
}
```

It will enter this:

<img width="309" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/190bec06-5ccd-49d4-b701-8b38a1b6e747">

When it should be this:

<img width="249" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/19e33c72-27ef-4c83-92c3-0e5c80f3e7f5">

**Comment by nikitavoloboev** [comment]
Maybe the issue is with my parameters?

<img width="567" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/b325b860-39d1-4e04-8fd5-24a985961e04">

My karabiner.json is this:

https://gist.github.com/nikitavoloboev/7dab08f7f38167dcc8fb74e4f5640288/edit

It has launcher key on `t`.

Everything was working well before recent driver update.

**Comment by nikitavoloboev** [comment]
I added more details here too: https://github.com/microsoft/vscode/issues/192707#issuecomment-1712842020

This is super frustrating issue. As I can't actually code now. And I don't want to disable Karabiner as I rely on its bindings.

Please help fix this. ♥️

**Comment by nikitavoloboev** [comment]
Ok with more debugging, the issue is certainly my layers.

With this karabiner.json: https://gist.github.com/nikitavoloboev/02f8afea9c7033c7691e279eb2da0025

I can type things normally

<img width="294" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/d5c9d7fc-a8bb-4c3a-baa2-57f197d55db3">

As seen above with `the the`.

But `console.log()` is still breaking. Above config makes it so pressing `dot key` + `a` should enter `console.log()` by typing it character by character. 

In my case, with my karabiner config here:

https://gist.githubusercontent.com/nikitavoloboev/7dab08f7f38167dcc8fb74e4f5640288/raw/4bb871b29ba03af54bccc4db464b128f5e44942d/karabiner.json

I can't even type `the the` properly. I have to wait like 2 seconds after typing `t` to enter `h` so it shows.

`dot+a` is also broken in that it does not insert `console.log()` properly.

This all started happening after I updated the karabiner driver. 

I can't downgrade the driver though. I sent you a DM on Twitter @tekezo showing video when I tried to downgrade it does not let me. 😿

Don't know what to do at this point.

**Comment by nikitavoloboev** [comment]
When I turn off the `t` layer, I can start typing `the the ` properly

<img width="388" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/4ffb7e5d-c293-44c6-9ef6-29e71f9c0dd0">


Above config is using [goku](https://github.com/yqrashawn/GokuRakuJoudo). Config [here](https://github.com/nikitavoloboev/config/blob/master/karabiner/karabiner.edn).

**Comment by nikitavoloboev** [comment]
Ok found it that typing `pp` using my config I shared above will not work in vscode. The 2nd p won't register..

**Comment by nikitavoloboev** [comment]
<img width="130" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/1b245383-05d4-41c3-913e-a418e15c5741">

is breaking too. Trying to type `rtrtrtrt` but get above in vscode with new karabiner driver and my bindings.

**Comment by nikitavoloboev** [comment]
Ok I took another macbook that did not have Karabiner. 

Installed 14.12.0 on it. Then installed latest VSCode Insiders.

Added my config in there. This one:

https://gist.github.com/nikitavoloboev/988aaa9c08c143214c5b6c5d287cf562

`w+e` enters `console.log()` correctly in there.

So the issue is officially the new Karabiner Elements 14.12.21 and the new engine it has.

It's not issue of VSCode Insiders. 

Please fix the issue in there. 

And allow a way to downgrade because my mac is unuseable with this regression.

Thank you. ♥️

**Comment by tekezo** [comment]
@nikitavoloboev 
So far, I have not been able to reproduce this. (macOS 13.5.2, Apple Silicon, Karabiner-Elements 14.12.21)
To simplify, please let me know if the following settings also reproduce your issue.

```json
{
    "description": "console.log",
    "manipulators": [
        {
            "from": {
                "key_code": "right_shift"
            },
            "to": [
                {
                    "key_code": "c"
                },
                {
                    "key_code": "o"
                },
                {
                    "key_code": "n"
                },
                {
                    "key_code": "s"
                },
                {
                    "key_code": "o"
                },
                {
                    "key_code": "l"
                },
                {
                    "key_code": "e"
                },
                {
                    "key_code": "period"
                },
                {
                    "key_code": "l"
                },
                {
                    "key_code": "o"
                },
                {
                    "key_code": "g"
                },
                {
                    "key_code": "9",
                    "modifiers": [
                        "left_shift"
                    ]
                },
                {
                    "key_code": "0",
                    "modifiers": [
                        "left_shift"
                    ]
                },
                {
                    "key_code": "left_arrow"
                }
            ],
            "type": "basic"
        }
    ]
}
```

<img width="1100" alt="Screenshot 2023-09-11 at 8 41 50" src="https://github.com/pqrs-org/Karabiner-Elements/assets/659178/ac52fa36-1214-473d-bcdd-0ceef0de544c">

**Comment by nikitavoloboev** [comment]
/var/folders/bn/br2v7mf14zb2yqhsyd4xd7nw0000gn/T/Screen Studio Exports/Export-1694419248427.mp4

**Comment by nikitavoloboev** [comment]
https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/44d677bf-6056-4681-b50c-e60880277c30

not sure what I'm doing wrong, I thought pressing right shift would enter those symbols, it does not.

**Comment by nikitavoloboev** [comment]
https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/e678c2af-226b-405f-9283-f10dca6856b5

and this is video of the issue I have actually showing. it's with my config above, basically vscode is fully broken

I don't get why it happens but it happens 100% of times after mac restarts etc. too

**Comment by nikitavoloboev** [comment]
Ok I took another mac where everything is working. And did an upgrade to new driver of Karabiner Elements.

Video here: https://www.youtube.com/watch?v=RdCMXF5Zy6o

To my surprise, everything works smoothly on that mac. Unlike on my main mac.

**Comment by nikitavoloboev** [comment]
https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/0afa3ee9-749f-424e-b455-7263d228b35e

https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/86d1f00a-6f61-467b-a591-e210b8a30e9c

Above is me trying to downgrade Karabiner Elements hoping it will solve the issue. As the issue is 100% in the latest Karabiner driver update. 

I can't downgrade though. I can't resolve the issue in any way.

@tekezo can you try repeat the steps above and check if you can replicate the issue.

Also help me downgrade to earlier version of Karabiner Elements where things worked.

Thank you.

**Comment by nikitavoloboev** [comment]
p.s. It's so messed up now. I can't actually write any code inside VSCode. It just eats like half of the symbols I type.

@tekezo please please hope you can replicate it and until it is fixed give a fix for how to downgrade karabiner to a way where vscode + karabiner works well together 🙏

**Comment by tekezo** [comment]
Hmm, I still cannot reproduce the issue.

1. Upgrade Karabiner-Elements 14.12.20
2. Replace karabiner.json with https://gist.github.com/nikitavoloboev/988aaa9c08c143214c5b6c5d287cf562
3. Install Visual Studio Code Insiders
4. Open plain Visual Studio Code Insiders (without any extra extensions)
5. Press period(.) + 3, 3, 3, 3, ....
6. `Fix #` is repeatedly input.

<img width="1024" alt="Screenshot 2023-09-11 at 23 32 11" src="https://github.com/pqrs-org/Karabiner-Elements/assets/659178/c3e77028-ed07-45da-87a2-6d6b88648b85">

**Comment by nikitavoloboev** [comment]
@tekezo 

Ok so I made a video of downgrading to 12.17 and testing it out.

Video here: https://www.youtube.com/watch?v=RtEQndiFFFc

Summary is that it fails there too.

I am starting to think it's something with VSCode that is broken. The thing is that I can replicate this on another mac too. After updating to latest Karabiner and trying it it in VSCode insiders.

If it is issue with VSCode Insiders, I don't even know what issue I should enter.

Again, things worked well before I did an upgrade to latest version, something happened there. Strange you can't replicate it. 🤔

**Comment by tekezo** [comment]
@nikitavoloboev Thank you! It helped me a lot.
In the process of gamepad support, Karabiner-Elements has increased the number of device events it supports (e.g. Z-rotation), so I think this is the effect of that.
I'll continue to investigate and will keep you posted.

**Comment by nikitavoloboev** [comment]
Please let me know as soon as you have any build that can potentially fix this. 

I can't buy a new mac right now and really need to be able to use VSCode for my work. Downgrading Karabiner still keeps the issue. Turning off Karabiner is not an option too as I rely for Karabiner to work in my work too.

Thank you lots.

**Comment by nicoandmee** [comment]
> Please let me know as soon as you have any build that can potentially fix this.
> 
> I can't buy a new mac right now and really need to be able to use VSCode for my work. Downgrading Karabiner still keeps the issue. Turning off Karabiner is not an option too as I rely for Karabiner to work in my work too.
> 
> Thank you lots.

+1 for this. Am having the same experience after upgrading the driver 😢

**Comment by tekezo** [comment]
@nikitavoloboev  @nicoandmee 
I have not yet been able to reproduce this issue in my environment, so I are still trying to figure it out, but I have addressed the possible cause in the latest beta version (14.12.23), so please give it a try.

If the problem persists after reverting to an older version, turning off VS Code extensions (e.g., completion extensions) or reducing the connected devices may also help to isolate the problem.

**Comment by nikitavoloboev** [comment]
@tekezo 

14.12.23 did not help.

> turning off VS Code extensions

This actually helped. Ran `code-insiders --disable-extensions .`

And 

<img width="510" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/6391776/5bd2f48e-ba04-4c13-af7b-701f673d7353">

It works there! Will now try turning extensions one by one to find the cause. I have a feeling it's maybe vim extension.

**Comment by nikitavoloboev** [comment]
@tekezo yes its https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

Can you try install it and try it again with the extension. I turned off the extension and everything works. Turn it back on and it breaks.

**Comment by tekezo** [comment]
@nikitavoloboev Thanks, I'm glad you found the cause!
I also confirmed this issue was reproduced with vscodevim-1.26.0.

<img width="1024" alt="Screenshot 2023-09-18 at 20 26 39" src="https://github.com/pqrs-org/Karabiner-Elements/assets/659178/82c440c4-ef96-40df-bdf6-029ee697d61b">


It works well with vscodevim-1.23.0.

<img width="1024" alt="Screenshot 2023-09-18 at 20 27 47" src="https://github.com/pqrs-org/Karabiner-Elements/assets/659178/6eed80f1-23ac-48d6-b9ca-a99dbb413a73">
