### ISSUE TITLE
Input monitoring not showing items

### ISSUE THREAD

**Issue by antoine-boue** [pqrs-org/Karabiner-Elements#3601]
Hello, it seems input monitoring items are missing after installation of Karabiner elements:

<img width="491" alt="Screenshot 2023-09-14 at 0 21 06" src="https://github.com/pqrs-org/Karabiner-Elements/assets/57998384/0e23ce84-e1ec-4a7c-b506-549741e62f30">

I have tried reinstalling it, installing other versions, updating my macOS version, nothing worked...

macOS version: 13.5.2
Karabiner version: 14.12.0
Mac hardware: M2 Pro

**Comment by CodeJeans** [comment]
Me too

**Comment by antoine-boue** [comment]
Still happening on macOS 14.0 (Sonoma)

**Comment by aperechnev** [comment]
Same to me. Catalina 10.15.7.

**Comment by antoine-boue** [comment]
On my side, it was fixed by upgrading to latest update of Karabiners (14.13.0)

**Comment by spikespaz** [comment]
This is still relevant for me on Sequoia 15.2
