### ISSUE TITLE
Mouse Wheel / Scroll not working in Karabiner Elements and Eventviewer

### ISSUE THREAD

**Issue by areenshahbaloch** [pqrs-org/Karabiner-Elements#3610]
I want to remap the mouse wheel (scroll) to an up and down arrow in Karabiner Element, the issue I am using is that Karabiner Eventviewer is not detecting mouse scrolling and Karabiner Element is not working with the mouse wheel (button4 and button5).

Below is the snippet I am using, it works great if I change button4 to button3 but not work with button4 and button5.

{ "description": "Decreese Value", "manipulators": [ { "conditions": [ { "bundle_identifiers": [ "^com\.adobe\.LightroomClassicCC7$" ], "type": "frontmost_application_if" } ], "from": { "pointing_button": "button5" }, "to": [ { "key_code": "down_arrow" } ], "type": "basic" } ] }

I tried the below snippet to remap the mouse wheel (scrolling up or down) to arrow down and arrow up

{ "description": "Decreese Value", "manipulators": [ { "conditions": [ { "bundle_identifiers": [ "^com\.adobe\.LightroomClassicCC7$" ], "type": "frontmost_application_if" } ], "from": { "pointing_button": "button5" }, "to": [ { "key_code": "down_arrow" } ], "type": "basic" } ] }

**Comment by TylerWhittaker** [comment]
Users have been requesting the ability to react to mouse scroll wheel events for years now. There have been at least a dozen other issues filed that are running up against the same limitation -- Karabiner currently can't detect mouse scroll wheel events.   See issue #1362 which has 67 comments between 2018 and 2023, including a Swift script hack to rebind scroll wheel left/right to arrow key left/right.  

It appears that macOS does not treat scroll wheel up/down/left/right the same as other mouse buttons (which is the behavior I expected coming from a Linux background).  You can see in screenshot in the first comment of issue #1362 that scroll wheel events produce a dx/dy/dz value as opposed to a keycode.  This actually makes sense when you consider that Apple has never made a mouse with a traditional scroll wheel that produces discrete click events (their first mouse that featured scrolling had a ball that could move continuously in any direction, and more recent mice have integrated touchpad functionality for scrolling).  Touchpad scrolling support is also an inherently a continuous operation.  

The good news is that [support for scroll wheel events is in the roadmap](https://github.com/pqrs-org/Karabiner-Elements/blob/main/TASKS.md).  According to git blame, it was added in August 2023.  Given that the TODO list is only 6 items long, I'm optimistic that we'll see this implemented sometime soon.  It's a big deal for me -- it's the last part of my config I haven't been able to port over from BetterTouchTool to Karabiner.  

If the devs posted a bounty for this specific feature, I know I wouldn't be the only person who would be happy to contribute some cash.

**Comment by nejmeijer** [comment]
Closing this in favour of #1362
