### ISSUE TITLE
CLI is slow

### ISSUE THREAD

**Issue by jannis-baum** [pqrs-org/Karabiner-Elements#3627]
Hello! I am having problems using the CLI to set variables because it is very slow; anything I do with it takes more than 400ms, even just `karabiner_cli --version` or `--help`:

```plain
$ time karabiner_cli --version
14.12.0
karabiner_cli   0.00s user 0.00s system 1% cpu 0.420 total
```

For my use-case of setting variables based on events that happen on my computer, I would need to be able to adjust the variables at roughly typing speed. I have also tried manually modifying `/Library/Application\ Support/org.pqrs/tmp/karabiner_grabber_manipulator_environment.json` instead of using the CLI, which is significantly faster but unfortunately not feasible due to the file's permissions (requires `sudo`).

Is there anything else I could do/try or any hope that the CLI will be faster at some point?

Thanks!

---

**Edit:** Additional context in case it's relevant, I'm using

- CLI from `/Library/Application\ Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli`
- Karabiner Elements version 14.12.0 as seen above
- macOS 14.0
- M2 Pro chip

**Comment by tshu-w** [comment]
This may be caused by macOS design: https://sigpipe.macromates.com/2020/macos-catalina-slow-by-design/
Add Terminal to Developer Tools seems fix this:
<img width="827" alt="Screenshot 2024-05-19 at 14 47 23" src="https://github.com/pqrs-org/Karabiner-Elements/assets/13161779/abad2096-46fe-4b73-9ae9-e4c8c3c0ea91">

```console
λ time karabiner_cli --version
14.13.0
karabiner_cli --version  0.00s user 0.00s system 9% cpu 0.061 total
```

**Comment by jannis-baum** [comment]
> This may be caused by macOS design: https://sigpipe.macromates.com/2020/macos-catalina-slow-by-design/
> Add Terminal to Developer Tools seems fix this:

Woooooow🤯 Thanks so much for these pointers, I didn't know about this! Adding my terminal to the "Developer Tools" list indeed fixes the issue. It might be placebo but lots of other things suddenly also feel much snappier. I have felt so many of the issues the article mentions but never knew what causes them. Thank you again!
