### ISSUE TITLE
Can't change F5 and up for some reason. (Sonoma latest, M3 Pro Max)

### ISSUE THREAD

**Issue by nedempst** [pqrs-org/Karabiner-Elements#3648]
Hello.  I love your utility it's amazing :)

Anything I have to do to get it to bind anything above F4?  It just won't bind them doesn't recognize even if I try and change it in a few different ways.  I get nothing no key recon. 

Thank you if you can help me it might be something I am doing wrong.

**Comment by bintoro** [comment]
Have you looked at Karabiner EventViewer’s output for those keys?

**Comment by nedempst** [comment]
Thanks for this.

It might have something to do with my keychron keyboard, it seems that despite turning the settings on in the Mac to use function keys normally, only the f5/f6 key doesn’t switch and requires the function key.

Really strange.

**Comment by nedempst** [comment]
Hi is there a way to bind FN+F5/F6 back to F5/F6 standalone?  I know it’s weird but that might actually work lol unless I can figure out why in macOS my keyboard doesn’t like F5/F6 as regular function keys setting haha.

Thank you for your help!

**Comment by bintoro** [comment]
This doesn't sound like a Karabiner issue.

**Comment by nedempst** [comment]
I figured it out. Thanks.

**Comment by bintoro** [comment]
> I figured it out. Thanks.

Great! If there's nothing for this project to address here, can you please close the issue?
