### ISSUE TITLE
[Feature] Add "Restart Karabiner" to Icon in Menu Bar

### ISSUE THREAD

**Issue by davidleejy** [pqrs-org/Karabiner-Elements#3694]
Proposal is to have "Restart Karabiner" added to the list of options shown when the menu bar icon is clicked on, as depicted in this illustration:

 
![Screenshot 2024-01-12 at 12 04 50 AM](https://github.com/pqrs-org/Karabiner-Elements/assets/1690072/e1982a0d-de7d-41ec-8b6b-84d808226ba2)

The reason for this is proposal is because I've found myself needing to restart Karabiner quite frequently to recover modifications made. For reasons unclear to me, Karabiner modifications seem to disappear (and can be rectified by a Karabiner restart) after the OS awakes from sleep, connects/disconnects to external displays, etc.

Does anyone else find their Karabiner modifications frequently becoming inactive for seemingly no reason, and using a restart to re-activate them?

Thank you for reading this feature request, and would be great to hope to hear from users, contributors, & maintainers.

**Comment by tekezo** [comment]
I have never faced such an issue, but I have added a restart feature to the menu.

<img width="417" alt="Screenshot 2024-01-21 at 12 40 30" src="https://github.com/pqrs-org/Karabiner-Elements/assets/659178/e0ccdf30-c03b-4bf8-be34-ca588e1b0780">

Please try the beta release.

![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by tekezo** [comment]
If your settings are device-specific modifications or a complex modification that has a toggle feature, there is a possibility that it may be disabled by unintended device id changes or disabled unintendedly.

**Comment by davidleejy** [comment]
Thank you @tekezo for including this feature in the version 14.13.3 beta release. 

I am able to update this version and verify that the "Restart Karabiner" button is visible in the Karabiner icon's menu 😀

> If your settings are device-specific modifications or a complex modification that has a toggle feature, there is a possibility that it may be disabled by unintended device id changes or disabled unintendedly.

My modifications are device-specific but not complex. I'm not sure if device IDs are being changed unintentionally at the moment, but restarting karabiner solves the issue almost always for me.

I would be happy for this issue ticket to closed if contributors & maintainers are ready to do so 😌.

Once again, thank you for considering and implementing this feature request. Wishing you a happy new year, and hope you have a good week ahead.
