### ISSUE TITLE
Feature Request: Copying Profile/Switching Country Code According to Connected Device

### ISSUE THREAD

**Issue by KentaroxKondo** [pqrs-org/Karabiner-Elements#3734]
I use both JIS and US keyboards. Basically, I need the same modifications but a different country code. So it would be better if you could add a new feature to copy an existing profile to make almost the same but slightly different one.

Or it would be much better if Karabiner could switch country code (keyboard layout) according to which external device is connected. In this way, I don't even need to make additional profiles. 

Please consider these. Thanks!

**Comment by nejmeijer** [comment]
Have a look at #3319 for copying functionality.

Keyboard-specific profile functionality has already been requested in #3331.
