### ISSUE TITLE
Disable F14/F15 for Brightness Control

### ISSUE THREAD

**Issue by cucarachaSL1200** [pqrs-org/Karabiner-Elements#3848]
How do I disable the F14 & F15 keys for Brightness Control? By default, they are enabled. Karabiner only lists F1-F12.
<img width="694" alt="Screenshot 2024-06-16 at 4 08 36 PM" src="https://github.com/pqrs-org/Karabiner-Elements/assets/85314640/9491dd5c-5a16-4b88-9ea5-cc10deeeedba">
<img width="729" alt="Screenshot 2024-06-16 at 4 12 50 PM" src="https://github.com/pqrs-org/Karabiner-Elements/assets/85314640/74fe2d83-f7dc-43c7-a1da-5ae3897500cd">

**Comment by cucarachaSL1200** [comment]
Easy enough to solve.
![Screenshot 2024-06-17 at 3 07 20 PM](https://github.com/pqrs-org/Karabiner-Elements/assets/85314640/1103851a-4bbd-42a7-bd54-46e12f6dd3ac)

**Comment by noel-yap** [comment]
> I created a JAMF policy that pushes out the 'com.apple.symbolichotkeys.plist' with keys 53 & 54 set to false. The computer must be restarted to see the effects.

`/System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u` avoids having to restart the computer
