### ISSUE TITLE
You cannot specify multiple items into one to entry.

### ISSUE THREAD

**Issue by VanSantCode** [pqrs-org/Karabiner-Elements#3870]
Would like to trigger command+c, copying the current selection to clipboard, before feeding clipboard contents to shell command to open a specific url.

Current world this is not possible according to the [to documentation](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/#:~:text=%7D-,Note,-The%20following%20keys).

   ```
  {
        "description": "open url based on current selection",
        "manipulators":[
          {
            "type": "basic",
            "from": {
              "key_code": "f1",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [
              {
                "key_code": "c",
                "modifiers":[
                  "command"
                ],
                
                "shell_command": "open 'https://www.youtube.com/results?search_query='$(echo $(pbpaste) | tr \" \" \"+\")"
              }
            ]
          }
        ]
      }
```

**Comment by VanSantCode** [comment]
@tekezo any chance this implementation could be possible?

looking forward to hearing from you!

**Comment by raxigan** [comment]
This works for me:

```json
{
  "description": "open url based on current selection",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "f1"
      },
      "to": [
        {
          "key_code": "c",
          "modifiers": [
            "command"
          ]
        },
        {
          "shell_command": "open 'https://www.youtube.com/results?search_query='$(echo $(pbpaste) | tr \" \" \"+\")"
        }
      ]
    }
  ]
}

**Comment by VanSantCode** [comment]
> This works for me:
> 
> ```json
> {
>   "description": "open url based on current selection",
>   "manipulators": [
>     {
>       "type": "basic",
>       "from": {
>         "key_code": "f1"
>       },
>       "to": [
>         {
>           "key_code": "c",
>           "modifiers": [
>             "command"
>           ]
>         },
>         {
>           "shell_command": "open 'https://www.youtube.com/results?search_query='$(echo $(pbpaste) | tr \" \" \"+\")"
>         }
>       ]
>     }
>   ]
> }
> ```

@raxigan Can you provide additional detail as to how this works for you? I've moved back over to Windows/AutoHotKey so I have been out of the loop with any Karabiner-Elements enhancements that may have been released since I opened this issue. A screen recording could be super.
