### ISSUE TITLE
caps_lock remapping doesn't work (left_control and vk_none)

### ISSUE THREAD

**Issue by jerclarke** [pqrs-org/Karabiner-Elements#3876]
Hi all, first issue here sorry if I do anything wrong. 

I've used Karabiner for years without issues to remap `caps_lock` to `left_control`, but suddenly it doesn't work. I also tried `vk_none` and got the same result, which is that pushing caps lock lights up the led on the key, and does the normal caps lock thing of altering the case when I type.

Could totally be my setup, but I haven't changed anything. 

Karabiner-Elements version 14.13.0
MacBook Pro 16" 2021 (M1 Pro 32GB)
Sonoma 14.1.2

My setting:
<img width="964" alt="Screenshot 2024-07-21 at 2 07 18 PM" src="https://github.com/user-attachments/assets/95a51059-6308-478c-bbe6-ec9b3b482d48">

Relevant section of karabiner.json:

```json
   "simple_modifications": [
                {
                    "from": {
                        "key_code": "caps_lock"
                    },
                    "to": [
                        {
                            "key_code": "left_control"
                        }
                    ]
                }
            ],
```

**Comment by ganwell** [comment]
Same issue here.

**Comment by jerclarke** [comment]
This is working again. Sorry for the noise. Some mix of system updates and rebooting resolved the issue. 

Thanks for this amazing software! I couldn't live without it!
