### ISSUE TITLE
Solved: Switching Profiles through Complex Modification with Notification Invocation of Active Profile

### ISSUE THREAD

**Issue by AustinCDavis** [pqrs-org/Karabiner-Elements#3878]
Hi, I’m new to karabiner and am learning a lot so far. For the set up I have I am wanting to run a few different profiles that I can alternate through via a single press on one of my mouse buttons. In addition to changing profiles I was curious if it is possible to invoke a notification to tell me which profile I currently have selected. So basically use one button to cycle through a list of profiles and produce a notification or something that can tell me which profile I am currently using. 

Haven’t attempted any code on it yet was just wanting to get some thoughts and input from more experienced karabiner users. 

Edit: Figured it out. Listing my setup, code and steps here to hopefully help someone else with the similar issue.

Setup:
macOS Sonoma 14.5
Karabiner Element 14.13.0
Red Dragon Elite m913 (2.4ghz wireless usb)
Used Terminal for all coding aspects

### **_Step 1: Create a Scripts Folder and the Shell Script in Karabiner Assets Folder_**

2. Navigate to the Karabiner Assets Folder:
  - Go to the Karabiner Elements assets folder:

```typescript
cd ~/.config/karabiner/assets
``` 

3. Create a Scripts Directory:
  - Create a directory named scripts for organizing your scripts:

```typescript
mkdir -p scripts
``` 

5. Create the Shell Script:
  - Use Nano to create the script:

```typescript
nano ~/.config/karabiner/assets/scripts/profile_switcher.sh
``` 

6. Paste the Shell Script Content:
  - Copy and paste the following script content into the Nano editor:
  - NOTE: You will need to change the "profiles=("Default" "Test" "Test 2")" to whatever profile names you have saved in your karabiner elements

```typescript
#!/bin/bash

# Define profiles
profiles=("Default" "Test" "Test 2")

# Read the current profile from a file
current_profile=$(cat ~/.karabiner_profile 2>/dev/null)

# Find the index of the current profile
index=0
for i in "${!profiles[@]}"; do
  if [[ "${profiles[$i]}" == "$current_profile" ]]; then
    index=$I
    break
  fi
done

# Calculate the next profile index
next_index=$(( (index + 1) % ${#profiles[@]} ))

# Set the next profile
next_profile=${profiles[$next_index]}
echo "$next_profile" > ~/.karabiner_profile

# Change the Karabiner profile
/Library/Application\ Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli --select-profile "$next_profile"

# Display a notification
osascript -e "display notification \"$next_profile Profile Activated\" with title \"Karabiner Elements\""
``` 

7. Save the Script:
  - In Nano, save the file by pressing Ctrl + O, then press Enter. Exit by pressing Ctrl + X.

8. Make the Script Executable:
  - Run the following command to make the script executable:

```typescript
chmod +x ~/.config/karabiner/assets/scripts/profile_switcher.sh
``` 

### **_Step 2: Create Karabiner Elements Configuration File_**

1. Create the JSON Configuration File:
  - In Terminal create and edit a new JSON file for the complex modification.
       
```typescript
nano ~/.config/karabiner/assets/complex_modifications/profile_switcher.json
``` 

2. Paste the JSON Content:
  - NOTE 1: I am using the 1 button on my mouse keypad if you are simply wanting to use a keyboard button and only use one keyboard you should remove the modifiers and conditions statement
  - NOTE 2: If you are using a mouse with a keypad or programmable buttons you will need to retrieve your own identifiers set up i.e. vendor_id and product_id from karabiner elements devices pain
  - NOTE 3: My mouse displays as a separate keyboard and mouse with the same vendor and product id so to remove a delay I added the is_keyboard statement to immediately identify the correct device. So, if your device identifies as one you can remove the is_keyboard statement 

```typescript
{
  "title": "Profile Switcher",
  "rules": [
    {
      "description": "Cycle through profiles with Mouse Keypad #1",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "1",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "~/.config/karabiner/assets/scripts/profile_switcher.sh"
            }
          ],
          "conditions": [ 
            {
              "type": "device_if",
              "identifiers": [
                {
                  "vendor_id": 9639,
                  "product_id": 64007,
                  "is_keyboard": true 
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
``` 

3. Save the JSON File:
  -  Save the file by pressing Ctrl + O, then press Enter. Exit by pressing Ctrl + X.

### **_Step 3: Load the Karabiner Elements Configuration_**

1. Open Karabiner Elements:
  - Go to the “Complex Modifications” tab.
  - Click on “Add Rule”.
  - You should see the “Profile Switcher” rule available. Enable it.

**Comment by nejmeijer** [comment]
Since this issue is marked as "solved" in the title, is there any reason it is still open?

**Comment by AustinCDavis** [comment]
> Since this issue is marked as "solved" in the title, is there any reason it is still open?

Apologies! I meant to close it yesterday when I updated the title. Thanks for catching that!

**Comment by CannoNadav** [comment]
@AustinCDavis I slightly polished up your script, if anyone wants they can use it. I'm using zsh but so adapt to your shell if you need.

#!/bin/zsh

if ! $(which karabiner_cli &> /dev/null);then 
  osascript -e 'display notification "'"$0: Can't find karabiner_cli. Add it to your path variable."'" with title "Karabiner Elements Profile Switcher"' 
  exit 1
fi

profiles=()
# get profile names via karabiner_cli
while IFS= read -r line; do
  profiles+=("$line")
done < <(karabiner_cli --list-profile-names)


# Get the current profile using karabiner_cli
response="$(karabiner_cli --show-current-profile-name 2>&1)"
retcode=$?
if [[ "$retcode" != 0 ]]; then
  osascript -e 'display notification "'"$0: Error running karabiner_cli: '$response'. retcode: $retcode."'" with title "Karabiner Elements Profile Switcher"'  
  exit "$retcode"
fi

current_profile="$response"

# Check if the current profile is recognized in the list
profile_index="$(($profiles[(Ie)$current_profile]))"


if [[ "$profile_index" = 0 ]]; then
  osascript -e 'display notification "'"$0: Current profile: $current_profile not found in profiles list."'" with title "Karabiner Elements Profile Switcher"'
  exit 2
fi


# Calculate the next profile index
next_index=$(( (profile_index % ${#profiles}) + 1 ))

# Set the next profile
next_profile="${profiles[$next_index]}"

# Change the Karabiner profile
karabiner_cli --select-profile "$next_profile"

# Display a notification
osascript -e 'display notification "'"Profile: $(karabiner_cli --show-current-profile-name 2>/dev/null) is now active."'" with title "Karabiner Elements Profile Switcher"'

**Comment by AustinCDavis** [comment]
@CannoNadav Much appreciated! I’m very new to karabiner elements and coding so any help is always appreciated!

**Comment by CannoNadav** [comment]
I made a few more additions. I have a profile called Karabiner-Elements-Activated, one called Karabiner-Elements-Deactivated and a few more. I'm putting the Karabiner-Elements-Deactivated first in the list so that if I'm on it the next one will be Karabiner-Elements-Activated and will trigger the "Starting Karabiner-Elements" notification(and action) if it isn't already started. also worth mentioning I'm not using karabiner for the shortcut to this script.. otherwise how would the script run when karabiner isn't started. I'm using keyboard maestro for that, but you can create a keyboard shortcut through the mac settings too.

```
#!/bin/zsh

get_karabiner_profile(){
# Get the current profile using karabiner_cli
  local retcode response
  response="$(karabiner_cli --show-current-profile-name 2>&1)"
  retcode=$?
  if [ "$retcode" != 0 ]; then
    osascript -e 'display notification "'"$0: Error running karabiner_cli: '$response'. retcode: $retcode."'" with title "Karabiner Elements Profile Switcher"'  
    exit "$retcode"
  fi

  echo "$response"
}


if ! $(which karabiner_cli &> /dev/null);then 
  osascript -e 'display notification "'"$0: Can't find karabiner_cli. Add it to your path variable."'" with title "Karabiner Elements Profile Switcher"' 
  exit 1
fi

profiles=()
# get profile names via karabiner_cli
while IFS= read -r line; do
  profiles+=("$line")
done < <(karabiner_cli --list-profile-names)


current_profile="$(get_karabiner_profile)"

# Check if the current profile is recognized in the list
profile_index="$(($profiles[(Ie)$current_profile]))"


if [[ "$profile_index" = 0 ]]; then
  osascript -e 'display notification "'"$0: Current profile: $current_profile not found in profiles list."'" with title "Karabiner Elements Profile Switcher"'
  exit 2
fi


# Calculate the next profile index
next_index=$(( (profile_index % ${#profiles}) + 1 ))
#echo "next index: $next_index"

# Set the next profile
next_profile="${profiles[$next_index]}"

# Change the Karabiner profile
karabiner_cli --select-profile "$next_profile"



#make sure karabiner-elements is running in the background
if ! $(ps aux | grep Karabiner-Elements | grep -qEv "karabiner_observer|karabiner_session_monitor|karabiner_grabber|grep"); then
  osascript -e 'display notification "'"Starting Karabiner-Elements.."'" with title "Karabiner Elements Profile Switcher"'
  open -a Karabiner-Elements
  retcode=$?
  if [ "$retcode" -ne 0 ]; then
    osascript -e 'display notification "Karabiner-Elements failed to start. \"open -a Karabiner-Elements\" failed with exit code '"$retcode"'." with title "Karabiner Elements Profile Switcher"'
  fi
fi

# Display a notification
current_profile="$(get_karabiner_profile)"

if [ "$current_profile" = Karabiner-Elements-Activated ]; then
  osascript -e 'display notification "'"Karabiner-Elements is now Activated."'" with title "Karabiner Elements Profile Switcher"'
elif [ "$current_profile" = Karabiner-Elements-Deactivated ]; then
  osascript -e 'display notification "'"Karabiner-Elements is now Deactivated."'" with title "Karabiner Elements Profile Switcher"'
else
  osascript -e 'display notification "'"Karabiner-Elements profile: $(karabiner_cli --show-current-profile-name 2>/dev/null) is now active."'" with title "Karabiner Elements Profile Switcher"'
fi
```

**Comment by AustinCDavis** [comment]
@CannoNadav Love this feature addition! I am actually just starting with keyboard maestro myself. Any chance you know how to use keyboard maestro or Karabiner elements to control UI components (checkboxes, menus, etc) in a java-based application? I've been attempted to use AppleScript in conjunction with hammerspoon/karabiner elements and keyboard maestro, but the app I want to utilize functions out of a java-arm on my Mac and the hierarchy of the UI elements isn't readily accessible via accessibility inspector or UI browser.

**Comment by CannoNadav** [comment]
sorry I haven't played with gui automation. If you can use the command line or builtin features in the app/keyboard maestro instead I recommend it. Taking a quick look at keyboard maestro I see there's an action called 'click a button when enabled' and 'click at found image', but never used them.

**Comment by AustinCDavis** [comment]
No worries! Unfortunately, this app doesn’t have a native support for command line interfacing. I tried using AppleScript and some JavaScript but no success. Primarily believe it’s due to the hierarchy not following the AppleScript window structure. I’m sure if I had a better understanding of the languages and the app folder structure I could figure it out but for the time being it’s not a necessity fortunately. I also greatly appreciate your input on the initial file and suggestions on my other problem!

**Comment by MasterHegel** [comment]
I can’t code. Could someone explain how I would need to modify the script if I wanted the profile switching to be linked to hot-keys on my keyboard?
