### ISSUE TITLE
snapping windows feature from Sequoia not working

### ISSUE THREAD

**Issue by swifty99** [pqrs-org/Karabiner-Elements#3879]
Sequoia has a nice new feature to rearrange windows by these keys:
fn+ctrl + left/right.
This would snap the window to the left or right of the screen. 

If karabiner is running with this feature is off.
I tried:
- empty profile
- beta of Karabiner 14.99.10

Only solution so far:
- quit Karabiner completely 

setup:
- M1 air 
- external display 4k
- logitech mx keys

**Comment by juandpinto** [comment]
+1 

I used the event viewer to realize that globe+right with Karabiner running (even on an empty profile) acts as "end", whereas without Karabiner running it acts as "right_arrow". I think this is what's causing the issue, but I don't see how to deactivate this while having Karabiner running.

**Comment by GreyAsteroid** [comment]
This is caused by the fn-arrow implicit behaviors (https://karabiner-elements.pqrs.org/docs/manual/misc/implicit-behavior/). I created an issue asking for the behavior to be removed or an option to disable it. (https://github.com/pqrs-org/Karabiner-Elements/issues/3886)

**Comment by tekezo** [comment]
Progress:
In the beta version (15.0.4), I modified it so that fn+arrows do not get converted when other modifiers are pressed.
However, even with this change, snapping using fn+control+arrows still is not working.

It seems that macOS behaves differently when fn is sent from an Apple device versus when it's sent from the virtual keyboard of Karabiner-Elements, likely only during snapping. I am currently investigating how to work around this issue.

**Comment by tekezo** [comment]
I have confirmed that changing the Vendor ID and Product ID of the virtual keyboard to those of the Magic Keyboard makes it work correctly. I plan to update the virtual device in that direction.

**Comment by Josefer25** [comment]
> I have confirmed that changing the Vendor ID and Product ID of the virtual keyboard to those of the Magic Keyboard makes it work correctly. I plan to update the virtual device in that direction.

Could you explain a bit more how to do that?

**Comment by swifty99** [comment]
Apple usually allows some features for their own hardware only. By simulating Apple hardware these features become available.

I tested beta 15.0.4. Disabled the new Flag "change fn+..." in Virtual keyboards. Still the Fn+Ctrl Snapping stops working while Karabiner is running. What am I missing?

Cheers

**Comment by imyelmo** [comment]
> Apple usually allows some features for their own hardware only. By simulating Apple hardware these features become available.
> 
> I tested beta 15.0.4. Disabled the new Flag "change fn+..." in Virtual keyboards. Still the Fn+Ctrl Snapping stops working while Karabiner is running. What am I missing?
> 
> Cheers

I would say that still work in progress: 

https://github.com/pqrs-org/Karabiner-Elements/compare/main...improve-globe-key-supports

**Comment by b3ku** [comment]
> Apple usually allows some features for their own hardware only. By simulating Apple hardware these features become available.
> 
> I tested beta 15.0.4. Disabled the new Flag "change fn+..." in Virtual keyboards. Still the Fn+Ctrl Snapping stops working while Karabiner is running. What am I missing?
> 
> Cheers

You should **enable** it (That's the default). The old behaviour (implicit remapping of fn+arrows) _now_ occurs only when no other modifier is pressed. Since the window snapping feature is working with fn _and_ control pressed, everything ist working like a charm.

**Comment by tekezo** [comment]
The latest beta release (v15.0.14) has resolved the issue.

How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

## Note

You have to restart macOS after upgrade, and then select the keyboard type.

<img src="https://karabiner-elements.pqrs.org/docs/releasenotes/images/v15.1.0/macos-restart-required@2x.png" alt="macOS restart required" />
<img src="https://karabiner-elements.pqrs.org/docs/releasenotes/images/v15.1.0/keyboard-type-selector@2x.png?v=2" alt="keyboard type selector" />

**Comment by swifty99** [comment]
Nice! Thank you!

now the next wish arises, maybe related: Use an external keyboard to use this feature:

I tried this, no expert here, it does not work:
```
{
  "title": "Remap left_arrow with left_option and left_control to left_arrow with left_option and fn",
  "rules": [
    {
      "description": "Map left_arrow + left_option + left_control to left_arrow + left_option + fn",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_arrow",
            "modifiers": {
              "mandatory": [
                "left_control",
                "left_option"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": [
                "left_option",
                {
                  "apple_vendor_top_case_key_code": "keyboard_fn"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

```

Would someone please have a look?

**Comment by tekezo** [comment]
@swifty99 

If you want to change control+option+left arrow, use this json.

```json
{
    "description": "Map left_arrow + left_option + left_control to left_arrow + left_option + fn",
    "manipulators": [
        {
            "from": {
                "key_code": "left_arrow",
                "modifiers": { "mandatory": ["left_control", "left_option"] }
            },
            "to": [
                {
                    "key_code": "left_arrow",
                    "modifiers": ["left_option", "fn"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

Otherwise, if you want to change option+fn+left arrow, use this JSON.

```json
{
    "description": "Map left_arrow + left_option + left_control to left_arrow + left_option + fn",
    "manipulators": [
        {
            "from": {
                "key_code": "left_arrow",
                "modifiers": { "mandatory": ["fn", "left_option"] }
            },
            "to": [
                {
                    "key_code": "left_arrow",
                    "modifiers": ["left_control", "left_option"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by g4rb4g3** [comment]
Just upgraded to 15.2.0 and remapping to fn+control+left_arrow and fn+control+right_arrow works just fine. Thank you very much!
As a previous window user I'm still using command (windows key actually 😉 ) + left/right arrow to move windows to either side of the screen. This works fine for me now:

```
{
    "description": "Control + cursor for window tiling",
    "manipulators": [
        {
            "from": {
                "key_code": "left_arrow",
                "modifiers": { "mandatory": ["left_command"] }
            },
            "to": [
                {
                    "key_code": "left_arrow",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "right_arrow",
                "modifiers": { "mandatory": ["left_command"] }
            },
            "to": [
                {
                    "key_code": "right_arrow",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by swifty99** [comment]
Thank you all!

Works great.

**Comment by stevenguh** [comment]
Just sharing, this remaps the most native window tiling shortcuts from `fn + control` to `control + command` in case your keyboard doesn't have a `fn` key.

```json
{
    "description": "Map window tiling to control + option",
    "manipulators": [
        {
            "from": {
                "key_code": "left_arrow",
                "modifiers": { "mandatory": ["left_control", "left_option"] }
            },
            "to": [
                {
                    "key_code": "left_arrow",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "right_arrow",
                "modifiers": { "mandatory": ["left_control", "left_option"] }
            },
            "to": [
                {
                    "key_code": "right_arrow",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "up_arrow",
                "modifiers": { "mandatory": ["left_control", "left_option"] }
            },
            "to": [
                {
                    "key_code": "up_arrow",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "down_arrow",
                "modifiers": { "mandatory": ["left_control", "left_option"] }
            },
            "to": [
                {
                    "key_code": "down_arrow",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "r",
                "modifiers": { "mandatory": ["left_control", "left_option"] }
            },
            "to": [
                {
                    "key_code": "r",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "f",
                "modifiers": { "mandatory": ["left_control", "left_option"] }
            },
            "to": [
                {
                    "key_code": "f",
                    "modifiers": ["fn", "left_control"]
                }
            ],
            "type": "basic"
        }
    ]
}
```
