### ISSUE TITLE
Remove fn-arrow implicit behavior

### ISSUE THREAD

**Issue by GreyAsteroid** [pqrs-org/Karabiner-Elements#3886]
macOS Sequoia includes ctrl+fn+arrow shortcuts by default for arranging windows. I've attempted to map some keys on my numpad to activate these but because of Karabiner's implicit behavior for fn-arrow keys the mappings are hijacked.

Therefore I'd like this behavior to be removed or hidden behind an option.

**Comment by JakeCarter** [comment]
Agreed. It would be really great if there was some way to disable the implicit mappings.

**Comment by chaitb** [comment]
This is addressed in https://github.com/pqrs-org/Karabiner-Elements/issues/3879#issuecomment-2308550026, might take some more time to land in an update

**Comment by GreyAsteroid** [comment]
> This is addressed in [#3879 (comment)](https://github.com/pqrs-org/Karabiner-Elements/issues/3879#issuecomment-2308550026), might take some more time to land in an update

This update is in beta now and it does seem to disable the implicit behavior though only when other modifiers are pressed. This works for me since that was why I wanted the implicit behavior removed in the first place so I'll go ahead and close this issue even though the update doesn't explicitly allow disabling the implicit behavior.
