### ISSUE TITLE
How to can I change my dollar sign to a pound?

### ISSUE THREAD

**Issue by echapman02** [pqrs-org/Karabiner-Elements#3888]
I would like to code a complex modification to change the dollar sign (shift+4) to a British pound sign.
In the keys list, Karabiner has a 'non_us_pound' key. I am not sure if there is another key combo I can use to get a pound sign.

I have got a refurbed US laptop and am new to karabiner and coding, so any help is appreciated, thank you!

**Comment by toonarmy14** [comment]
See complex modification below. It changes <SHIFT>+4 to <OPT>+3, which is a macOS default (for my {US} location at least). This should work for you.  
```
    {
      "description": "Change $ (US Dollar) to £ (British Pound)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "4",
            "modifiers": {
              "mandatory": ["shift"],
              "optional": ["caps_lock"]
            }
          },
          "to": [
            {
              "key_code": "3",
              "modifiers": ["option"]
            }
          ]
        }
      ]
    }
```
