### ISSUE TITLE
macOS Sequoia: Karabiner 15 prevents Sequoia’s new Move & Resize keyboard shortcuts from working

### ISSUE THREAD

**Issue by hide-tanaka** [pqrs-org/Karabiner-Elements#3896]
macOS version: 15.0
Karabiner version: 15.0.0
Your Mac hardware: MacBook Pro M3
Your keyboard hardware: Apple Internal Keyboard

The new Move & Resize keyboard shortcuts introduced in Sequoia, such as control-globe-left arrow, don’t work when Karabiner Elements is enabled. I confirmed that they work if Karabiner is disabled.

**Comment by tekezo** [comment]
Duplicated https://github.com/pqrs-org/Karabiner-Elements/issues/3879
