### ISSUE TITLE
Using brackets + arrow to go back or forward through history Safari doesn't work, but works on other browsers

### ISSUE THREAD

**Issue by casualNavigator** [pqrs-org/Karabiner-Elements#3897]
Using brackets + arrow to go back or forward through history in Safari doesn't work, but works on other browsers, such as chrome, firefox, etc.. Webkit based browsers, such as Orion also works, just Safari that doesn't.

here's the complex modification:

For going back:
```json
{
    "description": "Back Mouse Button to cmd+[",
    "manipulators": [
        {
            "from": {
                "pointing_button": "button4"
            },
            "to": [
                {
                    "key_code": "[",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
```

For going forward:

```json
{
    "description": "Forward Mouse Button to cmd+]",
    "manipulators": [
        {
            "from": {
                "pointing_button": "button5"
            },
            "to": [
                {
                    "key_code": "close_bracket",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
```

Can anyone point to the problem causing this?

**Comment by tekezo** [comment]
Please check if you can normally navigate through your history in Safari using the command+[ shortcut key. If it doesn’t work, then the problem lies with Safari.

If the shortcut works fine, there might already be a rule in Karabiner-Elements that changes button4 or button5 to another key specifically when using Safari. Try disabling other rules to confirm.

**Comment by casualNavigator** [comment]
First of all thank you for creating this great software, 

I can use the command+[ and command+] to navigate through Safari's history using an external or the built-in keyboard.  Only the mouse's forward and backward buttons with the complex modifications above isn't working in Safari.

Maybe this is relevant? There is an interesting read about the navigating history in Safari here and how the author solved it here:
https://sensible-side-buttons.archagon.net (in the Technical Notes section)

His github: https://github.com/archagon/sensible-side-buttons

Maybe Karabiner Elements can do this in its current version?

**Comment by raxigan** [comment]
@casualNavigator the rules you have provided work for me in Safari, just make sure you use "open_bracket" and "close_bracket" instead of "[" and "]" and have "Modify events" option enabled for you mouse in KE settings. Tested on Sonoma 14.6.1

**Comment by casualNavigator** [comment]
@raxigan Thanks for the suggestion, 

Turns out I didn't enable modify events for the external mouse 😆.

I overlooked this as other browsers worked without enabling it.
