### ISSUE TITLE
I can't use my caps keys when I exit Karabiner Elements

### ISSUE THREAD

**Issue by pzxy** [pqrs-org/Karabiner-Elements#3905]
macOS version：Apple M1 Pro ，Sonoma 14.5 (23F79)

I don't know what I set up。Now I have to run Karabiner Elements if I want to use my caps lock key
If I exit Karabiner-Elements, or uninstall Karabiner-Elements, my caps lock key won't work

help me please

**Comment by pzxy** [comment]
Now I just want to get my old keys back, I don't want to use Karabiner Elements anymore, I'm too hard, guys

**Comment by tekezo** [comment]
Check macOS configuration: https://support.apple.com/en-ca/guide/mac-help/mchlp1011/mac
