### ISSUE TITLE
Caps Lock to Escape mapping is not working

### ISSUE THREAD

**Issue by Skadabucci** [pqrs-org/Karabiner-Elements#3934]
Hello I am trying to swap the functionality of my caps lock and escape keys. I cannot get the `Simple Modifications` to work on my laptop. Any help or tips would be greatly appreciated!

### Information

- macOS version: 14.6.1
- Karabiner version: 15.0.0
- Keyboard Maestro is installed but disabled for debugging. I have no other input capturing software that I am aware of.
- I do not have any System Preferences > Keyboard > Shortcut changes to either of these keys

#### Simple Modifications Configuration
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/7b1c658a-f23b-41ae-8898-b4c98e5f0e90">
(note that I have replicated the same configuration to the Apple Internal Keyboard/Trackpad (Apple))

#### Devices Configuration
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/e32e8471-2a61-41b7-80c3-d53379e9b587">

#### Karabiner Event Viewer 
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/97be1fd1-086f-47c6-a087-04092095992e">

### What I've tried
1. Restarted my computer
2. Unplugged all other keyboards/devices
3. Ensured that all the permissions are correct (karabiner_grabber and karabiner event viewer are enabled in the input monitor)

Any help would be greatly appreciated. Thank you!

**Comment by oneElectron** [comment]
I had this problem, too.
I am going to guess that you had caps lock mapped to escape before in the system settings.
I don't know for sure, but I think that Karabiner looks at your keyboard at install time and saves it somewhere, presumably it mistakenly mapped caps lock to escape internally at install time. I also had the issue that when Karabiner was open the caps lock key was mapped to escape even when i hadn't set anything keymaps in Karabiner.

# Fix
1. Uninstall Karabiner.
2. remove the driver from system settings (on sequoia this is general -> login items & extensions -> Driver Extensions).
3. make sure that caps lock is mapped to caps lock in system settings.
4. restart your computer
5. reinstall Karabiner

**Comment by Skadabucci** [comment]
Thanks for the reply oneElectron. I ended up having a completely different issue where karabiner_grabber needed permission to the file system on macOS Sonoma. 

I did have my capslock key bound to escape before installing so I do like to think that without your help I would still have been stuck. 

I hope this helps others in the future 🥂
