### ISSUE TITLE
stopped working after latest update 15.1.0

### ISSUE THREAD

**Issue by ctf0** [pqrs-org/Karabiner-Elements#3948]
no matter what i do i keep getting those images 

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/779f69eb-905c-48ea-bcdd-1a3a3622146a">
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/0b17288b-5258-4ec5-b21c-22131cb6ef25">

macbook pro m1, v14.7.

**Comment by thecasualpenguin** [comment]
Same issue here, M2 Max, Ventura 13.6.1.
Deactivating and restarting multiple times did not solve the issue.

**Comment by MX48Live** [comment]
Same here, try to remove Driver couple times, seem not work.

**Comment by miqm** [comment]
same here, reverted to 14.x

**Comment by miqm** [comment]
For me mappings work only within few seconds after service restart, then stops. M1 Pro, Sonoma 14.7. Reverted to 14.x

**Comment by oddko** [comment]
Completely non functional as well for that new version on an MBP 14 M1 Pro laptop. Key events to appear in karabiner event viewer, but bindings don't work at all.

Reverting to 15.0.0 works.

**Comment by rickgladwin** [comment]
Same issue on an M1 Pro running macOS Sonoma 14.7

**Comment by ThxAndBye** [comment]
Same issue for me on a M2 Air. Even a complete reinstall and multiple restarts did not solve the issue.

**Comment by martin-braun** [comment]
Same issue on the 2019's Pro model (Intel).

**Comment by ctf0** [comment]
solved on v1.5.2

**Comment by madAndroid** [comment]
I'm still experiencing the same problem on `15.2.0`

**Comment by simonthehero** [comment]
Had the same situation after updating to 15.2.0. The following (wonky) approach worked for me:

1. Downgrade to 15.1.0
2. Now I get the new dialogue "You need to allow Karabiner in System/ Privacy & Security" - And I can allow it there
3. Afterwards, upgrade to 15.2.0 again
4. Now everything works as it should -- Looks like Karabiner 15.2.0 somehow stops trying too early and that second dialogue never comes up..?
