### ISSUE TITLE
remappings (complex modifications) do not work in password fields on macOS 15.0

### ISSUE THREAD

**Issue by breuerfelix** [pqrs-org/Karabiner-Elements#3958]
As described in the title my complex modifications do not work in password fields since macOS 15.0.

The grabber runs with root priviledges.

How to test:
Open a browser and go to any password input field.
Try to execute a complex modification -> does not work.
Change the input field to type="text". Try to execute a complex modification -> does work.

I am running version 15.1.0

**Comment by rikhuijzer** [comment]
Did you verify that your "Modifier Keys" in the settings are correct? For me Karabiner reset them this morning which took me a few hours to figure out.

**Comment by tekezo** [comment]
My complex modifications work without any issues even in password fields on my machine.
Could you provide some examples of the complex modifications that are being affected?

**Comment by breuerfelix** [comment]
Okay i figured out that karabiner mapped everything correctly. it is raycast that is just not able to listen on that keybinding while i am in a password field ... i searched and debugged the wrong location. 
thanks!
