### ISSUE TITLE
Capslock function not working anymore with 15.2

### ISSUE THREAD

**Issue by Skelbti** [pqrs-org/Karabiner-Elements#3972]
Here is my complex modification for using `CapsLock` as a launcher for app when pressed with `a` and act normal when it is tap. Everything works fine until today when I updated to 15.2. It's really annoying.

[CapslockConfig.json](https://github.com/user-attachments/files/17382034/CapslockConfig.json)

It seems that macOS can't understand `"caps_lock"` anymore when it's trigger by `"to_if_alone": [{ "key_code": "caps_lock" }],`

EDIT :
Thanks to @berndlosert to redirect to [this solution](https://github.com/pqrs-org/Karabiner-Elements/issues/3949#issuecomment-2415228881). Everything works againç!

**Comment by berndlosert** [comment]
One of my caps_lock modifications also stopped working after upgrading to 15.2.

**Comment by berndlosert** [comment]
Oh, I just found this issue: https://github.com/pqrs-org/Karabiner-Elements/issues/3949. Adding `"hold_down_milliseconds": 100` fixes it.
