### ISSUE TITLE
Apple adjustable keyboard m1242 - volume up/down/mute/record not working/detected

### ISSUE THREAD

**Issue by dynamike2010** [pqrs-org/Karabiner-Elements#3977]
Just wanted to ask if these keys on that particular keyboard are "supported"?
Or maybe issue is that I am connecting this keyboard to MacBook Air m2 via iMate USB to ADB adapter?
Anyways, when running EventViewer pressing those keys is not detected at all while esc/power button works fine...

https://en.wikipedia.org/wiki/Apple_Adjustable_Keyboard
https://deskthority.net/wiki/Griffin_iMate

**Comment by dynamike2010** [comment]
OK, for those who may have same question the answer is: griffin mate doesn't support media buttons - don't have any link that states this exactly but some reddit search via google showed that kind of message in serach results.
So, iMate sucks - karabiner GOOD ;-)

**Comment by nicmalone** [comment]
Does this mean you found a way to remove the media keys using Karabiner? I can't see them with my m1242 in that app but perhaps it's a limitation of the TinkerBoy USB adapter I'm using.

**Comment by dynamike2010** [comment]
All works fine with Drakware adb2usb.
