### ISSUE TITLE
[BUG] Strange space key triggered after mapping modified keys

### ISSUE THREAD

**Issue by Autumn-one** [pqrs-org/Karabiner-Elements#3986]
-  I set up the mapping of several decoration buttons, as shown below
![image](https://github.com/user-attachments/assets/f8e003eb-f8a3-401a-b653-e3eaede07bbe)
- After the settings are completed, I press the command(actually fn after mapping) + shift button, and then lift one button first and then the other button in order. Many strange buttons will be triggered. The triggered buttons are as follows:
![image](https://github.com/user-attachments/assets/eac67b87-1eab-4f4e-95ae-e403a4756c63)
Why are there a few extra buttons to operate? After I turn off the karabiner-element and test it, there will be no problem. as shown below
![image](https://github.com/user-attachments/assets/ea434b29-ad4b-4712-b17e-610f24b35925)

The system I currently use is：macos 15.0.1
karabiner-elements for the latest version

**Comment by tekezo** [comment]
I guess there are some settings in Complex Modifications. Please check it.

**Comment by Autumn-one** [comment]
This issue was my own mistake. I added a complex configuration that mapped the shift key to control+space, which caused this problem. I resolved it by modifying the configuration.

![image](https://github.com/user-attachments/assets/3141bba9-87ec-4966-813d-1609eb337ca0)
![image](https://github.com/user-attachments/assets/55f9d46f-0527-436a-893c-6dabc352d278)
