### ISSUE TITLE
Cmd + Option Switched on ANSI Keyboard Type

### ISSUE THREAD

**Issue by M1kep** [pqrs-org/Karabiner-Elements#3988]
Since 15.1 Cmd and Option keys are swapped(I have to press Opt + A to select all), unless I switch to ISO, but then other keys are incorrect. The key presses show properly in the event viewer.

The following mappings "solves" the issue:
![CleanShot 2024-10-29 at 16 51 43](https://github.com/user-attachments/assets/7b20e967-a8d3-42e6-9a65-fb0475987b2b)

Physical Device(Apple Magic Keyboard)
```
        "device_identifiers": {
            "is_keyboard": true,
            "product_id": 671,
            "vendor_id": 76
        },
```

**Comment by krykra7** [comment]
I have the same issue, strangely sometimes it does work correctly as if not swapped.

**Comment by tekezo** [comment]
Please check macOS system settings.
https://karabiner-elements.pqrs.org/docs/help/troubleshooting/breaking-changes/#modifiers

**Comment by kruzyk** [comment]
I have the same problem. And I have macOS settings as in the link.

I have this and nothing works:
![Screenshot 2024-11-13 at 03 31 23](https://github.com/user-attachments/assets/2d87dd0a-b08d-4bcc-a63e-9e8733eaea07)

![image](https://github.com/user-attachments/assets/be7ea013-920a-49e2-898f-fdaa5cb19295)
![image](https://github.com/user-attachments/assets/c477031e-c450-4d83-a759-8c4143294d85)
![image](https://github.com/user-attachments/assets/91a869fc-74de-4e25-8965-a2ade9e0113e)

**Comment by kruzyk** [comment]
I restored my backup karabiner config and this works:
`{
    "profiles": [
        {
            "devices": [
                {
                    "identifiers": {
                        "is_keyboard": true,
                        "product_id": 591,
                        "vendor_id": 1452
                    },
                    "simple_modifications": [
                        {
                            "from": { "key_code": "right_command" },
                            "to": [{ "key_code": "right_option" }]
                        }
                    ]
                }
            ],
            "name": "Default profile",
            "selected": true,
            "virtual_hid_keyboard": {
                "country_code": 0,
                "keyboard_type_v2": "ansi"
            }
        }
    ]
}`
