### ISSUE TITLE
[bug] command + escape to command + f8 not working as expected

### ISSUE THREAD

**Issue by eret9616** [pqrs-org/Karabiner-Elements#3994]
macos: 15.1 (24B83)
google-chrome: Version 131.0.6778.24 (Official Build) beta (arm64)
ms-edge: Version 130.0.2849.56 (Official build) (arm64) (stable)
karabiner elements: 15.3.0

There is a shortcut in google-chrome/ms-edge devtools to "deactive breakpoints":
![image](https://github.com/user-attachments/assets/ab61fa25-c8f2-49ad-afd3-f924ac613d46)
![image](https://github.com/user-attachments/assets/8de2ab01-a89d-4f37-a1f5-d7dd459ecf22)

I used to set command + escape  => command + f8 in google chrome  (command + f8),
```
                            {
                                "from": {
                                    "key_code": "escape",
                                    "modifiers": { "mandatory": ["left_command"] }
                                },
                                "to": [
                                    {
                                        "key_code": "f8",
                                        "modifiers": ["left_command"]
                                    }
                                ],
                                "type": "basic"
                            },
```

I recently found its not working, in eventviewer i can see the cmd+f8  events is dispached, but there is no response in chomr/edge:
<img width="303" alt="image" src="https://github.com/user-attachments/assets/4d255ef9-1c27-4a54-91c3-1f1e59f42037">

but other mapping like command + f1 => command + \ worked well,

I tried use keyboard maestro to map the shortcut binding , its worked, i think there may be some bug in karabiner elements?

![image](https://github.com/user-attachments/assets/5cb83b3a-985f-45b3-a76e-6ba4e1f4b47b)

**Comment by tekezo** [comment]
You have to send command+fn+f8.
https://karabiner-elements.pqrs.org/docs/help/how-to/function-keys/

**Comment by eret9616** [comment]
> You have to send command+fn+f8. https://karabiner-elements.pqrs.org/docs/help/how-to/function-keys/

it's working, and there are  some breaks to my old scripts
