### ISSUE TITLE
How to toggle off multiple sticky keys in to_if_alone?

### ISSUE THREAD

**Issue by singlexyz** [pqrs-org/Karabiner-Elements#3995]
What I expect is for the key to act as Shift when held down, and as a toggle for four modifier keys when tapped. However, after toggling on, tapping it again does not toggle it off.

```json
{
  "from": {
    "key_code": "right_shift"
  },
  "to": {
    "key_code": "right_shift"
  },
  "to_if_alone": [
    { "sticky_modifier": { "left_option": "toggle" } },
    { "sticky_modifier": { "left_command": "toggle" } },
    { "sticky_modifier": { "left_control": "toggle" } },
    { "sticky_modifier": { "left_shift": "toggle" } }
  ],
  "type": "basic"
}
```

**Comment by tekezo** [comment]
You have to add `"modifiers": { "optional": ["any"] }` for this purpose.

```json
{
    "description": "example",
    "manipulators": [
        {
            "from": {
                "key_code": "right_shift",
                "modifiers": { "optional": ["any"] }
            },
            "to": { "key_code": "right_shift" },
            "to_if_alone": [
                { "sticky_modifier": { "left_option": "toggle" } },
                { "sticky_modifier": { "left_command": "toggle" } },
                { "sticky_modifier": { "left_control": "toggle" } },
                { "sticky_modifier": { "left_shift": "toggle" } }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by singlexyz** [comment]
> You have to add `"modifiers": { "optional": ["any"] }` for this purpose.
> 
> ```json
> {
>     "description": "example",
>     "manipulators": [
>         {
>             "from": {
>                 "key_code": "right_shift",
>                 "modifiers": { "optional": ["any"] }
>             },
>             "to": { "key_code": "right_shift" },
>             "to_if_alone": [
>                 { "sticky_modifier": { "left_option": "toggle" } },
>                 { "sticky_modifier": { "left_command": "toggle" } },
>                 { "sticky_modifier": { "left_control": "toggle" } },
>                 { "sticky_modifier": { "left_shift": "toggle" } }
>             ],
>             "type": "basic"
>         }
>     ]
> }
> ```

👍🏼 Nice, it works.
