### ISSUE TITLE
Enable complex modifications file/group to be disabled based on conditions

### ISSUE THREAD

**Issue by gdanov** [pqrs-org/Karabiner-Elements#4023]
I use custom dvorak complex modification file that works great, but when using UniversalControl (mac's mouse & keyboard control my iPad), the keyboard input is a mess — does not match neither the dvorak mapping, nor the physical keyboard.

The way I understand documentation, I have to add the same app exclusion rule to each and every modification in the "manipulators" array and this is overkill and ugly.

**Comment by tekezo** [comment]
Wouldn’t it work to use profiles?
https://karabiner-elements.pqrs.org/docs/manual/operation/profiles/

**Comment by gdanov** [comment]
I don't see how. Can I enable/disable profile based on the current frontmost application in which I'm typing?
Effectively I need to disable **all** mappings when my focus is on specific app.

**Comment by tekezo** [comment]
Yeah, if you want to change behavior based on the frontmost application, profiles are not suitable.
For now, the only way is to insert frontmost_application_if into all the rules. 

here have been similar requests, so I’ll address this at some point.

**Comment by gdanov** [comment]
thanks
