### ISSUE TITLE
How to quit karabiner in shell?

### ISSUE THREAD

**Issue by singlexyz** [pqrs-org/Karabiner-Elements#4024]
For some reasons, I need to restart Karabiner from the shell, but first, I need to quit it from the shell.

I tried `pkill Karabiner-Menu` and `pkill Karabiner-Elements`, but Karabiner is still running.

Which processes need to be killed with `pkill` to fully quit Karabiner?

**Comment by tekezo** [comment]
I've added the instructions for restarting or terminating from the command line to the documentation, so please check it out.

https://karabiner-elements.pqrs.org/docs/manual/operation/restart/
https://karabiner-elements.pqrs.org/docs/manual/operation/quit/

**Comment by singlexyz** [comment]
> I've added the instructions for restarting or terminating from the command line to the documentation, so please check it out.
> 
> https://karabiner-elements.pqrs.org/docs/manual/operation/restart/ https://karabiner-elements.pqrs.org/docs/manual/operation/quit/

Thanks.

**Comment by rublev** [comment]
> I've added the instructions for restarting or terminating from the command line to the documentation, so please check it out.
> 
> https://karabiner-elements.pqrs.org/docs/manual/operation/restart/ https://karabiner-elements.pqrs.org/docs/manual/operation/quit/

These files don't exist and this is out of date.

**Comment by tekezo** [comment]
> These files don't exist and this is out of date.

Thank you for feedback!
I fixed the document.
