### ISSUE TITLE
option key registered as command on Sequoia 15.2 and latest KBE

### ISSUE THREAD

**Issue by jrnxf** [pqrs-org/Karabiner-Elements#4061]
In Sequoia 15.2 Apple reverted the change that made the option key function the same as the command key (hallelujah). When I'm not running karabiner on 15.2, I can see the option key functions as it used to, however as soon as karabiner boots up it's back to registering the key as command (even though I see left_option in events viewer)

Is this a known bug?

OS: Mac Sequoia 15.2
KBE: 15.3.9

**Comment by mspinelli** [comment]
Perhaps see here: https://developer.apple.com/forums/thread/763878?page=2#818269022

**Comment by jrnxf** [comment]
Oh you know what, I figured out what it was - never knew this existed. In case anyone else sees this look here 
<img width="673" alt="image" src="https://github.com/user-attachments/assets/1c20932f-553f-4b76-8940-0d7123d7166b" />
