### ISSUE TITLE
Settings window not displaying in the center of the monitor

### ISSUE THREAD

**Issue by extrajoker** [pqrs-org/Karabiner-Elements#4064]
It appears that since version 15.3, the settings window no longer displays in the center of the monitor.

The window always appears in the upper right corner of the screen, and on 13-inch MacBooks, a significant portion of the settings window is often displayed outside the monitor's viewable area.

As a result, users are consistently inconvenienced by having to manually move the settings window to the center of the screen.

This issue is also observed with the Event Viewer.
This phenomenon has been confirmed on multiple Mac devices.

**Comment by tekezo** [comment]
duplicated: https://github.com/pqrs-org/Karabiner-Elements/issues/3997
