### ISSUE TITLE
The "to_if_alone" option is also outputting the "to" keycode

### ISSUE THREAD

**Issue by kris-anderson** [pqrs-org/Karabiner-Elements#4071]
I'm seeing this on both the latest version 15.3, and the latest beta 15.3.10.

I deleted my profile and created a fresh profile, leaving me no rules defined. I then installed one of the pre-defined rules "Change spacebar to left_shift. (Post spacebar if pressed alone)"

```json
{
    "description": "Change spacebar to left_shift. (Post spacebar if pressed alone)",
    "manipulators": [
        {
            "from": {
                "key_code": "spacebar",
                "modifiers": { "optional": ["any"] }
            },
            "to": [{ "key_code": "left_shift" }],
            "to_if_alone": [{ "key_code": "spacebar" }],
            "type": "basic"
        }
    ]
}
```

When I press the spacebar alone, I'm getting both the left shift and spacebar as outputs in EventViewer (when I should only be getting the spacebar as output):

```json
[
  {
    "type": "down",
    "name": {"key_code":"left_shift"},
    "usagePage": "7 (0x0007)",
    "usage": "225 (0x00e1)",
    "misc": "flags left_shift"
  },
  {
    "type": "up",
    "name": {"key_code":"left_shift"},
    "usagePage": "7 (0x0007)",
    "usage": "225 (0x00e1)",
    "misc": ""
  },
  {
    "type": "down",
    "name": {"key_code":"spacebar"},
    "usagePage": "7 (0x0007)",
    "usage": "44 (0x002c)",
    "misc": ""
  },
  {
    "type": "up",
    "name": {"key_code":"spacebar"},
    "usagePage": "7 (0x0007)",
    "usage": "44 (0x002c)",
    "misc": ""
  }
]
```

If I hold spacebar and press a key, I'm getting the correct (capitalized) word:

```json
[
  {
    "type": "down",
    "name": {"key_code":"left_shift"},
    "usagePage": "7 (0x0007)",
    "usage": "225 (0x00e1)",
    "misc": "flags left_shift"
  },
  {
    "type": "down",
    "name": {"key_code":"f"},
    "usagePage": "7 (0x0007)",
    "usage": "9 (0x0009)",
    "misc": "flags left_shift"
  },
  {
    "type": "up",
    "name": {"key_code":"f"},
    "usagePage": "7 (0x0007)",
    "usage": "9 (0x0009)",
    "misc": "flags left_shift"
  },
  {
    "type": "up",
    "name": {"key_code":"left_shift"},
    "usagePage": "7 (0x0007)",
    "usage": "225 (0x00e1)",
    "misc": ""
  }
]
```

I would expect that if I press spacebar alone, I would only get a spacebar down and spacebar up event, and not the additional left_shift events that I'm getting. The reason I noticed this was when I was setting up more complex modifications with my alpha keys. You wouldn't notice any errors with this default rule since the output of the shift key is silent. But when you start using to `to_if_alone` option on alpha keys, you end up with outputs you don't expect. I'm just using a default rule that ships with Karabiner to keep this example simple.

**Comment by kris-anderson** [comment]
I believe I figured out how to resolve my issue. I added `"lazy": true` as an option to my `to` statement.

**Comment by tekezo** [comment]
Yes, using lazy is the correct approach. Combining it with to_if_held_down is also recommended to improve compatibility with mouse events.

Example:
https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/#post-escape-if-left_control-is-pressed-alone
