### ISSUE TITLE
How to make this key sequence using complex modification?

### ISSUE THREAD

**Issue by s-yongchul** [pqrs-org/Karabiner-Elements#4077]
<img width="654" alt="image" src="https://github.com/user-attachments/assets/8427abca-c33f-4407-abbe-090f3fe5036a" />

I wonder if there's a way to make this key sequence in black background work using complex modification.

Using "repeat: false" or "to_after_key_up" doesn't seem help.

Anyone can help me to solve it?

**Comment by tekezo** [comment]
For the behavior shown in that image, you can achieve it by remapping left_option to left_command+left_option.

```json
{
    "description": "example",
    "manipulators": [
        {
            "from": {
                "key_code": "left_option",
                "modifiers": { "optional": ["any"] }
            },
            "to": [
                {
                    "key_code": "left_option",
                    "modifiers": ["left_command"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by s-yongchul** [comment]
@tekezo Thanks for quick reply!

In my case, the remapped left_command should be released (3rd row in black screenshot) while the actual left_option key is pressing down. (The script you told me has different result compared to what I intended)

It seems not possible to achieve this sequence with my knowledge. 😭 Any other idea?

**Comment by tekezo** [comment]
Oops, I misread your request. My apologies. How about this?

```json
{
    "description": "example",
    "manipulators": [
        {
            "from": {
                "key_code": "left_option",
                "modifiers": { "optional": ["any"] }
            },
            "to": [
                {
                    "key_code": "vk_none",
                    "modifiers": ["left_command"]
                },
                {
                    "key_code": "vk_none",
                    "modifiers": ["left_command", "left_option"]
                },
                { "key_code": "left_option" }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by s-yongchul** [comment]
@tekezo It works perfectly like a magic!
Never thought of using vk_none. Wow it's just... brilliant.
Really appreciated. 🙏

**Comment by tekezo** [comment]
This time it happened to work because it was a modifier, but ideally, sending only key_down or key_up for arbitrary keys is already on the feature request list. I'd like to implement a more general solution for this in the future.

**Comment by s-yongchul** [comment]
@tekezo Great! Looking forward to use that feature soon. 👍
