### ISSUE TITLE
[Bug?] Caps lock LED not turning on

### ISSUE THREAD

**Issue by MahdiNazemi** [pqrs-org/Karabiner-Elements#4079]
I have the following settings for my "Apple Internal Keyboard":

- [x] Modify events
    - [ ] Manipulate caps lock LED

When I press the caps lock key, I get all caps text but the LED does not turn on.

Karabiner-Elements version:
15.3.11

macOS version:
15.2

**Comment by tekezo** [comment]
This is the intended behavior. When "Manipulate caps lock LED" is turned off, the LED will not be controlled.
This setting is designed for the following cases:

- You want to use other software to repurpose the caps lock LED
- This is to disable the operation in case issues occur, such as with keyboard firmware problems, when attempting to control the Caps Lock LED on a keyboard that doesn't have one.
