### ISSUE TITLE
complex modifications don't work when Caps Lock is on

### ISSUE THREAD

**Issue by wygdove** [pqrs-org/Karabiner-Elements#4080]
My computer is connected to an external keyboard and an external mouse.
I use Karabiner to modify the mouse button 4 to "left_control + right_arrow", and button 5 to "left_control + left_arrow", it has been working smoothly. But when I turn on Caps Lock, these complex modifications don't work all the time.

OS: macOS Ventura 13.3 with Intel Core
Version: Karabiner-Elements 15.3.0

**Comment by Reluxer** [comment]
Me too. Hope to get reply as soon as possible.

**Comment by tekezo** [comment]
This is by design. You need to specify `"optional": ["caps_lock"]` within the rules of Complex Modifications.
https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/

**Comment by wygdove** [comment]
Thank you for your support! The issue is now resolved.
