### ISSUE TITLE
"multi-touch extension" replacement

### ISSUE THREAD

**Issue by franciscolourenco** [pqrs-org/Karabiner-Elements#665]
Any tool out there which can serve as an interim replacement for the "multi-touch extension"?

**Comment by nathanielescribano** [comment]
Would like to know as well

**Comment by denismaciel** [comment]
I am dying for something like this. Haven't upgraded the OS for over a year just because of it.

**Comment by iryan2** [comment]
Thread has been marked stale, I'm bumping to keep it alive. Every day I wish I had the functionality this extension provided. Would love to have official word on the likelihood of its return, even if it's 0%.

**Comment by paullinator** [comment]
Yes please. I am willing to fund the effort of getting the multitouch functionality to work. specifically the ability to shrink the touchpad area. This is SUPER important with the new MacBooks with the horribly large trackpad.

**Comment by lacostenycoder** [comment]
I have a 2015 mbp running 10.11.6 and seem to have multi-touch extension running but I can't seem to get it to do what I want. I posted this here as I've always had problems with this track pad.   https://apple.stackexchange.com/questions/210936/how-to-disable-accidental-trackpad-input-in-yosemite/322252#322252

Even typing this post, I accidentally opened a new tab.  I even tried using mouse-keys mode but that disables the keyboard for typing.  Looks like I'll have to go back to the tape stip hack.  This is surely the last mac I will ever buy.

**Comment by paullinator** [comment]
To clarify my offer above, I'd be happy to offer a bounty of $5000 USD for anyone that can get multitouch extension working on a 2018 MacBook Pro so that I can shrink the effective touch area.

**Comment by lacostenycoder** [comment]
@paullinator You might wanna use my Apple Script.  Also see my other comments on https://apple.stackexchange.com/questions/210936/how-to-disable-accidental-trackpad-input-in-yosemite/322252#322252

**Comment by paullinator** [comment]
@lacostenycoder I’m not trying to prevent “accidental touches”. My problem is that while I’m dragging, I need to rest my non tracking fingers somewhere. On the older mbp there was a space between the KB and the pad. Now that space is gone so when I rest my middle and ring finger down, it either touches the pad or the space bar. 

Keeping the entire hand elevated above the pad is fatiguing and causes my wrists to ache. I have a history of repetitive strain so I don’t need my trackpad creating more problems.

**Comment by lacostenycoder** [comment]
@paullinator hmmm. I guess my problem is the opposite,mainly with typing. But in any case, I use  3 finger tap and drag.  It sounds like you're dragging then with your thumb?  But give the BetterTouchTool a try, it might somehow help you, there's 45 day free trial.

**Comment by paullinator** [comment]
Actually, its when I'm just moving the mouse around. I use my index finger to move the mouse, but rest my middle and ring finger on the space between the KB and pad. I use the single tap and hold to drag things around. I have and use BetterTouchTool and love it for other things but it doesn't help this problem.

**Comment by iryan2** [comment]
bump

**Comment by denismaciel** [comment]
@paullinator ever considered funding this issue via [gitcoin](https://gitcoin.co/)?

**Comment by nkgm** [comment]
@tekezo could you share any thoughs on the kind of effort required to port the multitouch extension over to elements? Would it have to be a full rewrite as well? This is pretty much the reason I'm sticking with El Capitan for as long as possible.

**Comment by iryan2** [comment]
Bump.

**Comment by cocoahuke** [comment]
> To clarify my offer above, I'd be happy to offer a bounty of $5000 USD for anyone that can get multitouch extension working on a 2018 MacBook Pro so that I can shrink the effective touch area.

Do you still interested on this feature? My skill is fit for tweaking system.

**Comment by paullinator** [comment]
@cocoahuke For sure. Would you take crypto for this (Bitcoin, Bitcoin Cash, Dash, etc)?

**Comment by cocoahuke** [comment]
> @cocoahuke For sure. Would you take crypto for this (Bitcoin, Bitcoin Cash, Dash, etc)?

Yes.
How do I send you message privately?

**Comment by cocoahuke** [comment]
> @paullinator 
I've started working about it.
I tried to install and use "multi-touch extension" (On High Sierra), the "ignored" area is literally means ignored gesture, not really disable partial of trackpad.
Could you describe how was "multi-touch extension" works like?

I suppose shrink size of trackpad would make "disabled" area completely out of response, include clicking and Force-Touch, is this most satisfy way?

**Comment by paullinator** [comment]
Correct. The ignored area should not respond to any touches, taps, clicks, or gestures. It’s as if it’s not a trackpad at all.

**Comment by cocoahuke** [comment]
@paullinator Gotcha, Writing App UI right now.
It has to load a Kernel Extension, before someone willing sign it for me, it has to disable SIP in order to load unsigned. Everything will be open source.

**Comment by cocoahuke** [comment]
@paullinator Current progress: Kernel extension and IPC
Remain: Connect User-Kernel; A main page and reset/login-boot feature for app. Kext requires the app communicate as root, for safety purpose.

**Comment by cocoahuke** [comment]
@paullinator Will be finish today.

**Comment by cocoahuke** [comment]
@franciscolourenco 
@nathanielescribano 
@denismaciel 
@iryan2 
@paullinator 
@nkgm 
@lacostenycoder 
Check out my work! 
[https://github.com/cocoahuke/shrink_trackpad](https://github.com/cocoahuke/shrink_trackpad)

**Comment by cocoahuke** [comment]
@paullinator Hi, Mr. Paul, hope you would have time to review my project soon.

**Comment by paullinator** [comment]
@cocoahuke Sure. I'll take a look at it today. Thanks

**Comment by paullinator** [comment]
Do you have instructions on how to build this?

**Comment by cocoahuke** [comment]
@paullinator Just updated! Correct a library path.
With Xcode 9, Respectively open .xcodeproj and Build (Shift + Command + R) for two program.
After compiled, you got **app_shrinkTrackpad.app** and  **kext_shrink_trackpad.kext** 
- Move **kext_shrink_trackpad.kext** to **app_shrinkTrackpad.app/Contents/Resources/**
- Then only need to follow [How to use](https://github.com/cocoahuke/shrink_trackpad)

**Comment by paullinator** [comment]
Those instructions are a bit unclear. I can build the kext using Shift CMD R but that doesn't work for the app project. I get a 

```
clang: error: no such file or directory: '/Users/System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport'```

**Comment by cocoahuke** [comment]
That's because Xcode use relative path to link, and we open the project in different path, Fixed by change to absolute path!
[https://github.com/cocoahuke/shrink_trackpad/commit/322ed420013976d2171aa575418adce07083ece6](https://github.com/cocoahuke/shrink_trackpad/commit/322ed420013976d2171aa575418adce07083ece6)
To build them shouldn't be complex because Xcode wraps everything, please try again and follow from Step 2 [How to use](https://github.com/cocoahuke/shrink_trackpad)

**Comment by iryan2** [comment]
Bump

**Comment by sgithens** [comment]
bump

**Comment by sgithens** [comment]
I'm curious if downgrading to Karabiner 10.22.0 works on macOS Mojave, with the ability to shrink the trackpad.  It's actually the primary reason I'm trying to install karabiner.

**Comment by gordonpeterson** [comment]
Hey everyone. I hacked a version that kind of does what the multi-touch extension does with just the key remappings (no touchpad trigger). It essentially uses mouse-keys. I set the trigger to be the F key and the mouse down to be the spacebar. I've been using it for a couple of weeks and now that I'm used to it I've ditched my mouse and gone back to  the trackpad again. Give it a go and let me know what you think: [https://github.com/gordonpeterson/karabiner-elements](https://github.com/gordonpeterson/karabiner-elements)

Here are the two key bindings that I use for the mouse down functionality [F + spacebar] and [ctrl + spacebar]. it can be a little awkward at times and isn't as good as multi-touch, but it's the closest thing I've been able to come up with. 

If you do download it and try it here's another little tip. With multi-touch, all you had to do was touch the trackpad and you got the trigger. With just key-remappings, it's a little different. The F key times out if you don't trigger something. I personally like holding it down until I press the spacebar, which doesn't really work how I want. BUT, if you hold down F and tap the D key it triggers the remapping and you can just hold the F key down the whole time. It takes a minute to get used to, but now I'm totally used to it. 

I know it's not as good as before, but it is a little closer. Let me know what you think.

**Comment by nkgm** [comment]
@paullinator have you had any luck with @cocoahuke's prototype?
Calling for @tekezo's comment!

**Comment by iryan2** [comment]
Bump, still praying for official word on this, or an alternative. Not sure if it’s possible in current MacOS. 

The specific functionality I’m after is: when one finger is resting on the trackpad and the “f” key is pressed, fire mouseclick

**Comment by gsjackson** [comment]
I could vote for this with a slight modification:

> when one finger is resting on the trackpad and the “f” key is pressed, fire my boss.

**Comment by nkgm** [comment]
> The specific functionality I’m after is: when one finger is resting on the trackpad and the “f” key is pressed, fire mouseclick

`f` = left click
`d` = right click
`g` = middle click

Effortless and extremely ergonomic.

If only @tekezo would bootstrap a skeleton project, the community could start doing its part.

**Comment by tekezo** [comment]
MultitouchExtension is back at v12.6.9.
You can confirm it with the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

Usage of MultitouchExtension:
https://pqrs.org/osx/karabiner/document.html#multitouch-extension

**Comment by iryan2** [comment]
@tekezo Oh. my. god. Thank you so so much @tekezo, you have made my day! I'm very excited to use this again.

Took me a while to figure out how to send mouse clicks, so this snippet from my karabiner.json might be helpful to others (follow the setup guides in @tekezo's links above first!)

The first rule is just to confirm it was working, it turns `k` to `Up arrow` when one finger is on the trackpad. The second rule fires left click when you press `f` with one finger on trackpad.

The thing to note is instead of `key_code`, use `pointing_button` when you want to send mouse clicks.

[This is under `profiles.complex_modifications`:]
```
"rules": [
    {
        "description": "Multitouch extension",
        "manipulators": [
            {
                "type": "basic",
                "from": {
                    "key_code": "k"
                },
                "to": [
                    {
                        "key_code": "up_arrow"
                    }
                ],
                "conditions": [
                    {
                        "type": "variable_unless",
                        "name": "multitouch_extension_finger_count_total",
                        "value": 0
                    }
                ]
            },
            {
                "type": "basic",
                "from": {
                    "key_code": "f"
                },
                "to": [
                    {
                        "pointing_button": "button1"
                    }
                ],
                "conditions": [
                    {
                        "type": "variable_unless",
                        "name": "multitouch_extension_finger_count_total",
                        "value": 0
                    }
                ]
            }
        ]
    }
]
```


Again, thank you so much @tekezo, I've been missing this every day since Sierra (or was it High Sierra) broke Karabiner. If macOS Catalina breaks it again later this month I will probably cry.

**Comment by tekezo** [comment]
I updated karabiner.json example document.
https://pqrs.org/osx/karabiner/json.html#multitouch-extension

The change is added from.modifiers block which allows you to change the key while modifier keys (command,control,option,shift) are pressed.

```
{
  ...
  "from": {
    ...
    "modifiers": {
      "optional": [
        "any"
      ]
    }
  }
  ...
```

**Comment by nicksergeant** [comment]
👋 is there a way to use the new multi-touch extension to disable areas of the trackpad entirely? I have the same problem as https://github.com/tekezo/Karabiner-Elements/issues/665#issuecomment-381453193.

I see https://github.com/cocoahuke/shrink_trackpad, but I cannot / won't disable SIP.

**Comment by tekezo** [comment]
I guess the only way to disable trackpad is enable the option which is provided by Apple.
http://osxdaily.com/2017/01/05/disable-built-in-trackpad-macbook/

Disabling areas is not planned to support multi-touch extension, unfortunately.

**Comment by nicksergeant** [comment]
@tekezo gotcha, yeah I am doing a combination of that option + toggling Mouse Keys + Karabiner, which works _okay_, but really frustrating that the trackpad is so large. My thumbs rest on the top of the trackpad and as a result, my palms register clicks on the trackpad if pressed hard enough inadvertently.
